root: true

globals:
  # Libraries
  angular: false
  $: false
  moment: false
  # Zemanta
  zemSpecsHelper: false
  constants: false
  options: false
  defaults: false
  overwrittes: false
  # Jasmine
  jasmine: false
  describe: false
  fdescribe: false
  it: false
  fit: false
  module: false
  inject: false
  beforeEach: false
  afterEach: false
  expect: false
  spyOn: false
  # Webpack and CommonJS
  require: false
  process: false

rules:      
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
  comma-dangle:
    - 2
    - 'only-multiline'
  complexity:
    - 2
    - 10
  dot-notation:
    - 2
  eqeqeq:
    - 2    
  guard-for-in:
    - 2
  no-alert:
    - 2
  no-else-return:
    - 2
  no-trailing-spaces:
    - 2  
  brace-style:
    - 2
    - 1tbs
    - allowSingleLine: true
  array-bracket-spacing:
    - 2
  object-curly-spacing:
    - 2
  block-spacing:
    - 2
  camelcase:
    - 2
    - properties: never
  comma-spacing:
    - 2
  key-spacing:
    - 2
  no-lonely-if:
    - 2
  no-multiple-empty-lines:
    - 2
  semi-spacing:
    - 2
  keyword-spacing:
    - 2
  space-before-blocks:
    - 2  
  space-in-parens:
    - 2
  space-infix-ops:
    - 2
  space-unary-ops:
    - 2
  func-call-spacing:
    - 2
    - never
  no-unused-vars:
    - 2
  no-undef:
    - 2
  jasmine/new-line-between-declarations:
    - 0
  jasmine/no-suite-dupes:
    - 2
    - branch
  jasmine/no-spec-dupes:
    - 2
    - branch
  jasmine/new-line-before-expect:
    - 0
  jasmine/prefer-toHaveBeenCalledWith:
    - 0
  jasmine/prefer-jasmine-matcher:
    - 0
  no-prototype-builtins: off


env:
  browser: true
  jasmine: true

plugins:
  - jasmine

extends:
  - eslint:recommended
  - plugin:jasmine/recommended
