# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0046_remove_adgroupsourcesettings_autopilot_state'),
        ('dash', '0047_auto_20160413_1420'),
    ]

    operations = [
    ]
