# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0048_merge'),
        ('dash', '0047_auto_20160413_1256'),
    ]

    operations = [
    ]
