# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0049_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adgroup',
            name='content_ads_tab_with_cms',
        ),
    ]
