# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0050_remove_adgroup_content_ads_tab_with_cms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsettings',
            name='service_fee',
        ),
        migrations.RemoveField(
            model_name='campaignsettings',
            name='service_fee',
        ),
    ]
