# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0051_auto_20160419_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgroupsettings',
            name='system_user',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Campaign Stop'), (2, b'Zemanta Autopilot')], null=True),
        ),
        migrations.AlterField(
            model_name='campaigngoal',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Time on Site - Seconds'), (4, b'$CPA'), (5, b'CPC'), (3, b'Pageviews per Visit'), (2, b'Max Bounce Rate'), (7, b'New Unique Visitors')], default=1),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='system_user',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Campaign Stop'), (2, b'Zemanta Autopilot')], null=True),
        ),
    ]
