# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0052_auto_20160421_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='account_type',
            field=models.IntegerField(choices=[(6, b'Managed'), (1, b'Unknown'), (2, b'Test'), (3, b'Sandbox'), (5, b'Self-managed'), (4, b'Pilot')], default=1),
        ),
    ]
