# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0053_merge'),
        ('dash', '0053_accountsettings_account_type'),
    ]

    operations = [
    ]
