# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 16:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0054_auto_20160426_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
