# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 08:01


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0054_merge'),
        ('dash', '0054_auto_20160426_1517'),
    ]

    operations = [
    ]
