# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0054_auto_20160425_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ('-created_dt',), 'verbose_name_plural': 'Agencies'},
        ),
    ]
