# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0055_auto_20160425_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='groups',
        ),
    ]
