# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0056_auto_20160504_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisherblacklist',
            name='external_id',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name=b'External ID'),
        ),
    ]
