# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0056_auto_20160504_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditlineitem',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agencies', to='dash.Agency'),
        ),
        migrations.AlterField(
            model_name='creditlineitem',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='dash.Account'),
        ),
    ]
