# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0057_auto_20160504_1245'),
        ('dash', '0057_auto_20160505_1232'),
    ]

    operations = [
    ]
