# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0058_merge'),
        ('dash', '0057_auto_20160504_1245'),
    ]

    operations = [
    ]
