# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 14:31


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0059_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditlineitem',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='dash.Agency'),
        ),
    ]
