# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 13:41


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0060_auto_20160513_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversiongoal',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='automatic_campaign_stop',
            field=models.BooleanField(default=True),
        ),
    ]
