# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 14:47
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0061_auto_20160520_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAdCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25, null=True)),
                ('url', models.CharField(max_length=936, null=True)),
                ('title', models.CharField(max_length=256, null=True)),
                ('image_url', models.CharField(max_length=936, null=True)),
                ('image_crop', models.CharField(max_length=25, null=True)),
                ('display_url', models.CharField(max_length=25, null=True)),
                ('brand_name', models.CharField(max_length=25, null=True)),
                ('description', models.CharField(max_length=140, null=True)),
                ('call_to_action', models.CharField(max_length=25, null=True)),
                ('tracker_urls', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048), null=True, size=None)),
                ('image_id', models.CharField(max_length=256, null=True)),
                ('image_width', models.PositiveIntegerField(null=True)),
                ('image_height', models.PositiveIntegerField(null=True)),
                ('image_hash', models.CharField(max_length=128, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name=b'Created at')),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dash.AdGroup')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dash.UploadBatch')),
            ],
        ),
        migrations.AddField(
            model_name='contentad',
            name='label',
            field=models.CharField(default=b'', max_length=25),
        ),
    ]
