# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 12:42


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0062_auto_20160524_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAccount',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dash.Account')),
                ('ad_account_id', models.CharField(max_length=127)),
                ('page_url', models.CharField(max_length=255)),
            ],
        ),
    ]
