# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0063_facebookaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookaccount',
            name='status',
            field=models.IntegerField(choices=[(2, b'Connected'), (3, b'Pending'), (1, b'Empty')], default=1),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='ad_account_id',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
