# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 15:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0063_facebookaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentadcandidate',
            name='redirect_id',
        ),
        migrations.AddField(
            model_name='contentad',
            name='image_crop',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='contentadcandidate',
            name='image_status',
            field=models.IntegerField(choices=[(4, b'Failed'), (3, b'OK'), (2, b'Waiting for response'), (1, b'Pending')], default=1),
        ),
        migrations.AddField(
            model_name='contentadcandidate',
            name='url_status',
            field=models.IntegerField(choices=[(4, b'Failed'), (3, b'OK'), (2, b'Waiting for response'), (1, b'Pending')], default=1),
        ),
    ]
