# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 15:13


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0064_auto_20160527_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.PositiveSmallIntegerField(blank=True, choices=[(2, b'Campaign settings change'), (9, b'Depleting budet notification'), (3, b'Budget change'), (6, b'New user introduction email'), (5, b'User password reset'), (1, b'Ad group settings change'), (12, b'Autopilot initialisation notification'), (10, b'Campaign stopped notification'), (4, b'New conversion pixel'), (7, b'Supply report'), (8, b'Scheduled report'), (11, b'Autopilot changes notification')], null=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together=set([('template_type',)]),
        ),
    ]
