# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0064_auto_20160527_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dash.Account'),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='original_filename',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
