# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 08:38
from __future__ import unicode_literals

from django.db import migrations
from dash.constants import EmailTemplateType


def load_data(apps, schema_editor):
    EmailTemplate = apps.get_model('dash', 'EmailTemplate')

    EmailTemplate(
        template_type=EmailTemplateType.ADGROUP_CHANGE,
        subject=u'Settings change - ad group {ad_group.name}, campaign {campaign.name}, account {account.name}',
        body=u'''Hi account manager of ad group {ad_group.name}

We'd like to notify you that {user.email} has made the following change in the settings of the ad group {ad_group.name}, campaign {campaign.name}, account {account.name}:

{changes_text}

Please check {link_url} for further details.

Yours truly,
Zemanta
    '''
    ).save()

    EmailTemplate(
        template_type=EmailTemplateType.CAMPAIGN_CHANGE,
        subject=u'Settings change - campaign {campaign.name}, account {account.name}',
        body='''Hi account manager of campaign {campaign.name}

We'd like to notify you that {user.email} has made the following change in the settings of campaign {campaign.name}, account {account.name}:

{changes_text}

Please check {link_url} for further details.

Yours truly,
Zemanta
    '''
    ).save()

    EmailTemplate(
        template_type=EmailTemplateType.BUDGET_CHANGE,
        subject=u'Settings change - campaign {campaign.name}, account {account.name}',
        body=u'''Hi account manager of campaign {campaign.name}

We'd like to notify you that {user.email} has made the following change in the budget of campaign {campaign.name}, account {account.name}:

{changes_text}

Please check {link_url} for further details.

Yours truly,
Zemanta
    ''').save()

    EmailTemplate(
        template_type=EmailTemplateType.PASSWORD_RESET,
        subject='Recover Password',
        body=u'''<p>Hi {user.first_name},</p>
<p>You told us you forgot your password. If you really did, click here to choose a new one:</p>
<a href="{link_url}">Choose a New Password</a>
<p>If you didn't mean to reset your password, then you can just ignore this email; your password will not change.</p>
<p>
As always, please don't hesitate to contact help@zemanta.com with any questions.
</p>
<p>
Thanks,<br/>
Zemanta Client Services
</p>
    '''
    ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0065_auto_20160530_1513'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
