# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 09:58


import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0066_auto_20160531_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_account_name', models.CharField(max_length=127, unique=True)),
                ('demo_campaign_name_pool', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127, unique=True), size=None)),
                ('demo_ad_group_name_pool', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127, unique=True), size=None)),
                ('real_account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dash.Account')),
            ],
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, b'Campaign settings change'), (3, b'Budget change'), (12, b'Autopilot initialisation notification'), (5, b'User password reset'), (6, b'New user introduction email'), (4, b'New conversion pixel'), (8, b'Scheduled report'), (7, b'Supply report'), (1, b'Ad group settings change'), (14, b'Campaign is running out of budget notification'), (9, b'Depleting budget notification'), (10, b'Campaign stopped notification'), (13, b'Campaign switched to landing mode notification'), (11, b'Autopilot changes notification')], null=True),
        ),
    ]
