# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 13:58


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0067_auto_20160601_1344'),
        ('dash', '0067_auto_20160601_0910'),
    ]

    operations = [
    ]
