# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 10:02


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0068_merge'),
        ('dash', '0067_auto_20160601_0958'),
    ]

    operations = [
    ]
