# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 16:28


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0068_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='ad_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dash.AdGroup'),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='original_filename',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
