# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 14:44


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0069_merge'),
        ('dash', '0069_auto_20160601_1628'),
    ]

    operations = [
    ]
