# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 07:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0070_accounthistory_adgrouphistory_campaignhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgrouphistory',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Ad Group History'), (2, b'Ad Group Source History')]),
        ),
    ]
