# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 09:10


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0070_merge'),
        ('dash', '0070_accounthistory_adgrouphistory_campaignhistory'),
    ]

    operations = [
    ]
