# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 12:16


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0071_merge'),
        ('dash', '0071_auto_20160607_0751'),
    ]

    operations = [
    ]
