# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0071_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroupsettings',
            name='ga_property_id',
            field=models.CharField(blank=True, default=b'', max_length=25),
        ),
        migrations.AlterField(
            model_name='adgrouphistory',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Ad Group History'), (2, b'Ad Group Source History')]),
        ),
    ]
