# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 08:44


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0071_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, b'Ad Group Level'), (2, b'Campaign Level'), (4, b'Agency Level'), (3, b'Account Level')])),
                ('type', models.PositiveSmallIntegerField(choices=[(4, b'Account History'), (2, b'Campaign History'), (3, b'Budget History'), (5, b'Credit History'), (2, b'Campaign History'), (1, b'Ad Group History')])),
                ('changes_text', models.TextField()),
                ('changes', jsonfield.fields.JSONField()),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name=b'Created at')),
                ('system_user', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Campaign Stop'), (2, b'Zemanta Autopilot')], null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history', to='dash.Account')),
                ('ad_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history', to='dash.AdGroup')),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history', to='dash.Agency')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history', to='dash.Campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='accounthistory',
            name='account',
        ),
        migrations.RemoveField(
            model_name='accounthistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='adgrouphistory',
            name='ad_group',
        ),
        migrations.RemoveField(
            model_name='adgrouphistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='campaignhistory',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaignhistory',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='AccountHistory',
        ),
        migrations.DeleteModel(
            name='AdGroupHistory',
        ),
        migrations.DeleteModel(
            name='CampaignHistory',
        ),
    ]
