# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 13:18


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0072_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookaccount',
            name='ad_account_id',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='page_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='status',
            field=models.IntegerField(choices=[(2, b'Connected'), (1, b'Empty'), (5, b'Unknown'), (3, b'Pending'), (4, b'Invalid')], default=1),
        ),
    ]
