# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 09:41


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0073_auto_20160608_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookaccount',
            name='status',
            field=models.IntegerField(choices=[(2, b'Connected'), (1, b'Empty'), (5, b'Error'), (3, b'Pending'), (4, b'Invalid')], default=1),
        ),
    ]
