# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 13:56


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0073_auto_20160613_1013'),
        ('dash', '0074_auto_20160614_0941'),
    ]

    operations = [
    ]
