# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 11:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0075_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroupsettings',
            name='ga_property_id',
            field=models.CharField(blank=True, default=b'', max_length=25),
        ),
        migrations.AlterField(
            model_name='campaigngoal',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Time on Site - Seconds'), (4, b'$CPA'), (5, b'CPC'), (3, b'Pageviews per Visit'), (2, b'Max Bounce Rate'), (7, b'New Unique Visitors'), (8, b'Cost per Visit')], default=1),
        ),
    ]
