# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0075_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroupsourcesettings',
            name='system_user',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Campaign Stop'), (2, b'Zemanta Autopilot')], null=True),
        ),
    ]
