# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 07:54


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0077_auto_20160617_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(4, b'Account History'), (2, b'Campaign History'), (3, b'Budget History'), (5, b'Credit History'), (6, b'Ad Group Source History'), (1, b'Ad Group History')]),
        ),
    ]
