# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 10:00


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0077_merge'),
        ('dash', '0078_auto_20160620_0754'),
    ]

    operations = [
    ]
