# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 11:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0079_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentad',
            name='image_crop',
            field=models.CharField(default='faces', max_length=25),
            preserve_default=False,
        ),
    ]
