# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 11:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0080_auto_20160621_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentad',
            name='image_crop',
            field=models.CharField(default=b'center', max_length=25),
        ),
    ]
