# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 08:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0081_auto_20160621_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='action_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, b'Change Credit'), (2, b'Change Budget'), (8, b'Change Settings'), (1, b'Change Campaign Goal'), (11, b'Create Conversion Pixel'), (12, b'Archive/Restore Conversion Pixel'), (5, b'Set Global Publisher Blacklist'), (7, b'Set Content Ad(s) State'), (4, b'Set Publisher Blacklist'), (9, b'Create'), (13, b'Archive/Restore'), (16, b'Add Media Source'), (6, b'Manage Reporting'), (15, b'Set Media Source Settings'), (10, b'Create Content Ad'), (14, b'Archive/Restore Content Ad(s)')], null=True),
        ),
    ]
