# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 11:20


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0082_history_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(5, b'All Accounts'), (1, b'Ad Group Level'), (2, b'Campaign Level'), (4, b'Agency Level'), (3, b'Account Level')]),
        ),
    ]
