# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 09:27


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0083_auto_20160622_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(3, b'Account Level'), (4, b'Agency Level'), (2, b'Campaign Level'), (5, b'All Accounts'), (1, b'Ad Group Level')]),
        ),
    ]
