# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0083_auto_20160622_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='type',
        ),
    ]
