# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 09:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0085_auto_20160624_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgroupsettings',
            name='system_user',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Campaign Stop'), (3, b'System User '), (2, b'Zemanta Autopilot')], null=True),
        ),
        migrations.AlterField(
            model_name='adgroupsourcesettings',
            name='system_user',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Campaign Stop'), (3, b'System User '), (2, b'Zemanta Autopilot')], null=True),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='system_user',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Campaign Stop'), (3, b'System User '), (2, b'Zemanta Autopilot')], null=True),
        ),
        migrations.AlterField(
            model_name='contentadcandidate',
            name='brand_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentadcandidate',
            name='call_to_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentadcandidate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentadcandidate',
            name='display_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentadcandidate',
            name='image_crop',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentadcandidate',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentadcandidate',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentadcandidate',
            name='primary_tracker_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentadcandidate',
            name='secondary_tracker_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentadcandidate',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentadcandidate',
            name='tracker_urls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentadcandidate',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='system_user',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Campaign Stop'), (3, b'System User '), (2, b'Zemanta Autopilot')], null=True),
        ),
    ]
