# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0084_auto_20160624_1222'),
        ('dash', '0086_auto_20160630_0914'),
    ]

    operations = [
    ]
