# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 14:08


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0087_auto_20160630_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pixie_slug', models.CharField(max_length=255)),
                ('ttl', models.PositiveSmallIntegerField()),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name=b'Created at')),
                ('modified_dt', models.DateTimeField(auto_now=True, verbose_name=b'Modified at')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dash.Account')),
                ('ad_group_settings', models.ManyToManyField(to='dash.AdGroupSettings')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(2, b'Contains'), (1, b'Starts with')])),
                ('value', models.CharField(max_length=255)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dash.Audience')),
            ],
        ),
    ]
