# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 15:47


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0088_auto_20160701_1347'),
        ('dash', '0088_audience_rule'),
    ]

    operations = [
    ]
