# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0088_auto_20160701_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookaccount',
            name='status',
            field=models.IntegerField(choices=[(6, b'Revoked'), (4, b'Invalid'), (2, b'Connected'), (3, b'Pending'), (5, b'Error'), (1, b'Empty')], default=1),
        ),
    ]
