# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 13:39


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0088_audience_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audience',
            name='account',
        ),
        migrations.RemoveField(
            model_name='audience',
            name='pixie_slug',
        ),
        migrations.AddField(
            model_name='audience',
            name='pixel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dash.ConversionPixel'),
            preserve_default=False,
        ),
    ]
