# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 13:59


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0088_auto_20160701_1347'),
        ('dash', '0089_auto_20160704_1339'),
    ]

    operations = [
    ]
