# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 14:08


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0089_merge'),
        ('dash', '0090_merge'),
    ]

    operations = [
    ]
