# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 09:36


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0091_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='type',
        ),
    ]
