# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0091_merge'),
        ('dash', '0089_auto_20160705_0857'),
    ]

    operations = [
    ]
