# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 15:45


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0092_remove_contentadcandidate_tracker_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadbatch',
            name='batch_size',
        ),
        migrations.RemoveField(
            model_name='uploadbatch',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='uploadbatch',
            name='error_report_key',
        ),
        migrations.RemoveField(
            model_name='uploadbatch',
            name='inserted_content_ads',
        ),
        migrations.RemoveField(
            model_name='uploadbatch',
            name='num_errors',
        ),
        migrations.RemoveField(
            model_name='uploadbatch',
            name='processed_content_ads',
        ),
        migrations.RemoveField(
            model_name='uploadbatch',
            name='propagated_content_ads',
        ),
    ]
