# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 09:17


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0093_auto_20160705_1545'),
        ('dash', '0092_remove_history_type'),
    ]

    operations = [
    ]
