# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 08:02


from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0093_auto_20160705_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportreport',
            name='filtered_account_types',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
        migrations.AddField(
            model_name='exportreport',
            name='filtered_agencies',
            field=models.ManyToManyField(blank=True, to='dash.Agency'),
        ),
    ]
