# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 09:30


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0094_merge'),
        ('dash', '0094_auto_20160707_0802'),
    ]

    operations = [
    ]
