# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 10:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0094_auto_20160707_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
