# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 14:05


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0094_auto_20160707_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceTypePixel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('source_pixel_id', models.CharField(max_length=127)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name=b'Created on')),
                ('modified_dt', models.DateTimeField(auto_now=True, verbose_name=b'Modified at')),
                ('pixel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dash.ConversionPixel')),
                ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dash.SourceType')),
            ],
        ),
        migrations.AlterField(
            model_name='rule',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='sourcetypepixel',
            unique_together=set([('pixel', 'source_type')]),
        ),
    ]
