# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 08:49


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0095_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractionlog',
            name='account',
        ),
        migrations.RemoveField(
            model_name='useractionlog',
            name='account_settings',
        ),
        migrations.RemoveField(
            model_name='useractionlog',
            name='ad_group',
        ),
        migrations.RemoveField(
            model_name='useractionlog',
            name='ad_group_settings',
        ),
        migrations.RemoveField(
            model_name='useractionlog',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='useractionlog',
            name='campaign_settings',
        ),
        migrations.RemoveField(
            model_name='useractionlog',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='UserActionLog',
        ),
    ]
