# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 14:11


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0097_auto_20160708_1227'),
        ('dash', '0095_auto_20160708_1405'),
    ]

    operations = [
    ]
