# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 14:57


from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0098_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetlineitem',
            name='margin',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5),
        ),
    ]
