# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-25 12:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0099_budgetlineitem_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigngoal',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Time on Site - Seconds'), (4, b'$CPA'), (5, b'CPC'), (3, b'Pageviews per Visit'), (9, b'Cost per Non-Bounced Visit'), (2, b'Max Bounce Rate'), (7, b'New Unique Visitors'), (8, b'Cost per Visit')], default=1),
        ),
    ]
