# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 11:40


from django.db import migrations


def set_names(apps, schema_editor):
    ConversionPixel = apps.get_model('dash', 'ConversionPixel')
    for pixel in ConversionPixel.objects.all():
        if not pixel.name:
            pixel.name = pixel.slug
            pixel.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0100_auto_20160720_1131'),
    ]

    operations = [
        migrations.RunPython(set_names, lambda a, s: None)
    ]
