# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 11:41


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0101_auto_20160720_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionpixel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
