# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 11:48


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0102_auto_20160720_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionpixel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
