# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-25 13:41


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0100_auto_20160725_1212'),
        ('dash', '0103_auto_20160720_1148'),
    ]

    operations = [
    ]
