# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 12:25


from django.db import migrations

from dash.constants import EmailTemplateType

def load_data(apps, schema_editor):
    EmailTemplate = apps.get_model('dash', 'EmailTemplate')

    EmailTemplate(
        template_type=EmailTemplateType.LIVESTREAM_SESSION,
        subject='Livestream session started',
        body='User {user.email} started a new livestream session, accesssible on: {session_url}'
    ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0103_auto_20160720_1148'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
