# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 08:32


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0104_auto_20160727_1225'),
        ('dash', '0104_merge'),
    ]

    operations = [
    ]
