# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 08:54


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0106_auto_20160805_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='name',
            field=models.CharField(default='audience', max_length=127),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='action_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, b'Change Credit'), (2, b'Change Budget'), (8, b'Change Settings'), (1, b'Change Campaign Goal'), (11, b'Create Conversion Pixel'), (17, b'Rename conversion pixel'), (12, b'Archive/Restore Conversion Pixel'), (5, b'Set Global Publisher Blacklist'), (7, b'Set Content Ad(s) State'), (4, b'Set Publisher Blacklist'), (9, b'Create'), (13, b'Archive/Restore'), (16, b'Add Media Source'), (6, b'Manage Reporting'), (15, b'Set Media Source Settings'), (10, b'Create Content Ad'), (14, b'Archive/Restore Content Ad(s)')], null=True),
        ),
    ]
