# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 14:34


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0107_auto_20160808_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledexportreport',
            name='time_period',
            field=models.IntegerField(choices=[(3, b'Last 30 Days'), (7, b'Last Month'), (1, b'Yesterday'), (4, b'This Week'), (2, b'Last 7 Days'), (6, b'This Month'), (5, b'Last Week')], default=1),
        ),
    ]
