# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-11 09:34


from django.db import migrations

from dash import constants


def _get_default_time_period(sending_frequency):
    return {
        constants.ScheduledReportSendingFrequency.DAILY: constants.ScheduledReportTimePeriod.YESTERDAY,
        constants.ScheduledReportSendingFrequency.WEEKLY: constants.ScheduledReportTimePeriod.LAST_WEEK,
        constants.ScheduledReportSendingFrequency.MONTHLY: constants.ScheduledReportTimePeriod.LAST_MONTH,
    }.get(sending_frequency)


def set_default_time_period(apps, schema_editor):
    ScheduledExportReport = apps.get_model("dash", "ScheduledExportReport")
    for scheduled_report in ScheduledExportReport.objects.all():
        scheduled_report.time_period = _get_default_time_period(scheduled_report.sending_frequency)
        scheduled_report.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0108_scheduledexportreport_time_period'),
    ]

    operations = [
        migrations.RunPython(set_default_time_period)
    ]
