# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-19 09:08


from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0111_auto_20160817_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroupsettings',
            name='exclusion_retargeting_ad_groups',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
    ]
