# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-22 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0112_adgroupsettings_exclusion_retargeting_ad_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audience',
            name='ad_group_settings',
        ),
        migrations.AddField(
            model_name='audience',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dash.Account'),
            preserve_default=False,
        ),
    ]
