# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-23 11:25


from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0112_adgroupsettings_exclusion_retargeting_ad_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroupsettings',
            name='bluekai_targeting',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
        migrations.AddField(
            model_name='adgroupsettings',
            name='exclusion_interest_targeting',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
        migrations.AddField(
            model_name='adgroupsettings',
            name='interest_targeting',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
        migrations.AddField(
            model_name='adgroupsettings',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adgroupsettings',
            name='redirect_javascript',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adgroupsettings',
            name='redirect_pixel_urls',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
    ]
