# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-26 12:39


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0113_auto_20160823_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audience',
            name='ad_group_settings',
        ),
    ]
