# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-26 08:48


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0113_auto_20160823_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='default_account_type',
            field=models.IntegerField(choices=[(6, b'Managed'), (1, b'Unknown'), (2, b'Test'), (3, b'Sandbox'), (5, b'Self-managed'), (4, b'Pilot')], default=1),
        ),
    ]
