# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-23 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0113_auto_20160822_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audience',
            name='account',
        ),
        migrations.AddField(
            model_name='audience',
            name='ad_group_settings',
            field=models.ManyToManyField(to='dash.AdGroupSettings'),
        ),
    ]
