# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-26 12:55


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0114_agency_default_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='salesforce_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
