# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-26 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0113_auto_20160823_1125'),
        ('dash', '0114_auto_20160823_0837'),
    ]

    operations = [
    ]
