# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-29 12:27


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0114_remove_audience_ad_group_settings'),
        ('dash', '0115_account_salesforce_url'),
    ]

    operations = [
    ]
