# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-29 14:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0115_account_salesforce_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
