# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 08:42


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0116_audience_archived'),
        ('dash', '0116_merge'),
    ]

    operations = [
    ]
