# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 08:44


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0117_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='action_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, b'Change Credit'), (2, b'Change Budget'), (8, b'Change Settings'), (1, b'Change Campaign Goal'), (18, b'Create custom audience'), (11, b'Create Conversion Pixel'), (17, b'Rename conversion pixel'), (12, b'Archive/Restore Conversion Pixel'), (5, b'Set Global Publisher Blacklist'), (7, b'Set Content Ad(s) State'), (4, b'Set Publisher Blacklist'), (9, b'Create'), (13, b'Archive/Restore'), (16, b'Add Media Source'), (6, b'Manage Reporting'), (15, b'Set Media Source Settings'), (10, b'Create Content Ad'), (19, b'Archive custom audience'), (14, b'Archive/Restore Content Ad(s)')], null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(4, b'Not contains'), (3, b'Not starts with'), (2, b'Contains'), (5, b'Visit'), (1, b'Starts with')]),
        ),
    ]
