# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 14:22


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0120_auto_20160907_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='value',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
