# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-13 08:43


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0122_auto_20160909_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsettings',
            name='adobe_tracking_param',
            field=models.CharField(blank=True, default=b'', max_length=10),
        ),
        migrations.AddField(
            model_name='campaignsettings',
            name='enable_adobe_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaignsettings',
            name='enable_ga_tracking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaignsettings',
            name='ga_property_id',
            field=models.CharField(blank=True, default=b'', max_length=25),
        ),
        migrations.AddField(
            model_name='campaignsettings',
            name='ga_tracking_type',
            field=models.IntegerField(choices=[(2, b'API'), (1, b'Email')], default=1),
        ),
    ]
