# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-13 08:45


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0123_auto_20160913_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaanalyticsaccount',
            name='account',
        ),
        migrations.RemoveField(
            model_name='adgroupsettings',
            name='adobe_tracking_param',
        ),
        migrations.RemoveField(
            model_name='adgroupsettings',
            name='enable_adobe_tracking',
        ),
        migrations.RemoveField(
            model_name='adgroupsettings',
            name='enable_ga_tracking',
        ),
        migrations.RemoveField(
            model_name='adgroupsettings',
            name='ga_property_id',
        ),
        migrations.RemoveField(
            model_name='adgroupsettings',
            name='ga_tracking_type',
        ),
        migrations.DeleteModel(
            name='GAAnalyticsAccount',
        ),
    ]
