# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 14:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0124_auto_20160913_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportreport',
            name='include_totals',
            field=models.BooleanField(default=False),
        ),
    ]
