# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-16 13:42


from django.db import migrations
from dash.constants import EmailTemplateType


def load_data(apps, schema_editor):
    EmailTemplate = apps.get_model('dash', 'EmailTemplate')

    EmailTemplate(
        template_type=EmailTemplateType.OUTBRAIN_ACCOUNTS_RUNNING_OUT,
        subject='Unused Outbrain accounts running out',
        body='''Hi,
there are only {n} unused Outbrain accounts left on Z1.
    '''
    ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0125_exportreport_include_totals'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
