# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-16 13:24


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0125_exportreport_include_totals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rule',
            new_name='AudienceRule',
        ),
    ]
