# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-19 09:07


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0126_auto_20160916_1324'),
        ('dash', '0126_ob_running_out_email'),
    ]

    operations = [
    ]
