# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 13:54


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0129_auto_20160920_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='default_brand_name',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='default_call_to_action',
            field=models.TextField(blank=True, default=b'Read more', null=True),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='default_description',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='default_display_url',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='default_image_crop',
            field=models.TextField(blank=True, default=b'center', null=True),
        ),
    ]
