# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-23 12:36


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0130_auto_20160920_1354'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop),
    ]
