# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-21 14:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0130_auto_20160920_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionpixel',
            name='outbrain_sync',
            field=models.BooleanField(default=False),
        ),
    ]
