# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 06:34


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0131_conversionpixel_outbrain_sync'),
        ('dash', '0131_change_landing_mode_emails_20160923_1236'),
    ]

    operations = [
    ]
