# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 11:41


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0132_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='impression_trackers_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of impression trackers we know this source supports.'),
        ),
        migrations.AlterField(
            model_name='history',
            name='action_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(21, b'Sync Conversion Pixel to Outbrain'), (11, b'Create Conversion Pixel'), (22, b'Update custom audience'), (2, b'Change Budget'), (8, b'Change Settings'), (15, b'Set Media Source Settings'), (18, b'Create custom audience'), (3, b'Change Credit'), (13, b'Archive/Restore'), (17, b'Rename conversion pixel'), (19, b'Archive custom audience'), (5, b'Set Global Publisher Blacklist'), (7, b'Set Content Ad(s) State'), (4, b'Set Publisher Blacklist'), (9, b'Create'), (12, b'Archive/Restore Conversion Pixel'), (16, b'Add Media Source'), (20, b'Restore custom audience'), (6, b'Manage Reporting'), (1, b'Change Campaign Goal'), (10, b'Create Content Ad'), (14, b'Archive/Restore Content Ad(s)')], null=True),
        ),
    ]
