# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-07 14:10


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0134_auto_20161007_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgroupsettings',
            name='b1_sources_group_daily_budget',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name=b"Bidder's Daily Budget"),
        ),
    ]
