# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-14 12:05


from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0135_auto_20161007_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgroupsettings',
            name='autopilot_daily_budget',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True, verbose_name=b"Autopilot's Daily Spend Cap"),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='autopilot_state',
            field=models.IntegerField(blank=True, choices=[(2, b'Disabled'), (1, b'Optimize Bids and Daily Spend Caps'), (3, b'Optimize Bids')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='b1_sources_group_daily_budget',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name=b"Bidder's Daily Cap"),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='daily_budget_cc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name=b'Daily spend cap'),
        ),
        migrations.AlterField(
            model_name='adgroupsourcesettings',
            name='daily_budget_cc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name=b'Daily spend cap'),
        ),
        migrations.AlterField(
            model_name='adgroupsourcestate',
            name='daily_budget_cc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name=b'Daily spend cap'),
        ),
        migrations.AlterField(
            model_name='defaultsourcesettings',
            name='daily_budget_cc',
            field=models.DecimalField(blank=True, decimal_places=4, help_text=b'This setting has moved. See Source model.', max_digits=10, null=True, verbose_name=b'Default daily spend cap'),
        ),
        migrations.AlterField(
            model_name='source',
            name='default_daily_budget_cc',
            field=models.DecimalField(decimal_places=4, default=Decimal('10.00'), max_digits=10, verbose_name=b'Default daily spend cap'),
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='max_daily_budget',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name=b'Maximum Daily Spend Cap'),
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='min_daily_budget',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name=b'Minimum Daily Spend Cap'),
        ),
    ]
