# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-18 13:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0136_auto_20161014_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='auto_save',
            field=models.BooleanField(default=False),
        ),
    ]
