# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-14 12:08


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0136_auto_20161014_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversionpixel',
            name='outbrain_sync',
        ),
        migrations.AddField(
            model_name='conversionpixel',
            name='audience_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='action_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(11, b'Create Conversion Pixel'), (22, b'Update custom audience'), (2, b'Change Budget'), (8, b'Change Settings'), (15, b'Set Media Source Settings'), (18, b'Create custom audience'), (3, b'Change Credit'), (13, b'Archive/Restore'), (17, b'Rename conversion pixel'), (19, b'Archive custom audience'), (5, b'Set Global Publisher Blacklist'), (7, b'Set Content Ad(s) State'), (21, b'Enable pixel for building audiences'), (4, b'Set Publisher Blacklist'), (9, b'Create'), (12, b'Archive/Restore Conversion Pixel'), (16, b'Add Media Source'), (20, b'Restore custom audience'), (6, b'Manage Reporting'), (1, b'Change Campaign Goal'), (10, b'Create Content Ad'), (14, b'Archive/Restore Content Ad(s)')], null=True),
        ),
    ]
