# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-20 09:30


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0137_auto_20161014_1208'),
        ('dash', '0137_uploadbatch_auto_save'),
    ]

    operations = [
    ]
