# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-21 10:34


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0138_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demoadgrouprealadgroup',
            name='demo_ad_group',
        ),
        migrations.RemoveField(
            model_name='demoadgrouprealadgroup',
            name='real_ad_group',
        ),
        migrations.RemoveField(
            model_name='adgroup',
            name='is_demo',
        ),
        migrations.DeleteModel(
            name='DemoAdGroupRealAdGroup',
        ),
    ]
