# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-30 15:40


from django.db import migrations
from dash.constants import EmailTemplateType


def load_data(apps, schema_editor):
    EmailTemplate = apps.get_model('dash', 'EmailTemplate')

    try:
        template = EmailTemplate.objects.get(template_type=EmailTemplateType.ASYNC_REPORT_RESULTS)
    except EmailTemplate.DoesNotExist:
        template = EmailTemplate(subject='Report results', template_type=EmailTemplateType.ASYNC_REPORT_RESULTS)

    template.body = '''Hi,

You requested a report with the following settings for {ad_group.campaign.account.name} - {ad_group.campaign.name} - {ad_group.name}:

Date range: {start_date} - {end_date}
View: {tab_name}
Breakdowns: {breakdown}
Columns: {columns}
Filters: {filters}
Totals included: {include_totals}

You can download the report here: {link_url}.
Report will be available for download until {expiry_date}.

Yours truly,
Zemanta
    '''
    template.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0144_change_demo_running_email'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
