# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-08 08:16


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0146_auto_20161202_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsettings',
            name='account_type',
            field=models.IntegerField(choices=[(6, b'Managed'), (1, b'Unknown'), (5, b'Activated'), (3, b'Sandbox'), (2, b'Test'), (4, b'Pilot')], default=1),
        ),
        migrations.AlterField(
            model_name='agency',
            name='default_account_type',
            field=models.IntegerField(choices=[(6, b'Managed'), (1, b'Unknown'), (5, b'Activated'), (3, b'Sandbox'), (2, b'Test'), (4, b'Pilot')], default=1),
        ),
    ]
