# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-09 17:11


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0147_auto_20161208_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentadcandidate',
            name='original_content_ad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dash.ContentAd'),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='type',
            field=models.IntegerField(choices=[(1, b'Default'), (2, b'Edit')], default=1),
        ),
    ]
