# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-19 12:27


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0148_auto_20161209_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionpixel',
            name='additional_pixel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='type',
            field=models.IntegerField(choices=[(2, b'Edit'), (1, b'Insert')], default=1),
        ),
    ]
