# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-23 07:14


from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0149_auto_20161219_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroupsource',
            name='blockers',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
