# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-28 12:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0150_adgroupsource_blockers'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroupsettings',
            name='max_cpm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name=b'Maximum CPM'),
        ),
    ]
