# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-06 10:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0151_adgroupsettings_max_cpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionpixel',
            name='impressions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversionpixel',
            name='last_triggered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
