# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-10 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0152_auto_20170106_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adgroupsource',
            name='submission_status',
        ),
    ]
