# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-09 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0152_auto_20170106_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroupsettings',
            name='b1_sources_group_cpc_cc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name=b"Bidder's Bid CPC"),
        ),
    ]
