# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-11 16:02


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0153_publishergroup_publishergroupentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adgroupsource',
            name='submission_errors',
        ),
        migrations.RemoveField(
            model_name='adgroupsource',
            name='submission_status',
        ),
    ]
