# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-11 10:37


from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0153_publishergroup_publishergroupentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroupsettings',
            name='blacklist_publisher_groups',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
        migrations.AddField(
            model_name='adgroupsettings',
            name='whitelist_publisher_groups',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
    ]
