# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-10 14:12
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0153_adgroupsettings_b1_sources_group_cpc_cc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgroupsettings',
            name='b1_sources_group_cpc_cc',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0100'), max_digits=10, verbose_name=b"Bidder's Bid CPC"),
        ),
    ]
