# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-12 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0154_auto_20170111_1602'),
        ('dash', '0154_auto_20170110_1412'),
    ]

    operations = [
    ]
