# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-12 10:22


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0154_auto_20170111_1037'),
        ('dash', '0154_auto_20170111_1602'),
    ]

    operations = [
    ]
