# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-12 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0154_auto_20170111_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpcConstraint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('min_cpc', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name=b'Minimum CPC')),
                ('max_cpc', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name=b'Maximum CPC')),
                ('constraint_type', models.IntegerField(choices=[(1, b'Manual'), (2, b'Outbrain blacklist')], default=1)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name=b'Created at')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cpc_constraints', to='dash.Account')),
                ('ad_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cpc_constraints', to='dash.AdGroup')),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cpc_constraints', to='dash.Agency')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cpc_constraints', to='dash.Campaign')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cpc_constraints', to='dash.Source')),
            ],
        ),
    ]
