# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-19 13:06


from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0156_auto_20170113_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroupsettings',
            name='b1_sources_group_cpc_cc',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.01'), max_digits=10, verbose_name=b"Bidder's Bid CPC"),
        ),
    ]
