# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-19 15:28


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0157_adgroupsettings_b1_sources_group_cpc_cc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpcconstraint',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cpc_constraints', to='dash.Account'),
        ),
        migrations.AlterField(
            model_name='cpcconstraint',
            name='ad_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cpc_constraints', to='dash.AdGroup'),
        ),
        migrations.AlterField(
            model_name='cpcconstraint',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cpc_constraints', to='dash.Agency'),
        ),
        migrations.AlterField(
            model_name='cpcconstraint',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cpc_constraints', to='dash.Campaign'),
        ),
        migrations.AlterField(
            model_name='cpcconstraint',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cpc_constraints', to='dash.Source'),
        ),
    ]
