# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-19 16:54


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0158_auto_20170119_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpcconstraint',
            name='max_cpc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name=b'Maximum CPC'),
        ),
        migrations.AlterField(
            model_name='cpcconstraint',
            name='min_cpc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name=b'Minimum CPC'),
        ),
    ]
