# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-31 16:16


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0160_auto_20170127_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='default_blacklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blacklisted_accounts', to='dash.PublisherGroup'),
        ),
        migrations.AlterField(
            model_name='account',
            name='default_whitelist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='whitelisted_accounts', to='dash.PublisherGroup'),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='default_blacklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blacklisted_ad_groups', to='dash.PublisherGroup'),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='default_whitelist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='whitelisted_ad_groups', to='dash.PublisherGroup'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='default_blacklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blacklisted_campaigns', to='dash.PublisherGroup'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='default_whitelist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='whitelisted_campaigns', to='dash.PublisherGroup'),
        ),
    ]
