# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-01 10:29


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0161_auto_20170131_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomHack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rtb_only', models.BooleanField(default=False)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('service', models.CharField(choices=[(b'z1', b'Zemanta One'), (b'r1', b'Redirector'), (b'k1', b'Konsistency One'), (b'b1', b'Bidder')], default=b'z1', max_length=255)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name=b'Created at')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hacks', to='dash.Account')),
                ('ad_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hacks', to='dash.AdGroup')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hacks', to='dash.Agency')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hacks', to='dash.Campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hacks', to='dash.Source')),
            ],
        ),
    ]
