# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-02 09:39


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0161_auto_20170201_1203'),
        ('dash', '0162_customhack'),
    ]

    operations = [
    ]
