# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-03 10:22


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0164_customhack_removed_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionpixel',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='action_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(11, b'Create Conversion Pixel'), (22, b'Update custom audience'), (2, b'Change Budget'), (16, b'Add Media Source'), (8, b'Change Settings'), (15, b'Set Media Source Settings'), (18, b'Create custom audience'), (3, b'Change Credit'), (13, b'Archive/Restore'), (17, b'Rename conversion pixel'), (19, b'Archive custom audience'), (5, b'Set Global Publisher Blacklist'), (7, b'Set Content Ad(s) State'), (21, b'Enable pixel for building audiences'), (4, b'Set Publisher Blacklist'), (9, b'Create'), (12, b'Archive/Restore Conversion Pixel'), (23, b'Set redirect url for pixel'), (20, b'Restore custom audience'), (6, b'Manage Reporting'), (1, b'Change Campaign Goal'), (10, b'Create Content Ad'), (24, b'Remove redirect url for pixel'), (14, b'Archive/Restore Content Ad(s)')], null=True),
        ),
    ]
