# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-06 10:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0165_auto_20170203_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionpixel',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
