# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-03 11:34


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0165_auto_20170203_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='customhack',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customhack',
            name='confirmed_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Confirmed at'),
        ),
    ]
