# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-06 11:19


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0166_conversionpixel_notes'),
        ('dash', '0166_auto_20170203_1134'),
    ]

    operations = [
    ]
