# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-13 14:42


import textwrap
from django.db import migrations
from dash.constants import EmailTemplateType


def load_data(apps, schema_editor):
    EmailTemplate = apps.get_model('dash', 'EmailTemplate')

    EmailTemplate(
        template_type=EmailTemplateType.ACCOUNT_CHANGE,
        subject='Settings change - account {account.name}',
        body='''Hi account manager of account {account.name}

We'd like to notify you that {user.email} has made the following change in the settings of the account {account.name}:

{changes_text}

Please check {link_url} for further details.

Yours truly,
Zemanta
    '''
    ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0168_accountsettings_salesforce_url'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
