# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-15 08:35


from django.db import migrations

from dash.constants import EmailTemplateType


def load_data(apps, schema_editor):
    EmailTemplate = apps.get_model('dash', 'EmailTemplate')

    EmailTemplate(
        template_type=EmailTemplateType.WEEKLY_CLIENT_REPORT,
        subject='Weekly Client Report',
        body='''Email client has to support HTML templates.'''
    ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0169_add_depleting_credit_email'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
