# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-14 09:43


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0169_add_depleting_credit_email'),
        ('dash', '0169_auto_20170213_1442'),
    ]

    operations = [
    ]
