# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-16 11:25


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0170_merge'),
        ('dash', '0171_auto_20170215_1055'),
    ]

    operations = [
    ]
