# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-16 16:11


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0172_add_pacing_email'),
        ('dash', '0172_merge'),
    ]

    operations = [
    ]
