# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-17 12:30
from __future__ import unicode_literals

from django.db import migrations
from dash.constants import EmailTemplateType


def load_data(apps, schema_editor):
    EmailTemplate = apps.get_model('dash', 'EmailTemplate')

    EmailTemplate(
        template_type=EmailTemplateType.WEEKLY_INVENTORY_REPORT,
        subject=u'Inventory report',
        body=u'''This week's inventory report for the last 30 days is available at {report_url}.'''
    ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0173_merge'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
