# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 09:55


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0177_auto_20170222_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishergroupentry',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dash.Source'),
        ),
    ]
