# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 13:17


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0177_auto_20170222_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishergroup',
            name='implicit',
            field=models.BooleanField(default=False),
        ),
    ]
