# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 09:02


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0179_auto_20170227_1321'),
        ('dash', '0178_auto_20170223_0955'),
    ]

    operations = [
    ]
