# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 10:26


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0180_merge_20170301_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[(b'dma', b'DMA'), (b'zip', b'Postal Code'), (b'ci', b'City'), (b'co', b'Country'), (b're', b'Region')], max_length=3)),
                ('name', models.CharField(max_length=127)),
            ],
        ),
    ]
