# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 13:53


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0181_geolocation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishergroup',
            name='default_include_subdomains',
            field=models.BooleanField(default=True),
        ),
    ]
