# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 09:50


from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0182_publishergroup_default_include_subdomains'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroupsettings',
            name='exclusion_target_regions',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignsettings',
            name='exclusion_target_regions',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
