# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 14:36


from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0183_location_targeting_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgroupsettings',
            name='exclusion_target_regions',
            field=jsonfield.fields.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='exclusion_target_regions',
            field=jsonfield.fields.JSONField(blank=True, default=[], null=True),
        ),
    ]
