# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 10:55


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0183_auto_20170309_1435'),
        ('dash', '0184_location_targeting_extension_2'),
    ]

    operations = [
    ]
