# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 11:08


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0185_merge_20170310_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='whitelabel',
            field=models.CharField(blank=True, choices=[(b'greenpark', b'Green Park Content')], max_length=255),
        ),
    ]
