# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 07:51


from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0186_agency_whitelabel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geolocation',
            options={'ordering': ('-type',)},
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='account_type',
            field=models.IntegerField(choices=[(7, 7), (6, b'Managed'), (1, b'Unknown'), (5, b'Activated'), (3, b'Sandbox'), (2, b'Test'), (4, b'Pilot')], default=1),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='exclusion_target_regions',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='agency',
            name='default_account_type',
            field=models.IntegerField(choices=[(7, 7), (6, b'Managed'), (1, b'Unknown'), (5, b'Activated'), (3, b'Sandbox'), (2, b'Test'), (4, b'Pilot')], default=1),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='exclusion_target_regions',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
    ]
