# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 10:11


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0187_auto_20170321_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='outbrain_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='geolocation',
            name='woeid',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
