# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 17:05


from django.db import migrations
from dash.constants import EmailTemplateType


def load_data(apps, schema_editor):
    EmailTemplate = apps.get_model('dash', 'EmailTemplate')

    EmailTemplate(
        template_type=EmailTemplateType.NEW_DEVICE_LOGIN,
        subject='New login to Zemanta One from {{ browser }} on {{ os }}',
        body='''Hi,

We noticed you logged into Zemanta using {{ browser }} on {{ os }} at {{ time }} from {{ geo location }}.

Note: Your location may be inaccurate since it was estimated using your IP address.

If this wasn’t you your account may have been compromised. We suggest you change your password here.

If this was you no action is required.

Yours truly,
Zemanta'''
    ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0187_auto_20170321_0751'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
