# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 14:10


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0188_auto_20170323_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, b'Budget change'), (12, b'Autopilot initialisation notification'), (5, b'User password reset'), (19, b'Google Analytics Setup Instructions'), (21, b'Depleting credits'), (26, b'New device login'), (6, b'New user introduction email'), (24, b'Pacing notification'), (18, b'Unused Outbrain accounts running out'), (23, b'Weekly client report'), (8, b'Scheduled report'), (25, b'Weekly inventory report'), (7, b'Supply report'), (16, b'Livestream sesion id'), (22, None), (17, b'Daily management report'), (1, b'Ad group settings change'), (14, b'Campaign is running out of budget notification'), (9, b'Depleting budget notification'), (15, b'Demo is running'), (10, b'Campaign stopped notification'), (11, b'Autopilot changes notification'), (2, b'Campaign settings change'), (20, b'Report results'), (13, b'Campaign switched to landing mode notification'), (4, b'New conversion pixel')], null=True),
        ),
    ]
