# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 07:02


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0188_auto_20170323_1011'),
        ('dash', '0192_auto_20170324_1511'),
    ]

    operations = [
    ]
