# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 12:10


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0193_merge_20170327_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=127),
        ),
    ]
