# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 11:39


import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0196_creditlineitem_refund'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publishergroupentry',
            options={'ordering': ('pk',)},
        ),
        migrations.AddField(
            model_name='adgroupsettings',
            name='target_os',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'Operating System'),
        ),
        migrations.AddField(
            model_name='adgroupsettings',
            name='target_placements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, null=True, size=None, verbose_name=b'Placement'),
        ),
        migrations.AddField(
            model_name='campaignsettings',
            name='target_os',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'Operating Systems'),
        ),
        migrations.AddField(
            model_name='campaignsettings',
            name='target_placements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, null=True, size=None, verbose_name=b'Placement'),
        ),
    ]
