# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 15:02


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0199_add_reportjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name=b'Created at')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.IntegerField(choices=[(2, b'Paused'), (1, b'Enabled'), (3, b'Removed')], default=1)),
                ('sending_frequency', models.IntegerField(choices=[(3, b'Monthly'), (1, b'Daily'), (2, b'Weekly')], default=1)),
                ('day_of_week', models.IntegerField(choices=[(1, b'Monday'), (2, b'Tuesday'), (5, b'Friday'), (3, b'Wednesday'), (4, b'Thursday'), (7, b'Sunday'), (6, b'Saturday')], default=1)),
                ('time_period', models.IntegerField(choices=[(3, b'Last 30 Days'), (7, b'Last Month'), (1, b'Yesterday'), (4, b'This Week'), (2, b'Last 7 Days'), (6, b'This Month'), (5, b'Last Week')], default=1)),
                ('query', jsonfield.fields.JSONField()),
                ('last_sent_dt', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dash.Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
