# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 09:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0200_scheduledreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='custom_dashboard_title',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='agency',
            name='custom_favicon_url',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
    ]
