# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0201_auto_20170412_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='customhack',
            name='trello_ticket_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
