# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 10:40


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0203_scheduled_report_results_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportjob',
            name='scheduled_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='dash.ScheduledReport'),
        ),
    ]
