# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 15:01


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0204_reportjob_scheduled_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='customhack',
            name='trello_ticket_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportjob',
            name='scheduled_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='dash.ScheduledReport'),
        ),
    ]
