# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 14:49


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0205_auto_20170418_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetDailyStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('media_spend_nano', models.BigIntegerField()),
                ('data_spend_nano', models.BigIntegerField()),
                ('license_fee_nano', models.BigIntegerField()),
                ('margin_nano', models.BigIntegerField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='dash.BudgetLineItem')),
            ],
            options={
                'get_latest_by': 'date',
            },
        ),
        migrations.AlterUniqueTogether(
            name='budgetdailystatement',
            unique_together=set([('budget', 'date')]),
        ),
    ]
