# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 12:53


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0207_supplyreportrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='history',
            name='action_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(11, b'Create Conversion Pixel'), (22, b'Update custom audience'), (26, b'Update publisher group'), (16, b'Add Media Source'), (8, b'Change Settings'), (15, b'Set Media Source Settings'), (18, b'Create custom audience'), (3, b'Change Credit'), (25, b'Create publisher group'), (17, b'Rename conversion pixel'), (19, b'Archive custom audience'), (5, b'Set Global Publisher Blacklist'), (7, b'Set Content Ad(s) State'), (21, b'Enable pixel for building audiences'), (4, b'Set Publisher Blacklist'), (9, b'Create'), (2, b'Change Budget'), (12, b'Archive/Restore Conversion Pixel'), (23, b'Set redirect url for pixel'), (20, b'Restore custom audience'), (6, b'Manage Reporting'), (1, b'Change Campaign Goal'), (10, b'Create Content Ad'), (13, b'Archive/Restore'), (24, b'Remove redirect url for pixel'), (26, b'Update publisher group'), (14, b'Archive/Restore Content Ad(s)')], null=True),
        ),
    ]
