# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 06:01


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0208_auto_20170420_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsettings',
            name='account_type',
            field=models.IntegerField(choices=[(7, b'PAAS'), (6, b'Managed'), (1, b'Unknown'), (5, b'Activated'), (3, b'Sandbox'), (2, b'Test'), (4, b'Pilot')], default=1),
        ),
        migrations.AlterField(
            model_name='agency',
            name='default_account_type',
            field=models.IntegerField(choices=[(7, b'PAAS'), (6, b'Managed'), (1, b'Unknown'), (5, b'Activated'), (3, b'Sandbox'), (2, b'Test'), (4, b'Pilot')], default=1),
        ),
    ]
