# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 15:35


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0209_auto_20170425_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueKaiCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name=b'Created at')),
                ('category_id', models.PositiveIntegerField(unique=True)),
                ('parent_category_id', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('reach', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('navigation_only', models.BooleanField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, b'Active'), (2, b'Inactive')], default=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='geolocation',
            options={},
        ),
    ]
