# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 15:38


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0210_auto_20170516_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluekaicategory',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
