# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 07:02


from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0210_auto_20170516_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name=b'Created at')),
                ('modified_dt', models.DateTimeField(auto_now=True, verbose_name=b'Modified at')),
                ('status', models.IntegerField(choices=[(2, b'Video is ready for use in creating ads.'), (0, b'Video is not uploaded yet'), (1, b'Video is processing'), (3, b'An error has occurred while processing the video')], default=0)),
                ('name', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dash.Account')),
            ],
        ),
        migrations.AlterModelOptions(
            name='campaigngoalvalue',
            options={'ordering': ['created_dt']},
        ),
    ]
