# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 13:20


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0211_auto_20170525_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaigngoalvalue',
            options={'ordering': ['created_dt']},
        ),
        migrations.AlterField(
            model_name='bluekaicategory',
            name='reach',
            field=models.BigIntegerField(),
        ),
    ]
