# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 12:06


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0212_auto_20170526_1320'),
        ('dash', '0211_videoassets'),
    ]

    operations = [
    ]
