# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 06:59


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0213_merge_20170529_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoasset',
            name='status',
            field=models.IntegerField(choices=[(2, b'Video is ready for use in creating ads'), (0, b'Video is not uploaded yet'), (1, b'Video is processing'), (3, b'An error has occurred while processing the video')], default=0),
        ),
    ]
