# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 11:25


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0214_auto_20170530_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentadcandidate',
            name='video_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dash.VideoAsset'),
        ),
    ]
