# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 12:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0214_auto_20170530_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoasset',
            name='error_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
