# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 13:46


from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0215_videoasset_error_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoasset',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoasset',
            name='formats',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
