# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 06:51


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0215_videoasset_error_code'),
        ('dash', '0216_contentad_video_asset'),
    ]

    operations = [
    ]
