# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 09:53


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0216_auto_20170607_1346'),
        ('dash', '0217_merge_20170608_0651'),
    ]

    operations = [
    ]
