# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 09:57


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0218_merge_20170608_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroupsettings',
            name='budget_pacing_type',
            field=models.IntegerField(choices=[(2, b'Accelerated'), (1, b'Standard')], default=1),
        ),
    ]
