# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 14:10


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0219_adgroupsettings_budget_pacing_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adgroupsettings',
            old_name='budget_pacing_type',
            new_name='delivery_type',
        ),
    ]
