# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 06:41


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0221_auto_20170620_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgroupsettings',
            name='click_capping_type',
            field=models.IntegerField(blank=True, choices=[(2, b'Content Ad'), (0, b'Disabled'), (1, b'Ad Group')], default=0, null=True),
        ),
    ]
