# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 11:03


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0222_auto_20170620_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgroupsettings',
            name='click_capping_type',
            field=models.IntegerField(blank=True, choices=[(2, b'Content Ad'), (0, b'Disabled'), (1, b'Ad Group')], default=0),
        ),
    ]
