# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 13:02


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0223_auto_20170620_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adgroupsettings',
            old_name='click_capping_max_clicks',
            new_name='click_capping_daily_ad_group_max_clicks',
        ),
        migrations.RemoveField(
            model_name='adgroupsettings',
            name='click_capping_type',
        ),
    ]
