# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 08:41


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0224_auto_20170621_1302'),
        ('dash', '0224_auto_20170620_1512'),
    ]

    operations = [
    ]
