# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 13:46


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0225_merge_20170622_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adgroupsourcestate',
            name='ad_group_source',
        ),
        migrations.DeleteModel(
            name='AdGroupSourceState',
        ),
    ]
