# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 09:45


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0226_auto_20170623_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversiongoal',
            name='pixel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dash.ConversionPixel'),
        ),
    ]
