# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 11:12


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0227_auto_20170626_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dash.Account'),
        ),
        migrations.AlterField(
            model_name='contentadcandidate',
            name='ad_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dash.AdGroup'),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='ad_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dash.AdGroup'),
        ),
    ]
