# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0227_auto_20170626_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditlineitem',
            name='contract_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name=b'SalesForce Contract ID'),
        ),
        migrations.AlterField(
            model_name='creditlineitem',
            name='part_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name=b'SalesForce Contract Part ID'),
        ),
    ]
