# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 13:38


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0227_auto_20170626_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='uses_bcm_v2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='ad_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dash.AdGroup'),
        ),
    ]
