# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 16:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0229_auto_20170705_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditlineitem',
            name='part_id',
        ),
        migrations.AddField(
            model_name='creditlineitem',
            name='contract_number',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name=b'SalesForce Contract Number'),
        ),
        migrations.AddField(
            model_name='creditlineitem',
            name='special_terms',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
