# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 09:27


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0228_auto_20170703_1112'),
        ('dash', '0229_auto_20170705_1233'),
    ]

    operations = [
    ]
