# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 12:23


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0230_merge_20170712_0927'),
        ('dash', '0230_auto_20170711_1639'),
    ]

    operations = [
    ]
