# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 14:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0231_merge_20170713_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishergroupentry',
            name='outbrain_amplify_publisher_id',
            field=models.CharField(blank=True, max_length=127, verbose_name=b'Special Outbrain Amplify publisher ID'),
        ),
        migrations.AddField(
            model_name='publishergroupentry',
            name='outbrain_section_id',
            field=models.CharField(blank=True, max_length=127, verbose_name=b'Special Outbrain section ID'),
        ),
    ]
