# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 13:17
from __future__ import unicode_literals

from django.db import migrations
from dash.constants import EmailTemplateType


class Migration(migrations.Migration):


    def load_data(apps, schema_editor):
        EmailTemplate = apps.get_model('dash', 'EmailTemplate')

        template = EmailTemplate.objects.get(template_type=EmailTemplateType.OEN_POSTCLICKKPI_CPA_FACTORS)
        template.subject = u'Zemanta CPA Optimization Factors'
        template.body = u'''Hi OEN,

    Please find current CPA optimization factors attached.

    Yours truly,
    Zemanta'''
        template.save()

    dependencies = [
        ('dash', '0231_merge_20170713_1223'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]