# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 12:32


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0233_auto_20170727_1236'),
        ('dash', '0232_auto_20170724_1446'),
    ]

    operations = [
    ]
