# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-30 15:40


from django.db import migrations
from dash.constants import EmailTemplateType


def load_data(apps, schema_editor):
    EmailTemplate = apps.get_model('dash', 'EmailTemplate')

    try:
        template = EmailTemplate.objects.get(template_type=EmailTemplateType.ASYNC_REPORT_FAIL)
    except EmailTemplate.DoesNotExist:
        template = EmailTemplate(subject='Your report failed', template_type=EmailTemplateType.ASYNC_REPORT_FAIL)

    template.body = '''Hi,

We were unable to generate the report you requested.
Please contact support at help@zemanta.com.

Report settings

Account: {account_name}
Campaign: {campaign_name}
Ad Group: {ad_group_name}
Date range: {start_date} - {end_date}
View: {tab_name}
Breakdowns: {breakdown}
Filters: {filters}
Totals included: {include_totals}
Columns: {columns}

Yours truly,
Zemanta
    '''
    template.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0235_auto_20170804_1312'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
