# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 11:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0236_report_failed_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishergroupentry',
            name='outbrain_engage_publisher_id',
            field=models.CharField(blank=True, max_length=127, verbose_name=b'Special Outbrain Engage publisher ID'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='whitelabel',
            field=models.CharField(blank=True, choices=[(b'adtechnacity', b'Adtechnacity'), (b'newscorp', b'Newscorp'), (b'greenpark', b'Green Park Content')], max_length=255),
        ),
    ]
