# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 08:31


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0237_auto_20170808_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledreport',
            name='last_sent_dt',
        ),
    ]
