# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-12 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0238_remove_scheduledreport_last_sent_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='whitelabel',
            field=models.CharField(blank=True, choices=[(b'adtechnacity', b'Adtechnacity'), (b'newscorp', b'Newscorp'), (b'burda', b'Burda'), (b'greenpark', b'Green Park Content')], max_length=255),
        ),
    ]
