# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 11:26


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0239_auto_20170908_1022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publisherblacklist',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='publisherblacklist',
            name='account',
        ),
        migrations.RemoveField(
            model_name='publisherblacklist',
            name='ad_group',
        ),
        migrations.RemoveField(
            model_name='publisherblacklist',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='publisherblacklist',
            name='source',
        ),
        migrations.AlterField(
            model_name='campaigngoal',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Time on Site - Seconds'), (5, b'CPC'), (4, b'$CPA'), (12, b'Cost per Completed Video View'), (10, b'Cost per New Visitor'), (3, b'Pageviews per Visit'), (9, b'Cost per Non-Bounced Visit'), (2, b'Max Bounce Rate'), (7, b'New Unique Visitors'), (8, b'Cost per Visit'), (11, b'Cost per Pageview')], default=1),
        ),
        migrations.DeleteModel(
            name='PublisherBlacklist',
        ),
    ]
