# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 12:50


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0240_auto_20170911_1126'),
        ('dash', '0239_auto_20170912_1024'),
    ]

    operations = [
    ]
