# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 11:26


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0243_auto_20171004_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroupsettings',
            name='click_capping_daily_click_budget',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
