# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 19:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0243_auto_20171004_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='GALinkedAccounts',
            fields=[
                ('customer_ga_account_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('zem_ga_account_email', models.CharField(max_length=254)),
                ('has_read_and_analyze', models.BooleanField()),
            ],
        ),
    ]
