# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0244_galinkedaccounts'),
        ('dash', '0244_adgroupsettings_click_capping_daily_click_budget'),
    ]

    operations = [
    ]
