# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 14:22


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0245_merge_20171013_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentad',
            name='label',
            field=models.CharField(default=b'', max_length=256),
        ),
    ]
