# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-17 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0246_auto_20171013_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='new_accounts_use_bcm_v2',
            field=models.BooleanField(default=True, help_text=b"New accounts created by this agency's users will have license fee and margin included into all costs.", verbose_name=b'Margins v2'),
        ),
    ]
