# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0247_auto_20171017_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFlag',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
