# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-09 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0249_auto_20171023_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='users',
        ),
    ]
