# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-09 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0250_auto_20171109_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('-created_dt',)},
        ),
        migrations.RemoveField(
            model_name='account',
            name='groups',
        ),
    ]
