# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-16 10:26


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0251_auto_20171109_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgroup',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
