# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0254_add_settings_id_to_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='new_settings',
            field=models.ForeignKey(blank=True, db_column=b'settings_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='latest_for_campaign', to='dash.CampaignSettings'),
        ),
    ]
