# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 10:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0258_update_settings_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='new_settings',
            new_name='settings',
        ),
        migrations.AlterField(
            model_name='account',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='latest_for_account', to='dash.AccountSettings'),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='created_dt',
            field=models.DateTimeField(verbose_name=b'Created at'),
        ),

        migrations.RenameField(
            model_name='campaign',
            old_name='new_settings',
            new_name='settings',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='latest_for_campaign', to='dash.CampaignSettings'),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dash.Campaign'),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='created_dt',
            field=models.DateTimeField(verbose_name=b'Created at'),
        ),

        migrations.RenameField(
            model_name='adgroup',
            old_name='new_settings',
            new_name='settings',
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='latest_for_ad_group', to='dash.AdGroupSettings'),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='created_dt',
            field=models.DateTimeField(verbose_name=b'Created at'),
        ),

        migrations.RenameField(
            model_name='adgroupsource',
            old_name='new_settings',
            new_name='settings',
        ),
        migrations.AlterField(
            model_name='adgroupsource',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='latest_for_ad_group_source', to='dash.AdGroupSourceSettings'),
        ),
        migrations.AlterField(
            model_name='adgroupsourcesettings',
            name='ad_group_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dash.AdGroupSource'),
        ),
        migrations.AlterField(
            model_name='adgroupsourcesettings',
            name='created_dt',
            field=models.DateTimeField(verbose_name=b'Created at'),
        ),
    ]
