# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0259_auto_20171124_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uses_bcm_v2',
            field=models.BooleanField(default=True, help_text=b'This account will have license fee and margin included into all costs.', verbose_name=b'Margins v2'),
        ),
    ]
