# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 14:37


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0265_adgroupsource_settings_onetoone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='real_time_campaign_stop',
            field=models.BooleanField(default=False, help_text=b'Campaigns of this account will use real time campaign stop instead of landing mode.', verbose_name=b'Default to real time campaign stop'),
        ),
    ]
