# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 13:14


import core.features.history.history_mixin
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dash", "0266_account_real_time_campaign_stop"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgencySettings",
            fields=[
                ("created_dt", models.DateTimeField(verbose_name=b"Created at")),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "whitelist_publisher_groups",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(), blank=True, default=list, size=None
                    ),
                ),
                (
                    "blacklist_publisher_groups",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(), blank=True, default=list, size=None
                    ),
                ),
                ("agency", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="dash.Agency")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("-created_dt",)},
            bases=(models.Model, core.features.history.history_mixin.HistoryMixin),
        ),
        migrations.AddField(
            model_name="agency",
            name="settings",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="latest_for_entity",
                to="dash.AgencySettings",
            ),
        ),
    ]
