# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0268_auto_20180117_1456'),
        ('dash', '0268_agency_allowed_sources'),
    ]

    operations = [
    ]
