# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0269_merge_20180117_1622'),
        ('dash', '0267_account_currency'),
    ]

    operations = [
    ]
