# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0271_currencyexchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsettings',
            name='language',
            field=models.IntegerField(choices=[(15, b'Swedish'), (12, b'Portuguese'), (16, b'Turkish'), (2, b'German'), (11, b'Dutch'), (7, b'Indonesian'), (6, b'French'), (9, b'Japanese'), (3, b'Greek'), (1, b'English'), (4, b'Arabic'), (19, b'Traditional Chinese'), (8, b'Italian'), (17, b'Vietnamese'), (13, b'Romanian'), (18, b'Simplified Chinese'), (10, b'Malay'), (5, b'Spanish'), (14, b'Russian')], default=1),
        ),
    ]
