# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 15:38


from django.db import migrations, models

remap = {
    '1': 'en',
    '2': 'de',
    '3': 'el',
    '4': 'ar',
    '5': 'es',
    '6': 'fr',
    '7': 'id',
    '8': 'it',
    '9': 'ja',
    '10': 'ms',
    '11': 'nl',
    '12': 'pt',
    '13': 'ro',
    '14': 'ru',
    '15': 'sv',
    '16': 'tr',
    '17': 'vi',
    '18': 'zh_CN',
    '19': 'zh_TW',
}


def remap_languages(apps, schema_editor):
    CampaignSettings = apps.get_model('dash', 'CampaignSettings')
    for old_language, new_language in list(remap.items()):
        CampaignSettings.objects.filter(language=old_language).update(language=new_language)


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0272_campaignsettings_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='allowed_sources',
            field=models.ManyToManyField(blank=True, to='dash.Source'),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='language',
            field=models.SlugField(choices=[(b'sv', b'Swedish'), (b'pt', b'Portuguese'), (b'tr', b'Turkish'), (b'de', b'German'), (b'nl', b'Dutch'), (b'id', b'Indonesian'), (b'fr', b'French'), (b'ja', b'Japanese'), (b'el', b'Greek'), (b'en', b'English'), (b'ar', b'Arabic'), (b'zh_TW', b'Traditional Chinese'), (b'it', b'Italian'), (b'vi', b'Vietnamese'), (b'ro', b'Romanian'), (b'zh_CN', b'Simplified Chinese'), (b'ms', b'Malay'), (b'es', b'Spanish'), (b'ru', b'Russian')], default=b'en'),
        ),
        migrations.RunPython(remap_languages)
    ]
