# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0275_auto_20180201_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='default_blacklist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blacklisted_agencies', to='dash.PublisherGroup'),
        ),
        migrations.AddField(
            model_name='agency',
            name='default_whitelist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='whitelisted_agencies', to='dash.PublisherGroup'),
        ),
    ]
