# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 14:16


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0276_auto_20180202_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentad',
            name='description',
            field=models.CharField(blank=True, default=b'', max_length=150),
        ),
    ]
