# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 10:00
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0277_auto_20180206_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='account',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='account',
            name='real_time_campaign_stop',
            field=models.BooleanField(default=False, help_text='Campaigns of this account will use real time campaign stop instead of landing mode.', verbose_name='Default to real time campaign stop'),
        ),
        migrations.AlterField(
            model_name='account',
            name='uses_bcm_v2',
            field=models.BooleanField(default=False, help_text='This account will have license fee and margin included into all costs.', verbose_name='Margins v2'),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='account_type',
            field=models.IntegerField(choices=[(1, 'Unknown'), (2, 'Test'), (3, 'Sandbox'), (4, 'Pilot'), (5, 'Activated'), (6, 'Managed'), (7, 'PAAS')], default=1),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='created_dt',
            field=models.DateTimeField(verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='ad_group_name',
            field=models.CharField(blank=True, default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='autopilot_daily_budget',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True, verbose_name="Autopilot's Daily Spend Cap"),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='autopilot_state',
            field=models.IntegerField(blank=True, choices=[(1, 'Optimize Bids and Daily Spend Caps'), (2, 'Disabled'), (3, 'Optimize Bids')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='b1_sources_group_cpc_cc',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.01'), max_digits=10, verbose_name="Bidder's Bid CPC"),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='b1_sources_group_daily_budget',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name="Bidder's Daily Cap"),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='b1_sources_group_state',
            field=models.IntegerField(choices=[(1, 'Enabled'), (2, 'Paused')], default=2),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='brand_name',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='call_to_action',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='cpc_cc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Maximum CPC'),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='created_dt',
            field=models.DateTimeField(verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='daily_budget_cc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Daily spend cap'),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='delivery_type',
            field=models.IntegerField(choices=[(1, 'Standard'), (2, 'Accelerated')], default=1),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='description',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='display_url',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='max_cpm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Maximum CPM'),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='state',
            field=models.IntegerField(choices=[(1, 'Enabled'), (2, 'Paused')], default=2),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='system_user',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Campaign Stop'), (2, 'Zemanta Autopilot'), (3, 'System User ')], null=True),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='target_os',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Operating System'),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='target_placements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, null=True, size=None, verbose_name='Placement'),
        ),
        migrations.AlterField(
            model_name='adgroupsourcesettings',
            name='cpc_cc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='CPC'),
        ),
        migrations.AlterField(
            model_name='adgroupsourcesettings',
            name='created_dt',
            field=models.DateTimeField(verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='adgroupsourcesettings',
            name='daily_budget_cc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Daily spend cap'),
        ),
        migrations.AlterField(
            model_name='adgroupsourcesettings',
            name='state',
            field=models.IntegerField(choices=[(1, 'Enabled'), (2, 'Paused')], default=2),
        ),
        migrations.AlterField(
            model_name='adgroupsourcesettings',
            name='system_user',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Campaign Stop'), (2, 'Zemanta Autopilot'), (3, 'System User ')], null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='custom_dashboard_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='agency',
            name='custom_favicon_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='agency',
            name='default_account_type',
            field=models.IntegerField(choices=[(1, 'Unknown'), (2, 'Test'), (3, 'Sandbox'), (4, 'Pilot'), (5, 'Activated'), (6, 'Managed'), (7, 'PAAS')], default=1),
        ),
        migrations.AlterField(
            model_name='agency',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='new_accounts_use_bcm_v2',
            field=models.BooleanField(default=True, help_text="New accounts created by this agency's users will have license fee and margin included into all costs.", verbose_name='Margins v2'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='whitelabel',
            field=models.CharField(blank=True, choices=[('greenpark', 'Green Park Content'), ('adtechnacity', 'Adtechnacity'), ('newscorp', 'Newscorp'), ('burda', 'Burda'), ('mediamond', 'Mediamond')], max_length=255),
        ),
        migrations.AlterField(
            model_name='agencysettings',
            name='created_dt',
            field=models.DateTimeField(verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='audience',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='audience',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='audiencerule',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Starts with'), (2, 'Contains'), (3, 'Not starts with'), (4, 'Not contains'), (5, 'Visit')]),
        ),
        migrations.AlterField(
            model_name='bluekaicategory',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='bluekaicategory',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=2),
        ),
        migrations.AlterField(
            model_name='budgethistory',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='budgetlineitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='budgetlineitem',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='budgetlineitem',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='campaigngoal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='campaigngoal',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='campaigngoal',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Time on Site - Seconds'), (2, 'Max Bounce Rate'), (3, 'Pageviews per Visit'), (4, '$CPA'), (5, 'CPC'), (7, 'New Unique Visitors'), (8, 'Cost per Visit'), (9, 'Cost per Non-Bounced Visit'), (10, 'Cost per New Visitor'), (11, 'Cost per Pageview'), (12, 'Cost per Completed Video View')], default=1),
        ),
        migrations.AlterField(
            model_name='campaigngoalvalue',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='campaigngoalvalue',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='adobe_tracking_param',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='campaign_goal',
            field=models.IntegerField(choices=[(1, 'CPA'), (2, '% bounce rate'), (3, 'new unique visitors'), (4, 'seconds time on site'), (5, 'pages per session')], default=3),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='created_dt',
            field=models.DateTimeField(verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='ga_property_id',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='ga_tracking_type',
            field=models.IntegerField(choices=[(1, 'Email'), (2, 'API')], default=1),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='iab_category',
            field=models.SlugField(choices=[('IAB1', 'Arts & Entertainment'), ('IAB1-1', 'Books & Literature'), ('IAB1-2', 'Celebrity Fan/Gossip'), ('IAB1-3', 'Fine Art'), ('IAB1-4', 'Humor'), ('IAB1-5', 'Movies'), ('IAB1-6', 'Music'), ('IAB1-7', 'Television'), ('IAB2', 'Automotive'), ('IAB2-1', 'Auto Parts'), ('IAB2-2', 'Auto Repair'), ('IAB2-3', 'Buying/Selling Cars'), ('IAB2-4', 'Car Culture'), ('IAB2-5', 'Certified Pre-Owned'), ('IAB2-6', 'Convertible'), ('IAB2-7', 'Coupe'), ('IAB2-8', 'Crossover'), ('IAB2-9', 'Diesel'), ('IAB2-10', 'Electric Vehicle'), ('IAB2-11', 'Hatchback'), ('IAB2-12', 'Hybrid'), ('IAB2-13', 'Luxury'), ('IAB2-14', 'MiniVan'), ('IAB2-15', 'Mororcycles'), ('IAB2-16', 'Off-Road Vehicles'), ('IAB2-17', 'Performance Vehicles'), ('IAB2-18', 'Pickup'), ('IAB2-19', 'Road-Side Assistance'), ('IAB2-20', 'Sedan'), ('IAB2-21', 'Trucks & Accessories'), ('IAB2-22', 'Vintage Cars'), ('IAB2-23', 'Wagon'), ('IAB3', 'Business'), ('IAB3-1', 'Advertising'), ('IAB3-2', 'Agriculture'), ('IAB3-3', 'Biotech/Biomedical'), ('IAB3-4', 'Business Software'), ('IAB3-5', 'Construction'), ('IAB3-6', 'Forestry'), ('IAB3-7', 'Government'), ('IAB3-8', 'Green Solutions'), ('IAB3-9', 'Human Resources'), ('IAB3-10', 'Logistics'), ('IAB3-11', 'Marketing'), ('IAB3-12', 'Metals'), ('IAB4', 'Careers'), ('IAB4-1', 'Career Planning'), ('IAB4-2', 'College'), ('IAB4-3', 'Financial Aid'), ('IAB4-4', 'Job Fairs'), ('IAB4-5', 'Job Search'), ('IAB4-6', 'Resume Writing/Advice'), ('IAB4-7', 'Nursing'), ('IAB4-8', 'Scholarships'), ('IAB4-9', 'Telecommuting'), ('IAB4-10', 'U.S. Military'), ('IAB4-11', 'Career Advice'), ('IAB5', 'Education'), ('IAB5-1', '7-12 Education'), ('IAB5-2', 'Adult Education'), ('IAB5-3', 'Art History'), ('IAB5-4', 'Colledge Administration'), ('IAB5-5', 'College Life'), ('IAB5-6', 'Distance Learning'), ('IAB5-7', 'English as a 2nd Language'), ('IAB5-8', 'Language Learning'), ('IAB5-9', 'Graduate School'), ('IAB5-10', 'Homeschooling'), ('IAB5-11', 'Homework/Study Tips'), ('IAB5-12', 'K-6 Educators'), ('IAB5-13', 'Private School'), ('IAB5-14', 'Special Education'), ('IAB5-15', 'Studying Business'), ('IAB6', 'Family & Parenting'), ('IAB6-1', 'Adoption'), ('IAB6-2', 'Babies & Toddlers'), ('IAB6-3', 'Daycare/Pre School'), ('IAB6-4', 'Family Internet'), ('IAB6-5', 'Parenting - K-6 Kids'), ('IAB6-6', 'Parenting teens'), ('IAB6-7', 'Pregnancy'), ('IAB6-8', 'Special Needs Kids'), ('IAB6-9', 'Eldercare'), ('IAB7', 'Health & Fitness'), ('IAB7-1', 'Exercise'), ('IAB7-2', 'A.D.D.'), ('IAB7-3', 'AIDS/HIV'), ('IAB7-4', 'Allergies'), ('IAB7-5', 'Alternative Medicine'), ('IAB7-6', 'Arthritis'), ('IAB7-7', 'Asthma'), ('IAB7-8', 'Autism/PDD'), ('IAB7-9', 'Bipolar Disorder'), ('IAB7-10', 'Brain Tumor'), ('IAB7-11', 'Cancer'), ('IAB7-12', 'Cholesterol'), ('IAB7-13', 'Chronic Fatigue Syndrome'), ('IAB7-14', 'Chronic Pain'), ('IAB7-15', 'Cold & Flu'), ('IAB7-16', 'Deafness'), ('IAB7-17', 'Dental Care'), ('IAB7-18', 'Depression'), ('IAB7-19', 'Dermatology'), ('IAB7-20', 'Diabetes'), ('IAB7-21', 'Epilepsy'), ('IAB7-22', 'GERD/Acid Reflux'), ('IAB7-23', 'Headaches/Migraines'), ('IAB7-24', 'Heart Disease'), ('IAB7-25', 'Herbs for Health'), ('IAB7-26', 'Holistic Healing'), ('IAB7-27', "IBS/Crohn's Disease"), ('IAB7-28', 'Incest/Abuse Support'), ('IAB7-29', 'Incontinence'), ('IAB7-30', 'Infertility'), ('IAB7-31', "Men's Health"), ('IAB7-32', 'Nutrition'), ('IAB7-33', 'Orthopedics'), ('IAB7-34', 'Panic/Anxiety Disorders'), ('IAB7-35', 'Pediatrics'), ('IAB7-36', 'Physical Therapy'), ('IAB7-37', 'Psychology/Psychiatry'), ('IAB7-38', 'Senior Health'), ('IAB7-39', 'Sexuality'), ('IAB7-40', 'Sleep Disorders'), ('IAB7-41', 'Smoking Cessation'), ('IAB7-42', 'Substance Abuse'), ('IAB7-43', 'Thyroid Disease'), ('IAB7-44', 'Weight Loss'), ('IAB7-45', "Women's Health"), ('IAB8', 'Food & Drink'), ('IAB8-1', 'American Cuisine'), ('IAB8-2', 'Barbecues & Grilling'), ('IAB8-3', 'Cajun/Creole'), ('IAB8-4', 'Chinese Cuisine'), ('IAB8-5', 'Cocktails/Beer'), ('IAB8-6', 'Coffee/Tea'), ('IAB8-7', 'Cuisine-Specific'), ('IAB8-8', 'Desserts & Baking'), ('IAB8-9', 'Dining Out'), ('IAB8-10', 'Food Allergies'), ('IAB8-11', 'French Cuisine'), ('IAB8-12', 'Health/Lowfat Cooking'), ('IAB8-13', 'Italian Cuisine'), ('IAB8-14', 'Japanese Cuisine'), ('IAB8-15', 'Mexican Cuisine'), ('IAB8-16', 'Vegan'), ('IAB8-17', 'Vegetarian'), ('IAB8-18', 'Wine'), ('IAB9', 'Hobbies & Interests'), ('IAB9-1', 'Art/Technology'), ('IAB9-2', 'Arts & Crafts'), ('IAB9-3', 'Beadwork'), ('IAB9-4', 'Birdwatching'), ('IAB9-5', 'Board Games/Puzzles'), ('IAB9-6', 'Candle & Soap Making'), ('IAB9-7', 'Card Games'), ('IAB9-8', 'Chess'), ('IAB9-9', 'Cigars'), ('IAB9-10', 'Collecting'), ('IAB9-11', 'Comic Books'), ('IAB9-12', 'Drawing/Sketching'), ('IAB9-13', 'Freelance Writing'), ('IAB9-14', 'Genealogy'), ('IAB9-15', 'Getting Published'), ('IAB9-16', 'Guitar'), ('IAB9-17', 'Home Recording'), ('IAB9-18', 'Investors & Patents'), ('IAB9-19', 'Jewelry Making'), ('IAB9-20', 'Magic & Illusion'), ('IAB9-21', 'Needlework'), ('IAB9-22', 'Painting'), ('IAB9-23', 'Photography'), ('IAB9-24', 'Radio'), ('IAB9-25', 'Roleplaying Games'), ('IAB9-26', 'Sci-Fi & Fantasy'), ('IAB9-27', 'Scrapbooking'), ('IAB9-28', 'Screenwriting'), ('IAB9-29', 'Stamps & Coins'), ('IAB9-30', 'Video & Computer Games'), ('IAB9-31', 'Woodworking'), ('IAB10', 'Home & Garden'), ('IAB10-1', 'Appliances'), ('IAB10-2', 'Entertaining'), ('IAB10-3', 'Environmental Safety'), ('IAB10-4', 'Gardening'), ('IAB10-5', 'Home Repair'), ('IAB10-6', 'Home Theater'), ('IAB10-7', 'Interior Decorating'), ('IAB10-8', 'Landscaping'), ('IAB10-9', 'Remodeling & Construction'), ('IAB11', "Law, Gov't & Politics"), ('IAB11-1', 'Immigration'), ('IAB11-2', 'Legal Issues'), ('IAB11-3', 'U.S. Government Resources'), ('IAB11-4', 'Politics'), ('IAB11-5', 'Commentary'), ('IAB12', 'News'), ('IAB12-1', 'International News'), ('IAB12-2', 'National News'), ('IAB12-3', 'Local News'), ('IAB13', 'Personal Finance'), ('IAB13-1', 'Beginning Investing'), ('IAB13-2', 'Credit/Debt & Loans'), ('IAB13-3', 'Financial News'), ('IAB13-4', 'Financial Planning'), ('IAB13-5', 'Hedge Fund'), ('IAB13-6', 'Insurance'), ('IAB13-7', 'Investing'), ('IAB13-8', 'Mutual Funds'), ('IAB13-9', 'Options'), ('IAB13-10', 'Retirement Planning'), ('IAB13-11', 'Stocks'), ('IAB13-12', 'Tax Planning'), ('IAB14', 'Society'), ('IAB14-1', 'Dating'), ('IAB14-2', 'Divorce Support'), ('IAB14-3', 'Gay Life'), ('IAB14-4', 'Marriage'), ('IAB14-5', 'Senior Living'), ('IAB14-6', 'Teens'), ('IAB14-7', 'Weddings'), ('IAB14-8', 'Ethnic Specific'), ('IAB15', 'Science'), ('IAB15-1', 'Astrology'), ('IAB15-2', 'Biology'), ('IAB15-3', 'Chemistry'), ('IAB15-4', 'Geology'), ('IAB15-5', 'Paranormal Phenomena'), ('IAB15-6', 'Physics'), ('IAB15-7', 'Space/Astronomy'), ('IAB15-8', 'Geography'), ('IAB15-9', 'Botany'), ('IAB15-10', 'Weather'), ('IAB16', 'Pets'), ('IAB16-1', 'Aquariums'), ('IAB16-2', 'Birds'), ('IAB16-3', 'Cats'), ('IAB16-4', 'Dogs'), ('IAB16-5', 'Large Animals'), ('IAB16-6', 'Reptiles'), ('IAB16-7', 'Veterinary Medicine'), ('IAB17', 'Sports'), ('IAB17-1', 'Auto Racing'), ('IAB17-2', 'Baseball'), ('IAB17-3', 'Bicycling'), ('IAB17-4', 'Bodybuilding'), ('IAB17-5', 'Boxing'), ('IAB17-6', 'Canoeing/Kayaking'), ('IAB17-7', 'Cheerleading'), ('IAB17-8', 'Climbing'), ('IAB17-9', 'Cricket'), ('IAB17-10', 'Figure Skating'), ('IAB17-11', 'Fly Fishing'), ('IAB17-12', 'Football'), ('IAB17-13', 'Freshwater Fishing'), ('IAB17-14', 'Game & Fish'), ('IAB17-15', 'Golf'), ('IAB17-16', 'Horse Racing'), ('IAB17-17', 'Horses'), ('IAB17-18', 'Hunting/Shooting'), ('IAB17-19', 'Inline Skating'), ('IAB17-20', 'Martial Arts'), ('IAB17-21', 'Mountain Biking'), ('IAB17-22', 'NASCAR Racing'), ('IAB17-23', 'Olympics'), ('IAB17-24', 'Paintball'), ('IAB17-25', 'Power & Motorcycles'), ('IAB17-26', 'Pro Basketball'), ('IAB17-27', 'Pro Ice Hockey'), ('IAB17-28', 'Rodeo'), ('IAB17-29', 'Rugby'), ('IAB17-30', 'Running/Jogging'), ('IAB17-31', 'Sailing'), ('IAB17-32', 'Saltwater Fishing'), ('IAB17-33', 'Scuba Diving'), ('IAB17-34', 'Skateboarding'), ('IAB17-35', 'Skiing'), ('IAB17-36', 'Snowboarding'), ('IAB17-37', 'Surfing/Bodyboarding'), ('IAB17-38', 'Swimming'), ('IAB17-39', 'Table Tennis/Ping-Pong'), ('IAB17-40', 'Tennis'), ('IAB17-41', 'Volleyball'), ('IAB17-42', 'Walking'), ('IAB17-43', 'Waterski/Wakeboard'), ('IAB17-44', 'World Soccer'), ('IAB18', 'Style & Fashion'), ('IAB18-1', 'Beauty'), ('IAB18-2', 'Body Art'), ('IAB18-3', 'Fashion'), ('IAB18-4', 'Jewelry'), ('IAB18-5', 'Clothing'), ('IAB18-6', 'Accessories'), ('IAB19', 'Technology & Computing'), ('IAB19-1', '3-D Graphics'), ('IAB19-2', 'Animation'), ('IAB19-3', 'Antivirus Software'), ('IAB19-4', 'C/C++'), ('IAB19-5', 'Cameras & Camcorders'), ('IAB19-6', 'Cell Phones'), ('IAB19-7', 'Computer Certification'), ('IAB19-8', 'Computer Networking'), ('IAB19-9', 'Computer Peripherals'), ('IAB19-10', 'Computer Reviews'), ('IAB19-11', 'Data Centers'), ('IAB19-12', 'Databases'), ('IAB19-13', 'Desktop Publishing'), ('IAB19-14', 'Desktop Video'), ('IAB19-15', 'Email'), ('IAB19-16', 'Graphics Software'), ('IAB19-17', 'Home Video/DVD'), ('IAB19-18', 'Internet Technology'), ('IAB19-19', 'Java'), ('IAB19-20', 'JavaScript'), ('IAB19-21', 'Mac Support'), ('IAB19-22', 'MP3/MIDI'), ('IAB19-23', 'Net Conferencing'), ('IAB19-24', 'Net for Beginners'), ('IAB19-25', 'Network Security'), ('IAB19-26', 'Palmtops/PDAs'), ('IAB19-27', 'PC Support'), ('IAB19-28', 'Portable'), ('IAB19-29', 'Entertainment'), ('IAB19-30', 'Shareware/Freeware'), ('IAB19-31', 'Unix'), ('IAB19-32', 'Visual Basic'), ('IAB19-33', 'Web Clip Art'), ('IAB19-34', 'Web Design/HTML'), ('IAB19-35', 'Web Search'), ('IAB19-36', 'Windows'), ('IAB20', 'Travel'), ('IAB20-1', 'Adventure Travel'), ('IAB20-2', 'Africa'), ('IAB20-3', 'Air Travel'), ('IAB20-4', 'Australia & New Zealand'), ('IAB20-5', 'Bed & Breakfasts'), ('IAB20-6', 'Budget Travel'), ('IAB20-7', 'Business Travel'), ('IAB20-8', 'By US Locale'), ('IAB20-9', 'Camping'), ('IAB20-10', 'Canada'), ('IAB20-11', 'Caribbean'), ('IAB20-12', 'Cruises'), ('IAB20-13', 'Eastern Europe'), ('IAB20-14', 'Europe'), ('IAB20-15', 'France'), ('IAB20-16', 'Greece'), ('IAB20-17', 'Honeymoons/Getaways'), ('IAB20-18', 'Hotels'), ('IAB20-19', 'Italy'), ('IAB20-20', 'Japan'), ('IAB20-21', 'Mexico & Central America'), ('IAB20-22', 'National Parks'), ('IAB20-23', 'South America'), ('IAB20-24', 'Spas'), ('IAB20-25', 'Theme Parks'), ('IAB20-26', 'Traveling with Kids'), ('IAB20-27', 'United Kingdom'), ('IAB21', 'Real Estate'), ('IAB21-1', 'Apartments'), ('IAB21-2', 'Architects'), ('IAB21-3', 'Buying/Selling Homes'), ('IAB22', 'Shopping'), ('IAB22-1', 'Contests & Freebies'), ('IAB22-2', 'Couponing'), ('IAB22-3', 'Comparison'), ('IAB22-4', 'Engines'), ('IAB23', 'Religion & Spirituality'), ('IAB23-1', 'Alternative Religions'), ('IAB23-2', 'Atheism/Agnosticism'), ('IAB23-3', 'Buddhism'), ('IAB23-4', 'Catholicism'), ('IAB23-5', 'Christianity'), ('IAB23-6', 'Hinduism'), ('IAB23-7', 'Islam'), ('IAB23-8', 'Judaism'), ('IAB23-9', 'Latter-Day Saints'), ('IAB23-10', 'Pagan/Wiccan'), ('IAB24', 'Uncategorized'), ('IAB25', 'Non-Standard Content'), ('IAB25-1', 'Unmoderated UGC'), ('IAB25-2', 'Extreme Graphic/Explicit Violence'), ('IAB25-3', 'Pornography'), ('IAB25-4', 'Profane Content'), ('IAB25-5', 'Hate Content'), ('IAB25-6', 'Under Construction'), ('IAB25-7', 'Incentivized'), ('IAB26', 'Illegal Content'), ('IAB26-1', 'Illegal Content'), ('IAB26-2', 'Warez'), ('IAB26-3', 'Spyware/Malware'), ('IAB26-4', 'CopyrightInfringement')], default='IAB24', max_length=10),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='language',
            field=models.SlugField(choices=[('en', 'English'), ('de', 'German'), ('el', 'Greek'), ('ar', 'Arabic'), ('es', 'Spanish'), ('fr', 'French'), ('id', 'Indonesian'), ('it', 'Italian'), ('ja', 'Japanese'), ('ms', 'Malay'), ('nl', 'Dutch'), ('pt', 'Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sv', 'Swedish'), ('tr', 'Turkish'), ('vi', 'Vietnamese'), ('zh_CN', 'Simplified Chinese'), ('zh_TW', 'Traditional Chinese'), ('any', 'Other')], default='en', null=True),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='promotion_goal',
            field=models.IntegerField(choices=[(1, 'Brand Building'), (2, 'Traffic Acquisition'), (3, 'Conversions')], default=1),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='system_user',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Campaign Stop'), (2, 'Zemanta Autopilot'), (3, 'System User ')], null=True),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='target_os',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Operating Systems'),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='target_placements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, null=True, size=None, verbose_name='Placement'),
        ),
        migrations.AlterField(
            model_name='contentad',
            name='brand_name',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='contentad',
            name='call_to_action',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='contentad',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='contentad',
            name='description',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='contentad',
            name='display_url',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='contentad',
            name='image_crop',
            field=models.CharField(default='center', max_length=25),
        ),
        migrations.AlterField(
            model_name='contentad',
            name='label',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='contentad',
            name='state',
            field=models.IntegerField(choices=[(1, 'Enabled'), (2, 'Paused')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='contentadcandidate',
            name='brand_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='contentadcandidate',
            name='call_to_action',
            field=models.TextField(blank=True, default='Read more', null=True),
        ),
        migrations.AlterField(
            model_name='contentadcandidate',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='contentadcandidate',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='contentadcandidate',
            name='display_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='contentadcandidate',
            name='image_crop',
            field=models.TextField(blank=True, default='center', null=True),
        ),
        migrations.AlterField(
            model_name='contentadcandidate',
            name='image_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Waiting for response'), (3, 'OK'), (4, 'Failed')], default=1),
        ),
        migrations.AlterField(
            model_name='contentadcandidate',
            name='label',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='contentadcandidate',
            name='title',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='contentadcandidate',
            name='url',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='contentadcandidate',
            name='url_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Waiting for response'), (3, 'OK'), (4, 'Failed')], default=1),
        ),
        migrations.AlterField(
            model_name='contentadsource',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='contentadsource',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='contentadsource',
            name='source_state',
            field=models.IntegerField(choices=[(1, 'Enabled'), (2, 'Paused')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='contentadsource',
            name='state',
            field=models.IntegerField(choices=[(1, 'Enabled'), (2, 'Paused')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='contentadsource',
            name='submission_status',
            field=models.IntegerField(choices=[(-1, 'Not submitted'), (1, 'Pending'), (2, 'Approved'), (3, 'Rejected'), (4, 'Limit reached')], default=-1),
        ),
        migrations.AlterField(
            model_name='conversiongoal',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='conversiongoal',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Conversion Pixel'), (2, 'Google Analytics'), (3, 'Adobe Analytics')]),
        ),
        migrations.AlterField(
            model_name='conversionpixel',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='cpcconstraint',
            name='constraint_type',
            field=models.IntegerField(choices=[(1, 'Manual'), (2, 'Outbrain blacklist')], default=1),
        ),
        migrations.AlterField(
            model_name='cpcconstraint',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='cpcconstraint',
            name='max_cpc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Maximum CPC'),
        ),
        migrations.AlterField(
            model_name='cpcconstraint',
            name='min_cpc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Minimum CPC'),
        ),
        migrations.AlterField(
            model_name='credithistory',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='creditlineitem',
            name='contract_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='SalesForce Contract ID'),
        ),
        migrations.AlterField(
            model_name='creditlineitem',
            name='contract_number',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='SalesForce Contract Number'),
        ),
        migrations.AlterField(
            model_name='creditlineitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='creditlineitem',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='creditlineitem',
            name='flat_fee_cc',
            field=models.IntegerField(default=0, verbose_name='Flat fee (cc)'),
        ),
        migrations.AlterField(
            model_name='creditlineitem',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='creditlineitem',
            name='status',
            field=models.IntegerField(choices=[(1, 'Signed'), (2, 'Pending'), (3, 'Canceled')], default=2),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro')], max_length=3),
        ),
        migrations.AlterField(
            model_name='customflag',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='customhack',
            name='confirmed_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmed at'),
        ),
        migrations.AlterField(
            model_name='customhack',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='customhack',
            name='removed_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removed at'),
        ),
        migrations.AlterField(
            model_name='customhack',
            name='service',
            field=models.CharField(choices=[('z1', 'Zemanta One'), ('k1', 'Konsistency One'), ('r1', 'Redirector'), ('b1', 'Bidder')], default='z1', max_length=255),
        ),
        migrations.AlterField(
            model_name='defaultsourcesettings',
            name='daily_budget_cc',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='This setting has moved. See Source model.', max_digits=10, null=True, verbose_name='Default daily spend cap'),
        ),
        migrations.AlterField(
            model_name='defaultsourcesettings',
            name='default_cpc_cc',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='This setting has moved. See Source model.', max_digits=10, null=True, verbose_name='Default CPC'),
        ),
        migrations.AlterField(
            model_name='defaultsourcesettings',
            name='mobile_cpc_cc',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='This setting has moved. See Source model.', max_digits=10, null=True, verbose_name='Default CPC (if ad group is targeting mobile only)'),
        ),
        migrations.AlterField(
            model_name='defaultsourcesettings',
            name='params',
            field=jsonfield.fields.JSONField(blank=True, default={}, help_text='Information about format can be found here: <a href="https://sites.google.com/a/zemanta.com/root/content-ads-dsp/additional-source-parameters-format" target="_blank">Zemanta Pages</a>', verbose_name='Additional action parameters'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ad group settings change'), (2, 'Campaign settings change'), (3, 'Budget change'), (4, 'New conversion pixel'), (5, 'User password reset'), (6, 'New user introduction email'), (7, 'Supply report'), (8, 'Scheduled report'), (9, 'Depleting budget notification'), (10, 'Campaign stopped notification'), (11, 'Autopilot changes notification'), (12, 'Autopilot initialisation notification'), (13, 'Campaign switched to landing mode notification'), (14, 'Campaign is running out of budget notification'), (15, 'Demo is running'), (16, 'Livestream sesion id'), (17, 'Daily management report'), (18, 'Unused Outbrain accounts running out'), (19, 'Google Analytics Setup Instructions'), (20, 'Report results'), (21, 'Depleting credits'), (22, None), (23, 'Weekly client report'), (24, 'Pacing notification'), (25, 'Weekly inventory report'), (26, 'New device login'), (27, 'Scheduled report results'), (28, 'Zemanta OEN CPA Optimization Factors'), (29, 'Report fail')], null=True),
        ),
        migrations.AlterField(
            model_name='exportreport',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='exportreport',
            name='granularity',
            field=models.IntegerField(choices=[(1, 'All Accounts'), (2, 'Account'), (3, 'Campaign'), (4, 'Ad Group'), (5, 'Content Ad')], default=5),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='status',
            field=models.IntegerField(choices=[(1, 'Empty'), (2, 'Connected'), (3, 'Pending'), (4, 'Invalid'), (5, 'Error')], default=1),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='type',
            field=models.CharField(choices=[('co', 'Country'), ('re', 'Region'), ('ci', 'City'), ('dma', 'DMA'), ('zip', 'Postal Code')], max_length=3),
        ),
        migrations.AlterField(
            model_name='history',
            name='action_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Change Campaign Goal'), (2, 'Change Budget'), (3, 'Change Credit'), (4, 'Set Publisher Blacklist'), (5, 'Set Global Publisher Blacklist'), (6, 'Manage Reporting'), (7, 'Set Content Ad(s) State'), (8, 'Change Settings'), (9, 'Create'), (10, 'Create Content Ad'), (11, 'Create Conversion Pixel'), (12, 'Archive/Restore Conversion Pixel'), (13, 'Archive/Restore'), (14, 'Archive/Restore Content Ad(s)'), (15, 'Set Media Source Settings'), (16, 'Add Media Source'), (17, 'Rename conversion pixel'), (18, 'Create custom audience'), (19, 'Archive custom audience'), (20, 'Restore custom audience'), (22, 'Update custom audience'), (21, 'Enable pixel for building audiences'), (23, 'Set redirect url for pixel'), (24, 'Remove redirect url for pixel'), (25, 'Create publisher group'), (26, 'Update publisher group'), (26, 'Update publisher group')], null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='history',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ad Group Level'), (2, 'Campaign Level'), (3, 'Account Level'), (4, 'Agency Level'), (5, 'All Accounts')]),
        ),
        migrations.AlterField(
            model_name='history',
            name='system_user',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Campaign Stop'), (2, 'Zemanta Autopilot'), (3, 'System User ')], null=True),
        ),
        migrations.AlterField(
            model_name='outbrainaccount',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='outbrainaccount',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='publisherbidmodifier',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='publisherbidmodifier',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='publisherbidmodifier',
            name='modifier',
            field=models.FloatField(verbose_name='Publisher bid modifier'),
        ),
        migrations.AlterField(
            model_name='publisherbidmodifier',
            name='publisher',
            field=models.CharField(max_length=127, verbose_name='Publisher name or domain'),
        ),
        migrations.AlterField(
            model_name='publishergroup',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='publishergroup',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='publishergroupentry',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='publishergroupentry',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='publishergroupentry',
            name='outbrain_amplify_publisher_id',
            field=models.CharField(blank=True, max_length=127, verbose_name='Special Outbrain Amplify publisher ID'),
        ),
        migrations.AlterField(
            model_name='publishergroupentry',
            name='outbrain_engage_publisher_id',
            field=models.CharField(blank=True, max_length=127, verbose_name='Special Outbrain Engage publisher ID'),
        ),
        migrations.AlterField(
            model_name='publishergroupentry',
            name='outbrain_publisher_id',
            field=models.CharField(blank=True, max_length=127, verbose_name='Special Outbrain publisher ID'),
        ),
        migrations.AlterField(
            model_name='publishergroupentry',
            name='outbrain_section_id',
            field=models.CharField(blank=True, max_length=127, verbose_name='Special Outbrain section ID'),
        ),
        migrations.AlterField(
            model_name='publishergroupentry',
            name='publisher',
            field=models.CharField(max_length=127, verbose_name='Publisher name or domain'),
        ),
        migrations.AlterField(
            model_name='reportjob',
            name='status',
            field=models.IntegerField(choices=[(1, 'Done'), (2, 'Failed'), (3, 'In progress'), (4, 'Cancelled')], default=3),
        ),
        migrations.AlterField(
            model_name='scheduledexportreport',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='scheduledexportreport',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1),
        ),
        migrations.AlterField(
            model_name='scheduledexportreport',
            name='sending_frequency',
            field=models.IntegerField(choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly')], default=1),
        ),
        migrations.AlterField(
            model_name='scheduledexportreport',
            name='state',
            field=models.IntegerField(choices=[(1, 'Enabled'), (2, 'Paused'), (3, 'Removed')], default=1),
        ),
        migrations.AlterField(
            model_name='scheduledexportreport',
            name='time_period',
            field=models.IntegerField(choices=[(1, 'Yesterday'), (2, 'Last 7 Days'), (3, 'Last 30 Days'), (4, 'This Week'), (5, 'Last Week'), (6, 'This Month'), (7, 'Last Month')], default=1),
        ),
        migrations.AlterField(
            model_name='scheduledexportreportlog',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='scheduledexportreportlog',
            name='state',
            field=models.IntegerField(choices=[(1, 'Success'), (2, 'Failed')], default=2),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='sending_frequency',
            field=models.IntegerField(choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly')], default=1),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='state',
            field=models.IntegerField(choices=[(1, 'Enabled'), (2, 'Paused'), (3, 'Removed')], default=1),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='time_period',
            field=models.IntegerField(choices=[(1, 'Yesterday'), (2, 'Last 7 Days'), (3, 'Last 30 Days'), (4, 'This Week'), (5, 'Last Week'), (6, 'This Month'), (7, 'Last Month')], default=1),
        ),
        migrations.AlterField(
            model_name='source',
            name='bidder_slug',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='B1 Slug'),
        ),
        migrations.AlterField(
            model_name='source',
            name='content_ad_submission_policy',
            field=models.IntegerField(choices=[(1, 'Automatic'), (2, 'Manual')], default=1, help_text='Designates weather content ads are submitted automatically'),
        ),
        migrations.AlterField(
            model_name='source',
            name='content_ad_submission_type',
            field=models.IntegerField(choices=[(1, 'Default'), (2, 'One submission per ad group'), (3, 'Submit whole batch at once')], default=1),
        ),
        migrations.AlterField(
            model_name='source',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='source',
            name='default_cpc_cc',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=10, verbose_name='Default CPC'),
        ),
        migrations.AlterField(
            model_name='source',
            name='default_daily_budget_cc',
            field=models.DecimalField(decimal_places=4, default=Decimal('10.00'), max_digits=10, verbose_name='Default daily spend cap'),
        ),
        migrations.AlterField(
            model_name='source',
            name='default_mobile_cpc_cc',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=10, verbose_name='Default CPC (if ad group is targeting mobile only)'),
        ),
        migrations.AlterField(
            model_name='source',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='source',
            name='tracking_slug',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tracking slug'),
        ),
        migrations.AlterField(
            model_name='sourcecredentials',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='sourcecredentials',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='cpc_decimal_places',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='CPC Decimal Places'),
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='delete_traffic_metrics_threshold',
            field=models.IntegerField(default=0, help_text="When we receive an empty report, we don't override existing data but we mark report aggregation as failed. But for smaller changes (as defined by this parameter), we do override existing data since they are not material. Zero value means no reports will get deleted.", verbose_name='Max clicks allowed to delete per daily report'),
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='max_cpc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Maximum CPC'),
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='max_daily_budget',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Maximum Daily Spend Cap'),
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='min_cpc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Minimum CPC'),
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='min_daily_budget',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Minimum Daily Spend Cap'),
        ),
        migrations.AlterField(
            model_name='sourcetypepixel',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='sourcetypepixel',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='submissionfilter',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='submissionfilter',
            name='state',
            field=models.IntegerField(choices=[(1, 'Block'), (2, 'Allow')], default=1),
        ),
        migrations.AlterField(
            model_name='supplyreportrecipient',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='supplyreportrecipient',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='supplyreportrecipient',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='supplyreportrecipient',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='supplyreportrecipient',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='default_brand_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='default_call_to_action',
            field=models.TextField(blank=True, default='Read more', null=True),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='default_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='default_display_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='default_image_crop',
            field=models.TextField(blank=True, default='center', null=True),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='status',
            field=models.IntegerField(choices=[(1, 'Done'), (2, 'Failed'), (3, 'In progress'), (4, 'Cancelled')], default=3),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='type',
            field=models.IntegerField(choices=[(1, 'Insert'), (2, 'Edit')], default=1),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='status',
            field=models.IntegerField(choices=[(0, 'Video is not uploaded yet'), (1, 'Video is processing'), (2, 'Video is ready for use in creating ads'), (3, 'An error has occurred while processing the video')], default=0),
        ),
    ]
