# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0279_reportjob_exception'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsettings',
            name='autopilot',
            field=models.BooleanField(default=False),
        ),
    ]
