# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0280_campaignsettings_autopilot'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroupsettings',
            name='local_autopilot_daily_budget',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Autopilot's Daily Spend Cap"),
        ),
        migrations.AddField(
            model_name='adgroupsettings',
            name='local_b1_sources_group_cpc_cc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Bidder's Bid CPC"),
        ),
        migrations.AddField(
            model_name='adgroupsettings',
            name='local_b1_sources_group_daily_budget',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Bidder's Daily Cap"),
        ),
        migrations.AddField(
            model_name='adgroupsettings',
            name='local_cpc_cc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Maximum CPC'),
        ),
        migrations.AddField(
            model_name='adgroupsettings',
            name='local_max_cpm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Maximum CPM'),
        ),
        migrations.AddField(
            model_name='adgroupsourcesettings',
            name='local_cpc_cc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='CPC'),
        ),
        migrations.AddField(
            model_name='adgroupsourcesettings',
            name='local_daily_budget_cc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Daily spend cap'),
        ),
        migrations.AddField(
            model_name='campaigngoalvalue',
            name='local_value',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
    ]
