# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0281_multicurrency'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllRTBAdGroupSource',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('dash.adgroupsource',),
        ),
    ]
