# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 09:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0282_allrtbadgroupsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroupsettings',
            name='target_browsers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Browsers'),
        ),
    ]
