# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0282_allrtbadgroupsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditlineitem',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro')], default='USD', max_length=3),
        ),
    ]
