# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0283_creditlineitem_currency'),
        ('dash', '0283_multicurrency_settings_backfill'),
    ]

    operations = [
    ]
