# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0283_adgroupsettings_target_browsers'),
        ('dash', '0284_merge_20180320_0758'),
    ]

    operations = [
    ]
