# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0286_auto_20180321_0755'),
        ('dash', '0286_multicurrency_campaign_goal_values_backfill'),
    ]

    operations = [
    ]
