# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0287_merge_20180323_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetdailystatement',
            name='local_data_spend_nano',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetdailystatement',
            name='local_license_fee_nano',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetdailystatement',
            name='local_margin_nano',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetdailystatement',
            name='local_media_spend_nano',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
