# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0288_auto_20180327_1459'),
    ]

    operations = [
        migrations.RunSQL(
            'UPDATE dash_budgetdailystatement SET '
            'local_media_spend_nano = media_spend_nano, '
            'local_data_spend_nano = data_spend_nano, '
            'local_license_fee_nano = license_fee_nano, '
            'local_margin_nano = margin_nano',
            migrations.RunSQL.noop,
        )
    ]
