# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0289_daily_statements_local_currency_backfill'),
    ]

    operations = [
        migrations.CreateModel(
            name='YahooAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser_id', models.CharField(max_length=255)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_dt', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dash.Account')),
            ],
        ),
    ]
