# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0289_daily_statements_local_currency_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='prefill_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
