# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-30 15:40


from django.db import migrations
from dash.constants import EmailTemplateType


def load_data(apps, schema_editor):
    EmailTemplate = apps.get_model('dash', 'EmailTemplate')

    try:
        template = EmailTemplate.objects.get(template_type=EmailTemplateType.AUTOPILOT_CAMPAIGN_BUDGET_INIT)
    except EmailTemplate.DoesNotExist:
        template = EmailTemplate(
            subject='Campaign put on budget optimization - {account.name}',
            template_type=EmailTemplateType.AUTOPILOT_CAMPAIGN_BUDGET_INIT,
        )

    template.body = '''Hi Manager of {account.name}

            Budget optimization settings on Your campaign {campaign.name} have been changed.
            System made the following changes:{changes}
            - all Paused Media Sources' Daily Spend Caps have been set to minimum values.

            Please check {link_url} for details.

            Yours truly,
            Zemanta
    '''
    template.save()

    try:
        template = EmailTemplate.objects.get(template_type=EmailTemplateType.AUTOPILOT_CAMPAIGN_CHANGE)
    except EmailTemplate.DoesNotExist:
        template = EmailTemplate(
            subject='Campaign budget optimization Changes - {campaign.name}, {account.name}',
            template_type=EmailTemplateType.AUTOPILOT_CAMPAIGN_CHANGE,
        )

    template.body = '''Hi Manager of {account.name}

            In campaign {campaign.name}, which is set to budget optimization, the system made the following changes:{changes}

            Please check {link_url} for details.

            Yours truly,
            Zemanta
    '''
    template.save()



class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0290_auto_20180403_0955'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
