# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0290_yahooaccount'),
        ('dash', '0291_campaign_autopilot_email'),
    ]

    operations = [
    ]
