# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0292_merge_20180406_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yahooaccount',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yahoo_account', to='dash.Account'),
        ),
    ]
