# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0293_auto_20180409_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='prefill_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
