# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0295_auto_20180410_1247'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currencyexchangerate',
            unique_together=set([('date', 'currency')]),
        ),
    ]
