# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 12:06
import textwrap

from django.db import migrations
from dash.constants import EmailTemplateType


def load_data(apps, schema_editor):
    EmailTemplate = apps.get_model('dash', 'EmailTemplate')

    try:
        template = EmailTemplate.objects.get(template_type=EmailTemplateType.CAMPAIGNSTOP_DEPLETING)
    except EmailTemplate.DoesNotExist:
        template = EmailTemplate(
            subject='Campaign is running out of budget',
            template_type=EmailTemplateType.CAMPAIGNSTOP_DEPLETING,
        )

    template.body = textwrap.dedent('''\
        Hi, campaign manager,

        your campaign {campaign.name} ({account.name}) will soon run out of budget.

        Please add more budget otherwise your campaign will end in a few days. To add more budget, please visit {link_url}.

        Yours truly,
        Zemanta''')
    template.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0296_auto_20180417_1408'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
