# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 13:26
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0298_auto_20180424_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahooaccount',
            name='budgets_tz',
            field=timezone_field.fields.TimeZoneField(default='America/Los_Angeles'),
        ),
    ]
