# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0299_yahooaccount_budgets_tz'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahooaccount',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro')], default='USD', max_length=3),
        ),
    ]
