# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 09:45
from __future__ import unicode_literals

from django.db import migrations
import re


def replace_template_braces(apps, front, back):
    EmailTemplate = apps.get_model('dash', 'EmailTemplate')
    templates = EmailTemplate.objects.all()

    for template in templates:
        template.subject = re.sub(*front, re.sub(*back, template.subject))
        template.body = re.sub(*front, re.sub(*back, template.body))
        template.save()


def update_email_templates(apps, schema_editor):
    replace_template_braces(apps, ('{+', '{{'), ('}+', '}}'))


def reverse_email_templates_update(apps, schema_editor):
    replace_template_braces(apps, ('{+', '{'), ('}+', '}'))


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0299_yahooaccount_budgets_tz'),
    ]

    operations = [
        migrations.RunPython(update_email_templates, reverse_email_templates_update)
    ]
