# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0300_email_template_rendering'),
        ('dash', '0300_yahooaccount_currency'),
    ]

    operations = [
    ]
