# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0300_email_template_rendering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgroupsettings',
            name='local_autopilot_daily_budget',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True, verbose_name="Autopilot's Daily Spend Cap"),
        ),
        migrations.AlterField(
            model_name='adgroupsettings',
            name='local_b1_sources_group_daily_budget',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True, verbose_name="Bidder's Daily Cap"),
        ),
    ]
