# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0301_merge_20180507_1559'),
        ('dash', '0301_auto_20180507_0853'),
    ]

    operations = [
    ]
