# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0302_merge_20180508_0532'),
        ('dash', '0301_autopilot_emails'),
    ]

    operations = [
    ]
