# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0304_auto_20180509_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='yahoo_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dash.YahooAccount'),
        ),
    ]
