# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0305_auto_20180509_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yahooaccount',
            name='advertiser_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
