# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 09:57
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0306_auto_20180509_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yahooaccount',
            name='budgets_tz',
            field=timezone_field.fields.TimeZoneField(default='America/New_York'),
        ),
    ]
