# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0307_auto_20180510_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='YahooMigrationAdGroupHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_campaign_key', jsonfield.fields.JSONField(blank=True, default={})),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dash.AdGroup')),
            ],
        ),
        migrations.CreateModel(
            name='YahooMigrationContentAdHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_content_ad_id', models.CharField(max_length=50, null=True)),
                ('content_ad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dash.ContentAd')),
            ],
        ),
    ]
