# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0308_yahoomigrationadgrouphistory_yahoomigrationcontentadhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgroupsettings',
            name='landing_mode',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adgroupsourcesettings',
            name='landing_mode',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='automatic_campaign_stop',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='landing_mode',
            field=models.NullBooleanField(default=False),
        ),
    ]
