# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 07:58
from __future__ import unicode_literals

from django.db import migrations


def delete_campaign_stop_emails(apps, schema_editor):
    EmailTemplate = apps.get_model('dash', 'EmailTemplate')
    EmailTemplate.objects.filter(template_type__in=[13, 14]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0309_auto_20180517_0654'),
    ]

    operations = [
        migrations.RunPython(delete_campaign_stop_emails)
    ]
