# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0311_auto_20180517_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcetype',
            name='budgets_tz',
        ),
    ]
