# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0311_remove_sourcetype_budgets_tz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adgroupsettings',
            name='landing_mode',
        ),
        migrations.RemoveField(
            model_name='adgroupsourcesettings',
            name='landing_mode',
        ),
        migrations.RemoveField(
            model_name='campaignsettings',
            name='landing_mode',
        ),
    ]
