# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0312_auto_20180516_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignsettings',
            name='automatic_campaign_stop',
        ),
    ]
