# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0312_remove_sourcetype_budgets_tz'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='yahoo_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dash.YahooAccount'),
        ),
        migrations.AlterField(
            model_name='account',
            name='yahoo_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dash.YahooAccount'),
        ),
    ]
