# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 09:13
from __future__ import unicode_literals

from django.db import migrations


DEFAULT_ADVERTISER_ID = '953699'


def set_default_yahoo_account_agencies(apps, schema_editor):

    Agency = apps.get_model('dash', 'Agency')
    YahooAccount = apps.get_model('dash', 'YahooAccount')

    default_yahoo_account = YahooAccount.objects.get(
        advertiser_id=DEFAULT_ADVERTISER_ID,
    )
    Agency.objects.filter(yahoo_account__isnull=True).update(
        yahoo_account=default_yahoo_account)


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0313_auto_20180511_0913'),
    ]

    operations = [
        migrations.RunPython(set_default_yahoo_account_agencies)
    ]
