# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0315_auto_20180523_0952'),
        ('dash', '0315_autopilot_email_update'),
    ]

    operations = [
    ]
