# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0316_merge_20180528_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='auto_archiving_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
