# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0316_merge_20180528_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adgroup',
            old_name='outbrain_ad_review',
            new_name='amplify_review',
        ),
        migrations.RenameField(
            model_name='contentad',
            old_name='outbrain_ad_review',
            new_name='amplify_review',
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='USD', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='yahoo_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dash.YahooAccount'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='yahoo_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dash.YahooAccount'),
        ),
        migrations.AlterField(
            model_name='creditlineitem',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], max_length=3),
        ),
        migrations.AlterField(
            model_name='source',
            name='content_ad_submission_policy',
            field=models.IntegerField(choices=[(1, 'Automatic'), (3, 'Automatic with Amplify approval'), (2, 'Manual')], default=1, help_text='Designates weather content ads are submitted automatically'),
        ),
        migrations.AlterField(
            model_name='yahooaccount',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='USD', max_length=3),
        ),
    ]
