# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0317_auto_20180604_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroup',
            name='amplify_review',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='contentad',
            name='amplify_review',
            field=models.NullBooleanField(default=None),
        ),
    ]
