# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0318_auto_20180605_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adgroup',
            name='outbrain_ad_review',
        ),
        migrations.RemoveField(
            model_name='contentad',
            name='outbrain_ad_review',
        ),
    ]
