# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0317_auto_20180530_0849'),
        ('dash', '0320_auto_20180606_1146'),
    ]

    operations = [
    ]
