# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('dash', '0321_merge_20180611_1208'),
    ]

    state_operations = [
        migrations.AlterField(
            model_name='contentadsource',
            name='source_content_ad_id',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]

    database_operations = [  # workaround for creating indexes concurrently
        migrations.RunSQL('CREATE INDEX CONCURRENTLY "dash_contentadsource_source_content_ad_id_aca28742" ON "dash_contentadsource" ("source_content_ad_id");'),
        migrations.RunSQL('CREATE INDEX CONCURRENTLY "dash_contentadsource_source_content_ad_id_aca28742_like" ON "dash_contentadsource" ("source_content_ad_id" varchar_pattern_ops);'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
            database_operations=database_operations,
        )
    ]
