# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0322_auto_20180611_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoasset',
            name='type',
            field=models.IntegerField(choices=[(1, 'DIRECT_UPLOAD'), (2, 'VAST_UPLOAD'), (3, 'VAST_URL')], default=1),
        ),
        migrations.AddField(
            model_name='videoasset',
            name='vast_url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
