# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0323_auto_20180612_0832'),
        ('dash', '0322_auto_20180613_1310'),
    ]

    operations = [
    ]
