# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 08:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0324_merge_20180614_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_dt', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='dash.Account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='dash.CreditLineItem')),
            ],
        ),
    ]
