# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 08:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0325_refundlineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', jsonfield.fields.JSONField()),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='dash.RefundLineItem')),
            ],
        ),
    ]
