# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 08:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0326_refundhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectDeal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deal_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DirectDealConnection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exclusive', models.BooleanField()),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_dt', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('adgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dash.AdGroup')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dash.Agency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deals', models.ManyToManyField(to='dash.DirectDeal')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dash.Source')),
            ],
        ),
    ]
