# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0327_auto_20180629_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundlineitem',
            name='comment',
            field=models.TextField(default='Unchecked credit refund'),
        ),
    ]
