# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 09:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0328_auto_20180629_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='ob_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agency',
            name='ob_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar'), ('SGD', 'Singapore Dollar')], default='USD', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='creditlineitem',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar'), ('SGD', 'Singapore Dollar')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar'), ('SGD', 'Singapore Dollar')], max_length=3),
        ),
        migrations.AlterField(
            model_name='yahooaccount',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar'), ('SGD', 'Singapore Dollar')], default='USD', max_length=3),
        ),
    ]
