# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0329_auto_20180705_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='customflag',
            name='advanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customflag',
            name='type',
            field=models.CharField(choices=[('int', 'number'), ('float', 'decimal number'), ('string', 'text'), ('boolean', 'boolean')], max_length=120, null=True),
        ),
    ]
