# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 10:56
from __future__ import unicode_literals

from django.db import migrations
from dash.constants import EmailTemplateType


def load_data(apps, schema_editor):
    EmailTemplate = apps.get_model("dash", "EmailTemplate")

    EmailTemplate(
        template_type=EmailTemplateType.CAMPAIGN_CREATED,
        subject="Campaign was created on account {{ account.name }}",
        body="""Hi,

a new campaign has just been created on one of your accounts.

Here are the details:
- campaign: {{ campaign_url }}
- account: {{ account_url }}
{% if agency_url %}- agency: {{ agency_url }}{% endif %}

Yours truly,
Zemanta""",
    ).save()


class Migration(migrations.Migration):

    dependencies = [("dash", "0331_auto_20180706_1055")]

    operations = [migrations.RunPython(load_data)]
