# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0332_add_campaign_created_email")]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="type",
            field=models.IntegerField(choices=[(1, "Content"), (2, "Video")], default=1),
        )
    ]
