# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0333_auto_20180814_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='type',
        ),
        migrations.AddField(
            model_name='campaignsettings',
            name='type',
            field=models.IntegerField(choices=[(1, 'Content'), (2, 'Video')], null=True),
        ),
    ]
