# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0336_auto_20180816_1154")]

    operations = [
        migrations.AddField(
            model_name="source",
            name="supports_video",
            field=models.BooleanField(default=False, help_text="Designates whether source supports video."),
        )
    ]
