# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 14:43
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0336_auto_20180816_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundlineitem',
            name='effective_margin',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar'), ('SGD', 'Singapore Dollar'), ('BRL', 'Brazilian Real'), ('MYR', 'Malaysian Ringgit'), ('CHF', 'Swiss Franc')], default='USD', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='creditlineitem',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar'), ('SGD', 'Singapore Dollar'), ('BRL', 'Brazilian Real'), ('MYR', 'Malaysian Ringgit'), ('CHF', 'Swiss Franc')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar'), ('SGD', 'Singapore Dollar'), ('BRL', 'Brazilian Real'), ('MYR', 'Malaysian Ringgit'), ('CHF', 'Swiss Franc')], max_length=3),
        ),
        migrations.AlterField(
            model_name='history',
            name='action_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Change Campaign Goal'), (2, 'Change Budget'), (3, 'Change Credit'), (4, 'Set Publisher Blacklist'), (5, 'Set Global Publisher Blacklist'), (6, 'Manage Reporting'), (7, 'Set Content Ad(s) State'), (8, 'Change Settings'), (9, 'Create'), (10, 'Create Content Ad'), (11, 'Create Conversion Pixel'), (12, 'Archive/Restore Conversion Pixel'), (13, 'Archive/Restore'), (14, 'Archive/Restore Content Ad(s)'), (15, 'Set Media Source Settings'), (16, 'Add Media Source'), (17, 'Rename conversion pixel'), (18, 'Create custom audience'), (19, 'Archive custom audience'), (20, 'Restore custom audience'), (22, 'Update custom audience'), (21, 'Enable pixel for building audiences'), (23, 'Set redirect url for pixel'), (24, 'Remove redirect url for pixel'), (25, 'Create publisher group'), (26, 'Update publisher group'), (26, 'Update publisher group'), (27, 'Pixel set as an additional audience pixel'), (28, 'Create Conversion Pixel as additional audience pixel')], null=True),
        ),
        migrations.AlterField(
            model_name='yahooaccount',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar'), ('SGD', 'Singapore Dollar'), ('BRL', 'Brazilian Real'), ('MYR', 'Malaysian Ringgit'), ('CHF', 'Swiss Franc')], default='USD', max_length=3),
        ),
    ]
