# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0337_auto_20180817_1443")]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="type",
            field=models.IntegerField(blank=True, choices=[(1, "Content"), (2, "Video")], default=1, null=True),
        )
    ]
