# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0338_campaign_type")]

    operations = [migrations.RemoveField(model_name="campaignsettings", name="type")]
