# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0337_auto_20180816_1519'),
        ('dash', '0339_remove_campaignsettings_type'),
    ]

    operations = [
    ]
