# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0340_merge_20180823_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='auto_add_new_sources',
            field=models.BooleanField(default=False),
        ),
    ]
