# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 10:18
from __future__ import unicode_literals

from django.db import migrations

from dash import constants


def set_campaign_type(apps, schema_editor):
    Campaign = apps.get_model("dash", "Campaign")
    Campaign.objects.filter(type__isnull=True).update(type=constants.CampaignType.CONTENT)


class Migration(migrations.Migration):

    dependencies = [("dash", "0341_auto_20180824_1149")]

    operations = [migrations.RunPython(set_campaign_type)]
