# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0342_set_campaign_type'),
        ('dash', '0341_accountsettings_auto_add_new_sources'),
    ]

    operations = [
    ]
