# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0343_merge_20180829_1653")]

    operations = [migrations.AlterField(model_name="source", name="released", field=models.BooleanField(default=False))]
