# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0344_auto_20180903_1203")]

    operations = [
        migrations.AddField(
            model_name="adgroup",
            name="bidding_type",
            field=models.IntegerField(choices=[(1, "CPC"), (2, "CPM")], default=1),
        ),
        migrations.AddField(
            model_name="adgroupsettings",
            name="b1_sources_group_cpm",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Bidder's Bid CPM"
            ),
        ),
        migrations.AddField(
            model_name="adgroupsettings",
            name="local_b1_sources_group_cpm",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Bidder's Bid CPM"
            ),
        ),
        migrations.AddField(
            model_name="adgroupsourcesettings",
            name="cpm",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="CPM"),
        ),
        migrations.AddField(
            model_name="adgroupsourcesettings",
            name="local_cpm",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="CPM"),
        ),
        migrations.AddField(
            model_name="source",
            name="default_cpm",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Default CPM"
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="default_mobile_cpm",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Default CPM (if ad group is targeting mobile only)",
            ),
        ),
        migrations.AddField(
            model_name="sourcetype",
            name="max_cpm",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Maximum CPM"
            ),
        ),
        migrations.AddField(
            model_name="sourcetype",
            name="min_cpm",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Minimum CPM"
            ),
        ),
    ]
