# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0344_auto_20180903_1203")]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Native Ad Campaign"),
                    (2, "Native Video Advertising"),
                    (3, "Native Conversion Marketing"),
                    (4, "Native Mobile App Advertising"),
                ],
                default=1,
                null=True,
            ),
        )
    ]
