# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 11:51
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0345_auto_20180925_1142")]

    operations = [
        migrations.AlterField(
            model_name="adgroupsettings",
            name="b1_sources_group_cpm",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=Decimal("0.01"),
                max_digits=10,
                null=True,
                verbose_name="Bidder's Bid CPM",
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="default_cpm",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=Decimal("0.60"),
                max_digits=10,
                null=True,
                verbose_name="Default CPM",
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="default_mobile_cpm",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=Decimal("0.60"),
                max_digits=10,
                null=True,
                verbose_name="Default CPM (if ad group is targeting mobile only)",
            ),
        ),
    ]
