# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0346_auto_20180925_1151"), ("dash", "0345_auto_20180925_1044")]

    operations = []
