# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0347_merge_20180927_0530")]

    operations = [
        migrations.CreateModel(
            name="PublisherClassification",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("publisher", models.CharField(max_length=128)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("entertainment", "Arts & Entertainment"),
                            ("fun_quizzes", "Viral, lists & Quizzes"),
                            ("music", "Music"),
                            ("cars", "Automotive"),
                            ("finance", "Business & Finance"),
                            ("education", "Education"),
                            ("family", "Family & Parenting"),
                            ("health", "Health & Fitness"),
                            ("food", "Food & Drink"),
                            ("hobbies", "Hobbies & Interests"),
                            ("games", "Games & Gaming"),
                            ("home", "Home & Garden"),
                            ("politics_law", "Law, Gov’t & Politics"),
                            ("media", "News"),
                            ("dating", "Dating & Relationships"),
                            ("science", "Science"),
                            ("weather", "Weather & Environment"),
                            ("pets", "Pets"),
                            ("sports", "Sports"),
                            ("fashion", "Beauty & Fashion"),
                            ("technology", "Technology"),
                            ("utility", "Apps & Online services"),
                            ("travel", "Travel"),
                            ("shopping_coupons", "Shopping"),
                            ("religion", "Religion & Spirituality"),
                            ("communication", "Communication Tools"),
                            ("career", "Careers"),
                            ("premium", "Premium"),
                            ("women", "Women’s Lifestyle"),
                            ("men", "Men’s Lifestyle"),
                            ("foreign", "Foreign"),
                            ("french", "French"),
                            ("spanish", "Spanish"),
                            ("other", "Other"),
                            ("?", "Unknown"),
                            ("outbrain", "Outbrain"),
                            ("technology-contextual", "Technology - Contextual"),
                            ("fun", "Fun & Entertaining Sites"),
                            ("quizzes", "Quizzes"),
                            ("politics", "Gov’t & Politics"),
                            ("law", "Law"),
                            ("coupons", "Couponing"),
                            ("shopping", "Shopping"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                ("ignored", models.BooleanField(default=False)),
            ],
        )
    ]
