# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("dash", "0348_publisherclassification")]

    operations = [
        migrations.AddField(
            model_name="publisherclassification",
            name="category",
            field=models.CharField(
                choices=[
                    ("entertainment", "Arts & Entertainment"),
                    ("fun_quizzes", "Viral, lists & Quizzes"),
                    ("music", "Music"),
                    ("cars", "Automotive"),
                    ("finance", "Business & Finance"),
                    ("education", "Education"),
                    ("family", "Family & Parenting"),
                    ("health", "Health & Fitness"),
                    ("food", "Food & Drink"),
                    ("hobbies", "Hobbies & Interests"),
                    ("games", "Games & Gaming"),
                    ("home", "Home & Garden"),
                    ("politics_law", "Law, Gov’t & Politics"),
                    ("media", "News"),
                    ("dating", "Dating & Relationships"),
                    ("science", "Science"),
                    ("weather", "Weather & Environment"),
                    ("pets", "Pets"),
                    ("sports", "Sports"),
                    ("fashion", "Beauty & Fashion"),
                    ("technology", "Technology"),
                    ("utility", "Apps & Online services"),
                    ("travel", "Travel"),
                    ("shopping_coupons", "Shopping"),
                    ("religion", "Religion & Spirituality"),
                    ("communication", "Communication Tools"),
                    ("career", "Careers"),
                    ("premium", "Premium"),
                    ("women", "Women’s Lifestyle"),
                    ("men", "Men’s Lifestyle"),
                    ("foreign", "Foreign"),
                    ("french", "French"),
                    ("spanish", "Spanish"),
                    ("other", "Other"),
                    ("?", "Unknown"),
                    ("outbrain", "Outbrain"),
                    ("technology-contextual", "Technology - Contextual"),
                    ("fun", "Fun & Entertaining Sites"),
                    ("quizzes", "Quizzes"),
                    ("politics", "Gov’t & Politics"),
                    ("law", "Law"),
                    ("coupons", "Couponing"),
                    ("shopping", "Shopping"),
                ],
                default="?",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="publisherclassification",
            name="created_dt",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Created at"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="publisherclassification",
            name="modified_dt",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified at"),
        ),
        migrations.RemoveField(model_name="publisherclassification", name="classification"),
        migrations.AlterUniqueTogether(
            name="publisherclassification", unique_together=set([("publisher", "category")])
        ),
    ]
