# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 13:34
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0349_cpm_buying_null")]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="default_cpm",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.60"), max_digits=10, verbose_name="Default CPM"
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="default_mobile_cpm",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.60"),
                max_digits=10,
                verbose_name="Default CPM (if ad group is targeting mobile only)",
            ),
        ),
    ]
