# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0350_auto_20181008_1334"), ("dash", "0349_auto_20181004_1255")]

    operations = []
