# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0351_merge_20181010_0949")]

    operations = [
        migrations.AlterField(
            model_name="directdealconnection",
            name="exclusive",
            field=models.BooleanField(
                help_text="If the deal is exclusive, we will only respond to requests that have this deal."
            ),
        )
    ]
