# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 15:01
from __future__ import unicode_literals

from django.db import migrations
from django.db import connection


AD_GROUP_SETTINGS_BACKFILL_SQL = """
UPDATE dash_adgroupsettings ags
SET    local_b1_sources_group_cpm = b1_sources_group_cpm * cer.exchange_rate
FROM   dash_adgroup ag
       JOIN dash_campaign cmp
         ON ag.campaign_id = cmp.id
       JOIN dash_account acc
         ON cmp.account_id = acc.id
       JOIN (SELECT DISTINCT currency,
                             First_value(exchange_rate)
                               OVER (
                                 partition BY currency
                                 ORDER BY date DESC) AS exchange_rate
             FROM   dash_currencyexchangerate) cer
         ON acc.currency = cer.currency
WHERE  ags.id = ag.settings_id AND ags.id BETWEEN %s AND %s;
"""

BATCH_SIZE = 100000


def ad_group_settings_backfill(apps, schema_editor):
    with connection.cursor() as c:
        c.execute("SELECT MAX(id) FROM dash_adgroupsettings")
        count = c.fetchone()[0] or 0
        for i in range(0, count, BATCH_SIZE):
            c.execute("BEGIN")
            print("Updating ids between %s and %s" % (i, i + BATCH_SIZE))
            c.execute(AD_GROUP_SETTINGS_BACKFILL_SQL, [i, i + BATCH_SIZE])
            c.execute("COMMIT")


class Migration(migrations.Migration):

    dependencies = [("dash", "0352_auto_20181011_0817")]

    operations = [migrations.RunPython(ad_group_settings_backfill)]
