# Generated by Django 2.1.2 on 2018-10-15 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dash", "0354_cpm_buying_fake")]

    operations = [
        migrations.AlterField(
            model_name="budgetdailystatement",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="statements", to="dash.BudgetLineItem"
            ),
        ),
        migrations.AlterField(
            model_name="campaigngoal",
            name="campaign",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="dash.Campaign"),
        ),
        migrations.AlterField(
            model_name="campaigngoalvalue",
            name="campaign_goal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="values", to="dash.CampaignGoal"
            ),
        ),
        migrations.AlterField(
            model_name="contentadcandidate",
            name="original_content_ad",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="dash.ContentAd"),
        ),
        migrations.AlterField(
            model_name="refundhistory",
            name="refund",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="history", to="dash.RefundLineItem"
            ),
        ),
        migrations.AlterField(
            model_name="scheduledexportreport",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="scheduled_reports", to="dash.ExportReport"
            ),
        ),
        migrations.AlterField(
            model_name="scheduledexportreportlog",
            name="scheduled_report",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="dash.ScheduledExportReport"),
        ),
        migrations.AlterField(
            model_name="scheduledexportreportrecipient",
            name="scheduled_report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="recipients", to="dash.ScheduledExportReport"
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="source_type",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="dash.SourceType"),
        ),
    ]
