# Generated by Django 2.1.2 on 2018-10-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0357_cachedonetoonefield")]

    operations = [
        migrations.AlterField(
            model_name="contentadsource",
            name="submission_status",
            field=models.IntegerField(
                choices=[
                    (-1, "Not submitted"),
                    (1, "Pending"),
                    (2, "Approved"),
                    (3, "Rejected"),
                    (4, "Limit reached"),
                    (5, "Not available"),
                ],
                default=-1,
            ),
        )
    ]
