# Generated by Django 2.1.2 on 2018-10-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [("dash", "0357_cachedonetoonefield")]

    operations = [
        migrations.AddIndex(
            model_name="contentadsource",
            index=models.Index(fields=["content_ad", "source"], name="dash_contentadsource_cadid_sid"),
        )
    ]
