# Generated by Django 2.1.2 on 2018-10-19 13:33

from django.db import migrations
from django.db import connection


SOURCETYPE_BACKFILL_SQL = """
UPDATE dash_sourcetype src
SET     min_cpm = '0.0100'
WHERE   min_cpm IS NULL AND src.id BETWEEN %s AND %s;

UPDATE dash_sourcetype src
SET     max_cpm = '25.0000'
WHERE   max_cpm IS NULL AND src.id BETWEEN %s AND %s;
"""

SOURCETYPE_BACKFILL_SQL_YAHOO = """
UPDATE dash_sourcetype src
SET     min_cpm = '0.2500'
WHERE   src.id=4;
"""

BATCH_SIZE = 100000


def sourcetype_backfill(apps, schema_editor):
    with connection.cursor() as c:
        c.execute("SELECT MAX(id) FROM dash_source")
        count = c.fetchone()[0] or 0
        for i in range(0, count, BATCH_SIZE):
            c.execute("BEGIN")
            print("Updating ids between %s and %s" % (i, i + BATCH_SIZE))
            c.execute(SOURCETYPE_BACKFILL_SQL, [i, i + BATCH_SIZE, i, i + BATCH_SIZE])
            c.execute("COMMIT")
        c.execute("BEGIN")
        c.execute(SOURCETYPE_BACKFILL_SQL_YAHOO)
        c.execute("COMMIT")


class Migration(migrations.Migration):

    dependencies = [("dash", "0357_undo_foreignkey_on_delete_protected")]

    operations = [migrations.RunPython(sourcetype_backfill)]
