# Generated by Django 2.1.2 on 2018-10-30 10:37

from django.db import migrations
from decimal import Decimal


def set_source_default_settings(apps, schema_editor):

    Source = apps.get_model("dash", "Source")

    for source in Source.objects.filter(deprecated=False):
        source.default_cpm = Decimal("1.0")
        source.default_mobile_cpm = Decimal("1.0")

        source.save()


class Migration(migrations.Migration):

    dependencies = [("dash", "0358_auto_20181025_1426")]

    operations = [migrations.RunPython(set_source_default_settings)]
