# Generated by Django 2.1.2 on 2018-11-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0358_auto_20181030_0828"), ("dash", "0359_cpm_buying_source_defaults")]

    operations = []
