# Generated by Django 2.1.2 on 2018-11-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0360_merge_20181105_1201")]

    operations = [
        migrations.AddField(
            model_name="source",
            name="supports_display",
            field=models.BooleanField(default=False, help_text="Designates whether source supports display ads."),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Native Ad Campaign"),
                    (2, "Native Video Advertising"),
                    (3, "Native Conversion Marketing"),
                    (4, "Native Mobile App Advertising"),
                    (5, "Display Ad Campaign"),
                ],
                default=1,
                null=True,
            ),
        ),
    ]
