# Generated by Django 2.1.2 on 2018-11-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0361_auto_20181109_1307"), ("dash", "0361_auto_20181107_1311")]

    operations = []
