# Generated by Django 2.1.2 on 2018-11-14 16:15

from django.db import migrations
from django.db import connection


AD_GROUP_SOURCE_SETTINGS_BACKFILL_SQL = """
UPDATE dash_adgroupsourcesettings agss
SET     cpm = '1.0000'
WHERE   cpm IS NULL AND agss.id BETWEEN %s AND %s;
"""

BATCH_SIZE = 100000


def ags_cpm_backfill(apps, schema_editor):
    with connection.cursor() as c:
        c.execute("SELECT MAX(id) FROM dash_adgroupsourcesettings")
        count = c.fetchone()[0] or 0
        for i in range(0, count, BATCH_SIZE):
            c.execute("BEGIN")
            print("Updating ids between %s and %s" % (i, i + BATCH_SIZE))
            c.execute(AD_GROUP_SOURCE_SETTINGS_BACKFILL_SQL, [i, i + BATCH_SIZE])
            c.execute("COMMIT")


class Migration(migrations.Migration):

    dependencies = [("dash", "0362_merge_20181112_1021")]

    operations = [migrations.RunPython(ags_cpm_backfill)]
