# Generated by Django 2.1.2 on 2018-11-14 17:43
from django.db import migrations
from django.db import connection


AD_GROUP_SOURCE_SETTINGS_BACKFILL_SQL = """
UPDATE dash_adgroupsourcesettings agss
SET    local_cpm = cpm * cer.exchange_rate
FROM   dash_adgroupsource ags
       JOIN dash_adgroup ag
         ON ags.ad_group_id = ag.id
       JOIN dash_campaign cmp
         ON ag.campaign_id = cmp.id
       JOIN dash_account acc
         ON cmp.account_id = acc.id
       JOIN (SELECT DISTINCT currency,
                             First_value(exchange_rate)
                               OVER (
                                 partition BY currency
                                 ORDER BY date DESC) AS exchange_rate
             FROM   dash_currencyexchangerate) cer
         ON acc.currency = cer.currency
WHERE  local_cpm IS NULL AND agss.id = ags.settings_id AND agss.id BETWEEN %s AND %s;
"""

BATCH_SIZE = 100000


def ad_group_source_settings_backfill(apps, schema_editor):
    with connection.cursor() as c:
        c.execute("SELECT MAX(id) FROM dash_adgroupsourcesettings")
        count = c.fetchone()[0] or 0
        for i in range(0, count, BATCH_SIZE):
            c.execute("BEGIN")
            print("Updating ids between %s and %s" % (i, i + BATCH_SIZE))
            c.execute(AD_GROUP_SOURCE_SETTINGS_BACKFILL_SQL, [i, i + BATCH_SIZE])
            c.execute("COMMIT")


class Migration(migrations.Migration):

    dependencies = [("dash", "0363_cpm_buying_ags_cpm_backfill")]

    operations = [migrations.RunPython(ad_group_source_settings_backfill)]
