# Generated by Django 2.1.2 on 2018-11-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0365_auto_20181120_1157")]

    operations = [
        migrations.AddField(model_name="contentad", name="ad_tag", field=models.TextField(blank=True, null=True)),
        migrations.AddField(
            model_name="contentad", name="image_file_size", field=models.PositiveIntegerField(null=True)
        ),
        migrations.AddField(
            model_name="contentad",
            name="type",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Content ad"), (2, "Video ad"), (3, "Image display ad"), (4, "Display ad tag")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contentadcandidate", name="ad_tag", field=models.TextField(blank=True, null=True)
        ),
        migrations.AddField(
            model_name="contentadcandidate", name="image_file_size", field=models.PositiveIntegerField(null=True)
        ),
        migrations.AddField(
            model_name="contentadcandidate",
            name="type",
            field=models.IntegerField(
                choices=[(1, "Content ad"), (2, "Video ad"), (3, "Image display ad"), (4, "Display ad tag")], default=1
            ),
        ),
    ]
