# Generated by Django 2.1.2 on 2018-11-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0366_auto_20181120_1437")]

    operations = [
        migrations.AlterField(
            model_name="contentad",
            name="type",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Content ad"), (2, "Video ad"), (3, "Image display ad"), (4, "Display ad tag")],
                default=1,
                null=True,
            ),
        )
    ]
