# Generated by Django 2.1.2 on 2018-11-27 13:45

from django.db import migrations
from django.db import connection


CONTENT_AD_CANDIDATE_BACKFILL_SQL_1 = """
UPDATE  dash_contentadcandidate cac
SET     type = 1
FROM    dash_adgroup ag
        JOIN dash_campaign cmp
        ON ag.campaign_id = cmp.id
WHERE   cac.ad_group_id = ag.id
        AND cmp.type IN (1, 3, 4)
        AND cac.id BETWEEN %s AND %s;
"""

CONTENT_AD_CANDIDATE_BACKFILL_SQL_2 = """
UPDATE  dash_contentadcandidate cac
SET     type = 2
FROM    dash_adgroup ag
        JOIN dash_campaign cmp
        ON ag.campaign_id = cmp.id
WHERE   cac.ad_group_id = ag.id
        AND cmp.type = 2
        AND cac.video_asset_id IS NOT NULL
        AND cac.id BETWEEN %s AND %s;
"""

CONTENT_AD_CANDIDATE_BACKFILL_SQL_3 = """
UPDATE  dash_contentadcandidate cac
SET     type = 3
FROM    dash_adgroup ag
        JOIN dash_campaign cmp
        ON ag.campaign_id = cmp.id
WHERE   cac.ad_group_id = ag.id
        AND cmp.type = 5
        AND image_url IS NOT NULL
        AND ad_tag IS NULL
        AND cac.id BETWEEN %s AND %s;
"""

CONTENT_AD_CANDIDATE_BACKFILL_SQL_4 = """
UPDATE  dash_contentadcandidate cac
SET     type = 4
FROM    dash_adgroup ag
        JOIN dash_campaign cmp
        ON ag.campaign_id = cmp.id
WHERE   cac.ad_group_id = ag.id
        AND cmp.type = 5
        AND image_url IS NULL
        AND ad_tag IS NOT NULL
        AND cac.id BETWEEN %s AND %s;
"""

CONTENT_AD_BACKFILL_SQL_1 = """
UPDATE  dash_contentad ca
SET     type = 1
FROM    dash_adgroup ag
        JOIN dash_campaign cmp
        ON ag.campaign_id = cmp.id
WHERE   ca.ad_group_id = ag.id
        AND cmp.type IN (1, 3, 4)
        AND ca.id BETWEEN %s AND %s;
"""

CONTENT_AD_BACKFILL_SQL_2 = """
UPDATE  dash_contentad ca
SET     type = 2
FROM    dash_adgroup ag
        JOIN dash_campaign cmp
        ON ag.campaign_id = cmp.id
WHERE   ca.ad_group_id = ag.id
        AND cmp.type = 2
        AND ca.id BETWEEN %s AND %s;
"""

CONTENT_AD_BACKFILL_SQL_3 = """
UPDATE  dash_contentad ca
SET     type = 3
FROM    dash_adgroup ag
        JOIN dash_campaign cmp
        ON ag.campaign_id = cmp.id
WHERE   ca.ad_group_id = ag.id
        AND cmp.type = 5
        AND image_id IS NOT NULL
        AND image_hash IS NOT NULL
        AND ad_tag IS NULL
        AND ca.id BETWEEN %s AND %s;
"""

CONTENT_AD_BACKFILL_SQL_4 = """
UPDATE  dash_contentad ca
SET     type = 4
FROM    dash_adgroup ag
        JOIN dash_campaign cmp
        ON ag.campaign_id = cmp.id
WHERE   ca.ad_group_id = ag.id
        AND cmp.type = 5
        AND image_id IS NULL
        AND image_hash IS NULL
        AND ad_tag IS NOT NULL
        AND ca.id BETWEEN %s AND %s;
"""

SET_CONTENTAD_TYPE_NOT_NULL = """
ALTER TABLE dash_contentad
ALTER COLUMN type
SET NOT NULL;
"""

BATCH_SIZE = 100000


def contentadcandidate_type_backfill(apps, schema_editor):
    with connection.cursor() as c:
        c.execute("SELECT MAX(id) FROM dash_contentadcandidate")
        count = c.fetchone()[0] or 0
        for i in range(0, count, BATCH_SIZE):
            c.execute("BEGIN")
            print("Updating contentadcandidate ids between %s and %s" % (i, i + BATCH_SIZE))
            c.execute(CONTENT_AD_CANDIDATE_BACKFILL_SQL_1, [i, i + BATCH_SIZE])
            c.execute(CONTENT_AD_CANDIDATE_BACKFILL_SQL_2, [i, i + BATCH_SIZE])
            c.execute(CONTENT_AD_CANDIDATE_BACKFILL_SQL_3, [i, i + BATCH_SIZE])
            c.execute(CONTENT_AD_CANDIDATE_BACKFILL_SQL_4, [i, i + BATCH_SIZE])
            c.execute("COMMIT")


def contentad_type_backfill(apps, schema_editor):
    with connection.cursor() as c:
        c.execute("SELECT MAX(id) FROM dash_contentad")
        count = c.fetchone()[0] or 0
        for i in range(0, count, BATCH_SIZE):
            c.execute("BEGIN")
            print("Updating contentad ids between %s and %s" % (i, i + BATCH_SIZE))
            c.execute(CONTENT_AD_BACKFILL_SQL_1, [i, i + BATCH_SIZE])
            c.execute(CONTENT_AD_BACKFILL_SQL_2, [i, i + BATCH_SIZE])
            c.execute(CONTENT_AD_BACKFILL_SQL_3, [i, i + BATCH_SIZE])
            c.execute(CONTENT_AD_BACKFILL_SQL_4, [i, i + BATCH_SIZE])
            c.execute("COMMIT")
        c.execute("BEGIN")
        print("Altering contentad table")
        c.execute(SET_CONTENTAD_TYPE_NOT_NULL)
        c.execute("COMMIT")


class Migration(migrations.Migration):

    dependencies = [("dash", "0367_auto_20181120_1438")]

    operations = [migrations.RunPython(contentadcandidate_type_backfill), migrations.RunPython(contentad_type_backfill)]
