# Generated by Django 2.1.2 on 2018-11-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0368_display_contentad_type_backfill")]

    operations = [
        migrations.AlterField(
            model_name="contentad",
            name="type",
            field=models.IntegerField(
                choices=[(1, "Content ad"), (2, "Video ad"), (3, "Image display ad"), (4, "Display ad tag")], default=1
            ),
        )
    ]
