# Generated by Django 2.1.2 on 2018-12-12 17:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0369_auto_20181128_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentad',
            name='document_features',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentad',
            name='document_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
