# Generated by Django 2.1.2 on 2018-12-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0369_auto_20181128_1058")]

    operations = [
        migrations.AddField(model_name="history", name="stack_trace", field=models.TextField(blank=True, null=True))
    ]
