# Generated by Django 2.1.2 on 2018-12-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0370_history_stack_trace")]

    operations = [
        migrations.RemoveField(model_name="source", name="cpc_billing"),
        migrations.AddField(
            model_name="source",
            name="billing_type",
            field=models.IntegerField(choices=[(1, "default"), (2, "fixed CPM"), (3, "fixed CPC")], default=1),
        ),
    ]
