# Generated by Django 2.1.2 on 2018-12-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0371_source_billing_type"), ("dash", "0370_auto_20181212_1752")]

    operations = []
