# Generated by Django 2.1.2 on 2019-01-15 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dash", "0373_auto_20190114_0806")]

    operations = [
        migrations.AddField(model_name="directdeal", name="description", field=models.TextField(blank=True, null=True)),
        migrations.AddField(
            model_name="directdealconnection",
            name="account",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="dash.Account"
            ),
        ),
        migrations.AddField(
            model_name="directdealconnection",
            name="campaign",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="dash.Campaign"
            ),
        ),
    ]
