# Generated by Django 2.1.2 on 2019-01-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0375_add_entity_tags")]

    operations = [
        migrations.AlterField(
            model_name="creditlineitem", name="comment", field=models.CharField(blank=True, max_length=10000, null=True)
        )
    ]
