# Generated by Django 2.1.2 on 2019-01-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0376_auto_20190123_1443")]

    operations = [
        migrations.AlterField(
            model_name="directdealconnection",
            name="exclusive",
            field=models.BooleanField(
                default=False,
                help_text="If the deal is exclusive, we will only respond to requests that have this deal.",
            ),
        )
    ]
