# Generated by Django 2.1.2 on 2019-01-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0377_document_id_to_bigint")]

    operations = [
        migrations.AlterField(
            model_name="contentad", name="document_id", field=models.BigIntegerField(blank=True, null=True)
        )
    ]
