# Generated by Django 2.1.2 on 2019-01-31 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0377_auto_20190131_1157"), ("dash", "0378_document_id_bigint_fake")]

    operations = []
