# Generated by Django 2.1.2 on 2019-02-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0379_merge_20190131_1517")]

    operations = [
        migrations.AddField(
            model_name="agency", name="default_csv_decimal_separator", field=models.CharField(default=".", max_length=1)
        ),
        migrations.AddField(
            model_name="agency", name="default_csv_separator", field=models.CharField(default=",", max_length=1)
        ),
    ]
