# Generated by Django 2.1.2 on 2019-02-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0380_auto_20190204_0857")]

    operations = [
        migrations.AddField(
            model_name="adgroupsettings", name="language_targeting_enabled", field=models.BooleanField(default=False)
        )
    ]
