# Generated by Django 2.1.2 on 2019-02-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0382_auto_20190211_0759")]

    operations = [migrations.RenameModel(old_name="PublisherBidModifier", new_name="BidModifier")]
