# Generated by Django 2.1.2 on 2019-02-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0383_rename_publisher_bid_modifiers")]

    operations = [
        migrations.AddField(
            model_name="contentadcandidate", name="can_append_tracking_codes", field=models.BooleanField(default=False)
        ),
        migrations.AddField(
            model_name="contentadcandidate",
            name="primary_tracker_url_status",
            field=models.IntegerField(
                choices=[(1, "Pending"), (2, "Waiting for response"), (3, "OK"), (4, "Failed")], default=1
            ),
        ),
        migrations.AddField(
            model_name="contentadcandidate",
            name="secondary_tracker_url_status",
            field=models.IntegerField(
                choices=[(1, "Pending"), (2, "Waiting for response"), (3, "OK"), (4, "Failed")], default=1
            ),
        ),
    ]
