# Generated by Django 2.1.2 on 2019-02-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0385_add_bid_modifier_type")]

    operations = [
        migrations.RenameField(model_name="bidmodifier", old_name="publisher", new_name="target"),
        migrations.AlterField(
            model_name="bidmodifier", name="modifier", field=models.FloatField(verbose_name="Bid modifier")
        ),
        migrations.AlterUniqueTogether(name="bidmodifier", unique_together={("ad_group", "source", "target")}),
        migrations.AlterField(
            model_name="bidmodifier",
            name="target",
            field=models.CharField(max_length=127, verbose_name="Bid modifier target"),
        ),
    ]
