# Generated by Django 2.1.2 on 2019-02-14 11:56

from django.db import migrations, models


def fill_source_slug(apps, schema_editor):
    BidModifier = apps.get_model("dash", "BidModifier")
    BidModifier.objects.update(
        source_slug=models.Subquery(
            BidModifier.objects.filter(id=models.OuterRef("id")).values("source__tracking_slug")[:1]
        )
    )


class Migration(migrations.Migration):

    dependencies = [("dash", "0386_rename_attr_publisher_to_target")]

    operations = [
        migrations.AddField(
            model_name="bidmodifier", name="source_slug", field=models.CharField(blank=True, default="", max_length=50)
        ),
        migrations.RunPython(fill_source_slug, reverse_code=migrations.RunPython.noop),
    ]
