# Generated by Django 2.1.2 on 2019-02-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0387_add_bid_modifier_source_slug")]

    operations = [
        migrations.AlterUniqueTogether(
            name="bidmodifier", unique_together={("type", "ad_group", "source_slug", "target")}
        )
    ]
