# Generated by Django 2.1.2 on 2019-02-20 13:41

from django.db import migrations, models


def fill_tracking_slug(apps, schema_editor):
    BidModifier = apps.get_model("dash", "BidModifier")
    BidModifier.objects.update(
        source_slug=models.Subquery(
            BidModifier.objects.filter(id=models.OuterRef("id")).values("source__tracking_slug")[:1]
        )
    )


def fill_bidder_slug(apps, schema_editor):
    BidModifier = apps.get_model("dash", "BidModifier")
    BidModifier.objects.update(
        source_slug=models.Subquery(
            BidModifier.objects.filter(id=models.OuterRef("id")).values("source__bidder_slug")[:1]
        )
    )


class Migration(migrations.Migration):

    dependencies = [("dash", "0389_bid_modifier_source_field_optional")]

    operations = [migrations.RunPython(fill_bidder_slug, reverse_code=fill_tracking_slug)]
