# Generated by Django 2.1.2 on 2019-02-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0391_source_bidder_slug_required")]

    operations = [
        migrations.AlterField(
            model_name="audiencerule",
            name="type",
            field=models.PositiveSmallIntegerField(choices=[(1, "Starts with"), (2, "Contains"), (5, "Visit")]),
        )
    ]
