# Generated by Django 2.1.2 on 2019-03-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0392_auto_20190226_1007")]

    operations = [
        migrations.CreateModel(
            name="WhiteLabel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "theme",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("greenpark", "Green Park Content"),
                            ("adtechnacity", "Adtechnacity"),
                            ("newscorp", "Newscorp"),
                            ("burda", "Burda"),
                            ("mediamond", "Mediamond"),
                        ],
                        max_length=255,
                    ),
                ),
                ("favicon_url", models.CharField(blank=True, default="", max_length=255)),
                ("dashboard_title", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={"verbose_name_plural": "Whitelabels"},
        ),
        migrations.AlterField(
            model_name="bidmodifier",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Publisher"),
                    (2, "Source"),
                    (3, "Device"),
                    (4, "Operating System"),
                    (5, "Placement"),
                    (6, "Country"),
                    (7, "State"),
                    (8, "DMA"),
                    (9, "Ad"),
                ]
            ),
        ),
    ]
