# Generated by Django 2.1.2 on 2019-03-04 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dash", "0393_auto_20190304_0936")]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="white_label",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agencies",
                to="dash.WhiteLabel",
            ),
        )
    ]
