# Generated by Django 2.1.2 on 2019-03-08 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dash", "0394_agency_white_label")]

    operations = [
        migrations.CreateModel(
            name="HistoryStacktrace",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.TextField()),
                (
                    "history",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="stacktrace", to="dash.History"
                    ),
                ),
            ],
        )
    ]
