# Generated by Django 2.1.2 on 2019-03-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0394_agency_white_label")]

    operations = [
        migrations.RemoveField(model_name="agency", name="custom_dashboard_title"),
        migrations.RemoveField(model_name="agency", name="custom_favicon_url"),
        migrations.RemoveField(model_name="agency", name="whitelabel"),
    ]
