# Generated by Django 2.1.2 on 2019-03-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0395_historystacktrace"), ("dash", "0395_auto_20190314_0856")]

    operations = []
