# Generated by Django 2.1.2 on 2019-03-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0396_merge_20190315_1157")]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_disabled",
            field=models.BooleanField(default=False, help_text="Agency can be disabled only if is externally managed."),
        ),
        migrations.AddField(
            model_name="agency",
            name="is_disabled",
            field=models.BooleanField(default=False, help_text="Agency can be disabled only if is externally managed."),
        ),
        migrations.AddField(
            model_name="agency",
            name="is_externally_managed",
            field=models.BooleanField(default=False, help_text="Agency is managed via SalesForce API."),
        ),
    ]
