# Generated by Django 2.1.2 on 2019-03-28 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("dash", "0398_auto_20190319_0903")]

    operations = [
        migrations.AddField(
            model_name="account",
            name="custom_attributes",
            field=jsonfield.fields.JSONField(
                blank=True,
                default=dict,
                help_text="Used only by Outbrain Salesforce to store attributes non existant on Z1.",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="salesforce_id",
            field=models.IntegerField(help_text="Outbrain custom Salesforce ID.", null=True),
        ),
        migrations.AddField(
            model_name="agency",
            name="custom_attributes",
            field=jsonfield.fields.JSONField(
                blank=True,
                default=dict,
                help_text="Used only by Outbrain Salesforce to store attributes non existant on Z1.",
            ),
        ),
        migrations.AlterField(
            model_name="agency",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
