# Generated by Django 2.1.2 on 2019-03-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0399_auto_20190328_1103")]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="salesforce_id",
            field=models.IntegerField(blank=True, help_text="Outbrain custom Salesforce ID.", null=True),
        )
    ]
