# Generated by Django 2.1.2 on 2019-04-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0402_auto_20190429_1419")]

    operations = [
        migrations.AlterField(
            model_name="account", name="archived", field=models.BooleanField(blank=True, default=False, null=True)
        ),
        migrations.AlterField(
            model_name="adgroup", name="archived", field=models.BooleanField(blank=True, default=False, null=True)
        ),
        migrations.AlterField(
            model_name="campaign", name="archived", field=models.BooleanField(blank=True, default=False, null=True)
        ),
    ]
