# Generated by Django 2.1.2 on 2019-05-06 09:33

from django.db import migrations


def account_archived_backfill(apps, schema_editor):
    Account = apps.get_model("dash", "Account")
    Account.objects.filter(settings__archived=True).update(archived=True)


class Migration(migrations.Migration):

    dependencies = [("dash", "0404_auto_20190429_1453")]

    operations = [migrations.RunPython(account_archived_backfill)]
