# Generated by Django 2.1.2 on 2019-05-06 09:33

from django.db import migrations


def campaign_archived_backfill(apps, schema_editor):
    Campaign = apps.get_model("dash", "Campaign")
    Campaign.objects.filter(settings__archived=True).update(archived=True)


class Migration(migrations.Migration):

    dependencies = [("dash", "0405_account_archived_backfill")]

    operations = [migrations.RunPython(campaign_archived_backfill)]
