# Generated by Django 2.1.2 on 2019-05-06 09:34

from django.db import migrations


def ad_group_archived_backfill(apps, schema_editor):
    AdGroup = apps.get_model("dash", "AdGroup")
    AdGroup.objects.filter(settings__archived=True).update(archived=True)


class Migration(migrations.Migration):

    dependencies = [("dash", "0406_campaign_archived_backfill")]

    operations = [migrations.RunPython(ad_group_archived_backfill)]
