# Generated by Django 2.1.8 on 2019-05-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0408_contentad_image_present")]

    operations = [
        migrations.AddField(model_name="account", name="amplify_review", field=models.NullBooleanField(default=True)),
        migrations.AddField(model_name="agency", name="amplify_review", field=models.NullBooleanField(default=True)),
    ]
