# Generated by Django 2.1.8 on 2019-05-23 08:02

from django.db import migrations


class Migration(migrations.Migration):
    # This migration should be faked in production to avoid locking DB table.
    # In production run "ad_group_source_unique_together_constraint_migration" management command

    dependencies = [("dash", "0409_auto_20190515_0829")]

    operations = [migrations.AlterUniqueTogether(name="adgroupsource", unique_together={("source", "ad_group")})]
