# Generated by Django 2.1.8 on 2019-05-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0410_ad_group_source_unique_together_constraint")]

    operations = [
        migrations.AddField(
            model_name="adgroupsettings",
            name="cpc",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="CPC"),
        ),
        migrations.AddField(
            model_name="adgroupsettings",
            name="cpm",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="CPM"),
        ),
        migrations.AddField(
            model_name="adgroupsettings",
            name="local_cpc",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="CPC"),
        ),
        migrations.AddField(
            model_name="adgroupsettings",
            name="local_cpm",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="CPM"),
        ),
    ]
