# Generated by Django 2.1.8 on 2019-05-16 09:58

from django.db import migrations, models

from utils.list_helper import list_chunker

BATCH_SIZE = 100000


def fill_new_fields(apps, schema_editor):
    AdGroupSettings = apps.get_model("dash", "AdGroupSettings")
    AdGroup = apps.get_model("dash", "AdGroup")
    all_ids = sorted(
        AdGroupSettings.objects.filter(
            id__in=models.Subquery(AdGroup.objects.filter(settings__id=models.OuterRef("id")).values("settings__id"))
        ).values_list("id", flat=True)
    )

    for batch_ids in list_chunker(all_ids, BATCH_SIZE):
        AdGroupSettings.objects.filter(id__in=batch_ids).update(
            cpc=models.F("cpc_cc"),
            local_cpc=models.F("local_cpc_cc"),
            cpm=models.F("max_cpm"),
            local_cpm=models.F("local_max_cpm"),
        )


def do_nothing(apps, schema_editor):
    # all changes can be undone by unapplying the previous migrations which removes the new columns
    pass


class Migration(migrations.Migration):

    dependencies = [("dash", "0411_add_cpc_cpm_fields")]

    operations = [migrations.RunPython(fill_new_fields, reverse_code=do_nothing)]
