# Generated by Django 2.1.8 on 2019-06-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0412_migrate_cpc_cpm_values")]

    operations = [
        migrations.AddField(
            model_name="account",
            name="outbrain_internal_marketer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
