# Generated by Django 2.1.8 on 2019-06-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dash", "0413_account_outbrain_internal_marketer_id")]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("AUD", "Australian Dollar"),
                    ("SGD", "Singapore Dollar"),
                    ("BRL", "Brazilian Real"),
                    ("MYR", "Malaysian Ringgit"),
                    ("CHF", "Swiss Franc"),
                    ("ZAR", "South African Rand"),
                    ("ILS", "Israeli New Shekel"),
                    ("INR", "Indian Rupee"),
                ],
                default="USD",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="creditlineitem",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("AUD", "Australian Dollar"),
                    ("SGD", "Singapore Dollar"),
                    ("BRL", "Brazilian Real"),
                    ("MYR", "Malaysian Ringgit"),
                    ("CHF", "Swiss Franc"),
                    ("ZAR", "South African Rand"),
                    ("ILS", "Israeli New Shekel"),
                    ("INR", "Indian Rupee"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="currencyexchangerate",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("AUD", "Australian Dollar"),
                    ("SGD", "Singapore Dollar"),
                    ("BRL", "Brazilian Real"),
                    ("MYR", "Malaysian Ringgit"),
                    ("CHF", "Swiss Franc"),
                    ("ZAR", "South African Rand"),
                    ("ILS", "Israeli New Shekel"),
                    ("INR", "Indian Rupee"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="directdealconnection",
            name="exclusive",
            field=models.BooleanField(
                default=True,
                help_text="If the deal is exclusive, we will only respond to requests that have this deal.",
            ),
        ),
        migrations.AlterField(
            model_name="yahooaccount",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("AUD", "Australian Dollar"),
                    ("SGD", "Singapore Dollar"),
                    ("BRL", "Brazilian Real"),
                    ("MYR", "Malaysian Ringgit"),
                    ("CHF", "Swiss Franc"),
                    ("ZAR", "South African Rand"),
                    ("ILS", "Israeli New Shekel"),
                    ("INR", "Indian Rupee"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
    ]
