# Generated by Django 2.1.10 on 2019-07-19 07:55

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0414_auto_20190627_0930")]

    operations = [
        migrations.AddIndex(
            model_name="campaign", index=models.Index(fields=["created_dt"], name="dash_campai_created_a5c0fd_idx")
        )
    ]
