# Generated by Django 2.1.8 on 2019-08-12 11:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0417_auto_20190805_0955")]

    operations = [
        migrations.AddField(
            model_name="uploadbatch",
            name="default_state",
            field=models.IntegerField(choices=[(1, "Enabled"), (2, "Paused")], null=True),
        )
    ]
