# Generated by Django 2.1.8 on 2019-08-19 14:01

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0417_auto_20190805_0955")]

    operations = [
        migrations.AddIndex(
            model_name="adgroupsource",
            index=models.Index(fields=["ad_review_only"], name="dash_adgrou_ad_revi_9ab6ec_idx"),
        )
    ]
