# Generated by Django 2.2.4 on 2019-08-26 09:33

from decimal import Decimal

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0418_auto_20190819_1401")]

    operations = [
        migrations.AlterField(
            model_name="adgroupsettings",
            name="b1_sources_group_cpc_cc",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.005"), max_digits=10, verbose_name="Bidder's Bid CPC"
            ),
        )
    ]
