# Generated by Django 2.1.8 on 2019-08-26 10:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0419_auto_20190826_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='adgroupsettings',
            name='additional_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
