# Generated by Django 2.1.8 on 2019-08-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0419_auto_20190826_0933"), ("dash", "0419_auto_20190814_1825")]

    operations = []
