# Generated by Django 2.1.8 on 2019-08-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0419_auto_20190814_1825"), ("dash", "0419_auto_20190826_0933")]

    operations = []
