# Generated by Django 2.1.8 on 2019-08-28 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0420_adgroupsettings_additional_data'),
        ('dash', '0420_merge_20190827_1228'),
    ]

    operations = [
    ]
