# Generated by Django 2.1.8 on 2019-05-17 11:15

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0421_merge_20190828_0826")]

    operations = [
        migrations.AlterField(
            model_name="bidmodifier",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Publisher"),
                    (2, "Source"),
                    (3, "Device"),
                    (4, "Operating System"),
                    (5, "Placement"),
                    (6, "Country"),
                    (7, "State"),
                    (8, "DMA"),
                    (9, "Ad"),
                ],
                db_index=True,
            ),
        )
    ]
