# Generated by Django 2.1.11 on 2019-09-09 11:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0425_auto_20190904_0941")]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("AUD", "Australian Dollar"),
                    ("SGD", "Singapore Dollar"),
                    ("BRL", "Brazilian Real"),
                    ("MYR", "Malaysian Ringgit"),
                    ("CHF", "Swiss Franc"),
                    ("ZAR", "South African Rand"),
                    ("ILS", "Israeli New Shekel"),
                    ("INR", "Indian Rupee"),
                    ("JPY", "Japanese Yen"),
                    ("CAD", "Canadian Dollar"),
                    ("NZD", "New Zealand Dollar"),
                ],
                default="USD",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="creditlineitem",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("AUD", "Australian Dollar"),
                    ("SGD", "Singapore Dollar"),
                    ("BRL", "Brazilian Real"),
                    ("MYR", "Malaysian Ringgit"),
                    ("CHF", "Swiss Franc"),
                    ("ZAR", "South African Rand"),
                    ("ILS", "Israeli New Shekel"),
                    ("INR", "Indian Rupee"),
                    ("JPY", "Japanese Yen"),
                    ("CAD", "Canadian Dollar"),
                    ("NZD", "New Zealand Dollar"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="currencyexchangerate",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("AUD", "Australian Dollar"),
                    ("SGD", "Singapore Dollar"),
                    ("BRL", "Brazilian Real"),
                    ("MYR", "Malaysian Ringgit"),
                    ("CHF", "Swiss Franc"),
                    ("ZAR", "South African Rand"),
                    ("ILS", "Israeli New Shekel"),
                    ("INR", "Indian Rupee"),
                    ("JPY", "Japanese Yen"),
                    ("CAD", "Canadian Dollar"),
                    ("NZD", "New Zealand Dollar"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="yahooaccount",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("AUD", "Australian Dollar"),
                    ("SGD", "Singapore Dollar"),
                    ("BRL", "Brazilian Real"),
                    ("MYR", "Malaysian Ringgit"),
                    ("CHF", "Swiss Franc"),
                    ("ZAR", "South African Rand"),
                    ("ILS", "Israeli New Shekel"),
                    ("INR", "Indian Rupee"),
                    ("JPY", "Japanese Yen"),
                    ("CAD", "Canadian Dollar"),
                    ("NZD", "New Zealand Dollar"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
    ]
