# Generated by Django 2.1.11 on 2019-09-04 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0425_auto_20190904_0941"), ("dash", "0425_auto_20190903_1035")]

    operations = []
