# Generated by Django 2.1.11 on 2019-09-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0426_merge_20190904_1234"), ("dash", "0426_auto_20190909_1141")]

    operations = []
