# Generated by Django 2.1.11 on 2019-09-03 10:35

import django.db.models.deletion
from django.db import migrations
from django.db import models
from django.db import transaction

from utils import zlogging
from utils.queryset_helper import chunk_iterator

BATCH_SIZE = 1000
logger = zlogging.getLogger(__name__)


def fix_direct_deal_connections(apps, schema_editor):
    logger.info("Fixing deal_connections with many deals...")
    DirectDealConnection = apps.get_model("dash", "DirectDealConnection")

    deal_connections_qs = DirectDealConnection.objects.select_related("source").prefetch_related("deals")

    chunk_number = 0
    for deal_connections_chunk in chunk_iterator(deal_connections_qs, chunk_size=BATCH_SIZE):
        chunk_number += 1
        logger.info("Processing chunk number %s...", chunk_number)

        with transaction.atomic():
            for deal_connection in deal_connections_chunk:
                deals = deal_connection.deals.all()
                if len(deals) == 0:
                    deal_connection.delete()
                elif len(deals) > 1:
                    for deal in deals:
                        deal_connection_copy = DirectDealConnection.objects.create(
                            source=deal_connection.source,
                            exclusive=deal_connection.exclusive,
                            agency=deal_connection.agency,
                            account=deal_connection.account,
                            campaign=deal_connection.campaign,
                            adgroup=deal_connection.adgroup,
                            created_dt=deal_connection.created_dt,
                            modified_dt=deal_connection.modified_dt,
                            created_by=deal_connection.created_by,
                        )
                        deal_connection_copy.deals.add(deal)
                        deal_connection_copy.save()
                    deal_connection.deals.clear()
                    deal_connection.delete()

        logger.info("Chunk number %s processed...", chunk_number)

    logger.info("Fixing deal_connections with many deals completed...")


def populate_deal_key(apps, schema_editor):
    logger.info("Populating deal_key...")
    DirectDealConnection = apps.get_model("dash", "DirectDealConnection")

    deal_connections_qs = DirectDealConnection.objects.prefetch_related("deals")

    chunk_number = 0
    for deal_connections_chunk in chunk_iterator(deal_connections_qs, chunk_size=BATCH_SIZE):
        chunk_number += 1
        logger.info("Processing chunk number %s...", chunk_number)

        with transaction.atomic():
            for deal_connection in deal_connections_chunk:
                deal = deal_connection.deals.first()
                deal_connection.deal_key = deal.pk
                deal_connection.save()

        logger.info("Chunk number %s processed...", chunk_number)

    logger.info("Populating deal_key completed...")


def populate_deal(apps, schema_editor):
    logger.info("Populating deal...")
    DirectDeal = apps.get_model("dash", "DirectDeal")
    DirectDealConnection = apps.get_model("dash", "DirectDealConnection")

    deal_connections_qs = DirectDealConnection.objects.all()

    chunk_number = 0
    for deal_connections_chunk in chunk_iterator(deal_connections_qs, chunk_size=BATCH_SIZE):
        chunk_number += 1
        logger.info("Processing chunk number %s...", chunk_number)

        with transaction.atomic():
            for deal_connection in deal_connections_chunk:
                deal = DirectDeal.objects.get(pk=deal_connection.deal_key)
                deal_connection.deal = deal
                deal_connection.save()

        logger.info("Chunk number %s processed...", chunk_number)

    logger.info("Populating deal completed...")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [("dash", "0426_auto_20190909_1141")]

    operations = [
        migrations.RunPython(fix_direct_deal_connections, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name="directdealconnection", name="deal_key", field=models.IntegerField(blank=True, null=True)
        ),
        migrations.RunPython(populate_deal_key, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(model_name="directdealconnection", name="deals"),
        migrations.AddField(
            model_name="directdealconnection",
            name="deal",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="dash.DirectDeal"
            ),
        ),
        migrations.RunPython(populate_deal, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(model_name="directdealconnection", name="deal_key"),
        migrations.AlterField(
            model_name="directdealconnection",
            name="deal",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="dash.DirectDeal"),
        ),
    ]
