# Generated by Django 2.1.11 on 2019-09-03 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models
from django.db import transaction

from utils import zlogging
from utils.queryset_helper import chunk_iterator

BATCH_SIZE = 1000
logger = zlogging.getLogger(__name__)


def update_direct_deal_from_direct_deal_connection(apps, schema_editor):
    logger.info("Updating direct_deal from direct_deal_connection...")
    DirectDealConnection = apps.get_model("dash", "DirectDealConnection")

    deal_connections_qs = DirectDealConnection.objects.select_related("source", "deal")

    chunk_number = 0
    for deal_connections_chunk in chunk_iterator(deal_connections_qs, chunk_size=BATCH_SIZE):
        chunk_number += 1
        logger.info("Processing chunk number %s...", chunk_number)

        with transaction.atomic():
            for deal_connection in deal_connections_chunk:
                do_save = False
                if deal_connection.deal.source is None:
                    deal_connection.deal.source = deal_connection.source
                    do_save = True
                if deal_connection.deal.created_dt is None:
                    deal_connection.deal.created_dt = deal_connection.created_dt
                    do_save = True
                if deal_connection.deal.modified_dt is None:
                    deal_connection.deal.modified_dt = deal_connection.modified_dt
                    do_save = True
                if deal_connection.deal.created_by is None:
                    deal_connection.deal.created_by = deal_connection.created_by
                    do_save = True
                if do_save:
                    deal_connection.deal.save()

        logger.info("Chunk number %s processed...", chunk_number)

    logger.info("Updating direct_deal from direct_deal_connection completed...")


def delete_direct_deals_with_no_direct_deal_connections(apps, schema_editor):
    logger.info("Deleting deals with no deal connections...")
    DirectDeal = apps.get_model("dash", "DirectDeal")

    deals_qs = DirectDeal.objects.all()

    chunk_number = 0
    for deals_chunk in chunk_iterator(deals_qs, chunk_size=BATCH_SIZE):
        chunk_number += 1
        logger.info("Processing chunk number %s...", chunk_number)

        with transaction.atomic():
            for deal in deals_chunk:
                if len(deal.directdealconnection_set.all()) == 0:
                    deal.delete()

        logger.info("Chunk number %s processed...", chunk_number)

    logger.info("Deleting deals with no deal connections completed...")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("dash", "0427_auto_20190909_1409")]

    operations = [
        migrations.AddField(
            model_name="directdeal",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="directdeal",
            name="created_dt",
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="Created at"),
        ),
        migrations.AddField(
            model_name="directdeal",
            name="floor_price",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="directdeal",
            name="modified_dt",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="Modified at"),
        ),
        migrations.AddField(
            model_name="directdeal", name="name", field=models.CharField(blank=True, max_length=127, null=True)
        ),
        migrations.AddField(
            model_name="directdeal",
            name="source",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="dash.Source"
            ),
        ),
        migrations.AddField(
            model_name="directdeal",
            name="valid_from_date",
            field=models.DateField(blank=True, null=True, verbose_name="Valid from"),
        ),
        migrations.AddField(
            model_name="directdeal",
            name="valid_to_date",
            field=models.DateField(blank=True, null=True, verbose_name="Valid to"),
        ),
        migrations.RunPython(update_direct_deal_from_direct_deal_connection, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(
            delete_direct_deals_with_no_direct_deal_connections, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="directdeal",
            name="created_dt",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="directdeal",
            name="modified_dt",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified at"),
        ),
        migrations.AlterField(
            model_name="directdeal",
            name="source",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="dash.Source"),
        ),
        migrations.RemoveField(model_name="directdealconnection", name="source"),
    ]
