# Generated by Django 2.1.11 on 2019-10-07 12:01

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0432_add_day_hour_bid_modifier_type")]

    operations = [
        migrations.AlterField(
            model_name="whitelabel",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("greenpark", "Green Park Content"),
                    ("adtechnacity", "Adtechnacity"),
                    ("newscorp", "Newscorp"),
                    ("burda", "Burda"),
                    ("mediamond", "Mediamond"),
                    ("adyoulike", "Adyoulike"),
                ],
                max_length=255,
            ),
        )
    ]
