# Generated by Django 2.1.11 on 2019-11-12 11:06

from django.db import migrations
from django.db import models
from django.db import transaction

from utils import zlogging
from utils.queryset_helper import chunk_iterator

BATCH_SIZE = 1000
logger = zlogging.getLogger(__name__)


def populate_name_field(apps, schema_editor):

    logger.info("Populating directDeals name fields...")
    DirectDeal = apps.get_model("dash", "DirectDeal")

    deals_qs = DirectDeal.objects.all()

    chunk_number = 0
    for deals_chunk in chunk_iterator(deals_qs, chunk_size=BATCH_SIZE):
        chunk_number += 1
        logger.info("Processing chunk number %s...", chunk_number)

        with transaction.atomic():
            for deal in deals_chunk:
                if not deal.name:
                    if deal.description:
                        deal.name = deal.description[:124]
                        deal.save()
                    else:
                        if deal.agency:
                            deal.name = f"{deal.source.name} / {deal.agency.name}"
                            deal.save()
                        else:
                            deal.name = f"{deal.source.name}"
                            deal.save()

        logger.info("Chunk number %s processed...", chunk_number)

    logger.info("Populating agency completed...")


class Migration(migrations.Migration):

    dependencies = [("dash", "0435_auto_20191023_1248")]

    operations = [
        migrations.RunPython(populate_name_field, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(model_name="directdeal", name="name", field=models.CharField(max_length=127)),
    ]
