# Generated by Django 2.1.11 on 2019-11-25 13:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0436_directdeal_name_required")]

    operations = [
        migrations.CreateModel(
            name="AccountStatusCache",
            fields=[
                ("account_id", models.IntegerField(primary_key=True, serialize=False)),
                ("status", models.IntegerField(choices=[(1, "Enabled"), (2, "Paused")], default=2)),
            ],
        )
    ]
