# Generated by Django 2.1.11 on 2019-11-25 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dash", "0436_directdeal_name_required")]

    operations = [
        migrations.CreateModel(
            name="ImageAsset",
            fields=[
                ("image_id", models.CharField(editable=False, max_length=256, primary_key=True, serialize=False)),
                ("hash", models.CharField(max_length=128)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("crop", models.CharField(default="center", max_length=25)),
                ("file_size", models.PositiveIntegerField()),
                ("origin_url", models.URLField(blank=True, null=True)),
                ("created_dt", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
            ],
        ),
        migrations.AddField(
            model_name="accountsettings",
            name="default_icon",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="dash.ImageAsset"),
        ),
    ]
