# Generated by Django 2.1.11 on 2019-11-27 09:01

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0437_auto_20191125_1053")]

    operations = [
        migrations.AlterField(model_name="adgroup", name="name", field=models.CharField(max_length=256)),
        migrations.AlterField(
            model_name="adgroupsettings",
            name="ad_group_name",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
