# Generated by Django 2.1.11 on 2019-11-28 09:27

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0438_auto_20191127_0901")]

    operations = [migrations.AlterField(model_name="campaign", name="name", field=models.CharField(max_length=256))]
