# Generated by Django 2.1.11 on 2019-11-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0437_accountstatuscache"), ("dash", "0439_auto_20191128_0927")]

    operations = []
