# Generated by Django 2.1.11 on 2019-11-28 11:52

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0439_auto_20191128_0927")]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="available_sources",
            field=models.ManyToManyField(blank=True, related_name="available_agencies", to="dash.Source"),
        )
    ]
