# Generated by Django 2.1.11 on 2019-12-03 07:38

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0440_merge_20191129_1514")]

    operations = [
        migrations.AlterField(model_name="campaignsettings", name="name", field=models.CharField(max_length=256))
    ]
