# Generated by Django 2.1.11 on 2019-12-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0441_auto_20191203_0738")]

    operations = [migrations.RemoveField(model_name="imageasset", name="crop")]
