# Generated by Django 2.1.11 on 2019-12-10 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dash", "0442_remove_imageasset_crop")]

    operations = [
        migrations.RenameField(model_name="imageasset", old_name="hash", new_name="image_hash"),
        migrations.RemoveField(model_name="contentad", name="icon_file_size"),
        migrations.RemoveField(model_name="contentad", name="icon_hash"),
        migrations.RemoveField(model_name="contentad", name="icon_id"),
        migrations.RemoveField(model_name="contentad", name="icon_size"),
        migrations.AddField(
            model_name="contentad",
            name="icon",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="dash.ImageAsset"),
        ),
    ]
