# Generated by Django 2.1.11 on 2019-12-12 11:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0443_auto_20191210_1445")]

    operations = [
        migrations.AddField(
            model_name="supplyreportrecipient",
            name="daily_breakdown_report",
            field=models.BooleanField(default=False, verbose_name="Month-to-date daily breakdown report"),
        ),
        migrations.AddField(
            model_name="supplyreportrecipient",
            name="mtd_report",
            field=models.BooleanField(default=False, verbose_name="Month-to-date report"),
        ),
    ]
