# Generated by Django 2.1.11 on 2019-12-19 09:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0444_auto_20191212_1111")]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="available_sources",
            field=models.ManyToManyField(blank=True, related_name="available_agencies", to="dash.Source"),
        )
    ]
