# Generated by Django 2.1.11 on 2019-10-07 11:08

from django.db import migrations
from django.db import models

BATCH_SIZE = 100000


class Migration(migrations.Migration):

    dependencies = [("dash", "0447_auto_20200127_1246")]

    operations = [
        migrations.AddField(
            model_name="adgroupsettings",
            name="local_max_autopilot_bid",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Maximum autopilot bid"
            ),
        ),
        migrations.AddField(
            model_name="adgroupsettings",
            name="max_autopilot_bid",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Maximum autopilot bid"
            ),
        ),
    ]
