# Generated by Django 2.1.11 on 2020-02-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0448_add_max_autopilot_bid"), ("dash", "0447_directdeal_account")]

    operations = []
