# Generated by Django 2.1.11 on 2020-02-10 13:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0449_merge_20200203_0919")]

    operations = [
        migrations.AddField(model_name="directdeal", name="is_internal", field=models.BooleanField(default=False))
    ]
