# Generated by Django 2.1.11 on 2020-02-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0450_auto_20200205_1342"), ("dash", "0450_directdeal_is_internal")]

    operations = []
