# Generated by Django 2.1.11 on 2020-02-14 18:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0451_merge_20200212_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adgroupsettings',
            name='target_placements',
        ),
        migrations.RemoveField(
            model_name='campaignsettings',
            name='target_placements',
        ),
        migrations.AddField(
            model_name='adgroupsettings',
            name='target_environments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, null=True, size=None, verbose_name='Environment'),
        ),
        migrations.AddField(
            model_name='campaignsettings',
            name='target_environments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, null=True, size=None, verbose_name='Environment'),
        ),
        migrations.AlterField(
            model_name='bidmodifier',
            name='type',
            field=models.IntegerField(choices=[(1, 'Publisher'), (2, 'Source'), (3, 'Device'), (4, 'Operating System'), (5, 'Environment'), (6, 'Country'), (7, 'State'), (8, 'DMA'), (9, 'Ad'), (10, 'Day - Hour')], db_index=True),
        ),
    ]
