# Generated by Django 2.1.11 on 2020-03-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0452_auto_20200214_1823")]

    operations = [
        migrations.RemoveField(model_name="accountsettings", name="ob_representative"),
        migrations.RemoveField(model_name="agency", name="ob_representative"),
    ]
