# Generated by Django 2.1.11 on 2020-03-02 18:17

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0453_auto_20200302_0912")]

    operations = [
        migrations.AddField(
            model_name="publishergroupentry", name="placement", field=models.CharField(max_length=127, null=True)
        )
    ]
