# Generated by Django 2.1.11 on 2020-03-03 13:09

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0454_publishergroupentry_placement")]

    operations = [
        migrations.AlterField(
            model_name="publishergroupentry",
            name="placement",
            field=models.CharField(blank=True, max_length=127, null=True),
        )
    ]
