# Generated by Django 2.1.11 on 2020-03-10 18:18

import textwrap

from django.db import migrations

from dash.constants import EmailTemplateType


def load_data(apps, schema_editor):
    EmailTemplate = apps.get_model("dash", "EmailTemplate")

    EmailTemplate(
        template_type=EmailTemplateType.AUTOMATION_RULE_RUN,
        subject="Rule “{{rule_name}}” performed actions on ad group {{ad_group_name}}",
        body=textwrap.dedent(
            """\
        Hi,

        We’re letting you know that your rule “{{rule_name}}” was successfully executed on your ad group {{ad_group_link}} with message:

        {{changes_text}}{% if errors_text %}

        The following errors were encountered during rule execution:

        {{errors_text}}{% endif %}

        Yours truly,
        Zemanta"""
        ),
    ).save()

    EmailTemplate(
        template_type=EmailTemplateType.AUTOMATION_RULE_NO_CHANGES,
        subject="Rule “{{rule_name}}” ran on ad group {{ad_group_name}}",
        body=textwrap.dedent(
            """\
        Hi,

        We’re letting you know that your rule “{{rule_name}}” was successfully executed on your ad group {{ad_group_link}} without doing any changes.

        Yours truly,
        Zemanta"""
        ),
    ).save()

    EmailTemplate(
        template_type=EmailTemplateType.AUTOMATION_RULE_ERRORS,
        subject="Rule “{{rule_name}}” encountered errors on ad group {{ad_group_name}}",
        body=textwrap.dedent(
            """\
        Hi,

        We’re letting you know that your rule “{{rule_name}}” was executed on your ad group {{ad_group_link}} and encountered the following errors:

        {{errors_text}}

        Yours truly,
        Zemanta"""
        ),
    ).save()


class Migration(migrations.Migration):

    dependencies = [("dash", "0455_auto_20200303_1309")]

    operations = [migrations.RunPython(load_data)]
