# Generated by Django 2.1.11 on 2020-03-26 08:58

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0457_auto_20200318_1443")]

    operations = [
        migrations.AddField(
            model_name="supplyreportrecipient",
            name="last_sent_dt",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Last sent at"),
        ),
        migrations.AddField(
            model_name="supplyreportrecipient",
            name="outbrain_publisher_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="supplyreportrecipient",
            name="daily_breakdown_report",
            field=models.BooleanField(default=False, verbose_name="MTD daily breakdown report"),
        ),
        migrations.AlterField(
            model_name="supplyreportrecipient",
            name="mtd_report",
            field=models.BooleanField(default=False, verbose_name="MTD report"),
        ),
    ]
