# Generated by Django 2.1.11 on 2020-05-13 07:46

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0462_increase_bidmodifier_type_size")]

    operations = [
        migrations.AlterField(
            model_name="bidmodifier",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Publisher"),
                    (2, "Source"),
                    (3, "Device"),
                    (4, "Operating System"),
                    (5, "Environment"),
                    (6, "Country"),
                    (7, "State"),
                    (8, "DMA"),
                    (9, "Ad"),
                    (10, "Day - Hour"),
                    (11, "Placement"),
                ],
                db_index=True,
            ),
        )
    ]
