# Generated by Django 2.1.11 on 2020-05-25 11:45

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0463_add_placement_bid_modifier_type")]

    operations = [
        migrations.AddField(
            model_name="historystacktrace",
            name="created_dt",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Created at"),
            preserve_default=False,
        )
    ]
