# Generated by Django 2.1.11 on 2020-05-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0464_historystacktrace_created_dt")]

    operations = [
        migrations.RemoveField(model_name="account", name="uses_bcm_v2"),
        migrations.RemoveField(model_name="agency", name="new_accounts_use_bcm_v2"),
    ]
