# Generated by Django 2.1.11 on 2020-06-19 11:22

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0465_auto_20200528_1415")]

    operations = [
        migrations.AddField(
            model_name="budgetdailystatement", name="base_data_spend_nano", field=models.BigIntegerField(null=True)
        ),
        migrations.AddField(
            model_name="budgetdailystatement", name="base_media_spend_nano", field=models.BigIntegerField(null=True)
        ),
        migrations.AddField(
            model_name="budgetdailystatement",
            name="local_base_data_spend_nano",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="budgetdailystatement",
            name="local_base_media_spend_nano",
            field=models.BigIntegerField(null=True),
        ),
    ]
