# Generated by Django 2.1.11 on 2020-06-18 14:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0465_add_outbrain_marketer_version")]

    operations = [
        migrations.AlterField(
            model_name="outbrainaccount", name="marketer_id", field=models.CharField(max_length=255, unique=True)
        )
    ]
