# Generated by Django 2.1.11 on 2020-06-19 11:48

from decimal import Decimal

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0467_daily_statement_base_backfill")]

    operations = [
        migrations.AddField(
            model_name="budgetdailystatement", name="local_service_fee_nano", field=models.BigIntegerField(default=0)
        ),
        migrations.AddField(
            model_name="budgetdailystatement", name="service_fee_nano", field=models.BigIntegerField(default=0)
        ),
        migrations.AddField(
            model_name="creditlineitem",
            name="service_fee",
            field=models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=5),
        ),
    ]
