# Generated by Django 2.1.11 on 2020-06-16 12:27

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0468_auto_20200619_1148")]

    operations = [
        migrations.AddField(
            model_name="account", name="outbrain_marketer_version", field=models.IntegerField(default=0)
        )
    ]
