# Generated by Django 2.1.11 on 2020-08-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0470_outbrain_account_marketer_id_unique")]

    operations = [
        migrations.RemoveField(model_name="creditlineitem", name="flat_fee_cc"),
        migrations.RemoveField(model_name="creditlineitem", name="flat_fee_end_date"),
        migrations.RemoveField(model_name="creditlineitem", name="flat_fee_start_date"),
    ]
