# Generated by Django 2.1.11 on 2020-08-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0471_auto_20200803_1803")]

    operations = [migrations.AlterModelOptions(name="entitytag", options={"ordering": ("name",)})]
