# Generated by Django 2.1.11 on 2020-08-13 08:59
from django.db import migrations

from dash.constants import EmailTemplateType


def change_rule_errors_email(apps, schema_editor):
    EmailTemplate = apps.get_model("dash", "EmailTemplate")

    template = EmailTemplate.objects.get(template_type=EmailTemplateType.AUTOMATION_RULE_ERRORS)
    template.body = """Hi,

We’re letting you know that your rule “{{rule_name}}” was executed on your ad group {{ad_group_link}} \
and has encountered errors. View in history: {% autoescape off %}{{history_link}}{% endautoescape %}

Yours truly,
Zemanta"""
    template.save()


class Migration(migrations.Migration):

    dependencies = [("dash", "0472_auto_20200810_0824")]

    operations = [migrations.RunPython(change_rule_errors_email)]
