# Generated by Django 2.1.11 on 2020-08-25 14:08

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0473_auto_20200814_0839")]

    operations = [
        migrations.AlterField(
            model_name="contentadcandidate",
            name="call_to_action",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="uploadbatch",
            name="default_call_to_action",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
