# Generated by Django 2.1.11 on 2020-08-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0473_auto_20200814_0839")]

    operations = [
        migrations.RemoveField(model_name="facebookaccount", name="account"),
        migrations.DeleteModel(name="FacebookAccount"),
    ]
