# Generated by Django 2.1.11 on 2020-08-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0475_change_default_call_to_action"),
        ("dash", "0474_adgroupsettings_exclusion_target_browsers"),
    ]

    operations = []
