# Generated by Django 2.1.11 on 2020-09-03 11:27

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0476_merge_20200826_1110")]

    operations = [
        migrations.AddField(
            model_name="adgroupsettings",
            name="daily_budget",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Ad group’s daily budget"
            ),
        ),
        migrations.AddField(
            model_name="adgroupsettings",
            name="local_daily_budget",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Ad group’s daily budget"
            ),
        ),
    ]
