# Generated by Django 2.1.11 on 2020-09-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0477_auto_20200903_1127"), ("dash", "0477_auto_20200902_1331")]

    operations = []
