# Generated by Django 2.1.11 on 2020-09-07 13:15

import datetime
from decimal import Decimal

from django.db import migrations
from django.db import models


def set_default_exchange_rate(apps, schema_editor):
    CurrencyExchangeRate = apps.get_model("dash", "CurrencyExchangeRate")
    CurrencyExchangeRate.objects.create(
        date=datetime.date(1970, 1, 1), currency="MXN", exchange_rate=Decimal("21.55674717108596520857963182")
    )


class Migration(migrations.Migration):

    dependencies = [("dash", "0478_merge_20200907_0956")]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("AUD", "Australian Dollar"),
                    ("SGD", "Singapore Dollar"),
                    ("BRL", "Brazilian Real"),
                    ("MYR", "Malaysian Ringgit"),
                    ("CHF", "Swiss Franc"),
                    ("ZAR", "South African Rand"),
                    ("ILS", "Israeli New Shekel"),
                    ("INR", "Indian Rupee"),
                    ("JPY", "Japanese Yen"),
                    ("CAD", "Canadian Dollar"),
                    ("NZD", "New Zealand Dollar"),
                    ("TRY", "Turkish Lira"),
                    ("MXN", "Mexican Peso"),
                ],
                default="USD",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="creditlineitem",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("AUD", "Australian Dollar"),
                    ("SGD", "Singapore Dollar"),
                    ("BRL", "Brazilian Real"),
                    ("MYR", "Malaysian Ringgit"),
                    ("CHF", "Swiss Franc"),
                    ("ZAR", "South African Rand"),
                    ("ILS", "Israeli New Shekel"),
                    ("INR", "Indian Rupee"),
                    ("JPY", "Japanese Yen"),
                    ("CAD", "Canadian Dollar"),
                    ("NZD", "New Zealand Dollar"),
                    ("TRY", "Turkish Lira"),
                    ("MXN", "Mexican Peso"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="currencyexchangerate",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("AUD", "Australian Dollar"),
                    ("SGD", "Singapore Dollar"),
                    ("BRL", "Brazilian Real"),
                    ("MYR", "Malaysian Ringgit"),
                    ("CHF", "Swiss Franc"),
                    ("ZAR", "South African Rand"),
                    ("ILS", "Israeli New Shekel"),
                    ("INR", "Indian Rupee"),
                    ("JPY", "Japanese Yen"),
                    ("CAD", "Canadian Dollar"),
                    ("NZD", "New Zealand Dollar"),
                    ("TRY", "Turkish Lira"),
                    ("MXN", "Mexican Peso"),
                ],
                max_length=3,
            ),
        ),
        migrations.RunPython(set_default_exchange_rate),
    ]
