# Generated by Django 2.1.11 on 2020-09-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0479_auto_20200907_1315")]

    operations = [migrations.AlterModelOptions(name="adgroupsettings", options={"ordering": ("-created_dt",)})]
