# Generated by Django 2.1.11 on 2020-09-13 18:04

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0480_auto_20200908_0625")]

    operations = [
        migrations.AlterField(
            model_name="adgroupsourcesettings", name="id", field=models.BigAutoField(primary_key=True, serialize=False)
        ),
        migrations.RunSQL(  # HACK: this was was added with intention to be faked in prod, only to keep consistency in test/dev database
            """ALTER SEQUENCE "dash_adgroupsourcesettings_id_seq" RESTART WITH 10000000;""", migrations.RunSQL.noop
        ),
    ]
