# Generated by Django 2.1.11 on 2020-09-17 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0482_adgroupsettings_target_connection_types")]

    operations = [
        migrations.RemoveField(model_name="source", name="billing_type"),
        migrations.RemoveField(model_name="source", name="cpc_billing"),
        migrations.RemoveField(model_name="source", name="supports_retargeting_manually"),
    ]
