# Generated by Django 2.1.11 on 2020-09-29 10:55

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0484_auto_20200924_0824")]

    operations = [
        migrations.AlterField(
            model_name="conversionpixel", name="additional_pixel", field=models.BooleanField(default=False, null=True)
        ),
        migrations.AlterField(
            model_name="conversionpixel", name="audience_enabled", field=models.BooleanField(default=False, null=True)
        ),
    ]
