# Generated by Django 2.1.11 on 2020-09-29 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0485_auto_20200929_1055")]

    operations = [
        migrations.RemoveField(model_name="conversionpixel", name="additional_pixel"),
        migrations.RemoveField(model_name="conversionpixel", name="audience_enabled"),
    ]
