# Generated by Django 2.1.11 on 2020-10-06 08:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0487_auto_20201005_0935")]

    operations = [
        migrations.AlterField(
            model_name="bidmodifier",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Publisher"),
                    (2, "Source"),
                    (3, "Device"),
                    (4, "Operating System"),
                    (5, "Environment"),
                    (6, "Country"),
                    (7, "State"),
                    (8, "DMA"),
                    (9, "Ad"),
                    (10, "Day - Hour"),
                    (11, "Placement"),
                    (12, "Browser"),
                    (13, "Connection Type"),
                ],
                db_index=True,
            ),
        ),
        migrations.AlterField(
            model_name="history",
            name="action_type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Change Campaign Goal"),
                    (2, "Change Budget"),
                    (3, "Change Credit"),
                    (4, "Set Publisher Blacklist"),
                    (5, "Set Global Publisher Blacklist"),
                    (6, "Manage Reporting"),
                    (7, "Set Content Ad(s) State"),
                    (8, "Change Settings"),
                    (9, "Create"),
                    (10, "Create Content Ad"),
                    (11, "Create Conversion Pixel"),
                    (12, "Archive/Restore Conversion Pixel"),
                    (13, "Archive/Restore"),
                    (14, "Archive/Restore Content Ad(s)"),
                    (15, "Set Media Source Settings"),
                    (16, "Add Media Source"),
                    (17, "Rename conversion pixel"),
                    (18, "Create custom audience"),
                    (19, "Archive custom audience"),
                    (20, "Restore custom audience"),
                    (22, "Update custom audience"),
                    (23, "Set redirect url for pixel"),
                    (24, "Remove redirect url for pixel"),
                    (25, "Create publisher group"),
                    (26, "Update publisher group"),
                    (26, "Update publisher group"),
                    (28, "Create Conversion Pixel as additional audience pixel"),
                    (29, "Create deal connection"),
                    (30, "Delete deal connection"),
                    (31, "Update bid modifier"),
                    (32, "Delete bid modifier"),
                    (33, "Automation rule run"),
                ],
                null=True,
            ),
        ),
    ]
