# Generated by Django 2.1.11 on 2020-05-07 11:35

import textwrap

from django.db import migrations

from dash.constants import EmailTemplateType


def load_data(apps, schema_editor):
    EmailTemplate = apps.get_model("dash", "EmailTemplate")

    EmailTemplate(
        template_type=EmailTemplateType.AD_GROUP_CLONED_SUCCESS,
        subject="Campaign “{{source_ad_group_name}}” successfully cloned to {{cloned_ad_group_name}}",
        body=textwrap.dedent(
            """\
        Hi,
        We’re letting you know that your ad group "{{source_ad_group_name}}" was successfully cloned to ad group {{cloned_ad_group_name}}.
        Yours truly,
        Zemanta"""
        ),
    ).save()

    EmailTemplate(
        template_type=EmailTemplateType.AD_GROUP_CLONED_ERROR,
        subject="Error cloning “{{source_ad_group_name}}” to {{cloned_ad_group_name}}",
        body=textwrap.dedent(
            """\
        Hi,
        We’re letting you know that there was an error cloning your ad group "{{source_ad_group_name}}" to the ad group {{cloned_ad_group_name}}.
        Yours truly,
        Zemanta"""
        ),
    ).save()


class Migration(migrations.Migration):

    dependencies = [("dash", "0489_auto_20201007_1602")]

    operations = [migrations.RunPython(load_data)]
