# Generated by Django 2.1.11 on 2020-10-20 12:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0490_ad_group_clone_email_template")]

    operations = [
        migrations.AddIndex(
            model_name="contentadsource",
            index=models.Index(fields=["source", "submission_status"], name="dash_conten_source__41a204_idx"),
        )
    ]
