# Generated by Django 2.1.11 on 2020-10-21 12:01

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0491_auto_20201020_1240")]

    operations = [
        migrations.RemoveIndex(model_name="contentadsource", name="dash_conten_source__41a204_idx"),
        migrations.AddIndex(
            model_name="contentadsource",
            index=models.Index(fields=["source", "submission_status"], name="dash_contentadsource_sid_ss"),
        ),
    ]
