# Generated by Django 2.1.11 on 2020-10-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0492_auto_20201021_1201"), ("dash", "0491_clone_email_templates")]

    operations = []
