# Generated by Django 2.1.11 on 2020-11-09 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0494_clone_email_templates")]

    operations = [
        migrations.RemoveField(model_name="account", name="users"),
        migrations.RemoveField(model_name="agency", name="users"),
    ]
