# Generated by Django 2.1.11 on 2020-11-03 10:56

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0494_clone_email_templates")]

    operations = [
        migrations.CreateModel(
            name="CampaignEventProcessedAt",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("budget", "Campaign budget update"),
                            ("daily_cap", "Campaign total daily cap update"),
                            ("initialization", "Real time campaign stop initialization"),
                            ("campaignstopstate", "Campaign stop state changed"),
                        ]
                    ),
                ),
                ("modified_dt", models.DateTimeField(auto_now=True, verbose_name="Modified at")),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="dash.Campaign")),
            ],
        ),
        migrations.AlterUniqueTogether(name="campaigneventprocessedat", unique_together={("campaign", "type")}),
    ]
