# Generated by Django 2.1.11 on 2020-11-10 18:56

from decimal import Decimal

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0494_clone_email_templates")]

    operations = [
        migrations.AlterField(
            model_name="adgroupsettings",
            name="autopilot_state",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Optimize Bids and Daily Spend Caps"),
                    (2, "Disabled"),
                    (3, "Optimize Bids"),
                    (4, "Optimal Bid Bidding Strategy"),
                ],
                default=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="adgroupsettings",
            name="b1_sources_group_cpc_cc",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=Decimal("0.005"),
                max_digits=10,
                null=True,
                verbose_name="Bidder's Bid CPC",
            ),
        ),
        migrations.AlterField(
            model_name="adgroupsettings",
            name="b1_sources_group_cpm",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=Decimal("0.01"),
                max_digits=10,
                null=True,
                verbose_name="Bidder's Bid CPM",
            ),
        ),
    ]
