# Generated by Django 2.1.11 on 2020-11-03 12:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0495_auto_20201103_1056")]

    operations = [
        migrations.AlterField(
            model_name="adgroupsettings",
            name="autopilot_state",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Optimize Bids and Daily Spend Caps"),
                    (2, "Disabled"),
                    (3, "Optimize Bids"),
                    (4, "Optimal Bid Bidding Strategy"),
                ],
                default=2,
                null=True,
            ),
        )
    ]
