# Generated by Django 2.1.11 on 2020-11-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0495_auto_20201109_0841"), ("dash", "0496_auto_20201103_1211")]

    operations = []
