# Generated by Django 2.1.11 on 2020-11-16 12:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0498_auto_20201110_1856")]

    operations = [
        migrations.AddField(
            model_name="contentad",
            name="trackers",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentadcandidate",
            name="trackers",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentadcandidate",
            name="trackers_status",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
