# Generated by Django 2.1.11 on 2020-09-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0499_auto_20201116_1252")]

    operations = [
        migrations.RemoveField(model_name="adgroupsettings", name="cpc_cc"),
        migrations.RemoveField(model_name="adgroupsettings", name="local_cpc_cc"),
        migrations.RemoveField(model_name="adgroupsettings", name="local_max_cpm"),
        migrations.RemoveField(model_name="adgroupsettings", name="max_cpm"),
    ]
