# Generated by Django 2.1.11 on 2020-11-23 18:29

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0500_remove_legacy_max_cpc_cpm")]

    operations = [
        migrations.AlterField(
            model_name="agency", name="uses_realtime_autopilot", field=models.BooleanField(default=True)
        )
    ]
