# Generated by Django 2.1.11 on 2020-11-24 19:03

import jsonfield.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0500_remove_legacy_max_cpc_cpm")]

    operations = [
        migrations.AlterField(
            model_name="adgroupsettings", name="redirect_javascript", field=models.TextField(blank=True, null=True)
        ),
        migrations.AlterField(
            model_name="adgroupsettings",
            name="redirect_pixel_urls",
            field=jsonfield.fields.JSONField(blank=True, default=[], null=True),
        ),
    ]
