# Generated by Django 2.1.11 on 2020-11-30 11:22

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0501_auto_20201123_1829")]

    operations = [
        migrations.AlterField(
            model_name="whitelabel",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("greenpark", "Green Park Content"),
                    ("adtechnacity", "Adtechnacity"),
                    ("newscorp", "Newscorp"),
                    ("burda", "Burda"),
                    ("mediamond", "Mediamond"),
                    ("adyoulike", "Adyoulike"),
                    ("das", "Native Ocean"),
                ],
                max_length=255,
            ),
        )
    ]
