# Generated by Django 2.1.11 on 2020-11-30 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0501_auto_20201130_0906"), ("dash", "0501_auto_20201123_1829")]

    operations = []
