# Generated by Django 2.1.11 on 2020-12-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0502_merge_20201130_0918")]

    operations = [
        migrations.RemoveField(model_name="adgroupsettings", name="redirect_javascript"),
        migrations.RemoveField(model_name="adgroupsettings", name="redirect_pixel_urls"),
    ]
