# Generated by Django 2.1.11 on 2020-12-01 15:28

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0502_auto_20201130_1122")]

    operations = [
        migrations.AddField(
            model_name="whitelabel",
            name="copyright_holder",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="whitelabel",
            name="copyright_holder_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="whitelabel",
            name="terms_of_service_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
