# Generated by Django 2.1.11 on 2020-12-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0502_merge_20201130_0918")]

    operations = [migrations.RemoveField(model_name="contentad", name="redirect_id")]
