# Generated by Django 2.1.11 on 2020-12-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0503_auto_20201201_1528"), ("dash", "0503_auto_20201203_0856")]

    operations = []
