# Generated by Django 2.1.11 on 2020-12-03 16:57

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0504_merge_20201203_1047")]

    operations = [
        migrations.AddField(
            model_name="videoasset",
            name="supported_privacy_frameworks",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), null=True, size=None
            ),
        )
    ]
