# Generated by Django 2.1.11 on 2020-12-16 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0505_videoasset_supported_privacy_frameworks"),
        ("dash", "0503_remove_contentad_redirect_id"),
    ]

    operations = []
