# Generated by Django 2.1.11 on 2020-12-18 13:59

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0506_merge_20201216_0921")]

    operations = [
        migrations.CreateModel(
            name="CreditNotifications",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sent_80_percent", models.BooleanField(default=False)),
                ("sent_90_percent", models.BooleanField(default=False)),
                (
                    "credit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="dash.CreditLineItem",
                    ),
                ),
            ],
        )
    ]
