# Generated by Django 2.1.11 on 2020-12-23 08:02

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0506_auto_20201218_1033")]

    operations = [
        migrations.AddField(
            model_name="creativetag",
            name="account",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="dash.Account"
            ),
        ),
        migrations.AddField(
            model_name="creativetag",
            name="agency",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="dash.Agency"
            ),
        ),
        migrations.AlterField(model_name="creativetag", name="name", field=models.CharField(max_length=255)),
        migrations.AlterUniqueTogether(name="creativetag", unique_together={("name", "agency"), ("name", "account")}),
    ]
