# Generated by Django 2.1.11 on 2020-12-11 10:38

import textwrap

from django.db import migrations

from dash.constants import EmailTemplateType


def load_data(apps, schema_editor):
    EmailTemplate = apps.get_model("dash", "EmailTemplate")

    template, _ = EmailTemplate.objects.get_or_create(template_type=EmailTemplateType.CREDIT_DEPLETED_80_PERCENT)
    template.subject = "Less than 20% amount remaining on credit"
    template.body = textwrap.dedent(
        """\
        Hi,

        We would like to notify you that there's less than 20% remaining on credit {{credit.id}}.{% if credit.agency %} Agency: {{ credit.agency.name }} ({{ credit.agency.id }}){% endif %}{% if credit.account %} Account: {{ credit.account.name }} ({{ credit.account.id }}){% endif %}

        Yours truly,
        Zemanta"""
    )
    template.save()

    template, _ = EmailTemplate.objects.get_or_create(template_type=EmailTemplateType.CREDIT_DEPLETED_90_PERCENT)
    template.subject = "Less than 10% amount remaining on credit"
    template.body = textwrap.dedent(
        """\
        Hi,

        We would like to notify you that there's less than 10% remaining on credit {{credit.id}}.{% if credit.agency %} Agency: {{ credit.agency.name }} ({{ credit.agency.id }}){% endif %}{% if credit.account %} Account: {{ credit.account.name }} ({{ credit.account.id }}){% endif %}

        Yours truly,
        Zemanta"""
    )
    template.save()


class Migration(migrations.Migration):

    dependencies = [("dash", "0507_creditnotifications")]

    operations = [migrations.RunPython(load_data, reverse_code=migrations.RunPython.noop)]
