# Generated by Django 2.1.11 on 2021-01-04 09:13

from django.db import migrations
from django.db import models

from dash.constants import EmailTemplateType


def load_data(apps, schema_editor):
    EmailTemplate = apps.get_model("dash", "EmailTemplate")

    EmailTemplate(
        template_type=EmailTemplateType.UNKNOWN_SALES_OFFICE,
        subject="Externally managed user was created with unknown Sales Office",
        body="""Hi,
Externally managed user was created with unknown Sales Office: {sales_office}.
Agency and code mapping for this sales office doesn't exist yet, please create the agency (if needed) add the mapping.
    """,
    ).save()


class Migration(migrations.Migration):

    dependencies = [("dash", "0508_auto_20201218_1401")]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="template_type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Ad group settings change"),
                    (2, "Campaign settings change"),
                    (3, "Budget change"),
                    (4, "New conversion pixel"),
                    (5, "User password reset"),
                    (6, "New user introduction email"),
                    (7, "Supply report"),
                    (8, "Scheduled report"),
                    (9, "Depleting budget notification"),
                    (10, "Campaign stopped notification"),
                    (11, "Autopilot changes notification"),
                    (12, "Autopilot initialisation notification"),
                    (15, "Demo is running"),
                    (16, "Livestream sesion id"),
                    (17, "Daily management report"),
                    (18, "Unused Outbrain accounts running out"),
                    (19, "Google Analytics Setup Instructions"),
                    (20, "Report results"),
                    (21, "Depleting credits"),
                    (22, "Account settings change"),
                    (23, "Weekly client report"),
                    (24, "Pacing notification"),
                    (25, "Weekly inventory report"),
                    (26, "New device login"),
                    (27, "Scheduled report results"),
                    (28, "Zemanta OEN CPA Optimization Factors"),
                    (29, "Report fail"),
                    (30, "Campaign Autopilot changes notification"),
                    (31, "Campaign Autopilot initialisation notification"),
                    (32, "Real-time campaign stop budget depleting"),
                    (33, "User was granted REST API access"),
                    (34, "Campaign created"),
                    (35, "Automation rule run"),
                    (36, "Automation rule run without changes"),
                    (37, "Automation rule run with errors"),
                    (38, "Campaign cloned successfully"),
                    (39, "Campaign cloned error"),
                    (40, "Ad group cloned successfully"),
                    (41, "Ad group cloned error"),
                    (42, "Credit depleted 80 percent"),
                    (43, "Credit depleted 90 percent"),
                    (44, "Externally managed user was created with unknown sales office"),
                ],
                null=True,
            ),
        ),
        migrations.RunPython(load_data),
    ]
