# Generated by Django 2.1.11 on 2021-01-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0507_auto_20201223_0802"), ("dash", "0509_auto_20210104_0913")]

    operations = []
