# Generated by Django 2.1.11 on 2021-01-12 15:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0511_auto_20210111_0854")]

    operations = [
        migrations.AlterField(
            model_name="creativebatch",
            name="original_filename",
            field=models.CharField(blank=True, default="", max_length=1024),
        )
    ]
