# Generated by Django 2.1.11 on 2021-01-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0512_auto_20210112_1511")]

    operations = [
        migrations.RenameField(model_name="creativebatch", old_name="default_brand_name", new_name="brand_name"),
        migrations.RenameField(
            model_name="creativebatch", old_name="default_call_to_action", new_name="call_to_action"
        ),
        migrations.RenameField(model_name="creativebatch", old_name="default_description", new_name="description"),
        migrations.RenameField(model_name="creativebatch", old_name="default_display_url", new_name="display_url"),
        migrations.RenameField(model_name="creativebatch", old_name="default_image_crop", new_name="image_crop"),
        migrations.RenameField(model_name="creativebatch", old_name="default_tags", new_name="tags"),
    ]
