# Generated by Django 2.1.11 on 2021-01-19 16:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0513_auto_20210113_1314")]

    operations = [
        migrations.AddField(model_name="agency", name="uses_source_groups", field=models.BooleanField(default=False))
    ]
