# Generated by Django 2.2.17 on 2021-02-02 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dash", "0515_unique_primary_campaign_goals")]

    operations = [migrations.RemoveField(model_name="creativecandidate", name="created_dt")]
