# Generated by Django 2.2.17 on 2021-02-02 14:37

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0516_remove_creativecandidate_created_dt")]

    operations = [
        migrations.AddField(
            model_name="creativebatch",
            name="ad_type",
            field=models.IntegerField(
                choices=[(1, "Content ad"), (2, "Video ad"), (3, "Image display ad"), (4, "Display ad tag")], default=1
            ),
        ),
        migrations.AddField(
            model_name="creativebatch",
            name="type",
            field=models.IntegerField(choices=[(1, "Insert"), (2, "Edit"), (3, "Clone")], default=1),
        ),
        migrations.AlterField(
            model_name="creativecandidate",
            name="icon_file_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="creativecandidate",
            name="icon_hash",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="creativecandidate", name="icon_height", field=models.PositiveIntegerField(blank=True, null=True)
        ),
        migrations.AlterField(
            model_name="creativecandidate",
            name="icon_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="creativecandidate", name="icon_width", field=models.PositiveIntegerField(blank=True, null=True)
        ),
        migrations.AlterField(
            model_name="creativecandidate",
            name="image_file_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="creativecandidate",
            name="image_hash",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="creativecandidate",
            name="image_height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="creativecandidate",
            name="image_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="creativecandidate", name="image_width", field=models.PositiveIntegerField(blank=True, null=True)
        ),
        migrations.AlterField(
            model_name="creativecandidate",
            name="original_creative",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="dash.Creative"
            ),
        ),
    ]
