# Generated by Django 2.2.17 on 2021-02-03 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0517_auto_20210202_1437"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creativecandidate",
            name="type",
        ),
    ]
