# Generated by Django 2.2.17 on 2021-02-09 09:26

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0518_remove_creativecandidate_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creativebatch",
            name="ad_type",
        ),
        migrations.AddField(
            model_name="creativebatch",
            name="mode",
            field=models.IntegerField(choices=[(1, "Insert"), (2, "Edit"), (3, "Clone")], default=1),
        ),
        migrations.AddField(
            model_name="creativecandidate",
            name="type",
            field=models.IntegerField(
                choices=[(1, "Content ad"), (2, "Video ad"), (3, "Image display ad"), (4, "Display ad tag")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="creativebatch",
            name="type",
            field=models.IntegerField(choices=[(1, "Native"), (2, "Video"), (3, "Display")], default=1),
        ),
    ]
