# Generated by Django 2.2.17 on 2021-02-16 07:10
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0519_auto_20210209_0926"),
    ]

    operations = [UnaccentExtension()]
