# Generated by Django 2.2.17 on 2021-02-16 14:53

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0519_auto_20210209_0926"),
    ]

    operations = [
        migrations.AddField(
            model_name="creative",
            name="image_height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creative",
            name="image_width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="creative",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="creatives",
                to="dash.ImageAsset",
            ),
        ),
        migrations.AlterField(
            model_name="creative",
            name="image",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="dash.ImageAsset"
            ),
        ),
        migrations.AlterField(
            model_name="creative",
            name="title",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="creative",
            name="url",
            field=models.CharField(blank=True, default="", max_length=2048),
        ),
    ]
