# Generated by Django 2.2.17 on 2021-02-26 19:11

from decimal import Decimal

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0520_auto_20210216_1453"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountstatuscache",
            name="local_daily_budget",
            field=models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=10),
        ),
    ]
