AD_GROUP_COLUMN_NAMES = [
    "date",
    "agency_id",
    "agency_name",
    "agency_created_dt",
    "account_id",
    "account_name",
    "account_created_dt",
    "account_type",
    "campaign_id",
    "campaign_name",
    "campaign_created_dt",
    "type",
    "adgroup_id",
    "adgroup_name",
    "adgroup_created_dt",
    "whitelabel",
    "whitelist_publisher_groups",
    "blacklist_publisher_groups",
    "real_time_campaign_stop",
    "currency",
    "auto_add_new_sources",
    "iab_category",
    "automatic_campaign_stop",
    "enable_adobe_tracking",
    "enable_ga_tracking",
    "ga_tracking_type",
    "language",
    "autopilot",
    "impressions",
    "clicks",
    "spend",
    "calculated_daily_budget",
    "calculated_bid",
    "start_date",
    "end_date",
    "bid",
    "target_devices",
    "target_regions",
    "world_region",
    "geo_targeting_type",
    "autopilot_daily_budget",
    "autopilot_state",
    "retargeting_ad_groups",
    "exclusion_retargeting_ad_groups",
    "bluekai_targeting",
    "exclusion_interest_targeting",
    "interest_targeting",
    "audience_targeting",
    "exclusion_audience_targeting",
    "b1_sources_group_daily_budget",
    "b1_sources_group_enabled",
    "b1_sources_group_state",
    "dayparting",
    "b1_sources_group_cpc_cc",
    "exclusion_target_regions",
    "target_os",
    "target_environments",
    "delivery_type",
    "click_capping_daily_ad_group_max_clicks",
    "b1_sources_group_cpm",
    "modified_by_id",
    "sales_representative_id",
    "cs_representative_id",
    "sales_email",
    "cs_email",
    "frequency_capping",
    "active_ssps",
    "active_ssps_count",
    "bidding_type",
    "goal_type",
    "goal_value",
    "budget_end_date",
    "credit_end_date",
    "remaining_credit",
    "remaining_budget",
    "agency_tags",
    "account_tags",
    "campaign_tags",
    "adgroup_tags",
    "rules",
    "rules_count",
    "target_browsers",
    "exclusion_target_browsers",
    "target_connection_types",
    "visits",
    "video_midpoint",
    "video_complete",
    "mrc50_measurable",
    "mrc50_viewable",
    "mrc100_measurable",
    "mrc100_viewable",
    "vast4_measurable",
    "vast4_viewable",
    "publisher_bid_modifiers_count",
    "source_bid_modifiers_count",
    "device_bid_modifiers_count",
    "operating_system_bid_modifiers_count",
    "environment_bid_modifiers_count",
    "country_bid_modifiers_count",
    "state_bid_modifiers_count",
    "dma_bid_modifiers_count",
    "ad_bid_modifiers_count",
    "day_hour_bid_modifiers_count",
    "placement_bid_modifiers_count",
    "license_fee",
    "js_tracking",
]

WORLD_REGIONS = {
    "": "World",
    "AE": "Middle East",
    "AR": "South America",
    "AT": "Europe",
    "AU": "APAC",
    "BE": "Europe",
    "BF": "Africa",
    "BH": "Middle East",
    "BJ": "South America",
    "BO": "Africa",
    "BR": "South America",
    "CA": "North America",
    "CG": "Africa",
    "CH": "Europe",
    "CI": "Africa",
    "CL": "South America",
    "CM": "Africa",
    "CN": "APAC",
    "CO": "South America",
    "CR": "South America",
    "DE": "Europe",
    "DO": "South America",
    "EC": "South America",
    "ES": "Europe",
    "FR": "Europe",
    "GB": "Europe",
    "GR": "Europe",
    "GT": "South America",
    "IT": "Europe",
    "JP": "APAC",
    "KE": "Africa",
    "KR": "APAC",
    "KW": "Middle East",
    "MX": "North America",
    "NG": "Africa",
    "NI": "South America",
    "NL": "Europe",
    "NZ": "APAC",
    "OM": "Middle East",
    "PA": "South America",
    "PE": "South America",
    "QA": "Middle East",
    "RU": "APAC",
    "SA": "Middle East",
    "SG": "APAC",
    "SI": "Europe",
    "SV": "South America",
    "US": "North America",
    "FI": "Europe",
    "NO": "Europe",
    "ZA": "Africa",
    "SE": "Europe",
    "TT": "South America",
    "UG": "Africa",
    "TZ": "Africa",
    "IE": "Europe",
    "IN": "APAC",
    "MA": "Africa",
    "RO": "Europe",
    "PT": "Europe",
    "PR": "South America",
    "MM": "APAC",
    "CZ": "Europe",
    "MY": "APAC",
    "AG": "South America",
    "HU": "Europe",
    "EE": "Europe",
}

MEDIA_SOURCE_COLUMN_NAMES = [
    "date",
    "adgroup_id",
    "source_id",
    "state",
    "name",
    "bidder_slug",
    "tracking_slug",
    "impressions",
    "clicks",
    "spend",
    "visits",
    "video_midpoint",
    "video_complete",
    "mrc50_measurable",
    "mrc50_viewable",
    "mrc100_measurable",
    "mrc100_viewable",
    "vast4_measurable",
    "vast4_viewable",
    "license_fee",
    "modifier",
]


CONTENT_AD_COLUMN_NAMES = [
    "date",
    "ad_group_id",
    "content_ad_id",
    "state",
    "type",
    "title",
    "url",
    "description",
    "impressions",
    "clicks",
    "spend",
    "visits",
    "video_midpoint",
    "video_complete",
    "mrc50_measurable",
    "mrc50_viewable",
    "mrc100_measurable",
    "mrc100_viewable",
    "vast4_measurable",
    "vast4_viewable",
    "license_fee",
    "modifier",
]
