/*exported defaults, options*/

var constants = {
    /**
     * Max. selected media sources in on sources tabs.
     */
    maxSelectedSources: 3,
    adGroupSettingsState: {
        ACTIVE: 1,
        INACTIVE: 2,
    },
    adGroupSettingsAutopilotState: {
        ACTIVE_CPC_BUDGET: 1,
        INACTIVE: 2,
        ACTIVE_CPC: 3,
    },
    adGroupRunningStatus: {
        ACTIVE: 1,
        INACTIVE: 2,
    },
    adGroupSourceSettingsState: {
        ACTIVE: 1,
        INACTIVE: 2,
    },
    publisherStatus: {
        ENABLED: 1,
        BLACKLISTED: 2,
    },
    adTargetDevice: {
        DESKTOP: 'desktop',
        MOBILE: 'mobile',
    },
    chartMetric: {
        CLICKS: 'clicks',
        IMPRESSIONS: 'impressions',
        CTR: 'ctr',
        COST: 'cost',
        DATA_COST: 'data_cost',
        EFFECTIVE_DATA_COST: 'e_data_cost',
        MEDIA_COST: 'media_cost',
        EFFECTIVE_MEDIA_COST: 'e_media_cost',
        BILLING_COST: 'billing_cost',
        LICENSE_FEE: 'license_fee',
        CPC: 'cpc',
        VISITS: 'visits',
        PAGEVIEWS: 'pageviews',
        NEW_USERS: 'percent_new_users',
        BOUNCE_RATE: 'bounce_rate',
        PV_PER_VISIT: 'pv_per_visit',
        AVG_TOS: 'avg_tos',
        CLICK_DISCREPANCY: 'click_discrepancy',
        CONVERSION_GOAL1: 'conversion_goal_1',
        CONVERSION_GOAL2: 'conversion_goal_2',
        CONVERSION_GOAL3: 'conversion_goal_3',
        CONVERSION_GOAL4: 'conversion_goal_4',
        CONVERSION_GOAL5: 'conversion_goal_5',
        TOTAL_SECONDS: 'total_seconds',
        TOTAL_PAGEVIEWS: 'total_pageviews',
        UNBOUNCED_VISITS: 'unbounced_visits',
        COST_PER_SECOND: 'avg_cost_per_second',
        COST_PER_PAGEVIEW: 'avg_cost_per_pageview',
        COST_PER_UNBOUNCED_VISITOR: 'avg_cost_per_non_bounced_visitor',
        COST_PER_NEW_VISITOR: 'avg_cost_for_new_visitor',
        COST_PER_CONVERSION_GOAL_1: 'avg_cost_per_conversion_goal_1',
        COST_PER_CONVERSION_GOAL_2: 'avg_cost_per_conversion_goal_2',
        COST_PER_CONVERSION_GOAL_3: 'avg_cost_per_conversion_goal_3',
        COST_PER_CONVERSION_GOAL_4: 'avg_cost_per_conversion_goal_4',
        COST_PER_CONVERSION_GOAL_5: 'avg_cost_per_conversion_goal_5',
    },
    creditLineItemStatus: {
        SIGNED: 1,
        PENDING: 2,
        CANCELED: 3,
    },
    budgetLineItemStatus: {
        ACTIVE: 1,
        PENDING: 2,
        INACTIVE: 3,
        DEPLETED: 4,
    },
    iabCategory: {
        IAB1: 'IAB1',
        IAB1_1: 'IAB1-1',
        IAB1_2: 'IAB1-2',
        IAB1_3: 'IAB1-3',
        IAB1_4: 'IAB1-4',
        IAB1_5: 'IAB1-5',
        IAB1_6: 'IAB1-6',
        IAB1_7: 'IAB1-7',
        IAB2: 'IAB2',
        IAB2_1: 'IAB2-1',
        IAB2_2: 'IAB2-2',
        IAB2_3: 'IAB2-3',
        IAB2_4: 'IAB2-4',
        IAB2_5: 'IAB2-5',
        IAB2_6: 'IAB2-6',
        IAB2_7: 'IAB2-7',
        IAB2_8: 'IAB2-8',
        IAB2_9: 'IAB2-9',
        IAB2_10: 'IAB2-10',
        IAB2_11: 'IAB2-11',
        IAB2_12: 'IAB2-12',
        IAB2_13: 'IAB2-13',
        IAB2_14: 'IAB2-14',
        IAB2_15: 'IAB2-15',
        IAB2_16: 'IAB2-16',
        IAB2_17: 'IAB2-17',
        IAB2_18: 'IAB2-18',
        IAB2_19: 'IAB2-19',
        IAB2_20: 'IAB2-20',
        IAB2_21: 'IAB2-21',
        IAB2_22: 'IAB2-22',
        IAB2_23: 'IAB2-23',
        IAB3: 'IAB3',
        IAB3_1: 'IAB3-1',
        IAB3_2: 'IAB3-2',
        IAB3_3: 'IAB3-3',
        IAB3_4: 'IAB3-4',
        IAB3_5: 'IAB3-5',
        IAB3_6: 'IAB3-6',
        IAB3_7: 'IAB3-7',
        IAB3_8: 'IAB3-8',
        IAB3_9: 'IAB3-9',
        IAB3_10: 'IAB3-10',
        IAB3_11: 'IAB3-11',
        IAB3_12: 'IAB3-12',
        IAB4: 'IAB4',
        IAB4_1: 'IAB4-1',
        IAB4_2: 'IAB4-2',
        IAB4_3: 'IAB4-3',
        IAB4_4: 'IAB4-4',
        IAB4_5: 'IAB4-5',
        IAB4_6: 'IAB4-6',
        IAB4_7: 'IAB4-7',
        IAB4_8: 'IAB4-8',
        IAB4_9: 'IAB4-9',
        IAB4_10: 'IAB4-10',
        IAB4_11: 'IAB4-11',
        IAB5: 'IAB5',
        IAB5_1: 'IAB5-1',
        IAB5_2: 'IAB5-2',
        IAB5_3: 'IAB5-3',
        IAB5_4: 'IAB5-4',
        IAB5_5: 'IAB5-5',
        IAB5_6: 'IAB5-6',
        IAB5_7: 'IAB5-7',
        IAB5_8: 'IAB5-8',
        IAB5_9: 'IAB5-9',
        IAB5_10: 'IAB5-10',
        IAB5_11: 'IAB5-11',
        IAB5_12: 'IAB5-12',
        IAB5_13: 'IAB5-13',
        IAB5_14: 'IAB5-14',
        IAB5_15: 'IAB5-15',
        IAB6: 'IAB6',
        IAB6_1: 'IAB6-1',
        IAB6_2: 'IAB6-2',
        IAB6_3: 'IAB6-3',
        IAB6_4: 'IAB6-4',
        IAB6_5: 'IAB6-5',
        IAB6_6: 'IAB6-6',
        IAB6_7: 'IAB6-7',
        IAB6_8: 'IAB6-8',
        IAB6_9: 'IAB6-9',
        IAB7: 'IAB7',
        IAB7_1: 'IAB7-1',
        IAB7_2: 'IAB7-2',
        IAB7_3: 'IAB7-3',
        IAB7_4: 'IAB7-4',
        IAB7_5: 'IAB7-5',
        IAB7_6: 'IAB7-6',
        IAB7_7: 'IAB7-7',
        IAB7_8: 'IAB7-8',
        IAB7_9: 'IAB7-9',
        IAB7_10: 'IAB7-10',
        IAB7_11: 'IAB7-11',
        IAB7_12: 'IAB7-12',
        IAB7_13: 'IAB7-13',
        IAB7_14: 'IAB7-14',
        IAB7_15: 'IAB7-15',
        IAB7_16: 'IAB7-16',
        IAB7_17: 'IAB7-17',
        IAB7_18: 'IAB7-18',
        IAB7_19: 'IAB7-19',
        IAB7_20: 'IAB7-20',
        IAB7_21: 'IAB7-21',
        IAB7_22: 'IAB7-22',
        IAB7_23: 'IAB7-23',
        IAB7_24: 'IAB7-24',
        IAB7_25: 'IAB7-25',
        IAB7_26: 'IAB7-26',
        IAB7_27: 'IAB7-27',
        IAB7_28: 'IAB7-28',
        IAB7_29: 'IAB7-29',
        IAB7_30: 'IAB7-30',
        IAB7_31: 'IAB7-31',
        IAB7_32: 'IAB7-32',
        IAB7_33: 'IAB7-33',
        IAB7_34: 'IAB7-34',
        IAB7_35: 'IAB7-35',
        IAB7_36: 'IAB7-36',
        IAB7_37: 'IAB7-37',
        IAB7_38: 'IAB7-38',
        IAB7_39: 'IAB7-39',
        IAB7_40: 'IAB7-40',
        IAB7_41: 'IAB7-41',
        IAB7_42: 'IAB7-42',
        IAB7_43: 'IAB7-43',
        IAB7_44: 'IAB7-44',
        IAB7_45: 'IAB7-45',
        IAB8: 'IAB8',
        IAB8_1: 'IAB8-1',
        IAB8_2: 'IAB8-2',
        IAB8_3: 'IAB8-3',
        IAB8_4: 'IAB8-4',
        IAB8_5: 'IAB8-5',
        IAB8_6: 'IAB8-6',
        IAB8_7: 'IAB8-7',
        IAB8_8: 'IAB8-8',
        IAB8_9: 'IAB8-9',
        IAB8_10: 'IAB8-10',
        IAB8_11: 'IAB8-11',
        IAB8_12: 'IAB8-12',
        IAB8_13: 'IAB8-13',
        IAB8_14: 'IAB8-14',
        IAB8_15: 'IAB8-15',
        IAB8_16: 'IAB8-16',
        IAB8_17: 'IAB8-17',
        IAB8_18: 'IAB8-18',
        IAB9: 'IAB9',
        IAB9_1: 'IAB9-1',
        IAB9_2: 'IAB9-2',
        IAB9_3: 'IAB9-3',
        IAB9_4: 'IAB9-4',
        IAB9_5: 'IAB9-5',
        IAB9_6: 'IAB9-6',
        IAB9_7: 'IAB9-7',
        IAB9_8: 'IAB9-8',
        IAB9_9: 'IAB9-9',
        IAB9_10: 'IAB9-10',
        IAB9_11: 'IAB9-11',
        IAB9_12: 'IAB9-12',
        IAB9_13: 'IAB9-13',
        IAB9_14: 'IAB9-14',
        IAB9_15: 'IAB9-15',
        IAB9_16: 'IAB9-16',
        IAB9_17: 'IAB9-17',
        IAB9_18: 'IAB9-18',
        IAB9_19: 'IAB9-19',
        IAB9_20: 'IAB9-20',
        IAB9_21: 'IAB9-21',
        IAB9_22: 'IAB9-22',
        IAB9_23: 'IAB9-23',
        IAB9_24: 'IAB9-24',
        IAB9_25: 'IAB9-25',
        IAB9_26: 'IAB9-26',
        IAB9_27: 'IAB9-27',
        IAB9_28: 'IAB9-28',
        IAB9_29: 'IAB9-29',
        IAB9_30: 'IAB9-30',
        IAB9_31: 'IAB9-31',
        IAB10: 'IAB10',
        IAB10_1: 'IAB10-1',
        IAB10_2: 'IAB10-2',
        IAB10_3: 'IAB10-3',
        IAB10_4: 'IAB10-4',
        IAB10_5: 'IAB10-5',
        IAB10_6: 'IAB10-6',
        IAB10_7: 'IAB10-7',
        IAB10_8: 'IAB10-8',
        IAB10_9: 'IAB10-9',
        IAB11: 'IAB11',
        IAB11_1: 'IAB11-1',
        IAB11_2: 'IAB11-2',
        IAB11_3: 'IAB11-3',
        IAB11_4: 'IAB11-4',
        IAB11_5: 'IAB11-5',
        IAB12: 'IAB12',
        IAB12_1: 'IAB12-1',
        IAB12_2: 'IAB12-2',
        IAB12_3: 'IAB12-3',
        IAB13: 'IAB13',
        IAB13_1: 'IAB13-1',
        IAB13_2: 'IAB13-2',
        IAB13_3: 'IAB13-3',
        IAB13_4: 'IAB13-4',
        IAB13_5: 'IAB13-5',
        IAB13_6: 'IAB13-6',
        IAB13_7: 'IAB13-7',
        IAB13_8: 'IAB13-8',
        IAB13_9: 'IAB13-9',
        IAB13_10: 'IAB13-10',
        IAB13_11: 'IAB13-11',
        IAB13_12: 'IAB13-12',
        IAB14: 'IAB14',
        IAB14_1: 'IAB14-1',
        IAB14_2: 'IAB14-2',
        IAB14_3: 'IAB14-3',
        IAB14_4: 'IAB14-4',
        IAB14_5: 'IAB14-5',
        IAB14_6: 'IAB14-6',
        IAB14_7: 'IAB14-7',
        IAB14_8: 'IAB14-8',
        IAB15: 'IAB15',
        IAB15_1: 'IAB15-1',
        IAB15_2: 'IAB15-2',
        IAB15_3: 'IAB15-3',
        IAB15_4: 'IAB15-4',
        IAB15_5: 'IAB15-5',
        IAB15_6: 'IAB15-6',
        IAB15_7: 'IAB15-7',
        IAB15_8: 'IAB15-8',
        IAB15_9: 'IAB15-9',
        IAB15_10: 'IAB15-10',
        IAB16: 'IAB16',
        IAB16_1: 'IAB16-1',
        IAB16_2: 'IAB16-2',
        IAB16_3: 'IAB16-3',
        IAB16_4: 'IAB16-4',
        IAB16_5: 'IAB16-5',
        IAB16_6: 'IAB16-6',
        IAB16_7: 'IAB16-7',
        IAB17: 'IAB17',
        IAB17_1: 'IAB17-1',
        IAB17_2: 'IAB17-2',
        IAB17_3: 'IAB17-3',
        IAB17_4: 'IAB17-4',
        IAB17_5: 'IAB17-5',
        IAB17_6: 'IAB17-6',
        IAB17_7: 'IAB17-7',
        IAB17_8: 'IAB17-8',
        IAB17_9: 'IAB17-9',
        IAB17_10: 'IAB17-10',
        IAB17_11: 'IAB17-11',
        IAB17_12: 'IAB17-12',
        IAB17_13: 'IAB17-13',
        IAB17_14: 'IAB17-14',
        IAB17_15: 'IAB17-15',
        IAB17_16: 'IAB17-16',
        IAB17_17: 'IAB17-17',
        IAB17_18: 'IAB17-18',
        IAB17_19: 'IAB17-19',
        IAB17_20: 'IAB17-20',
        IAB17_21: 'IAB17-21',
        IAB17_22: 'IAB17-22',
        IAB17_23: 'IAB17-23',
        IAB17_24: 'IAB17-24',
        IAB17_25: 'IAB17-25',
        IAB17_26: 'IAB17-26',
        IAB17_27: 'IAB17-27',
        IAB17_28: 'IAB17-28',
        IAB17_29: 'IAB17-29',
        IAB17_30: 'IAB17-30',
        IAB17_31: 'IAB17-31',
        IAB17_32: 'IAB17-32',
        IAB17_33: 'IAB17-33',
        IAB17_34: 'IAB17-34',
        IAB17_35: 'IAB17-35',
        IAB17_36: 'IAB17-36',
        IAB17_37: 'IAB17-37',
        IAB17_38: 'IAB17-38',
        IAB17_39: 'IAB17-39',
        IAB17_40: 'IAB17-40',
        IAB17_41: 'IAB17-41',
        IAB17_42: 'IAB17-42',
        IAB17_43: 'IAB17-43',
        IAB17_44: 'IAB17-44',
        IAB18: 'IAB18',
        IAB18_1: 'IAB18-1',
        IAB18_2: 'IAB18-2',
        IAB18_3: 'IAB18-3',
        IAB18_4: 'IAB18-4',
        IAB18_5: 'IAB18-5',
        IAB18_6: 'IAB18-6',
        IAB19: 'IAB19',
        IAB19_1: 'IAB19-1',
        IAB19_2: 'IAB19-2',
        IAB19_3: 'IAB19-3',
        IAB19_4: 'IAB19-4',
        IAB19_5: 'IAB19-5',
        IAB19_6: 'IAB19-6',
        IAB19_7: 'IAB19-7',
        IAB19_8: 'IAB19-8',
        IAB19_9: 'IAB19-9',
        IAB19_10: 'IAB19-10',
        IAB19_11: 'IAB19-11',
        IAB19_12: 'IAB19-12',
        IAB19_13: 'IAB19-13',
        IAB19_14: 'IAB19-14',
        IAB19_15: 'IAB19-15',
        IAB19_16: 'IAB19-16',
        IAB19_17: 'IAB19-17',
        IAB19_18: 'IAB19-18',
        IAB19_19: 'IAB19-19',
        IAB19_20: 'IAB19-20',
        IAB19_21: 'IAB19-21',
        IAB19_22: 'IAB19-22',
        IAB19_23: 'IAB19-23',
        IAB19_24: 'IAB19-24',
        IAB19_25: 'IAB19-25',
        IAB19_26: 'IAB19-26',
        IAB19_27: 'IAB19-27',
        IAB19_28: 'IAB19-28',
        IAB19_29: 'IAB19-29',
        IAB19_30: 'IAB19-30',
        IAB19_31: 'IAB19-31',
        IAB19_32: 'IAB19-32',
        IAB19_33: 'IAB19-33',
        IAB19_34: 'IAB19-34',
        IAB19_35: 'IAB19-35',
        IAB19_36: 'IAB19-36',
        IAB20: 'IAB20',
        IAB20_1: 'IAB20-1',
        IAB20_2: 'IAB20-2',
        IAB20_3: 'IAB20-3',
        IAB20_4: 'IAB20-4',
        IAB20_5: 'IAB20-5',
        IAB20_6: 'IAB20-6',
        IAB20_7: 'IAB20-7',
        IAB20_8: 'IAB20-8',
        IAB20_9: 'IAB20-9',
        IAB20_10: 'IAB20-10',
        IAB20_11: 'IAB20-11',
        IAB20_12: 'IAB20-12',
        IAB20_13: 'IAB20-13',
        IAB20_14: 'IAB20-14',
        IAB20_15: 'IAB20-15',
        IAB20_16: 'IAB20-16',
        IAB20_17: 'IAB20-17',
        IAB20_18: 'IAB20-18',
        IAB20_19: 'IAB20-19',
        IAB20_20: 'IAB20-20',
        IAB20_21: 'IAB20-21',
        IAB20_22: 'IAB20-22',
        IAB20_23: 'IAB20-23',
        IAB20_24: 'IAB20-24',
        IAB20_25: 'IAB20-25',
        IAB20_26: 'IAB20-26',
        IAB20_27: 'IAB20-27',
        IAB21: 'IAB21',
        IAB21_1: 'IAB21-1',
        IAB21_2: 'IAB21-2',
        IAB21_3: 'IAB21-3',
        IAB22: 'IAB22',
        IAB22_1: 'IAB22-1',
        IAB22_2: 'IAB22-2',
        IAB22_3: 'IAB22-3',
        IAB22_4: 'IAB22-4',
        IAB23: 'IAB23',
        IAB23_1: 'IAB23-1',
        IAB23_2: 'IAB23-2',
        IAB23_3: 'IAB23-3',
        IAB23_4: 'IAB23-4',
        IAB23_5: 'IAB23-5',
        IAB23_6: 'IAB23-6',
        IAB23_7: 'IAB23-7',
        IAB23_8: 'IAB23-8',
        IAB23_9: 'IAB23-9',
        IAB23_10: 'IAB23-10',
        IAB24: 'IAB24',
        IAB25: 'IAB25',
        IAB25_1: 'IAB25-1',
        IAB25_2: 'IAB25-2',
        IAB25_3: 'IAB25-3',
        IAB25_4: 'IAB25-4',
        IAB25_5: 'IAB25-5',
        IAB25_6: 'IAB25-6',
        IAB25_7: 'IAB25-7',
        IAB26: 'IAB26',
        IAB26_1: 'IAB26-1',
        IAB26_2: 'IAB26-2',
        IAB26_3: 'IAB26-3',
        IAB26_4: 'IAB26-4',
    },
    promotionGoal: {
        BRAND_BUILDING: 1,
        TRAFFIC_ACQUISITION: 2,
        CONVERSIONS: 3,
    },
    campaignGoal: {
        CPA: 1,
        PERCENT_BOUNCE_RATE: 2,
        NEW_UNIQUE_VISITORS: 3,
        SECONDS_TIME_ON_SITE: 4,
        PAGES_PER_SESSION: 5,
    },
    campaignGoalKPI: {
        TIME_ON_SITE: 1,
        MAX_BOUNCE_RATE: 2,
        PAGES_PER_SESSION: 3,
        CPA: 4,
        CPC: 5,
        CPM: 6,
        NEW_UNIQUE_VISITORS: 7,
    },
    conversionGoalType: {
        PIXEL: 1,
        GA: 2,
        OMNITURE: 3,
    },
    conversionGoalTypeText: {
        1: 'Conversion Pixel',
        2: 'Google Analytics',
        3: 'Adobe Analytics',
    },
    conversionWindowText: {
        24: '1 day',
        168: '7 days',
        720: '30 days',
    },
    entityType: {
        AD_GROUP: 'adGroup',
        CAMPAIGN: 'campaign',
        ACCOUNT: 'account',
    },
    level: {
        AD_GROUPS: 'ad_groups',
        CAMPAIGNS: 'campaigns',
        ACCOUNTS: 'accounts',
        ALL_ACCOUNTS: 'all_accounts',
    },
    contentAdApprovalStatus: {
        PENDING: 1,
        APPROVED: 2,
        REJECTED: 3,
    },
    uploadBatchStatus: {
        DONE: 1,
        FAILED: 2,
        IN_PROGRESS: 3,
        CANCELLED: 4,
    },
    contentAdSourceState: {
        ACTIVE: 1,
        INACTIVE: 2,
    },
    exportType: {
        ALL_ACCOUNTS: 'allaccounts-csv',
        ACCOUNT: 'account-csv',
        CAMPAIGN: 'campaign-csv',
        AD_GROUP: 'adgroup-csv',
        CONTENT_AD: 'contentad-csv',
    },
    exportFrequency: {
        DAILY: 'daily',
        WEEKLY: 'weekly',
        MONTHLY: 'monthly',
    },
    publisherBlacklistLevel: {
        ADGROUP: 'adgroup',
        CAMPAIGN: 'campaign',
        ACCOUNT: 'account',
        GLOBAL: 'global',
    },
    /* source type names are string values of dash.SourceType */
    sourceTypeName: {
        ADBLADE: 'AdBlade',
        GRAVITY: 'Gravity',
        NRELATE: 'nRelate',
        OUTBRAIN: 'Outbrain',
        YAHOO: 'Yahoo',
        ZEMANTA: 'Zemanta',
        B1: 'B1',
    },
    emoticon: {
        HAPPY: 1,
        NEUTRAL: 2,
        SAD: 3,
    },
};

var options = {
    adGroupSettingsStates: [
        {name: 'Paused', value: constants.adGroupSettingsState.INACTIVE},
        {name: 'Enabled', value: constants.adGroupSettingsState.ACTIVE},
    ],
    adGroupSettingsAutopilotStates: [{
        name: 'Disabled',
        help: 'Auto-Pilot will not operate on this Ad Group.',
        value: constants.adGroupSettingsAutopilotState.INACTIVE,
    }, {
        name: 'Optimize Bid CPCs',
        help: 'Bid CPCs on active Media Sources in this Ad Group will be optimized.' +
              'Ad Group\'s Maximum CPC constraint will be enforced.',
        value: constants.adGroupSettingsAutopilotState.ACTIVE_CPC,
    }, {
        name: 'Optimize Bid CPCs and Daily Budgets',
        help: 'Both Bid CPCs and Daily Budgets will be optimized on active Media Sources in this Ad Group.',
        value: constants.adGroupSettingsAutopilotState.ACTIVE_CPC_BUDGET,
    },
    ],
    adTargetDevices: [
        {name: 'Desktop', value: constants.adTargetDevice.DESKTOP},
        {name: 'Mobile', value: constants.adTargetDevice.MOBILE},
    ],
    adGroupChartMetrics: [
        {name: 'Clicks', value: constants.chartMetric.CLICKS},
        {name: 'Impressions', value: constants.chartMetric.IMPRESSIONS},
        {name: 'CTR', value: constants.chartMetric.CTR},
        {name: 'Avg. CPC', value: constants.chartMetric.CPC},
    ],
    adGroupAcquisitionChartPostClickMetrics: [
        {name: 'Visits', value: constants.chartMetric.VISITS},
        {name: 'Click Discrepancy', value: constants.chartMetric.CLICK_DISCREPANCY},
        {name: 'Pageviews', value: constants.chartMetric.PAGEVIEWS},
    ],
    adGroupEngagementChartPostClickMetrics: [
        {name: '% New Users', value: constants.chartMetric.NEW_USERS},
        {name: 'Bounce Rate', value: constants.chartMetric.BOUNCE_RATE},
        {name: 'Pageviews per Visit', value: constants.chartMetric.PV_PER_VISIT},
        {name: 'Avg. ToS', value: constants.chartMetric.AVG_TOS},
    ],
    adGroupConversionGoalChartMetrics: [
        {name: '', value: constants.chartMetric.CONVERSION_GOAL1, shown: false},
        {name: '', value: constants.chartMetric.CONVERSION_GOAL2, shown: false},
        {name: '', value: constants.chartMetric.CONVERSION_GOAL3, shown: false},
        {name: '', value: constants.chartMetric.CONVERSION_GOAL4, shown: false},
        {name: '', value: constants.chartMetric.CONVERSION_GOAL5, shown: false},
    ],
    campaignChartMetrics: [
        {name: 'Clicks', value: constants.chartMetric.CLICKS},
        {name: 'Impressions', value: constants.chartMetric.IMPRESSIONS},
        {name: 'CTR', value: constants.chartMetric.CTR},
        {name: 'Avg. CPC', value: constants.chartMetric.CPC},
    ],
    campaignConversionGoalChartMetrics: [
        {name: '', value: constants.chartMetric.CONVERSION_GOAL1, shown: false},
        {name: '', value: constants.chartMetric.CONVERSION_GOAL2, shown: false},
        {name: '', value: constants.chartMetric.CONVERSION_GOAL3, shown: false},
        {name: '', value: constants.chartMetric.CONVERSION_GOAL4, shown: false},
        {name: '', value: constants.chartMetric.CONVERSION_GOAL5, shown: false},
    ],
    campaignGoalChartMetrics: [
        {
            name: 'Total Seconds',
            value: constants.chartMetric.TOTAL_SECONDS,
            shown: false,
        },
        {
            name: 'Total Pageviews',
            value: constants.chartMetric.TOTAL_PAGEVIEWS,
            shown: false,
        },
        {
            name: 'Unbounced Visitors',
            value: constants.chartMetric.UNBOUNCED_VISITS,
            shown: false,
        },
        {
            name: 'Avg. Cost per Second',
            value: constants.chartMetric.COST_PER_SECOND,
            shown: false,
        },
        {
            name: 'Avg. Cost for Pageview',
            value: constants.chartMetric.COST_PER_PAGEVIEW,
            shown: false,
        },
        {
            name: 'Avg. Cost for Unbounced Visitor',
            value: constants.chartMetric.COST_PER_UNBOUNCED_VISITOR,
            shown: false,
        },
        {
            name: 'Avg. Cost for New Visitor',
            value: constants.chartMetric.COST_PER_NEW_VISITOR,
            shown: false,
        },
    ],
    campaignGoalConversionGoalChartMetrics: [
        {name: '', value: constants.chartMetric.COST_PER_CONVERSION_GOAL_1, shown: false},
        {name: '', value: constants.chartMetric.COST_PER_CONVERSION_GOAL_2, shown: false},
        {name: '', value: constants.chartMetric.COST_PER_CONVERSION_GOAL_3, shown: false},
        {name: '', value: constants.chartMetric.COST_PER_CONVERSION_GOAL_4, shown: false},
        {name: '', value: constants.chartMetric.COST_PER_CONVERSION_GOAL_5, shown: false},
    ],
    accountChartMetrics: [
        {name: 'Clicks', value: constants.chartMetric.CLICKS},
        {name: 'Impressions', value: constants.chartMetric.IMPRESSIONS},
        {name: 'CTR', value: constants.chartMetric.CTR},
        {name: 'Avg. CPC', value: constants.chartMetric.CPC},
    ],
    allAccountsChartMetrics: [
        {name: 'Clicks', value: constants.chartMetric.CLICKS},
        {name: 'Impressions', value: constants.chartMetric.IMPRESSIONS},
        {name: 'Avg. CPC', value: constants.chartMetric.CPC},
    ],
    legacyCostChartMetrics: [
        {name: 'Spend', value: constants.chartMetric.COST},
    ],
    effectiveCostChartMetrics: [
        {name: 'Data Cost', value: constants.chartMetric.EFFECTIVE_DATA_COST},
        {name: 'License Fee', value: constants.chartMetric.LICENSE_FEE},
        {name: 'Media Spend', value: constants.chartMetric.EFFECTIVE_MEDIA_COST},
        {name: 'Total Spend', value: constants.chartMetric.BILLING_COST},
    ],
    actualCostChartMetrics: [
        {name: 'Actual Media Spend', value: constants.chartMetric.MEDIA_COST},
        {name: 'Actual Data Cost', value: constants.chartMetric.DATA_COST},
    ],
    iabCategories: [
        {name: 'IAB1 - Arts & Entertainment', value: constants.iabCategory.IAB1},
        {name: 'IAB1-1 - Books & Literature', value: constants.iabCategory.IAB1_1},
        {name: 'IAB1-2 - Celebrity Fan/Gossip', value: constants.iabCategory.IAB1_2},
        {name: 'IAB1-3 - Fine Art', value: constants.iabCategory.IAB1_3},
        {name: 'IAB1-4 - Humor', value: constants.iabCategory.IAB1_4},
        {name: 'IAB1-5 - Movies', value: constants.iabCategory.IAB1_5},
        {name: 'IAB1-6 - Music', value: constants.iabCategory.IAB1_6},
        {name: 'IAB1-7 - Television', value: constants.iabCategory.IAB1_7},
        {name: 'IAB2 - Automotive', value: constants.iabCategory.IAB2},
        {name: 'IAB2-1 - Auto Parts', value: constants.iabCategory.IAB2_1},
        {name: 'IAB2-2 - Auto Repair', value: constants.iabCategory.IAB2_2},
        {name: 'IAB2-3 - Buying/Selling Cars', value: constants.iabCategory.IAB2_3},
        {name: 'IAB2-4 - Car Culture', value: constants.iabCategory.IAB2_4},
        {name: 'IAB2-5 - Certified Pre-Owned', value: constants.iabCategory.IAB2_5},
        {name: 'IAB2-6 - Convertible', value: constants.iabCategory.IAB2_6},
        {name: 'IAB2-7 - Coupe', value: constants.iabCategory.IAB2_7},
        {name: 'IAB2-8 - Crossover', value: constants.iabCategory.IAB2_8},
        {name: 'IAB2-9 - Diesel', value: constants.iabCategory.IAB2_9},
        {name: 'IAB2-10 - Electric Vehicle', value: constants.iabCategory.IAB2_10},
        {name: 'IAB2-11 - Hatchback', value: constants.iabCategory.IAB2_11},
        {name: 'IAB2-12 - Hybrid', value: constants.iabCategory.IAB2_12},
        {name: 'IAB2-13 - Luxury', value: constants.iabCategory.IAB2_13},
        {name: 'IAB2-14 - MiniVan', value: constants.iabCategory.IAB2_14},
        {name: 'IAB2-15 - Mororcycles', value: constants.iabCategory.IAB2_15},
        {name: 'IAB2-16 - Off-Road Vehicles', value: constants.iabCategory.IAB2_16},
        {name: 'IAB2-17 - Performance Vehicles', value: constants.iabCategory.IAB2_17},
        {name: 'IAB2-18 - Pickup', value: constants.iabCategory.IAB2_18},
        {name: 'IAB2-19 - Road-Side Assistance', value: constants.iabCategory.IAB2_19},
        {name: 'IAB2-20 - Sedan', value: constants.iabCategory.IAB2_20},
        {name: 'IAB2-21 - Trucks & Accessories', value: constants.iabCategory.IAB2_21},
        {name: 'IAB2-22 - Vintage Cars', value: constants.iabCategory.IAB2_22},
        {name: 'IAB2-23 - Wagon', value: constants.iabCategory.IAB2_23},
        {name: 'IAB3 - Business', value: constants.iabCategory.IAB3},
        {name: 'IAB3-1 - Advertising', value: constants.iabCategory.IAB3_1},
        {name: 'IAB3-2 - Agriculture', value: constants.iabCategory.IAB3_2},
        {name: 'IAB3-3 - Biotech/Biomedical', value: constants.iabCategory.IAB3_3},
        {name: 'IAB3-4 - Business Software', value: constants.iabCategory.IAB3_4},
        {name: 'IAB3-5 - Construction', value: constants.iabCategory.IAB3_5},
        {name: 'IAB3-6 - Forestry', value: constants.iabCategory.IAB3_6},
        {name: 'IAB3-7 - Government', value: constants.iabCategory.IAB3_7},
        {name: 'IAB3-8 - Green Solutions', value: constants.iabCategory.IAB3_8},
        {name: 'IAB3-9 - Human Resources', value: constants.iabCategory.IAB3_9},
        {name: 'IAB3-10 - Logistics', value: constants.iabCategory.IAB3_10},
        {name: 'IAB3-11 - Marketing', value: constants.iabCategory.IAB3_11},
        {name: 'IAB3-12 - Metals', value: constants.iabCategory.IAB3_12},
        {name: 'IAB4 - Careers', value: constants.iabCategory.IAB4},
        {name: 'IAB4-1 - Career Planning', value: constants.iabCategory.IAB4_1},
        {name: 'IAB4-2 - College', value: constants.iabCategory.IAB4_2},
        {name: 'IAB4-3 - Financial Aid', value: constants.iabCategory.IAB4_3},
        {name: 'IAB4-4 - Job Fairs', value: constants.iabCategory.IAB4_4},
        {name: 'IAB4-5 - Job Search', value: constants.iabCategory.IAB4_5},
        {name: 'IAB4-6 - Resume Writing/Advice', value: constants.iabCategory.IAB4_6},
        {name: 'IAB4-7 - Nursing', value: constants.iabCategory.IAB4_7},
        {name: 'IAB4-8 - Scholarships', value: constants.iabCategory.IAB4_8},
        {name: 'IAB4-9 - Telecommuting', value: constants.iabCategory.IAB4_9},
        {name: 'IAB4-10 - U.S. Military', value: constants.iabCategory.IAB4_10},
        {name: 'IAB4-11 - Career Advice', value: constants.iabCategory.IAB4_11},
        {name: 'IAB5 - Education', value: constants.iabCategory.IAB5},
        {name: 'IAB5-1 - 7-12 Education', value: constants.iabCategory.IAB5_1},
        {name: 'IAB5-2 - Adult Education', value: constants.iabCategory.IAB5_2},
        {name: 'IAB5-3 - Art History', value: constants.iabCategory.IAB5_3},
        {name: 'IAB5-4 - Colledge Administration', value: constants.iabCategory.IAB5_4},
        {name: 'IAB5-5 - College Life', value: constants.iabCategory.IAB5_5},
        {name: 'IAB5-6 - Distance Learning', value: constants.iabCategory.IAB5_6},
        {name: 'IAB5-7 - English as a 2nd Language', value: constants.iabCategory.IAB5_7},
        {name: 'IAB5-8 - Language Learning', value: constants.iabCategory.IAB5_8},
        {name: 'IAB5-9 - Graduate School', value: constants.iabCategory.IAB5_9},
        {name: 'IAB5-10 - Homeschooling', value: constants.iabCategory.IAB5_10},
        {name: 'IAB5-11 - Homework/Study Tips', value: constants.iabCategory.IAB5_11},
        {name: 'IAB5-12 - K-6 Educators', value: constants.iabCategory.IAB5_12},
        {name: 'IAB5-13 - Private School', value: constants.iabCategory.IAB5_13},
        {name: 'IAB5-14 - Special Education', value: constants.iabCategory.IAB5_14},
        {name: 'IAB5-15 - Studying Business', value: constants.iabCategory.IAB5_15},
        {name: 'IAB6 - Family & Parenting', value: constants.iabCategory.IAB6},
        {name: 'IAB6-1 - Adoption', value: constants.iabCategory.IAB6_1},
        {name: 'IAB6-2 - Babies & Toddlers', value: constants.iabCategory.IAB6_2},
        {name: 'IAB6-3 - Daycare/Pre School', value: constants.iabCategory.IAB6_3},
        {name: 'IAB6-4 - Family Internet', value: constants.iabCategory.IAB6_4},
        {name: 'IAB6-5 - Parenting - K-6 Kids', value: constants.iabCategory.IAB6_5},
        {name: 'IAB6-6 - Parenting teens', value: constants.iabCategory.IAB6_6},
        {name: 'IAB6-7 - Pregnancy', value: constants.iabCategory.IAB6_7},
        {name: 'IAB6-8 - Special Needs Kids', value: constants.iabCategory.IAB6_8},
        {name: 'IAB6-9 - Eldercare', value: constants.iabCategory.IAB6_9},
        {name: 'IAB7 - Health & Fitness', value: constants.iabCategory.IAB7},
        {name: 'IAB7-1 - Exercise', value: constants.iabCategory.IAB7_1},
        {name: 'IAB7-2 - A.D.D.', value: constants.iabCategory.IAB7_2},
        {name: 'IAB7-3 - AIDS/HIV', value: constants.iabCategory.IAB7_3},
        {name: 'IAB7-4 - Allergies', value: constants.iabCategory.IAB7_4},
        {name: 'IAB7-5 - Alternative Medicine', value: constants.iabCategory.IAB7_5},
        {name: 'IAB7-6 - Arthritis', value: constants.iabCategory.IAB7_6},
        {name: 'IAB7-7 - Asthma', value: constants.iabCategory.IAB7_7},
        {name: 'IAB7-8 - Autism/PDD', value: constants.iabCategory.IAB7_8},
        {name: 'IAB7-9 - Bipolar Disorder', value: constants.iabCategory.IAB7_9},
        {name: 'IAB7-10 - Brain Tumor', value: constants.iabCategory.IAB7_10},
        {name: 'IAB7-11 - Cancer', value: constants.iabCategory.IAB7_11},
        {name: 'IAB7-12 - Cholesterol', value: constants.iabCategory.IAB7_12},
        {name: 'IAB7-13 - Chronic Fatigue Syndrome', value: constants.iabCategory.IAB7_13},
        {name: 'IAB7-14 - Chronic Pain', value: constants.iabCategory.IAB7_14},
        {name: 'IAB7-15 - Cold & Flu', value: constants.iabCategory.IAB7_15},
        {name: 'IAB7-16 - Deafness', value: constants.iabCategory.IAB7_16},
        {name: 'IAB7-17 - Dental Care', value: constants.iabCategory.IAB7_17},
        {name: 'IAB7-18 - Depression', value: constants.iabCategory.IAB7_18},
        {name: 'IAB7-19 - Dermatology', value: constants.iabCategory.IAB7_19},
        {name: 'IAB7-20 - Diabetes', value: constants.iabCategory.IAB7_20},
        {name: 'IAB7-21 - Epilepsy', value: constants.iabCategory.IAB7_21},
        {name: 'IAB7-22 - GERD/Acid Reflux', value: constants.iabCategory.IAB7_22},
        {name: 'IAB7-23 - Headaches/Migraines', value: constants.iabCategory.IAB7_23},
        {name: 'IAB7-24 - Heart Disease', value: constants.iabCategory.IAB7_24},
        {name: 'IAB7-25 - Herbs for Health', value: constants.iabCategory.IAB7_25},
        {name: 'IAB7-26 - Holistic Healing', value: constants.iabCategory.IAB7_26},
        {name: 'IAB7-27 - IBS/Crohn\'s Disease', value: constants.iabCategory.IAB7_27},
        {name: 'IAB7-28 - Incest/Abuse Support', value: constants.iabCategory.IAB7_28},
        {name: 'IAB7-29 - Incontinence', value: constants.iabCategory.IAB7_29},
        {name: 'IAB7-30 - Infertility', value: constants.iabCategory.IAB7_30},
        {name: 'IAB7-31 - Men\'s Health', value: constants.iabCategory.IAB7_31},
        {name: 'IAB7-32 - Nutrition', value: constants.iabCategory.IAB7_32},
        {name: 'IAB7-33 - Orthopedics', value: constants.iabCategory.IAB7_33},
        {name: 'IAB7-34 - Panic/Anxiety Disorders', value: constants.iabCategory.IAB7_34},
        {name: 'IAB7-35 - Pediatrics', value: constants.iabCategory.IAB7_35},
        {name: 'IAB7-36 - Physical Therapy', value: constants.iabCategory.IAB7_36},
        {name: 'IAB7-37 - Psychology/Psychiatry', value: constants.iabCategory.IAB7_37},
        {name: 'IAB7-38 - Senor Health', value: constants.iabCategory.IAB7_38},
        {name: 'IAB7-39 - Sexuality', value: constants.iabCategory.IAB7_39},
        {name: 'IAB7-40 - Sleep Disorders', value: constants.iabCategory.IAB7_40},
        {name: 'IAB7-41 - Smoking Cessation', value: constants.iabCategory.IAB7_41},
        {name: 'IAB7-42 - Substance Abuse', value: constants.iabCategory.IAB7_42},
        {name: 'IAB7-43 - Thyroid Disease', value: constants.iabCategory.IAB7_43},
        {name: 'IAB7-44 - Weight Loss', value: constants.iabCategory.IAB7_44},
        {name: 'IAB7-45 - Women\'s Health', value: constants.iabCategory.IAB7_45},
        {name: 'IAB8 - Food & Drink', value: constants.iabCategory.IAB8},
        {name: 'IAB8-1 - American Cuisine', value: constants.iabCategory.IAB8_1},
        {name: 'IAB8-2 - Barbecues & Grilling', value: constants.iabCategory.IAB8_2},
        {name: 'IAB8-3 - Cajun/Creole', value: constants.iabCategory.IAB8_3},
        {name: 'IAB8-4 - Chinese Cuisine', value: constants.iabCategory.IAB8_4},
        {name: 'IAB8-5 - Cocktails/Beer', value: constants.iabCategory.IAB8_5},
        {name: 'IAB8-6 - Coffee/Tea', value: constants.iabCategory.IAB8_6},
        {name: 'IAB8-7 - Cuisine-Specific', value: constants.iabCategory.IAB8_7},
        {name: 'IAB8-8 - Desserts & Baking', value: constants.iabCategory.IAB8_8},
        {name: 'IAB8-9 - Dining Out', value: constants.iabCategory.IAB8_9},
        {name: 'IAB8-10 - Food Allergies', value: constants.iabCategory.IAB8_10},
        {name: 'IAB8-11 - French Cuisine', value: constants.iabCategory.IAB8_11},
        {name: 'IAB8-12 - Health/Lowfat Cooking', value: constants.iabCategory.IAB8_12},
        {name: 'IAB8-13 - Italian Cuisine', value: constants.iabCategory.IAB8_13},
        {name: 'IAB8-14 - Japanese Cuisine', value: constants.iabCategory.IAB8_14},
        {name: 'IAB8-15 - Mexican Cuisine', value: constants.iabCategory.IAB8_15},
        {name: 'IAB8-16 - Vegan', value: constants.iabCategory.IAB8_16},
        {name: 'IAB8-17 - Vegetarian', value: constants.iabCategory.IAB8_17},
        {name: 'IAB8-18 - Wine', value: constants.iabCategory.IAB8_18},
        {name: 'IAB9 - Hobbies & Interests', value: constants.iabCategory.IAB9},
        {name: 'IAB9-1 - Art/Technology', value: constants.iabCategory.IAB9_1},
        {name: 'IAB9-2 - Arts & Crafts', value: constants.iabCategory.IAB9_2},
        {name: 'IAB9-3 - Beadwork', value: constants.iabCategory.IAB9_3},
        {name: 'IAB9-4 - Birdwatching', value: constants.iabCategory.IAB9_4},
        {name: 'IAB9-5 - Board Games/Puzzles', value: constants.iabCategory.IAB9_5},
        {name: 'IAB9-6 - Candle & Soap Making', value: constants.iabCategory.IAB9_6},
        {name: 'IAB9-7 - Card Games', value: constants.iabCategory.IAB9_7},
        {name: 'IAB9-8 - Chess', value: constants.iabCategory.IAB9_8},
        {name: 'IAB9-9 - Cigars', value: constants.iabCategory.IAB9_9},
        {name: 'IAB9-10 - Collecting', value: constants.iabCategory.IAB9_10},
        {name: 'IAB9-11 - Comic Books', value: constants.iabCategory.IAB9_11},
        {name: 'IAB9-12 - Drawing/Sketching', value: constants.iabCategory.IAB9_12},
        {name: 'IAB9-13 - Freelance Writing', value: constants.iabCategory.IAB9_13},
        {name: 'IAB9-14 - Genealogy', value: constants.iabCategory.IAB9_14},
        {name: 'IAB9-15 - Getting Published', value: constants.iabCategory.IAB9_15},
        {name: 'IAB9-16 - Guitar', value: constants.iabCategory.IAB9_16},
        {name: 'IAB9-17 - Home Recording', value: constants.iabCategory.IAB9_17},
        {name: 'IAB9-18 - Investors & Patents', value: constants.iabCategory.IAB9_18},
        {name: 'IAB9-19 - Jewelry Making', value: constants.iabCategory.IAB9_19},
        {name: 'IAB9-20 - Magic & Illusion', value: constants.iabCategory.IAB9_20},
        {name: 'IAB9-21 - Needlework', value: constants.iabCategory.IAB9_21},
        {name: 'IAB9-22 - Painting', value: constants.iabCategory.IAB9_22},
        {name: 'IAB9-23 - Photography', value: constants.iabCategory.IAB9_23},
        {name: 'IAB9-24 - Radio', value: constants.iabCategory.IAB9_24},
        {name: 'IAB9-25 - Roleplaying Games', value: constants.iabCategory.IAB9_25},
        {name: 'IAB9-26 - Sci-Fi & Fantasy', value: constants.iabCategory.IAB9_26},
        {name: 'IAB9-27 - Scrapbooking', value: constants.iabCategory.IAB9_27},
        {name: 'IAB9-28 - Screenwriting', value: constants.iabCategory.IAB9_28},
        {name: 'IAB9-29 - Stamps & Coins', value: constants.iabCategory.IAB9_29},
        {name: 'IAB9-30 - Video & Computer Games', value: constants.iabCategory.IAB9_30},
        {name: 'IAB9-31 - Woodworking', value: constants.iabCategory.IAB9_31},
        {name: 'IAB10 - Home & Garden', value: constants.iabCategory.IAB10},
        {name: 'IAB10-1 - Appliances', value: constants.iabCategory.IAB10_1},
        {name: 'IAB10-2 - Entertaining', value: constants.iabCategory.IAB10_2},
        {name: 'IAB10-3 - Environmental Safety', value: constants.iabCategory.IAB10_3},
        {name: 'IAB10-4 - Gardening', value: constants.iabCategory.IAB10_4},
        {name: 'IAB10-5 - Home Repair', value: constants.iabCategory.IAB10_5},
        {name: 'IAB10-6 - Home Theater', value: constants.iabCategory.IAB10_6},
        {name: 'IAB10-7 - Interior Decorating', value: constants.iabCategory.IAB10_7},
        {name: 'IAB10-8 - Landscaping', value: constants.iabCategory.IAB10_8},
        {name: 'IAB10-9 - Remodeling & Construction', value: constants.iabCategory.IAB10_9},
        {name: 'IAB11 - Law, Gov\'t & Politics', value: constants.iabCategory.IAB11},
        {name: 'IAB11-1 - Immigration', value: constants.iabCategory.IAB11_1},
        {name: 'IAB11-2 - Legal Issues', value: constants.iabCategory.IAB11_2},
        {name: 'IAB11-3 - U.S. Government Resources', value: constants.iabCategory.IAB11_3},
        {name: 'IAB11-4 - Politics', value: constants.iabCategory.IAB11_4},
        {name: 'IAB11-5 - Commentary', value: constants.iabCategory.IAB11_5},
        {name: 'IAB12 - News', value: constants.iabCategory.IAB12},
        {name: 'IAB12-1 - International News', value: constants.iabCategory.IAB12_1},
        {name: 'IAB12-2 - National News', value: constants.iabCategory.IAB12_2},
        {name: 'IAB12-3 - Local News', value: constants.iabCategory.IAB12_3},
        {name: 'IAB13 - Personal Finance', value: constants.iabCategory.IAB13},
        {name: 'IAB13-1 - Beginning Investing', value: constants.iabCategory.IAB13_1},
        {name: 'IAB13-2 - Credit/Debt & Loans', value: constants.iabCategory.IAB13_2},
        {name: 'IAB13-3 - Financial News', value: constants.iabCategory.IAB13_3},
        {name: 'IAB13-4 - Financial Planning', value: constants.iabCategory.IAB13_4},
        {name: 'IAB13-5 - Hedge Fund', value: constants.iabCategory.IAB13_5},
        {name: 'IAB13-6 - Insurance', value: constants.iabCategory.IAB13_6},
        {name: 'IAB13-7 - Investing', value: constants.iabCategory.IAB13_7},
        {name: 'IAB13-8 - Mutual Funds', value: constants.iabCategory.IAB13_8},
        {name: 'IAB13-9 - Options', value: constants.iabCategory.IAB13_9},
        {name: 'IAB13-10 - Retirement Planning', value: constants.iabCategory.IAB13_10},
        {name: 'IAB13-11 - Stocks', value: constants.iabCategory.IAB13_11},
        {name: 'IAB13-12 - Tax Planning', value: constants.iabCategory.IAB13_12},
        {name: 'IAB14 - Society', value: constants.iabCategory.IAB14},
        {name: 'IAB14-1 - Dating', value: constants.iabCategory.IAB14_1},
        {name: 'IAB14-2 - Divorce Support', value: constants.iabCategory.IAB14_2},
        {name: 'IAB14-3 - Gay Life', value: constants.iabCategory.IAB14_3},
        {name: 'IAB14-4 - Marriage', value: constants.iabCategory.IAB14_4},
        {name: 'IAB14-5 - Senior Living', value: constants.iabCategory.IAB14_5},
        {name: 'IAB14-6 - Teens', value: constants.iabCategory.IAB14_6},
        {name: 'IAB14-7 - Weddings', value: constants.iabCategory.IAB14_7},
        {name: 'IAB14-8 - Ethnic Specific', value: constants.iabCategory.IAB14_8},
        {name: 'IAB15 - Science', value: constants.iabCategory.IAB15},
        {name: 'IAB15-1 - Astrology', value: constants.iabCategory.IAB15_1},
        {name: 'IAB15-2 - Biology', value: constants.iabCategory.IAB15_2},
        {name: 'IAB15-3 - Chemistry', value: constants.iabCategory.IAB15_3},
        {name: 'IAB15-4 - Geology', value: constants.iabCategory.IAB15_4},
        {name: 'IAB15-5 - Paranormal Phenomena', value: constants.iabCategory.IAB15_5},
        {name: 'IAB15-6 - Physics', value: constants.iabCategory.IAB15_6},
        {name: 'IAB15-7 - Space/Astronomy', value: constants.iabCategory.IAB15_7},
        {name: 'IAB15-8 - Geography', value: constants.iabCategory.IAB15_8},
        {name: 'IAB15-9 - Botany', value: constants.iabCategory.IAB15_9},
        {name: 'IAB15-10 - Weather', value: constants.iabCategory.IAB15_10},
        {name: 'IAB16 - Pets', value: constants.iabCategory.IAB16},
        {name: 'IAB16-1 - Aquariums', value: constants.iabCategory.IAB16_1},
        {name: 'IAB16-2 - Birds', value: constants.iabCategory.IAB16_2},
        {name: 'IAB16-3 - Cats', value: constants.iabCategory.IAB16_3},
        {name: 'IAB16-4 - Dogs', value: constants.iabCategory.IAB16_4},
        {name: 'IAB16-5 - Large Animals', value: constants.iabCategory.IAB16_5},
        {name: 'IAB16-6 - Reptiles', value: constants.iabCategory.IAB16_6},
        {name: 'IAB16-7 - Veterinary Medicine', value: constants.iabCategory.IAB16_7},
        {name: 'IAB17 - Sports', value: constants.iabCategory.IAB17},
        {name: 'IAB17-1 - Auto Racing', value: constants.iabCategory.IAB17_1},
        {name: 'IAB17-2 - Baseball', value: constants.iabCategory.IAB17_2},
        {name: 'IAB17-3 - Bicycling', value: constants.iabCategory.IAB17_3},
        {name: 'IAB17-4 - Bodybuilding', value: constants.iabCategory.IAB17_4},
        {name: 'IAB17-5 - Boxing', value: constants.iabCategory.IAB17_5},
        {name: 'IAB17-6 - Canoeing/Kayaking', value: constants.iabCategory.IAB17_6},
        {name: 'IAB17-7 - Cheerleading', value: constants.iabCategory.IAB17_7},
        {name: 'IAB17-8 - Climbing', value: constants.iabCategory.IAB17_8},
        {name: 'IAB17-9 - Cricket', value: constants.iabCategory.IAB17_9},
        {name: 'IAB17-10 - Figure Skating', value: constants.iabCategory.IAB17_10},
        {name: 'IAB17-11 - Fly Fishing', value: constants.iabCategory.IAB17_11},
        {name: 'IAB17-12 - Football', value: constants.iabCategory.IAB17_12},
        {name: 'IAB17-13 - Freshwater Fishing', value: constants.iabCategory.IAB17_13},
        {name: 'IAB17-14 - Game & Fish', value: constants.iabCategory.IAB17_14},
        {name: 'IAB17-15 - Golf', value: constants.iabCategory.IAB17_15},
        {name: 'IAB17-16 - Horse Racing', value: constants.iabCategory.IAB17_16},
        {name: 'IAB17-17 - Horses', value: constants.iabCategory.IAB17_17},
        {name: 'IAB17-18 - Hunting/Shooting', value: constants.iabCategory.IAB17_18},
        {name: 'IAB17-19 - Inline Skating', value: constants.iabCategory.IAB17_19},
        {name: 'IAB17-20 - Martial Arts', value: constants.iabCategory.IAB17_20},
        {name: 'IAB17-21 - Mountain Biking', value: constants.iabCategory.IAB17_21},
        {name: 'IAB17-22 - NASCAR Racing', value: constants.iabCategory.IAB17_22},
        {name: 'IAB17-23 - Olympics', value: constants.iabCategory.IAB17_23},
        {name: 'IAB17-24 - Paintball', value: constants.iabCategory.IAB17_24},
        {name: 'IAB17-25 - Power & Motorcycles', value: constants.iabCategory.IAB17_25},
        {name: 'IAB17-26 - Pro Basketball', value: constants.iabCategory.IAB17_26},
        {name: 'IAB17-27 - Pro Ice Hockey', value: constants.iabCategory.IAB17_27},
        {name: 'IAB17-28 - Rodeo', value: constants.iabCategory.IAB17_28},
        {name: 'IAB17-29 - Rugby', value: constants.iabCategory.IAB17_29},
        {name: 'IAB17-30 - Running/Jogging', value: constants.iabCategory.IAB17_30},
        {name: 'IAB17-31 - Sailing', value: constants.iabCategory.IAB17_31},
        {name: 'IAB17-32 - Saltwater Fishing', value: constants.iabCategory.IAB17_32},
        {name: 'IAB17-33 - Scuba Diving', value: constants.iabCategory.IAB17_33},
        {name: 'IAB17-34 - Skateboarding', value: constants.iabCategory.IAB17_34},
        {name: 'IAB17-35 - Skiing', value: constants.iabCategory.IAB17_35},
        {name: 'IAB17-36 - Snowboarding', value: constants.iabCategory.IAB17_36},
        {name: 'IAB17-37 - Surfing/Bodyboarding', value: constants.iabCategory.IAB17_37},
        {name: 'IAB17-38 - Swimming', value: constants.iabCategory.IAB17_38},
        {name: 'IAB17-39 - Table Tennis/Ping-Pong', value: constants.iabCategory.IAB17_39},
        {name: 'IAB17-40 - Tennis', value: constants.iabCategory.IAB17_40},
        {name: 'IAB17-41 - Volleyball', value: constants.iabCategory.IAB17_41},
        {name: 'IAB17-42 - Walking', value: constants.iabCategory.IAB17_42},
        {name: 'IAB17-43 - Waterski/Wakeboard', value: constants.iabCategory.IAB17_43},
        {name: 'IAB17-44 - World Soccer', value: constants.iabCategory.IAB17_44},
        {name: 'IAB18 - Style & Fashion', value: constants.iabCategory.IAB18},
        {name: 'IAB18-1 - Beauty', value: constants.iabCategory.IAB18_1},
        {name: 'IAB18-2 - Body Art', value: constants.iabCategory.IAB18_2},
        {name: 'IAB18-3 - Fashion', value: constants.iabCategory.IAB18_3},
        {name: 'IAB18-4 - Jewelry', value: constants.iabCategory.IAB18_4},
        {name: 'IAB18-5 - Clothing', value: constants.iabCategory.IAB18_5},
        {name: 'IAB18-6 - Accessories', value: constants.iabCategory.IAB18_6},
        {name: 'IAB19 - Technology & Computing', value: constants.iabCategory.IAB19},
        {name: 'IAB19-1 - 3-D Graphics', value: constants.iabCategory.IAB19_1},
        {name: 'IAB19-2 - Animation', value: constants.iabCategory.IAB19_2},
        {name: 'IAB19-3 - Antivirus Software', value: constants.iabCategory.IAB19_3},
        {name: 'IAB19-4 - C/C++', value: constants.iabCategory.IAB19_4},
        {name: 'IAB19-5 - Cameras & Camcorders', value: constants.iabCategory.IAB19_5},
        {name: 'IAB19-6 - Cell Phones', value: constants.iabCategory.IAB19_6},
        {name: 'IAB19-7 - Computer Certification', value: constants.iabCategory.IAB19_7},
        {name: 'IAB19-8 - Computer Networking', value: constants.iabCategory.IAB19_8},
        {name: 'IAB19-9 - Computer Peripherals', value: constants.iabCategory.IAB19_9},
        {name: 'IAB19-10 - Computer Reviews', value: constants.iabCategory.IAB19_10},
        {name: 'IAB19-11 - Data Centers', value: constants.iabCategory.IAB19_11},
        {name: 'IAB19-12 - Databases', value: constants.iabCategory.IAB19_12},
        {name: 'IAB19-13 - Desktop Publishing', value: constants.iabCategory.IAB19_13},
        {name: 'IAB19-14 - Desktop Video', value: constants.iabCategory.IAB19_14},
        {name: 'IAB19-15 - Email', value: constants.iabCategory.IAB19_15},
        {name: 'IAB19-16 - Graphics Software', value: constants.iabCategory.IAB19_16},
        {name: 'IAB19-17 - Home Video/DVD', value: constants.iabCategory.IAB19_17},
        {name: 'IAB19-18 - Internet Technology', value: constants.iabCategory.IAB19_18},
        {name: 'IAB19-19 - Java', value: constants.iabCategory.IAB19_19},
        {name: 'IAB19-20 - JavaScript', value: constants.iabCategory.IAB19_20},
        {name: 'IAB19-21 - Mac Support', value: constants.iabCategory.IAB19_21},
        {name: 'IAB19-22 - MP3/MIDI', value: constants.iabCategory.IAB19_22},
        {name: 'IAB19-23 - Net Conferencing', value: constants.iabCategory.IAB19_23},
        {name: 'IAB19-24 - Net for Beginners', value: constants.iabCategory.IAB19_24},
        {name: 'IAB19-25 - Network Security', value: constants.iabCategory.IAB19_25},
        {name: 'IAB19-26 - Palmtops/PDAs', value: constants.iabCategory.IAB19_26},
        {name: 'IAB19-27 - PC Support', value: constants.iabCategory.IAB19_27},
        {name: 'IAB19-28 - Portable', value: constants.iabCategory.IAB19_28},
        {name: 'IAB19-29 - Entertainment', value: constants.iabCategory.IAB19_29},
        {name: 'IAB19-30 - Shareware/Freeware', value: constants.iabCategory.IAB19_30},
        {name: 'IAB19-31 - Unix', value: constants.iabCategory.IAB19_31},
        {name: 'IAB19-32 - Visual Basic', value: constants.iabCategory.IAB19_32},
        {name: 'IAB19-33 - Web Clip Art', value: constants.iabCategory.IAB19_33},
        {name: 'IAB19-34 - Web Design/HTML', value: constants.iabCategory.IAB19_34},
        {name: 'IAB19-35 - Web Search', value: constants.iabCategory.IAB19_35},
        {name: 'IAB19-36 - Windows', value: constants.iabCategory.IAB19_36},
        {name: 'IAB20 - Travel', value: constants.iabCategory.IAB20},
        {name: 'IAB20-1 - Adventure Travel', value: constants.iabCategory.IAB20_1},
        {name: 'IAB20-2 - Africa', value: constants.iabCategory.IAB20_2},
        {name: 'IAB20-3 - Air Travel', value: constants.iabCategory.IAB20_3},
        {name: 'IAB20-4 - Australia & New Zealand', value: constants.iabCategory.IAB20_4},
        {name: 'IAB20-5 - Bed & Breakfasts', value: constants.iabCategory.IAB20_5},
        {name: 'IAB20-6 - Budget Travel', value: constants.iabCategory.IAB20_6},
        {name: 'IAB20-7 - Business Travel', value: constants.iabCategory.IAB20_7},
        {name: 'IAB20-8 - By US Locale', value: constants.iabCategory.IAB20_8},
        {name: 'IAB20-9 - Camping', value: constants.iabCategory.IAB20_9},
        {name: 'IAB20-10 - Canada', value: constants.iabCategory.IAB20_10},
        {name: 'IAB20-11 - Caribbean', value: constants.iabCategory.IAB20_11},
        {name: 'IAB20-12 - Cruises', value: constants.iabCategory.IAB20_12},
        {name: 'IAB20-13 - Eastern Europe', value: constants.iabCategory.IAB20_13},
        {name: 'IAB20-14 - Europe', value: constants.iabCategory.IAB20_14},
        {name: 'IAB20-15 - France', value: constants.iabCategory.IAB20_15},
        {name: 'IAB20-16 - Greece', value: constants.iabCategory.IAB20_16},
        {name: 'IAB20-17 - Honeymoons/Getaways', value: constants.iabCategory.IAB20_17},
        {name: 'IAB20-18 - Hotels', value: constants.iabCategory.IAB20_18},
        {name: 'IAB20-19 - Italy', value: constants.iabCategory.IAB20_19},
        {name: 'IAB20-20 - Japan', value: constants.iabCategory.IAB20_20},
        {name: 'IAB20-21 - Mexico & Central America', value: constants.iabCategory.IAB20_21},
        {name: 'IAB20-22 - National Parks', value: constants.iabCategory.IAB20_22},
        {name: 'IAB20-23 - South America', value: constants.iabCategory.IAB20_23},
        {name: 'IAB20-24 - Spas', value: constants.iabCategory.IAB20_24},
        {name: 'IAB20-25 - Theme Parks', value: constants.iabCategory.IAB20_25},
        {name: 'IAB20-26 - Traveling with Kids', value: constants.iabCategory.IAB20_26},
        {name: 'IAB20-27 - United Kingdom', value: constants.iabCategory.IAB20_27},
        {name: 'IAB21 - Real Estate', value: constants.iabCategory.IAB21},
        {name: 'IAB21-1 - Apartments', value: constants.iabCategory.IAB21_1},
        {name: 'IAB21-2 - Architects', value: constants.iabCategory.IAB21_2},
        {name: 'IAB21-3 - Buying/Selling Homes', value: constants.iabCategory.IAB21_3},
        {name: 'IAB22 - Shopping', value: constants.iabCategory.IAB22},
        {name: 'IAB22-1 - Contests & Freebies', value: constants.iabCategory.IAB22_1},
        {name: 'IAB22-2 - Couponing', value: constants.iabCategory.IAB22_2},
        {name: 'IAB22-3 - Comparison', value: constants.iabCategory.IAB22_3},
        {name: 'IAB22-4 - Engines', value: constants.iabCategory.IAB22_4},
        {name: 'IAB23 - Religion & Spirituality', value: constants.iabCategory.IAB23},
        {name: 'IAB23-1 - Alternative Religions', value: constants.iabCategory.IAB23_1},
        {name: 'IAB23-2 - Atheism/Agnosticism', value: constants.iabCategory.IAB23_2},
        {name: 'IAB23-3 - Buddhism', value: constants.iabCategory.IAB23_3},
        {name: 'IAB23-4 - Catholicism', value: constants.iabCategory.IAB23_4},
        {name: 'IAB23-5 - Christianity', value: constants.iabCategory.IAB23_5},
        {name: 'IAB23-6 - Hinduism', value: constants.iabCategory.IAB23_6},
        {name: 'IAB23-7 - Islam', value: constants.iabCategory.IAB23_7},
        {name: 'IAB23-8 - Judaism', value: constants.iabCategory.IAB23_8},
        {name: 'IAB23-9 - Latter-Day Saints', value: constants.iabCategory.IAB23_9},
        {name: 'IAB23-10 - Pagan/Wiccan', value: constants.iabCategory.IAB23_10},
        {name: 'IAB24 - Uncategorized', value: constants.iabCategory.IAB24},
        {name: 'IAB25 - Non-Standard Content', value: constants.iabCategory.IAB25},
        {name: 'IAB25-1 - Unmoderated UGC', value: constants.iabCategory.IAB25_1},
        {name: 'IAB25-2 - Extreme Graphic/Explicit Violence', value: constants.iabCategory.IAB25_2},
        {name: 'IAB25-3 - Pornography', value: constants.iabCategory.IAB25_3},
        {name: 'IAB25-4 - Profane Content', value: constants.iabCategory.IAB25_4},
        {name: 'IAB25-5 - Hate Content', value: constants.iabCategory.IAB25_5},
        {name: 'IAB25-6 - Under Construction', value: constants.iabCategory.IAB25_6},
        {name: 'IAB25-7 - Incentivized', value: constants.iabCategory.IAB25_7},
        {name: 'IAB26 - Illegal Content', value: constants.iabCategory.IAB26},
        {name: 'IAB26-1 - Illegal Content', value: constants.iabCategory.IAB26_1},
        {name: 'IAB26-2 - Warez', value: constants.iabCategory.IAB26_2},
        {name: 'IAB26-3 - Spyware/Malware', value: constants.iabCategory.IAB26_3},
        {name: 'IAB26-4 - CopyrightInfringement', value: constants.iabCategory.IAB26_4},
    ],
    promotionGoals: [
        {name: 'Brand Building', value: constants.promotionGoal.BRAND_BUILDING},
        {name: 'Traffic Acquisition', value: constants.promotionGoal.TRAFFIC_ACQUISITION},
        {name: 'Conversions', value: constants.promotionGoal.CONVERSIONS},
    ],
    campaignGoals: [
        {name: 'CPA', value: constants.campaignGoal.CPA},
        {name: '% bounce rate', value: constants.campaignGoal.PERCENT_BOUNCE_RATE},
        {name: 'new unique visitors', value: constants.campaignGoal.NEW_UNIQUE_VISITORS},
        {name: 'seconds time on site', value: constants.campaignGoal.SECONDS_TIME_ON_SITE},
        {name: 'pages per session', value: constants.campaignGoal.PAGES_PER_SESSION},
    ],
    campaignGoalKPIs: [
        {name: 'Time on Site - Seconds', value: constants.campaignGoalKPI.TIME_ON_SITE, unit: 's'},
        {name: 'Max Bounce Rate', value: constants.campaignGoalKPI.MAX_BOUNCE_RATE, unit: '%'},
        {name: 'Pageviews per Visit', value: constants.campaignGoalKPI.PAGES_PER_SESSION},
        {name: 'CPC', value: constants.campaignGoalKPI.CPC, unit: '$'},
        {name: 'New Unique Visitors', value: constants.campaignGoalKPI.NEW_UNIQUE_VISITORS, unit: '%'},
        {name: 'CPA - Setup Conversion Tracking', value: constants.campaignGoalKPI.CPA, unit: '$'},
    ],
    budgetAutomationGoals: [
        {name: 'time on site', value: constants.campaignGoalKPI.TIME_ON_SITE},
        {name: 'bounce rate', value: constants.campaignGoalKPI.MAX_BOUNCE_RATE},
        {name: 'pages per session', value: constants.campaignGoalKPI.PAGES_PER_SESSION},
        {name: 'average CPC', value: constants.campaignGoalKPI.CPC},
        {name: 'new visitors', value: constants.campaignGoalKPI.NEW_UNIQUE_VISITORS},
        {name: 'CPA', value: constants.campaignGoalKPI.CPA},
    ],
    conversionGoalTypes: [
        {name: 'Conversion Pixel', value: constants.conversionGoalType.PIXEL},
        {name: 'Google Analytics', value: constants.conversionGoalType.GA},
        {name: 'Adobe Analytics', value: constants.conversionGoalType.OMNITURE},
    ],
    conversionWindows: [
        {name: '1 day', value: 24},
        {name: '7 days', value: 168},
        {name: '30 days', value: 720},
    ],
    exportFrequency: [
        {name: 'Daily', value: constants.exportFrequency.DAILY},
        {name: 'Weekly (Monday)', value: constants.exportFrequency.WEEKLY},
        {name: 'Monthly (1st)', value: constants.exportFrequency.MONTHLY},
    ],
};

var defaults = {
    callToAction: [
        {id: 'Read Mode', text: 'Read More'},
        {id: 'Book Now', text: 'Book Now'},
        {id: 'Contact Us', text: 'Contact Us'},
        {id: 'Download', text: 'Download'},
        {id: 'Learn More', text: 'Learn More'},
        {id: 'Shop Now', text: 'Shop Now'},
        {id: 'Sign Up', text: 'Sign Up'},
        {id: 'Watch More', text: 'Watch More'},
    ],
    campaignGoalKPI: [
        {id: constants.campaignGoalKPI.TIME_ON_SITE, value: 30},
        {id: constants.campaignGoalKPI.MAX_BOUNCE_RATE, value: 75},
        {id: constants.campaignGoalKPI.PAGES_PER_SESSION, value: 1.2},
        {id: constants.campaignGoalKPI.CPC, value: 0.35},
        {id: constants.campaignGoalKPI.CPA, value: 50},
        {id: constants.campaignGoalKPI.NEW_UNIQUE_VISITORS, value: 0.1},
    ],
};

constants.campaignGoalValueText = {};
constants.campaignGoalValueText[constants.campaignGoalKPI.CPA] = 'CPA';
constants.campaignGoalValueText[constants.campaignGoalKPI.CPC] = 'CPC';
constants.campaignGoalValueText[constants.campaignGoalKPI.CPM] = 'CPM';
constants.campaignGoalValueText[constants.campaignGoalKPI.MAX_BOUNCE_RATE] = 'Bounce Rate';
constants.campaignGoalValueText[constants.campaignGoalKPI.NEW_UNIQUE_VISITORS] = 'New Unique Visitors';
constants.campaignGoalValueText[constants.campaignGoalKPI.TIME_ON_SITE] = 'seconds Time on Site';
constants.campaignGoalValueText[constants.campaignGoalKPI.PAGES_PER_SESSION] = 'Pageviews per Visit';
