engines:
  pep8:
    enabled: true
  radon:
    enabled: true
    config: 
      threshold: "C"
  fixme:
    enabled: true
  duplication:
    enabled: false
    config:
      languages:
      - python
  eslint:
    enabled: true

ratings:
   paths:
   - "**.py"
   - "**.js"

exclude_paths:
- client/lib/**/*
- server/**/migrations/*.py
