globals:
  # Libraries
  angular: false
  $: false
  moment: false
  # Zemanta
  constants: false
  # Jasmine
  jasmine: false
  describe: false
  fdescribe: false
  it: false
  fit: false
  module: false
  inject: false
  beforeEach: false
  expect: false

rules:
  indent:
    - 2
    - 4
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
  comma-dangle:
    - 2
    - 'only-multiline'
  complexity:
    - 2
    - 10
  dot-notation:
    - 0
  eqeqeq:
    - 0
  guard-for-in:
    - 0
  no-alert:
    - 0
  no-else-return:
    - 2
  no-trailing-spaces:
    - 2
  max-len:
    - 0
    - 120
    - 4
  brace-style:
    - 2
    - 1tbs
    - allowSingleLine: true
  array-bracket-spacing:
    - 2
  object-curly-spacing:
    - 2
  block-spacing:
    - 2
  camelcase:
    - 2
    - properties: never
  comma-spacing:
    - 2
  key-spacing:
    - 2
  no-lonely-if:
    - 2
  no-multiple-empty-lines:
    - 2
  semi-spacing:
    - 2
  keyword-spacing:
    - 2
  space-before-blocks:
    - 2
  space-before-function-paren:
    - 2
  space-in-parens:
    - 2
  space-infix-ops:
    - 2
  space-unary-ops:
    - 2
  no-unused-vars:
    - 0
  no-undef:
    - 2

env:
  browser: true

extends: 'eslint:recommended'
