cron:
- hosts: [knot01.zemanta.com]
  job: '*/5 * * * * cd /home/one/apps/server/server && /home/one/.virtualenvs/server/bin/python manage.py test --health-check zemauth.tests_ui.test_ui.LoginTestCase.test_login > /dev/null 2>&1'
