cron:
- hosts: [knot01.zemanta.com]
  job: '*/5 * * * * cd /home/one/apps/server/server && /home/one/.virtualenvs/server/bin/python manage.py test --health-check zemauth.tests_ui.test_ui.LoginTestCase.test_login > /dev/null 2>&1'
- job: '0 0 * * * date=`date +%Y-%m-%d --date="1 day ago"` && mv /home/one/log/zemanta-eins.server.log /home/one/log/zemanta-eins.server.$date.log'
