cron:
- hosts: [knot01.zemanta.com]
  job: '*/5 * * * * cd ~/apps/server/server && ~/.virtualenvs/server/bin/python manage.py test --health-check zemauth.tests_ui.test_ui.LoginTestCase.test_login > /dev/null 2>&1'

- hosts: [knot01.zemanta.com]
  job: '0 2 * * * cd ~/apps/server/server && ~/.virtualenvs/server/bin/python manage.py fetch_reports > /dev/null 2>&1'

- job: '0 0 * * * mv ~/log/zemanta-eins.server.log ~/log/zemanta-eins.server.$(date +\%Y-\%m-\%d --date="1 day ago").log > /dev/null 2>&1'
