postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=devpwd
      - POSTGRES_DB=one
      - POSTGRES_USER=eins
    command: "-c fsync=off -c full_page_writes=off -c synchronous_commit=off"
    volumes:
      - "./fixtures/:/docker-entrypoint-initdb.d/"

einsstatic:
    hostname: einsstatic
    image: digitallyseamless/nodejs-bower-grunt
    expose:
      - "9999"
    command: "sleep 1h"

eins:
    image: z1:$BUILD_NUMBER
    volumes:
      - "./server/.junit_xml/:/app/z1/.junit_xml/"
    links:
      - "postgres:db"
      - "memcached:memcached"
      - "einsstatic"
      - "telegraf"
