version: '2'

services:
    postgres:
        ports:
          - "5432:5432"

    # this is fake telegraf that only prints stats on stdout
    telegraf:
        ports:
          - "8135:8135/udp"

    memcached:
        ports:
          - "11211:11211"

    client:
        image: $Z1_CLIENT_IMAGE
        ports:
        - "9999:9999"
        environment:
        - CLIENT_SKIP_RUN
        volumes:
        - "./client/:/app/:cached"
        - "/app/node_modules/"
        entrypoint: /bin/bash
        command: -c "npm prune && npm install && bower install --dev; [[ -z \"$$CLIENT_SKIP_RUN\" ]] && npm run dev || bash"
        tty: true

