version: '2'

services:
    postgres:
        expose:
          - "5432"

    telegraf:
        expose:
          - "8135/udp"

    memcached:
        expose:
          - "11211"

    server:
        image: $Z1_SERVER_IMAGE
        ports:
          - "8123:8123"
        links:
          - "postgres:db"
          - "statspostgres:statsdb"
          - "memcached:memcached"
          - "telegraf"
          - "client"
        volumes:
          - "./server/:/app/z1/"
          - ".:/src:ro"
        working_dir: /app/z1/
        entrypoint: /src/docker/entrypoint_dev.sh
        command: python test-server.py --fixtures e2e --threading True --use-local-static True
        tty: true
        stdin_open: true

    client:
        image: $Z1_CLIENT_IMAGE
        ports:
          - "9898:9898"
        environment:
          - CLIENT_SKIP_RUN
        volumes:
          - "./client/:/app/:cached"
          - "/app/node_modules/"
        entrypoint: /bin/bash
        command: -c "npm prune && npm install && bower install --dev; [[ -z \"$$CLIENT_SKIP_RUN\" ]] && npm run e2e || bash"
        tty: true
