version: '2'

services:
    postgres:
        expose:
          - "5432"

    # this is fake telegraf that only prints stats on stdout
    telegraf:
        expose:
          - "8135/udp"

    memcached:
        expose:
          - "11211"

    e2e_server:
        restart: always
        hostname: e2e_server
        image: $Z1_SERVER_IMAGE
        expose:
          - "8123"
        links:
          - "postgres:db"
          - "statspostgres:statsdb"
          - "memcached:memcached"
          - "telegraf"
        volumes:
          - "./server/:/app/z1/"
          - ".:/src:ro"
        working_dir: /app/z1/
        entrypoint: /src/docker/entrypoint_dev.sh
        command: python test-server.py --fixtures e2e
        tty: true
        stdin_open: true

    # TODO (e2e-tests): Setup e2e test runner container
    # e2e_tests_runner:
    #     image: testim/docker-cli
    #     entrypoint: bash
