# Main dashboard instance
eins:
    image: z1-bundle:current
    restart: unless-stopped
    hostname: ${HOSTNAME}
    external_links:
      - memcached
    ports:
      - "8000"
    volumes:
      - "/mnt/logs/eins:/app/logs"
    command: /start-server.sh
    environment:
      CONF_ENV: "prod"
      VIRTUAL_HOST: "one.zemanta.com"
      NEW_RELIC_LICENSE_KEY: "1dfbd7b07a5cbf7bcc6eb18db5003808a058d16f"
      NEW_RELIC_APP_NAME: "Zemanta One"
      NEW_RELIC_PROCESS_HOST_DISPLAY_NAME: "${HOSTNAME}-docker"
      GUNICORN_TIMEOUT: "180"
      GUNICORN_WORKERS: "4"
    labels:
      traefik.backend: "one.zemanta.com"
      traefik.frontend.rule: "Host:one.zemanta.com"
      traefik.frontend.passHostHeader: "true"
    log_driver: json-file
    log_opt:
      max-size: "50m"
      max-file: "3"
      labels: "eins"
    mem_limit: 2g

one_ambassador:
    image: verb/socat
    restart: always
    command: TCP-LISTEN:8000,fork TCP:upstream:8000
    links:
      - eins:upstream
    ports:
      - "8001:8000"
    mem_limit: 128m
    labels:
      traefik.enable: "false"

# for local callback from K1 and BusinessWire integration
eins-api-callback:
    extends: eins
    environment:
      VIRTUAL_HOST: "one-cb.zemanta.com"
      NEW_RELIC_APP_NAME: "Zemanta One (callback API)"
      GUNICORN_WORKERS: "4"
    mem_limit: 1g
    #   default cpu.cfs_period_us is 100000. That is 100% of one CPU core
    cpu_quota: 200000
    labels:
      traefik.backend: "one-cb.zemanta.com"
      traefik.frontend.rule: "Host:one-cb.zemanta.com"

one-cb_ambassador:
    image: verb/socat
    restart: always
    command: TCP-LISTEN:8000,fork TCP:upstream:8000
    links:
      - eins-api-callback:upstream
    ports:
      - "8002:8000"
    mem_limit: 128m
    labels:
      traefik.enable: "false"

# for REST API
eins-rest-api:
    extends: eins
    environment:
      VIRTUAL_HOST: "oneapi.zemanta.com"
      NEW_RELIC_APP_NAME: "Zemanta One (REST API)"
      GUNICORN_WORKERS: "4"
    mem_limit: 1g
    #   default cpu.cfs_period_us is 100000. That is 100% of one CPU core
    cpu_quota: 200000
    labels:
      traefik.backend: "oneapi.zemanta.com"
      traefik.frontend.rule: "Host:oneapi.zemanta.com"

oneapi_ambassador:
    image: verb/socat
    restart: always
    command: TCP-LISTEN:8000,fork TCP:upstream:8000
    links:
      - eins-rest-api:upstream
    ports:
      - "8004:8000"
    mem_limit: 128m
    labels:
      traefik.enable: "false"

einsworker_reports:
    extends: eins
    mem_limit: 1g
    labels:
      traefik.enable: "false"
    entrypoint: ""
    command: "celery worker -A server -c 1 -Q z1-reports -l INFO -f /app/logs/eins_celery_reports.log --prefetch-multiplier 0"

einsworker_convapi:
    extends: eins
    mem_limit: 256m
    labels:
      traefik.enable: "false"
    entrypoint: ""
    command: "celery worker -A server -c 3 -Q prod-convapi -l INFO -f /app/logs/eins_celery_convapi.log"


# einsworker_convapi_v2:
#     extends: eins
#     mem_limit: 256m
#     labels:
#       traefik.enable: "false"
#     entrypoint: ""
#     command: "celery worker -A server -c 3 -Q prod-convapi_v2 -l INFO -f /app/logs/eins_celery_convapi_v2.log"
