version: '2'

services:
    postgres:
        ports:
          - "5432:5432"

    # this is fake telegraf that only prints stats on stdout
    telegraf:
        ports:
          - "8135:8135/udp"

    memcached:
        ports:
          - "11211:11211"
