version: '2'

services:
    postgres:
        image: postgres:9.6
        environment:
          - POSTGRES_PASSWORD=devpwd
          - POSTGRES_DB=one-dev
          - POSTGRES_USER=eins
        command: "-c fsync=off -c full_page_writes=off -c synchronous_commit=off"
        volumes:
          - "./fixtures/:/docker-entrypoint-initdb.d/"      

    client:        
        image: $Z1_CLIENT_IMAGE
        expose:
          - "9999"
        command: "sleep 1h"

    server:
        image: $Z1_SERVER_IMAGE
        volumes:
          - "./server/:/app/z1/"
          - "./server/.junit_xml/:/app/z1/.junit_xml/"
          - "./server/static/:/app/z1/static/"
        links:
          - "postgres:db"
          - "statspostgres:statsdb"
          - "memcached:memcached"
          - "client"          
          - "telegraf"
