version: "2.2"

services:
    # Main dashboard instance
    eins:
        image: z1-bundle:current
        restart: unless-stopped
        hostname: ${HOSTNAME}
        ports:
          - "8000"
        volumes:
          - "/mnt/logs/eins:/app/logs"
        command: /start-server.sh
        environment:
          CONF_ENV: "prod"
          VIRTUAL_HOST: "one.zemanta.com"
          NEW_RELIC_LICENSE_KEY: "1dfbd7b07a5cbf7bcc6eb18db5003808a058d16f"
          NEW_RELIC_APP_NAME: "Zemanta One"
          NEW_RELIC_PROCESS_HOST_DISPLAY_NAME: "${HOSTNAME}-docker"
          GUNICORN_TIMEOUT: "180"
          GUNICORN_WORKERS: "8"
          GUNICORN_THREADS: "1"
          GUNICORN_WORKER_CLASS: "gevent"
          GUNICORN_LOG_LEVEL: "warn"
        labels:
          traefik.backend: "one.zemanta.com"
          traefik.frontend.rule: "Host:one.zemanta.com"
          traefik.frontend.passHostHeader: "true"
        logging:
          driver: json-file
          options:
            max-size: "50m"
            max-file: "3"
            labels: "eins"
        mem_limit: 8g
        sysctls:
          net.core.somaxconn: 2048
        networks:
          - legacynet

    one_ambassador:
        image: verb/socat
        restart: always
        command: TCP-LISTEN:8000,fork TCP:eins:8000
        ports:
          - "8001:8000"
        mem_limit: 128m
        labels:
          traefik.enable: "false"
        networks:
          - legacynet

    # for local callback from K1 and BusinessWire integration
    eins-api-callback:
        extends: eins
        environment:
          VIRTUAL_HOST: "one-cb.zemanta.com"
          NEW_RELIC_APP_NAME: "Zemanta One (callback API)"
          GUNICORN_WORKERS: "6"
          GUNICORN_THREADS: "1"
          GUNICORN_WORKER_CLASS: "gevent"
        mem_limit: 4g
        #   default cpu.cfs_period_us is 100000. That is 100% of one CPU core
        cpu_quota: 400000
        labels:
          traefik.backend: "one-cb.zemanta.com"
          traefik.frontend.rule: "Host:one-cb.zemanta.com"

    one-cb_ambassador:
        image: verb/socat
        restart: always
        command: TCP-LISTEN:8000,fork TCP:eins-api-callback:8000
        ports:
          - "8002:8000"
        mem_limit: 128m
        labels:
          traefik.enable: "false"
        networks:
          - legacynet

    # for REST API
    eins-rest-api:
        extends: eins
        environment:
          VIRTUAL_HOST: "oneapi.zemanta.com"
          NEW_RELIC_APP_NAME: "Zemanta One (REST API)"
          GUNICORN_WORKERS: "6"
          GUNICORN_THREADS: "1"
          GUNICORN_WORKER_CLASS: "gevent"
          GUNICORN_LOG_LEVEL: "warn"
        mem_limit: 6g
        #   default cpu.cfs_period_us is 100000. That is 100% of one CPU core
        cpu_quota: 700000
        labels:
          traefik.backend: "oneapi.zemanta.com"
          traefik.frontend.rule: "Host:oneapi.zemanta.com"

    oneapi_ambassador:
        image: verb/socat
        restart: always
        command: TCP-LISTEN:8000,fork TCP:eins-rest-api:8000
        ports:
          - "8004:8000"
        mem_limit: 128m
        labels:
          traefik.enable: "false"
        networks:
          - legacynet

    einsworker_reports:
        extends: eins
        environment:
          VIRTUAL_HOST: "onereports.zemanta.com"
          NEW_RELIC_APP_NAME: "Zemanta One (Reports)"
        mem_limit: 4g
        labels:
          traefik.enable: "false"
        entrypoint: ""
        command: "/usr/local/bin/newrelic-admin run-program celery worker -A server -c 1 -Q z1-reports -l INFO -f /app/logs/eins_celery_reports.log --prefetch-multiplier 0 -P prefork"

    einsworker_redshift_background_cache:
        extends: eins
        environment:
          VIRTUAL_HOST: "oneredshiftbackgroundcache.zemanta.com"
          NEW_RELIC_APP_NAME: "Zemanta One (Redshift Background Cache)"
        mem_limit: 512m
        labels:
          traefik.enable: "false"
        entrypoint: ""
        command: "/usr/local/bin/newrelic-admin run-program celery worker -A server -c 1 -Q redshift-background-cache -l INFO -f /app/logs/eins_celery_redshift_background_cache.log --prefetch-multiplier 0 -P solo"

    einsworker_upload_lambda:
        environment:
          VIRTUAL_HOST: "onelambda.zemanta.com"
          NEW_RELIC_APP_NAME: "Zemanta One (Lambda)"
        extends: eins
        mem_limit: 256m
        labels:
          traefik.enable: "false"
        cpu_quota: 50000
        entrypoint: ""
        command: "/usr/local/bin/newrelic-admin run-program celery worker -A server -c 15 -Q z1-upload-lambda -l INFO -f /app/logs/eins_celery_upload_lambda.log --prefetch-multiplier 0 -P gevent"

    einsworker_convapi:
        extends: eins
        mem_limit: 512m
        labels:
          traefik.enable: "false"
        environment:
          VIRTUAL_HOST: "oneconvapi.zemanta.com"
          NEW_RELIC_APP_NAME: "Zemanta One (ConvAPI)"
        entrypoint: ""
        cpu_quota: 50000
        command: "/usr/local/bin/newrelic-admin run-program celery worker -A server -c 3 -Q prod-convapi -l INFO -f /app/logs/eins_celery_convapi.log"

    # einsworker_convapi_v2:
    #     extends: eins
    #     mem_limit: 256m
    #     labels:
    #       traefik.enable: "false"
    #     entrypoint: ""
    #     command: "celery worker -A server -c 3 -Q prod-convapi_v2 -l INFO -f /app/logs/eins_celery_convapi_v2.log"


    # ONE Whitelabel
    eins-newscorp:
        extends: eins
        environment:
          VIRTUAL_HOST: "newscorp.zemanta.com"
          NEW_RELIC_APP_NAME: "Zemanta One Whitelabel (Newscorp)"
        labels:
          traefik.backend: "newscorp.zemanta.com"
          traefik.frontend.rule: "Host:newscorp.zemanta.com"

# created with CLI: docker network create -d bridge legacynet
networks:
    legacynet:
        external: true

