/*globals oneApp*/
"use strict";

oneApp.constant('regions', {
    _regionIndexByCode: undefined,
    getByCode: function(code) {

        // cache code->regions array index
        if (!this._regionIndexByCode) {
            this._regionIndexByCode = {};
            for (var i=0; i<this.regions.length; i++) {
                this._regionIndexByCode[this.regions[i].code] = i;
            }
        }

        return this.regions[this._regionIndexByCode[code]];
    },
    isDMA: function(location) {
        return location.type === 'D';
    },
    isCountry: function(location) {
        return location.type === 'C';
    },
    isSubdivision: function(location) {
        return location.type === 'S';
    },
    isUSState: function(location) {
        return location.type === 'S' && location.code.indexOf('US') === 0;
    },
    regions: [{"code": "BD", "type": "C", "name": "Bangladesh"},
              {"code": "BE", "type": "C", "name": "Belgium"},
              {"code": "BF", "type": "C", "name": "Burkina Faso"},
              {"code": "BG", "type": "C", "name": "Bulgaria"},
              {"code": "BA", "type": "C", "name": "Bosnia and Herzegovina"},
              {"code": "BB", "type": "C", "name": "Barbados"},
              {"code": "WF", "type": "C", "name": "Wallis and Futuna"},
              {"code": "BN", "type": "C", "name": "Brunei Darussalam"},
              {"code": "BO", "type": "C", "name": "Bolivia,Plurinational State of"},
              {"code": "BH", "type": "C", "name": "Bahrain"},
              {"code": "BI", "type": "C", "name": "Burundi"},
              {"code": "BJ", "type": "C", "name": "Benin"},
              {"code": "BT", "type": "C", "name": "Bhutan"},
              {"code": "JM", "type": "C", "name": "Jamaica"},
              {"code": "BW", "type": "C", "name": "Botswana"},
              {"code": "WS", "type": "C", "name": "Samoa"},
              {"code": "BR", "type": "C", "name": "Brazil"},
              {"code": "BS", "type": "C", "name": "Bahamas"},
              {"code": "BY", "type": "C", "name": "Belarus"},
              {"code": "BZ", "type": "C", "name": "Belize"},
              {"code": "RU", "type": "C", "name": "Russian Federation"},
              {"code": "RW", "type": "C", "name": "Rwanda"},
              {"code": "RS", "type": "C", "name": "Serbia"},
              {"code": "TL", "type": "C", "name": "Timor-Leste"},
              {"code": "TM", "type": "C", "name": "Turkmenistan"},
              {"code": "TJ", "type": "C", "name": "Tajikistan"},
              {"code": "RO", "type": "C", "name": "Romania"},
              {"code": "TK", "type": "C", "name": "Tokelau"},
              {"code": "GW", "type": "C", "name": "Guinea-Bissau"},
              {"code": "GU", "type": "C", "name": "Guam"},
              {"code": "GT", "type": "C", "name": "Guatemala"},
              {"code": "GS", "type": "C", "name": "South Georgia and the South Sandwich Islands"},
              {"code": "GR", "type": "C", "name": "Greece"},
              {"code": "GQ", "type": "C", "name": "Equatorial Guinea"},
              {"code": "JP", "type": "C", "name": "Japan"},
              {"code": "GY", "type": "C", "name": "Guyana"},
              {"code": "GE", "type": "C", "name": "Georgia"},
              {"code": "GD", "type": "C", "name": "Grenada"},
              {"code": "GB", "type": "C", "name": "United Kingdom"},
              {"code": "GA", "type": "C", "name": "Gabon"},
              {"code": "GN", "type": "C", "name": "Guinea"},
              {"code": "GM", "type": "C", "name": "Gambia"},
              {"code": "GH", "type": "C", "name": "Ghana"},
              {"code": "OM", "type": "C", "name": "Oman"},
              {"code": "TN", "type": "C", "name": "Tunisia"},
              {"code": "JO", "type": "C", "name": "Jordan"},
              {"code": "HR", "type": "C", "name": "Croatia"},
              {"code": "HT", "type": "C", "name": "Haiti"},
              {"code": "HU", "type": "C", "name": "Hungary"},
              {"code": "HN", "type": "C", "name": "Honduras"},
              {"code": "HM", "type": "C", "name": "Heard Island and McDonald Islands"},
              {"code": "VE", "type": "C", "name": "Venezuela,Bolivarian Republic of"},
              {"code": "PW", "type": "C", "name": "Palau"},
              {"code": "PT", "type": "C", "name": "Portugal"},
              {"code": "KN", "type": "C", "name": "Saint Kitts and Nevis"},
              {"code": "PY", "type": "C", "name": "Paraguay"},
              {"code": "IQ", "type": "C", "name": "Iraq"},
              {"code": "PA", "type": "C", "name": "Panama"},
              {"code": "PF", "type": "C", "name": "French Polynesia"},
              {"code": "PG", "type": "C", "name": "Papua New Guinea"},
              {"code": "PE", "type": "C", "name": "Peru"},
              {"code": "PK", "type": "C", "name": "Pakistan"},
              {"code": "PH", "type": "C", "name": "Philippines"},
              {"code": "PN", "type": "C", "name": "Pitcairn"},
              {"code": "PL", "type": "C", "name": "Poland"},
              {"code": "PM", "type": "C", "name": "Saint Pierre and Miquelon"},
              {"code": "ZM", "type": "C", "name": "Zambia"},
              {"code": "EE", "type": "C", "name": "Estonia"},
              {"code": "EG", "type": "C", "name": "Egypt"},
              {"code": "ZA", "type": "C", "name": "South Africa"},
              {"code": "EC", "type": "C", "name": "Ecuador"},
              {"code": "IT", "type": "C", "name": "Italy"},
              {"code": "VN", "type": "C", "name": "Viet Nam"},
              {"code": "SB", "type": "C", "name": "Solomon Islands"},
              {"code": "ET", "type": "C", "name": "Ethiopia"},
              {"code": "SO", "type": "C", "name": "Somalia"},
              {"code": "ZW", "type": "C", "name": "Zimbabwe"},
              {"code": "SA", "type": "C", "name": "Saudi Arabia"},
              {"code": "ES", "type": "C", "name": "Spain"},
              {"code": "ER", "type": "C", "name": "Eritrea"},
              {"code": "ME", "type": "C", "name": "Montenegro"},
              {"code": "MD", "type": "C", "name": "Moldova,Republic of"},
              {"code": "MG", "type": "C", "name": "Madagascar"},
              {"code": "MA", "type": "C", "name": "Morocco"},
              {"code": "MC", "type": "C", "name": "Monaco"},
              {"code": "UZ", "type": "C", "name": "Uzbekistan"},
              {"code": "ML", "type": "C", "name": "Mali"},
              {"code": "MN", "type": "C", "name": "Mongolia"},
              {"code": "MH", "type": "C", "name": "Marshall Islands"},
              {"code": "MK", "type": "C", "name": "Macedonia,the Former Yugoslav Republic of"},
              {"code": "MU", "type": "C", "name": "Mauritius"},
              {"code": "MT", "type": "C", "name": "Malta"},
              {"code": "MW", "type": "C", "name": "Malawi"},
              {"code": "MV", "type": "C", "name": "Maldives"},
              {"code": "MP", "type": "C", "name": "Northern Mariana Islands"},
              {"code": "MR", "type": "C", "name": "Mauritania"},
              {"code": "UG", "type": "C", "name": "Uganda"},
              {"code": "TZ", "type": "C", "name": "Tanzania,United Republic of"},
              {"code": "MY", "type": "C", "name": "Malaysia"},
              {"code": "MX", "type": "C", "name": "Mexico"},
              {"code": "IL", "type": "C", "name": "Israel"},
              {"code": "FR", "type": "C", "name": "France"},
              {"code": "SH", "type": "C", "name": "Saint Helena,Ascension and Tristan da Cunha"},
              {"code": "FI", "type": "C", "name": "Finland"},
              {"code": "FJ", "type": "C", "name": "Fiji"},
              {"code": "FM", "type": "C", "name": "Micronesia,Federated States of"},
              {"code": "NI", "type": "C", "name": "Nicaragua"},
              {"code": "NL", "type": "C", "name": "Netherlands"},
              {"code": "NO", "type": "C", "name": "Norway"},
              {"code": "NA", "type": "C", "name": "Namibia"},
              {"code": "VU", "type": "C", "name": "Vanuatu"},
              {"code": "NC", "type": "C", "name": "New Caledonia"},
              {"code": "NE", "type": "C", "name": "Niger"},
              {"code": "NF", "type": "C", "name": "Norfolk Island"},
              {"code": "NG", "type": "C", "name": "Nigeria"},
              {"code": "NZ", "type": "C", "name": "New Zealand"},
              {"code": "NP", "type": "C", "name": "Nepal"},
              {"code": "NR", "type": "C", "name": "Nauru"},
              {"code": "NU", "type": "C", "name": "Niue"},
              {"code": "CK", "type": "C", "name": "Cook Islands"},
              {"code": "CH", "type": "C", "name": "Switzerland"},
              {"code": "CO", "type": "C", "name": "Colombia"},
              {"code": "CN", "type": "C", "name": "China"},
              {"code": "CM", "type": "C", "name": "Cameroon"},
              {"code": "CL", "type": "C", "name": "Chile"},
              {"code": "CC", "type": "C", "name": "Cocos (Keeling) Islands"},
              {"code": "CA", "type": "C", "name": "Canada"},
              {"code": "CG", "type": "C", "name": "Congo"},
              {"code": "CF", "type": "C", "name": "Central African Republic"},
              {"code": "CD", "type": "C", "name": "Congo,the Democratic Republic of the"},
              {"code": "CZ", "type": "C", "name": "Czech Republic"},
              {"code": "CY", "type": "C", "name": "Cyprus"},
              {"code": "CX", "type": "C", "name": "Christmas Island"},
              {"code": "CR", "type": "C", "name": "Costa Rica"},
              {"code": "CV", "type": "C", "name": "Cape Verde"},
              {"code": "SZ", "type": "C", "name": "Swaziland"},
              {"code": "KG", "type": "C", "name": "Kyrgyzstan"},
              {"code": "KE", "type": "C", "name": "Kenya"},
              {"code": "SR", "type": "C", "name": "Suriname"},
              {"code": "KI", "type": "C", "name": "Kiribati"},
              {"code": "KH", "type": "C", "name": "Cambodia"},
              {"code": "SV", "type": "C", "name": "El Salvador"},
              {"code": "KM", "type": "C", "name": "Comoros"},
              {"code": "ST", "type": "C", "name": "Sao Tome and Principe"},
              {"code": "SK", "type": "C", "name": "Slovakia"},
              {"code": "KR", "type": "C", "name": "Korea,Republic of"},
              {"code": "SI", "type": "C", "name": "Slovenia"},
              {"code": "KW", "type": "C", "name": "Kuwait"},
              {"code": "SN", "type": "C", "name": "Senegal"},
              {"code": "SM", "type": "C", "name": "San Marino"},
              {"code": "SL", "type": "C", "name": "Sierra Leone"},
              {"code": "SC", "type": "C", "name": "Seychelles"},
              {"code": "KZ", "type": "C", "name": "Kazakhstan"},
              {"code": "SG", "type": "C", "name": "Singapore"},
              {"code": "SE", "type": "C", "name": "Sweden"},
              {"code": "DO", "type": "C", "name": "Dominican Republic"},
              {"code": "DM", "type": "C", "name": "Dominica"},
              {"code": "DJ", "type": "C", "name": "Djibouti"},
              {"code": "DK", "type": "C", "name": "Denmark"},
              {"code": "DE", "type": "C", "name": "Germany"},
              {"code": "YE", "type": "C", "name": "Yemen"},
              {"code": "DZ", "type": "C", "name": "Algeria"},
              {"code": "US", "type": "C", "name": "United States"},
              {"code": "UY", "type": "C", "name": "Uruguay"},
              {"code": "UM", "type": "C", "name": "United States Minor Outlying Islands"},
              {"code": "LB", "type": "C", "name": "Lebanon"},
              {"code": "LC", "type": "C", "name": "Saint Lucia"},
              {"code": "LA", "type": "C", "name": "Lao People's Democratic Republic"},
              {"code": "TV", "type": "C", "name": "Tuvalu"},
              {"code": "TT", "type": "C", "name": "Trinidad and Tobago"},
              {"code": "TR", "type": "C", "name": "Turkey"},
              {"code": "LK", "type": "C", "name": "Sri Lanka"},
              {"code": "LI", "type": "C", "name": "Liechtenstein"},
              {"code": "LV", "type": "C", "name": "Latvia"},
              {"code": "TO", "type": "C", "name": "Tonga"},
              {"code": "LT", "type": "C", "name": "Lithuania"},
              {"code": "LU", "type": "C", "name": "Luxembourg"},
              {"code": "LR", "type": "C", "name": "Liberia"},
              {"code": "LS", "type": "C", "name": "Lesotho"},
              {"code": "TH", "type": "C", "name": "Thailand"},
              {"code": "TG", "type": "C", "name": "Togo"},
              {"code": "TD", "type": "C", "name": "Chad"},
              {"code": "LY", "type": "C", "name": "Libya"},
              {"code": "VA", "type": "C", "name": "Holy See (Vatican City State)"},
              {"code": "VC", "type": "C", "name": "Saint Vincent and the Grenadines"},
              {"code": "AE", "type": "C", "name": "United Arab Emirates"},
              {"code": "AD", "type": "C", "name": "Andorra"},
              {"code": "AG", "type": "C", "name": "Antigua and Barbuda"},
              {"code": "AF", "type": "C", "name": "Afghanistan"},
              {"code": "IS", "type": "C", "name": "Iceland"},
              {"code": "AM", "type": "C", "name": "Armenia"},
              {"code": "AL", "type": "C", "name": "Albania"},
              {"code": "AO", "type": "C", "name": "Angola"},
              {"code": "AQ", "type": "C", "name": "Antarctica"},
              {"code": "AS", "type": "C", "name": "American Samoa"},
              {"code": "AR", "type": "C", "name": "Argentina"},
              {"code": "AU", "type": "C", "name": "Australia"},
              {"code": "AT", "type": "C", "name": "Austria"},
              {"code": "IN", "type": "C", "name": "India"},
              {"code": "AZ", "type": "C", "name": "Azerbaijan"},
              {"code": "IE", "type": "C", "name": "Ireland"},
              {"code": "ID", "type": "C", "name": "Indonesia"},
              {"code": "UA", "type": "C", "name": "Ukraine"},
              {"code": "QA", "type": "C", "name": "Qatar"},
              {"code": "MZ", "type": "C", "name": "Mozambique"},
              {"code": "669", "type": "D", "name": "669 Madison,WI"},
              {"code": "762", "type": "D", "name": "762 Missoula,MT"},
              {"code": "760", "type": "D", "name": "760 Twin Falls,ID"},
              {"code": "766", "type": "D", "name": "766 Helena,MT"},
              {"code": "662", "type": "D", "name": "662 Abilene-Sweetwater,TX"},
              {"code": "764", "type": "D", "name": "764 Rapid City,SD"},
              {"code": "765", "type": "D", "name": "765 El Paso,TX"},
              {"code": "692", "type": "D", "name": "692 Beaumont-Port Arthur,TX"},
              {"code": "693", "type": "D", "name": "693 Little Rock-Pine Bluff,AR"},
              {"code": "691", "type": "D", "name": "691 Huntsville-Decatur (Florence),AL"},
              {"code": "698", "type": "D", "name": "698 Montgomery (Selma),AL"},
              {"code": "542", "type": "D", "name": "542 Dayton,OH"},
              {"code": "543", "type": "D", "name": "543 Springfield-Holyoke,MA"},
              {"code": "540", "type": "D", "name": "540 Traverse City-Cadillac,MI"},
              {"code": "541", "type": "D", "name": "541 Lexington,KY"},
              {"code": "546", "type": "D", "name": "546 Columbia,SC"},
              {"code": "547", "type": "D", "name": "547 Toledo,OH"},
              {"code": "544", "type": "D", "name": "544 Norfolk-Portsmouth-Newport News,VA"},
              {"code": "545", "type": "D", "name": "545 Greenville-New Bern-Washington,NC"},
              {"code": "810", "type": "D", "name": "810 Yakima-Pasco-Richland-Kennewick,WA"},
              {"code": "811", "type": "D", "name": "811 Reno,NV"},
              {"code": "548", "type": "D", "name": "548 West Palm Beach-Ft. Pierce,FL"},
              {"code": "813", "type": "D", "name": "813 Medford-Klamath Falls,OR"},
              {"code": "628", "type": "D", "name": "628 Monroe,LA-El Dorado,AR"},
              {"code": "678", "type": "D", "name": "678 Wichita-Hutchinson,KS"},
              {"code": "679", "type": "D", "name": "679 Des Moines-Ames,IA"},
              {"code": "718", "type": "D", "name": "718 Jackson,MS"},
              {"code": "717", "type": "D", "name": "717 Quincy,IL-Hannibal,MO-Keokuk,IA"},
              {"code": "675", "type": "D", "name": "675 Peoria-Bloomington,IL"},
              {"code": "676", "type": "D", "name": "676 Duluth,MN-Superior,WI"},
              {"code": "670", "type": "D", "name": "670 Ft. Smith-Fayetteville-Springdale-Rogers,AR"},
              {"code": "671", "type": "D", "name": "671 Tulsa,OK"},
              {"code": "711", "type": "D", "name": "711 Meridian,MS"},
              {"code": "767", "type": "D", "name": "767 Casper-Riverton,WY"},
              {"code": "661", "type": "D", "name": "661 San Angelo,TX"},
              {"code": "736", "type": "D", "name": "736 Bowling Green,KY"},
              {"code": "537", "type": "D", "name": "537 Bangor,ME"},
              {"code": "536", "type": "D", "name": "536 Youngstown,OH"},
              {"code": "535", "type": "D", "name": "535 Columbus,OH"},
              {"code": "534", "type": "D", "name": "534 Orlando-Daytona Beach-Melbourne,FL"},
              {"code": "533", "type": "D", "name": "533 Hartford & New Haven,CT"},
              {"code": "532", "type": "D", "name": "532 Albany-Schenectady-Troy,NY"},
              {"code": "530", "type": "D", "name": "530 Tallahassee,FL-Thomasville,GA"},
              {"code": "825", "type": "D", "name": "825 San Diego,CA"},
              {"code": "821", "type": "D", "name": "821 Bend,OR"},
              {"code": "820", "type": "D", "name": "820 Portland,OR"},
              {"code": "539", "type": "D", "name": "539 Tampa-St Petersburg (Sarasota),FL"},
              {"code": "538", "type": "D", "name": "538 Rochester,NY"},
              {"code": "605", "type": "D", "name": "605 Topeka,KS"},
              {"code": "592", "type": "D", "name": "592 Gainesville,FL"},
              {"code": "709", "type": "D", "name": "709 Tyler-Longview(Lufkin & Nacogdoches),TX"},
              {"code": "597", "type": "D", "name": "597 Parkersburg,WV"},
              {"code": "596", "type": "D", "name": "596 Zanesville,OH"},
              {"code": "705", "type": "D", "name": "705 Wausau-Rhinelander,WI"},
              {"code": "702", "type": "D", "name": "702 La Crosse-Eau Claire,WI"},
              {"code": "619", "type": "D", "name": "619 Springfield,MO"},
              {"code": "790", "type": "D", "name": "790 Albuquerque-Santa Fe,NM"},
              {"code": "839", "type": "D", "name": "839 Las Vegas,NV"},
              {"code": "798", "type": "D", "name": "798 Glendive,MT"},
              {"code": "524", "type": "D", "name": "524 Atlanta,GA"},
              {"code": "525", "type": "D", "name": "525 Albany,GA"},
              {"code": "526", "type": "D", "name": "526 Utica,NY"},
              {"code": "527", "type": "D", "name": "527 Indianapolis,IN"},
              {"code": "520", "type": "D", "name": "520 Augusta,GA"},
              {"code": "521", "type": "D", "name": "521 Providence,RI-New Bedford,MA"},
              {"code": "522", "type": "D", "name": "522 Columbus,GA"},
              {"code": "523", "type": "D", "name": "523 Burlington,VT-Plattsburgh,NY"},
              {"code": "528", "type": "D", "name": "528 Miami-Ft. Lauderdale,FL"},
              {"code": "529", "type": "D", "name": "529 Louisville,KY"},
              {"code": "828", "type": "D", "name": "828 Monterey-Salinas,CA"},
              {"code": "584", "type": "D", "name": "584 Charlottesville,VA"},
              {"code": "582", "type": "D", "name": "582 Lafayette,IN"},
              {"code": "583", "type": "D", "name": "583 Alpena,MI"},
              {"code": "581", "type": "D", "name": "581 Terre Haute,IN"},
              {"code": "588", "type": "D", "name": "588 South Bend-Elkhart,IN"},
              {"code": "598", "type": "D", "name": "598 Clarksburg-Weston,WV"},
              {"code": "881", "type": "D", "name": "881 Spokane,WA"},
              {"code": "630", "type": "D", "name": "630 Birmingham,AL"},
              {"code": "789", "type": "D", "name": "789 Tucson (Sierra Vista),AZ"},
              {"code": "737", "type": "D", "name": "737 Mankato,MN"},
              {"code": "519", "type": "D", "name": "519 Charleston,SC"},
              {"code": "640", "type": "D", "name": "640 Memphis,TN"},
              {"code": "643", "type": "D", "name": "643 Lake Charles,LA"},
              {"code": "642", "type": "D", "name": "642 Lafayette,LA"},
              {"code": "644", "type": "D", "name": "644 Alexandria,LA"},
              {"code": "647", "type": "D", "name": "647 Greenwood-Greenville,MS"},
              {"code": "649", "type": "D", "name": "649 Evansville,IN"},
              {"code": "648", "type": "D", "name": "648 Champaign & Springfield-Decatur,IL"},
              {"code": "513", "type": "D", "name": "513 Flint-Saginaw-Bay City,MI"},
              {"code": "512", "type": "D", "name": "512 Baltimore,MD"},
              {"code": "515", "type": "D", "name": "515 Cincinnati,OH"},
              {"code": "514", "type": "D", "name": "514 Buffalo,NY"},
              {"code": "517", "type": "D", "name": "517 Charlotte,NC"},
              {"code": "516", "type": "D", "name": "516 Erie,PA"},
              {"code": "623", "type": "D", "name": "623 Dallas-Ft. Worth,TX"},
              {"code": "622", "type": "D", "name": "622 New Orleans,LA"},
              {"code": "627", "type": "D", "name": "627 Wichita Falls,TX & Lawton,OK"},
              {"code": "626", "type": "D", "name": "626 Victoria,TX"},
              {"code": "625", "type": "D", "name": "625 Waco-Temple-Bryan,TX"},
              {"code": "624", "type": "D", "name": "624 Sioux City,IA"},
              {"code": "573", "type": "D", "name": "573 Roanoke-Lynchburg,VA"},
              {"code": "571", "type": "D", "name": "571 Ft. Myers-Naples,FL"},
              {"code": "570", "type": "D", "name": "570 Florence-Myrtle Beach,SC"},
              {"code": "577", "type": "D", "name": "577 Wilkes Barre-Scranton,PA"},
              {"code": "576", "type": "D", "name": "576 Salisbury,MD"},
              {"code": "575", "type": "D", "name": "575 Chattanooga,TN"},
              {"code": "574", "type": "D", "name": "574 Johnstown-Altoona,PA"},
              {"code": "743", "type": "D", "name": "743 Anchorage,AK"},
              {"code": "744", "type": "D", "name": "744 Honolulu,HI"},
              {"code": "558", "type": "D", "name": "558 Lima,OH"},
              {"code": "855", "type": "D", "name": "855 Santa Barbara-Santa Maria-San Luis Obispo,CA"},
              {"code": "603", "type": "D", "name": "603 Joplin,MO-Pittsburg,KS"},
              {"code": "819", "type": "D", "name": "819 Seattle-Tacoma,WA"},
              {"code": "745", "type": "D", "name": "745 Fairbanks,AK"},
              {"code": "602", "type": "D", "name": "602 Chicago,IL"},
              {"code": "656", "type": "D", "name": "656 Panama City,FL"},
              {"code": "657", "type": "D", "name": "657 Sherman,TX-Ada,OK"},
              {"code": "652", "type": "D", "name": "652 Omaha,NE"},
              {"code": "734", "type": "D", "name": "734 Jonesboro,AR"},
              {"code": "650", "type": "D", "name": "650 Oklahoma City,OK"},
              {"code": "651", "type": "D", "name": "651 Lubbock,TX"},
              {"code": "506", "type": "D", "name": "506 Boston,MA-Manchester,NH"},
              {"code": "507", "type": "D", "name": "507 Savannah,GA"},
              {"code": "504", "type": "D", "name": "504 Philadelphia,PA"},
              {"code": "505", "type": "D", "name": "505 Detroit,MI"},
              {"code": "502", "type": "D", "name": "502 Binghamton,NY"},
              {"code": "503", "type": "D", "name": "503 Macon,GA"},
              {"code": "500", "type": "D", "name": "500 Portland-Auburn,ME"},
              {"code": "501", "type": "D", "name": "501 New York,NY"},
              {"code": "753", "type": "D", "name": "753 Phoenix,AZ"},
              {"code": "569", "type": "D", "name": "569 Harrisonburg,VA"},
              {"code": "632", "type": "D", "name": "632 Paducah,KY-Cape Girardeau,MO-Harrisburg-Mount Vernon,IL"},
              {"code": "633", "type": "D", "name": "633 Odessa-Midland,TX"},
              {"code": "757", "type": "D", "name": "757 Boise,ID"},
              {"code": "508", "type": "D", "name": "508 Pittsburgh,PA"},
              {"code": "755", "type": "D", "name": "755 Great Falls,MT"},
              {"code": "637", "type": "D", "name": "637 Cedar Rapids-Waterloo-Iowa City & Dubuque,IA"},
              {"code": "638", "type": "D", "name": "638 St. Joseph,MO"},
              {"code": "561", "type": "D", "name": "561 Jacksonville,FL"},
              {"code": "759", "type": "D", "name": "759 Cheyenne,WY-Scottsbluff,NE"},
              {"code": "563", "type": "D", "name": "563 Grand Rapids-Kalamazoo-Battle Creek,MI"},
              {"code": "564", "type": "D", "name": "564 Charleston-Huntington,WV"},
              {"code": "565", "type": "D", "name": "565 Elmira,NY"},
              {"code": "566", "type": "D", "name": "566 Harrisburg-Lancaster-Lebanon-York,PA"},
              {"code": "567", "type": "D", "name": "567 Greenville-Spartanburg,SC-Asheville,NC-Anderson,SC"},
              {"code": "868", "type": "D", "name": "868 Chico-Redding,CA"},
              {"code": "549", "type": "D", "name": "549 Watertown,NY"},
              {"code": "747", "type": "D", "name": "747 Juneau,AK"},
              {"code": "862", "type": "D", "name": "862 Sacramento-Stockton-Modesto,CA"},
              {"code": "866", "type": "D", "name": "866 Fresno-Visalia,CA"},
              {"code": "724", "type": "D", "name": "724 Fargo-Valley City,ND"},
              {"code": "725", "type": "D", "name": "725 Sioux Falls(Mitchell),SD"},
              {"code": "722", "type": "D", "name": "722 Lincoln & Hastings-Kearney,NE"},
              {"code": "658", "type": "D", "name": "658 Green Bay-Appleton,WI"},
              {"code": "659", "type": "D", "name": "659 Nashville,TN"},
              {"code": "740", "type": "D", "name": "740 North Platte,NE"},
              {"code": "604", "type": "D", "name": "604 Columbia-Jefferson City,MO"},
              {"code": "631", "type": "D", "name": "631 Ottumwa,IA-Kirksville,MO"},
              {"code": "606", "type": "D", "name": "606 Dothan,AL"},
              {"code": "559", "type": "D", "name": "559 Bluefield-Beckley-Oak Hill,WV"},
              {"code": "600", "type": "D", "name": "600 Corpus Christi,TX"},
              {"code": "746", "type": "D", "name": "746 Biloxi-Gulfport,MS"},
              {"code": "752", "type": "D", "name": "752 Colorado Springs-Pueblo,CO"},
              {"code": "555", "type": "D", "name": "555 Syracuse,NY"},
              {"code": "554", "type": "D", "name": "554 Wheeling,WV-Steubenville,OH"},
              {"code": "557", "type": "D", "name": "557 Knoxville,TN"},
              {"code": "556", "type": "D", "name": "556 Richmond-Petersburg,VA"},
              {"code": "551", "type": "D", "name": "551 Lansing,MI"},
              {"code": "751", "type": "D", "name": "751 Denver,CO"},
              {"code": "553", "type": "D", "name": "553 Marquette,MI"},
              {"code": "552", "type": "D", "name": "552 Presque Isle,ME"},
              {"code": "550", "type": "D", "name": "550 Wilmington,NC"},
              {"code": "634", "type": "D", "name": "634 Amarillo,TX"},
              {"code": "756", "type": "D", "name": "756 Billings,MT"},
              {"code": "749", "type": "D", "name": "749 Laredo,TX"},
              {"code": "641", "type": "D", "name": "641 San Antonio,TX"},
              {"code": "636", "type": "D", "name": "636 Harlingen-Weslaco-Brownsville-McAllen,TX"},
              {"code": "518", "type": "D", "name": "518 Greensboro-High Point-Winston Salem,NC"},
              {"code": "754", "type": "D", "name": "754 Butte-Bozeman,MT"},
              {"code": "560", "type": "D", "name": "560 Raleigh-Durham (Fayetteville),NC"},
              {"code": "716", "type": "D", "name": "716 Baton Rouge,LA"},
              {"code": "618", "type": "D", "name": "618 Houston,TX"},
              {"code": "758", "type": "D", "name": "758 Idaho Falls-Pocatello,ID"},
              {"code": "771", "type": "D", "name": "771 Yuma,AZ-El Centro,CA"},
              {"code": "770", "type": "D", "name": "770 Salt Lake City,UT"},
              {"code": "773", "type": "D", "name": "773 Grand Junction-Montrose,CO"},
              {"code": "612", "type": "D", "name": "612 Shreveport,LA"},
              {"code": "613", "type": "D", "name": "613 Minneapolis-St. Paul,MN"},
              {"code": "610", "type": "D", "name": "610 Rockford,IL"},
              {"code": "611", "type": "D", "name": "611 Rochester,MN-Mason City,IA-Austin,MN"},
              {"code": "616", "type": "D", "name": "616 Kansas City,MO"},
              {"code": "617", "type": "D", "name": "617 Milwaukee,WI"},
              {"code": "511", "type": "D", "name": "511 Washington,DC (Hagerstown,MD)"},
              {"code": "710", "type": "D", "name": "710 Hattiesburg-Laurel,MS"},
              {"code": "510", "type": "D", "name": "510 Cleveland-Akron (Canton),OH"},
              {"code": "635", "type": "D", "name": "635 Austin,TX"},
              {"code": "673", "type": "D", "name": "673 Columbus-Tupelo-West Point,MS"},
              {"code": "687", "type": "D", "name": "687 Minot-Bismarck-Dickinson(Williston),ND"},
              {"code": "509", "type": "D", "name": "509 Ft. Wayne,IN"},
              {"code": "800", "type": "D", "name": "800 Bakersfield,CA"},
              {"code": "609", "type": "D", "name": "609 St. Louis,MO"},
              {"code": "682", "type": "D", "name": "682 Davenport,IA-Rock Island-Moline,IL"},
              {"code": "803", "type": "D", "name": "803 Los Angeles,CA"},
              {"code": "802", "type": "D", "name": "802 Eureka,CA"},
              {"code": "801", "type": "D", "name": "801 Eugene,OR"},
              {"code": "686", "type": "D", "name": "686 Mobile,AL-Pensacola (Ft. Walton Beach),FL"},
              {"code": "807", "type": "D", "name": "807 San Francisco-Oakland-San Jose,CA"},
              {"code": "639", "type": "D", "name": "639 Jackson,TN"},
              {"code": "804", "type": "D", "name": "804 Palm Springs,CA"},
              {"code": "US-AL", "type": "S", "name": "Alabama"},
              {"code": "US-AK", "type": "S", "name": "Alaska"},
              {"code": "US-AZ", "type": "S", "name": "Arizona"},
              {"code": "US-AR", "type": "S", "name": "Arkansas"},
              {"code": "US-CA", "type": "S", "name": "California"},
              {"code": "US-CO", "type": "S", "name": "Colorado"},
              {"code": "US-CT", "type": "S", "name": "Connecticut"},
              {"code": "US-DE", "type": "S", "name": "Delaware"},
              {"code": "US-FL", "type": "S", "name": "Florida"},
              {"code": "US-GA", "type": "S", "name": "Georgia"},
              {"code": "US-HI", "type": "S", "name": "Hawaii"},
              {"code": "US-ID", "type": "S", "name": "Idaho"},
              {"code": "US-IL", "type": "S", "name": "Illinois"},
              {"code": "US-IN", "type": "S", "name": "Indiana"},
              {"code": "US-IA", "type": "S", "name": "Iowa"},
              {"code": "US-KS", "type": "S", "name": "Kansas"},
              {"code": "US-KY", "type": "S", "name": "Kentucky"},
              {"code": "US-LA", "type": "S", "name": "Louisiana"},
              {"code": "US-ME", "type": "S", "name": "Maine"},
              {"code": "US-MD", "type": "S", "name": "Maryland"},
              {"code": "US-MA", "type": "S", "name": "Massachusetts"},
              {"code": "US-MI", "type": "S", "name": "Michigan"},
              {"code": "US-MN", "type": "S", "name": "Minnesota"},
              {"code": "US-MS", "type": "S", "name": "Mississippi"},
              {"code": "US-MO", "type": "S", "name": "Missouri"},
              {"code": "US-MT", "type": "S", "name": "Montana"},
              {"code": "US-NE", "type": "S", "name": "Nebraska"},
              {"code": "US-NV", "type": "S", "name": "Nevada"},
              {"code": "US-NH", "type": "S", "name": "New Hampshire"},
              {"code": "US-NJ", "type": "S", "name": "New Jersey"},
              {"code": "US-NM", "type": "S", "name": "New Mexico"},
              {"code": "US-NY", "type": "S", "name": "New York"},
              {"code": "US-NC", "type": "S", "name": "North Carolina"},
              {"code": "US-ND", "type": "S", "name": "North Dakota"},
              {"code": "US-OH", "type": "S", "name": "Ohio"},
              {"code": "US-OK", "type": "S", "name": "Oklahoma"},
              {"code": "US-OR", "type": "S", "name": "Oregon"},
              {"code": "US-PA", "type": "S", "name": "Pennsylvania"},
              {"code": "US-RI", "type": "S", "name": "Rhode Island"},
              {"code": "US-SC", "type": "S", "name": "South Carolina"},
              {"code": "US-SD", "type": "S", "name": "South Dakota"},
              {"code": "US-TN", "type": "S", "name": "Tennessee"},
              {"code": "US-TX", "type": "S", "name": "Texas"},
              {"code": "US-UT", "type": "S", "name": "Utah"},
              {"code": "US-VT", "type": "S", "name": "Vermont"},
              {"code": "US-VA", "type": "S", "name": "Virginia"},
              {"code": "US-WA", "type": "S", "name": "Washington"},
              {"code": "US-WV", "type": "S", "name": "West Virginia"},
              {"code": "US-WI", "type": "S", "name": "Wisconsin"},
              {"code": "US-WY", "type": "S", "name": "Wyoming"},
              {"code": "US-DC", "type": "S", "name": "District of Columbia"},
              {"code": "US-AS", "type": "S", "name": "American Samoa"},
              {"code": "US-GU", "type": "S", "name": "Guam"},
              {"code": "US-MP", "type": "S", "name": "Northern Mariana Islands"},
              {"code": "US-PR", "type": "S", "name": "Puerto Rico"},
              {"code": "US-UM", "type": "S", "name": "United States Minor Outlying Islands"},
              {"code": "US-VI", "type": "S", "name": "Virgin Islands"}
    ],
    legacy: [{"code": "AU", "type": "C", "name": "Australia"},
             {"code": "CA", "type": "C", "name": "Canada"},
             {"code": "IE", "type": "C", "name": "Ireland"},
             {"code": "NZ", "type": "C", "name": "New Zealand"},
             {"code": "GB", "type": "C", "name": "United Kingdom"},
             {"code": "US", "type": "C", "name": "United States"}
    ]
});
