export enum ExpandableSection {
    SCHEDULING = 'SCHEDULING',
    BUDGET = 'BUDGET',
    DEVICE_TARGETING = 'DEVICE_TARGETING',
    GEOTARGETING = 'GEOTARGETING',
    TRACKING = 'TRACKING',
    AUDIENCE = 'AUDIENCE',
}
