#!/bin/bash

LIVE_SESSIONS_COUNT=$(w -h | wc -l)
if [[ $LIVE_SESSIONS_COUNT > 1 ]]; then
        echo "there are still live sessions [" $((LIVE_SESSIONS_COUNT - 1)) "] - postponing termination"
else
        echo "terminating container"
        kill -9 $(cat /var/run/dropbear.pid)
fi

