FROM python:3.9.1-slim

RUN apt-get update && \
    apt-get install -y \
    git-core \
    curl \
    libpq-dev \
    python-dev \
    libcurl4-openssl-dev
# flake8-polyfill is only installed because radon plugin is loaded from flake8 and it has broken dependencies
RUN pip install -U flake8==3.7.7 flake8-polyfill==1.0.2 xenon pip-tools==5.5.0 black==20.8b1 mypy isort==4.3.21

RUN useradd --create-home --password '*' --shell /bin/bash --uid 1000 ubuntu
USER ubuntu
