FROM python:3.7-slim

RUN apt-get update
RUN apt-get install -y \
    git-core \
    curl \
    libpq-dev \
    python-dev \
    libcurl4-openssl-dev
RUN pip install -U flake8==3.7.7 xenon pip-tools==4.0.0 black==18.6b4 mypy isort==4.3.21
