FROM python:2.7-slim

RUN apt-get update && \
    apt-get install -y \
    git-core \
    curl \
    libpq-dev \
    python-dev \
    libcurl4-openssl-dev
RUN pip install -U flake8 xenon pip-tools isort==4.3.21

