# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0055_auto_20160428_1604'),
        ('reports', '0003_auto_20160413_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetDailyStatementK1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('media_spend_nano', models.BigIntegerField()),
                ('data_spend_nano', models.BigIntegerField()),
                ('license_fee_nano', models.BigIntegerField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements_k1', to='dash.BudgetLineItem')),
            ],
            options={
                'get_latest_by': 'date',
            },
        ),
        migrations.AlterUniqueTogether(
            name='budgetdailystatementk1',
            unique_together=set([('budget', 'date')]),
        ),
    ]
