# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-19 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20160428_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetdailystatement',
            name='margin_nano',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
