# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-25 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_budgetdailystatement_margin_nano'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyreportrecipient',
            name='publishers_report',
            field=models.BooleanField(default=False),
        ),
    ]
