# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-17 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_supplyreportrecipient_publishers_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyreportrecipient',
            name='custom_subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
