# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20170413_1418'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetdailystatementk1',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='budgetdailystatementk1',
            name='budget',
        ),
        migrations.DeleteModel(
            name='BudgetDailyStatementK1',
        ),
    ]
