# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20170413_1556'),
    ]

    database_operations = [
        migrations.AlterModelTable('SupplyReportRecipient', 'dash_supplyreportrecipient')
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='supplyreportrecipient',
            name='source',
        ),
        migrations.DeleteModel(
            name='SupplyReportRecipient',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations,
        )
    ]
