# Generated by Django 2.1.2 on 2018-11-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dcron", "0002_add_alert_field")]

    operations = [
        migrations.RenameField(
            model_name="dcronjobsettings", old_name="manual_warning_wait", new_name="manual_override"
        ),
        migrations.AddField(
            model_name="dcronjobsettings",
            name="max_duration",
            field=models.FloatField(default=3600),
            preserve_default=False,
        ),
    ]
