# Generated by Django 2.1.2 on 2018-11-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dcron", "0004_add_min_separation_field")]

    operations = [
        migrations.AlterField(
            model_name="dcronjobsettings", name="max_duration", field=models.FloatField(default=3600)
        ),
        migrations.AlterField(
            model_name="dcronjobsettings", name="min_separation", field=models.FloatField(default=30)
        ),
        migrations.AlterField(model_name="dcronjobsettings", name="warning_wait", field=models.FloatField(default=60)),
    ]
