# Generated by Django 2.1.2 on 2018-11-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dcron", "0005_ad_fload_field_defaults")]

    operations = [
        migrations.AddField(
            model_name="dcronjobsettings",
            name="severity",
            field=models.IntegerField(choices=[(0, "low"), (1, "high")], default=0),
        )
    ]
