# Generated by Django 2.1.2 on 2018-12-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dcron", "0006_add_dcron_job_severity_field")]

    operations = [
        migrations.AlterField(model_name="dcronjobsettings", name="warning_wait", field=models.FloatField(default=300))
    ]
