# Generated by Django 2.1.2 on 2019-04-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dcron", "0007_auto_20181213_0937")]

    operations = [
        migrations.AddField(
            model_name="dcronjobsettings", name="pause_execution", field=models.BooleanField(default=False)
        )
    ]
