# Generated by Django 2.1.11 on 2019-10-18 13:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dcron", "0008_add_pause_execution_flag")]

    operations = [
        migrations.CreateModel(
            name="DCronJobHistory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("command_name", models.CharField(db_index=True, max_length=150)),
                ("status", models.IntegerField(choices=[(0, "OK"), (3, "FAILURE")])),
                ("host", models.CharField(max_length=100)),
                ("executed_dt", models.DateTimeField()),
                ("completed_dt", models.DateTimeField()),
                ("expected_max_duration", models.FloatField()),
            ],
            options={
                "verbose_name": "Distributed Cron Job History",
                "verbose_name_plural": "Distributed Cron Job History Entries",
            },
        )
    ]
