# Generated by Django 2.1.11 on 2020-04-23 13:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dcron", "0009_create_dcron_job_history_model")]

    operations = [
        migrations.AddField(
            model_name="dcronjobsettings",
            name="ownership",
            field=models.IntegerField(choices=[(1, "Z1"), (2, "ProdOps")], default=1),
        )
    ]
