# Generated by Django 2.1.11 on 2019-11-04 13:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("product_feeds", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="productfeed",
            name="default_display_url",
            field=models.CharField(
                default="yahoo.com",
                help_text="Default to use when display url is not specified in the feed",
                max_length=35,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productfeed",
            name="default_brand_name",
            field=models.CharField(help_text="Default to use when brand is not specified in the feed", max_length=25),
        ),
    ]
