# Generated by Django 2.1.11 on 2019-11-22 14:54

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("product_feeds", "0002_auto_20191104_1321")]

    operations = [
        migrations.AlterField(
            model_name="productfeed",
            name="feed_type",
            field=models.IntegerField(
                choices=[(1, "Yahoo news feed"), (2, "Yahoo sports feed"), (3, "Google feed"), (4, "Reply.it feed")]
            ),
        ),
        migrations.AlterField(
            model_name="syncattempt",
            name="product_feed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_attempts",
                to="product_feeds.ProductFeed",
            ),
        ),
    ]
