# Generated by Django 2.1.11 on 2019-12-04 13:39

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("product_feeds", "0003_auto_20191122_1454")]

    operations = [
        migrations.AddField(
            model_name="productfeed",
            name="max_daily_uploads",
            field=models.IntegerField(
                blank=True, default=0, help_text="Maximum of number of ads that will be uploaded every day."
            ),
        )
    ]
