# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_auto_20160421_1626'),
        ('automation', '0009_auto_20160421_0810'),
    ]

    operations = [
    ]
