# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0010_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopilotlog',
            name='campaign_goal',
            field=models.IntegerField(blank=True, choices=[(1, b'Time on Site - Seconds'), (4, b'$CPA'), (5, b'CPC'), (3, b'Pageviews per Visit'), (2, b'Max Bounce Rate'), (7, b'New Unique Visitors')], default=None, null=True),
        ),
    ]
