# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0011_auto_20160426_0917'),
        ('automation', '0011_auto_20160504_1051'),
    ]

    operations = [
    ]
