# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 11:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0012_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopilotlog',
            name='campaign_goal',
            field=models.IntegerField(blank=True, choices=[(1, b'Time on Site - Seconds'), (4, b'$CPA'), (5, b'CPC'), (3, b'Pageviews per Visit'), (2, b'Max Bounce Rate'), (7, b'New Unique Visitors'), (8, b'Cost per Visit')], default=None, null=True),
        ),
    ]
