# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 13:03


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0013_auto_20160617_1146'),
        ('automation', '0013_auto_20160617_1047'),
    ]

    operations = [
    ]
