# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-14 12:05


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0016_auto_20160725_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopilotadgroupsourcebidcpclog',
            name='current_daily_budget_cc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name=b'Daily spend cap'),
        ),
        migrations.AlterField(
            model_name='autopilotlog',
            name='autopilot_type',
            field=models.IntegerField(choices=[(2, b'Disabled'), (1, b'Optimize Bids and Daily Spend Caps'), (3, b'Optimize Bids')], default=2),
        ),
        migrations.AlterField(
            model_name='autopilotlog',
            name='new_daily_budget',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name=b'New daily spend cap'),
        ),
        migrations.AlterField(
            model_name='autopilotlog',
            name='previous_daily_budget',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name=b'Previous daily spend cap'),
        ),
    ]
