# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-28 13:27


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0017_auto_20161014_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopilotlog',
            name='is_autopilot_job_run',
            field=models.BooleanField(default=False),
        ),
    ]
