# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-05 09:31


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0018_autopilotlog_is_autopilot_job_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopilotlog',
            name='is_autopilot_job_run',
            field=models.NullBooleanField(default=False),
        ),
    ]
