# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-12 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0019_auto_20170105_0931'),
        ('automation', '0019_auto_20170110_1552'),
    ]

    operations = [
    ]
