# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-26 15:43


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0019_auto_20170105_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopilotlog',
            name='is_rtb_as_one',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='autopilotlog',
            name='ad_group_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dash.AdGroupSource'),
        ),
    ]
