# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-07 15:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0020_auto_20170126_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopilotlog',
            name='campaign_goal_optimal_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name=b"Goal's optimal value"),
        ),
    ]
