# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-21 10:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0021_autopilotlog_campaign_goal_optimal_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopilotlog',
            name='campaign_goal',
            field=models.IntegerField(blank=True, choices=[(1, b'Time on Site - Seconds'), (5, b'CPC'), (4, b'$CPA'), (12, b'Cost per Completed Video View'), (10, b'Cost per New Visitor'), (3, b'Pageviews per Visit'), (9, b'Cost per Non-Bounced Visit'), (2, b'Max Bounce Rate'), (7, b'New Unique Visitors'), (8, b'Cost per Visit'), (11, b'Cost per Pageview')], default=None, null=True),
        ),
    ]
