# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-16 17:05


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0023_auto_20171116_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimedatahistory',
            name='etfm_spend',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
