# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 14:32


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0025_auto_20171116_1756'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='realtimedatahistory',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='realtimedatahistory',
            name='modified_dt',
        ),
    ]
