# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0253_campaign_real_time_campaign_stop'),
        ('automation', '0026_auto_20171117_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignStopState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, b'Enabled'), (2, b'Stopped')], default=2)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dash.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='RealTimeCampaignDataHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('etfm_spend', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name=b'Created at')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Campaign')),
            ],
        ),
    ]
