# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 12:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0027_campaignstopstate_realtimecampaigndatahistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstopstate',
            name='max_allowed_end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
