# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 16:21


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0028_campaignstopstate_max_allowed_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimecampaigndatahistory',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name=b'Created at'),
        ),
        migrations.AlterField(
            model_name='realtimecampaigndatahistory',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='realtimedatahistory',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name=b'Created at'),
        ),
        migrations.AlterField(
            model_name='realtimedatahistory',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
