# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 15:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0265_adgroupsource_settings_onetoone'),
        ('automation', '0029_auto_20180103_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeCampaignStopLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.IntegerField(choices=[(1, b'Budget depletion check'), (3, b'End date update'), (2, b'Selection check'), (4, b'Budget amount validation')])),
                ('context', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_dt', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name=b'Created at')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Campaign')),
            ],
        ),
    ]
