# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 15:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import utils.json_helper


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0030_realtimecampaignstoplog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimecampaignstoplog',
            name='context',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=utils.json_helper.JSONEncoder),
        ),
    ]
