# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0031_auto_20180109_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimecampaignstoplog',
            name='event',
            field=models.IntegerField(choices=[(1, b'Budget depletion check'), (3, b'Max allowed end date update'), (2, b'Selection check'), (4, b'Budget amount validation')]),
        ),
    ]
