# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 14:05


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0032_auto_20180111_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstopstate',
            name='almost_depleted',
            field=models.BooleanField(default=False),
        ),
    ]
