# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0033_campaignstopstate_almost_depleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopilotadgroupsourcebidcpclog',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='autopilotadgroupsourcebidcpclog',
            name='current_daily_budget_cc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Daily spend cap'),
        ),
        migrations.AlterField(
            model_name='autopilotadgroupsourcebidcpclog',
            name='new_cpc_cc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='New CPC'),
        ),
        migrations.AlterField(
            model_name='autopilotadgroupsourcebidcpclog',
            name='previous_cpc_cc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Previous CPC'),
        ),
        migrations.AlterField(
            model_name='autopilotadgroupsourcebidcpclog',
            name='yesterdays_spend_cc',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True, verbose_name="Yesterday's spend"),
        ),
        migrations.AlterField(
            model_name='autopilotlog',
            name='autopilot_type',
            field=models.IntegerField(choices=[(1, 'Optimize Bids and Daily Spend Caps'), (2, 'Disabled'), (3, 'Optimize Bids')], default=2),
        ),
        migrations.AlterField(
            model_name='autopilotlog',
            name='campaign_goal',
            field=models.IntegerField(blank=True, choices=[(1, 'Time on Site - Seconds'), (2, 'Max Bounce Rate'), (3, 'Pageviews per Visit'), (4, '$CPA'), (5, 'CPC'), (7, 'New Unique Visitors'), (8, 'Cost per Visit'), (9, 'Cost per Non-Bounced Visit'), (10, 'Cost per New Visitor'), (11, 'Cost per Pageview'), (12, 'Cost per Completed Video View')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='autopilotlog',
            name='campaign_goal_optimal_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Goal's optimal value"),
        ),
        migrations.AlterField(
            model_name='autopilotlog',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='autopilotlog',
            name='goal_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Goal's value"),
        ),
        migrations.AlterField(
            model_name='autopilotlog',
            name='new_cpc_cc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='New CPC'),
        ),
        migrations.AlterField(
            model_name='autopilotlog',
            name='new_daily_budget',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='New daily spend cap'),
        ),
        migrations.AlterField(
            model_name='autopilotlog',
            name='previous_cpc_cc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Previous CPC'),
        ),
        migrations.AlterField(
            model_name='autopilotlog',
            name='previous_daily_budget',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Previous daily spend cap'),
        ),
        migrations.AlterField(
            model_name='autopilotlog',
            name='yesterdays_spend_cc',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True, verbose_name="Yesterday's spend"),
        ),
        migrations.AlterField(
            model_name='campaignbudgetdepletionnotification',
            name='available_budget',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True, verbose_name='Budget available at creation'),
        ),
        migrations.AlterField(
            model_name='campaignbudgetdepletionnotification',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='campaignbudgetdepletionnotification',
            name='yesterdays_spend',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True, verbose_name="Campaign's yesterday's spend"),
        ),
        migrations.AlterField(
            model_name='campaignstoplog',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='campaignstopstate',
            name='state',
            field=models.IntegerField(choices=[(1, 'Enabled'), (2, 'Stopped')], default=2),
        ),
        migrations.AlterField(
            model_name='realtimecampaigndatahistory',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='realtimecampaignstoplog',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='realtimecampaignstoplog',
            name='event',
            field=models.IntegerField(choices=[(1, 'Budget depletion check'), (2, 'Selection check'), (3, 'Max allowed end date update'), (4, 'Budget amount validation')]),
        ),
        migrations.AlterField(
            model_name='realtimedatahistory',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
    ]
