# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0034_auto_20180212_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstopstate',
            name='pending_budget_updates',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='realtimecampaignstoplog',
            name='event',
            field=models.IntegerField(choices=[(1, 'Budget depletion check'), (2, 'Selection check'), (3, 'Max allowed end date update'), (4, 'Budget amount validation'), (5, 'Simple campaign stop')]),
        ),
    ]
