# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0037_auto_20180316_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstopstate',
            name='min_allowed_start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
