# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0038_campaignstopstate_min_allowed_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimecampaignstoplog',
            name='event',
            field=models.IntegerField(choices=[(1, 'Budget depletion check'), (2, 'Selection check'), (3, 'Max allowed end date update'), (4, 'Budget amount validation'), (5, 'Simple campaign stop'), (6, 'Min allowed start date update')]),
        ),
    ]
