# Generated by Django 2.1.10 on 2019-08-09 11:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("automation", "0040_rule_rulecondition_rulehistory")]

    operations = [
        migrations.AlterField(
            model_name="realtimecampaignstoplog",
            name="event",
            field=models.IntegerField(
                choices=[
                    (1, "Budget depletion check"),
                    (2, "Selection check"),
                    (3, "Max allowed end date update"),
                    (4, "Budget amount validation"),
                    (5, "Simple campaign stop"),
                    (6, "Min allowed start date update"),
                ],
                db_index=True,
            ),
        )
    ]
