# Generated by Django 2.1.8 on 2019-08-21 07:23

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("automation", "0041_auto_20190809_1121")]

    operations = [
        migrations.AddIndex(
            model_name="realtimedatahistory",
            index=models.Index(fields=["ad_group", "date"], name="automation__ad_grou_19908f_idx"),
        )
    ]
