# Generated by Django 2.1.11 on 2019-10-02 13:59

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0432_add_day_hour_bid_modifier_type"), ("automation", "0042_auto_20190821_0723")]

    operations = [
        migrations.RemoveField(model_name="rulecondition", name="left_operand_aggregate_type"),
        migrations.RemoveField(model_name="rulecondition", name="right_operand_aggregate_type"),
        migrations.AddField(
            model_name="rule",
            name="account",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="dash.Account"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rule",
            name="state",
            field=models.IntegerField(choices=[(1, "Enabled"), (2, "Paused")], default=1),
        ),
        migrations.AddField(
            model_name="rule",
            name="window",
            field=models.IntegerField(
                choices=[
                    (1, "N/A"),
                    (2, "Last day"),
                    (3, "Last 3 days"),
                    (4, "Last week"),
                    (5, "Last month"),
                    (6, "Lifetime"),
                ],
                default=6,
            ),
        ),
        migrations.AlterField(
            model_name="rulecondition",
            name="left_operand_type",
            field=models.IntegerField(
                choices=[
                    (1, "Daily cap"),
                    (2, "Daily cap spent percentage"),
                    (3, "Bid"),
                    (4, "Bid modifier"),
                    (5, "Total spend"),
                    (6, "Primary goal"),
                    (7, "Impressions"),
                    (8, "Clicks"),
                    (9, "CTR"),
                    (10, "Average CPC"),
                    (11, "Average CPM"),
                    (12, "Visits"),
                    (13, "Unique users"),
                    (14, "New users"),
                    (15, "Returning users"),
                    (16, "New users percentage"),
                    (17, "Click discrepancy"),
                    (18, "Pageviews"),
                    (19, "Pageviews per visit"),
                    (20, "Bounced visits"),
                    (21, "Non-bounced visits"),
                    (22, "Bounced rate"),
                    (23, "Total seconds"),
                    (24, "Time on site"),
                    (25, "Average cost per visit"),
                    (26, "Average cost per new visitor"),
                    (27, "Average cost per pageview"),
                    (28, "Average cost per non-bounced visit"),
                    (29, "Average cost per minute"),
                    (30, "Video start"),
                    (31, "Video fist quartile"),
                    (32, "Video midpoint"),
                    (33, "Video third quartile"),
                    (34, "Video complete"),
                    (35, "Average CPV"),
                    (36, "Average CPCV"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="rulecondition",
            name="right_operand_type",
            field=models.IntegerField(
                choices=[
                    (1, "Absolute value"),
                    (2, "Constant"),
                    (3, "Current time"),
                    (4, "Account manager"),
                    (5, "Campaign goal"),
                    (6, "Campaign budget"),
                    (7, "Remaining campaign budget"),
                    (8, "Ad group bid"),
                    (9, "Ad group click daily cap"),
                    (10, "Daily cap"),
                    (11, "Total spend"),
                    (12, "Total spend (daily average)"),
                ]
            ),
        ),
    ]
