# Generated by Django 2.1.11 on 2019-10-08 11:22

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("automation", "0043_auto_20191002_1359")]

    operations = [
        migrations.AlterField(
            model_name="rulecondition",
            name="operator",
            field=models.IntegerField(
                choices=[
                    (1, "Is equal to"),
                    (2, "Is not equal to"),
                    (3, "Is less than"),
                    (4, "Is greater than"),
                    (5, "Is between"),
                    (6, "Is not between"),
                    (7, "Contains"),
                    (8, "Does not contain"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="rulecondition",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="conditions", to="automation.Rule"
            ),
        ),
    ]
