# Generated by Django 2.1.11 on 2019-10-29 10:17

import django.db.models.deletion
from django.db import migrations
from django.db import models

import automation.rules.models.rule_history.instance


class Migration(migrations.Migration):

    dependencies = [("dash", "0435_auto_20191023_1248"), ("automation", "0044_auto_20191008_1122")]

    operations = [
        migrations.CreateModel(
            name="RuleTriggerHistory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target", models.CharField(max_length=127)),
                ("triggered_dt", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Triggered at")),
                (
                    "ad_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rule_trigger_history",
                        to="dash.AdGroup",
                    ),
                ),
            ],
            options={"verbose_name": "Rule trigger history", "verbose_name_plural": "Rule trigger history"},
            bases=(automation.rules.models.rule_history.instance.RuleHistoryInstanceMixin, models.Model),
        ),
        migrations.RenameField(model_name="rule", old_name="target", new_name="target_type"),
        migrations.RemoveField(model_name="rulecondition", name="left_operand_value"),
        migrations.AddField(
            model_name="rulecondition", name="left_operand_modifier", field=models.FloatField(default=1.0)
        ),
        migrations.AddField(
            model_name="rulehistory",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Rule applied successfully"), (2, "Rule application failed")], default=1
            ),
        ),
        migrations.AlterField(model_name="rule", name="change_limit", field=models.FloatField()),
        migrations.AlterField(model_name="rule", name="change_step", field=models.FloatField()),
        migrations.AlterField(
            model_name="rulecondition",
            name="left_operand_type",
            field=models.IntegerField(
                choices=[
                    (1, "Daily cap"),
                    (2, "Daily cap spent percentage"),
                    (3, "Bid"),
                    (4, "Bid modifier"),
                    (5, "Total spend"),
                    (6, "Primary goal"),
                    (7, "Impressions"),
                    (8, "Clicks"),
                    (9, "CTR"),
                    (10, "Average CPC"),
                    (11, "Average CPM"),
                    (12, "Visits"),
                    (13, "New visits"),
                    (14, "Unique users"),
                    (15, "New users"),
                    (16, "Returning users"),
                    (17, "New users percentage"),
                    (18, "Click discrepancy"),
                    (19, "Pageviews"),
                    (20, "Pageviews per visit"),
                    (21, "Bounced visits"),
                    (22, "Non-bounced visits"),
                    (23, "Bounced rate"),
                    (24, "Total seconds"),
                    (25, "Average time on site"),
                    (26, "Average cost per visit"),
                    (27, "Average cost per new visitor"),
                    (28, "Average cost per pageview"),
                    (29, "Average cost per non-bounced visit"),
                    (30, "Average cost per minute"),
                    (31, "Video start"),
                    (32, "Video fist quartile"),
                    (33, "Video midpoint"),
                    (34, "Video third quartile"),
                    (35, "Video complete"),
                    (36, "Average CPV"),
                    (37, "Average CPCV"),
                ]
            ),
        ),
        migrations.AddField(
            model_name="ruletriggerhistory",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="trigger_history", to="automation.Rule"
            ),
        ),
    ]
