# Generated by Django 2.1.11 on 2019-11-04 18:03

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("automation", "0045_auto_20191029_1017")]

    operations = [
        migrations.AlterField(
            model_name="rulecondition",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="conditions", to="automation.Rule"
            ),
        ),
        migrations.AlterField(
            model_name="rulehistory",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="history", to="automation.Rule"
            ),
        ),
        migrations.AlterField(
            model_name="rulehistory",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Rule application successful"), (2, "Rule application failed")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="ruletriggerhistory",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="trigger_history", to="automation.Rule"
            ),
        ),
    ]
