# Generated by Django 2.1.11 on 2019-11-07 10:25

import jsonfield.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("automation", "0046_auto_20191104_1803")]

    operations = [
        migrations.AlterField(
            model_name="rulecondition",
            name="operator",
            field=models.IntegerField(
                choices=[
                    (1, "Is equal to"),
                    (2, "Is not equal to"),
                    (3, "Is less than"),
                    (4, "Is greater than"),
                    (5, "Contains"),
                    (6, "Does not contain"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="rulehistory", name="changes", field=jsonfield.fields.JSONField(blank=True, null=True)
        ),
    ]
