# Generated by Django 2.1.11 on 2019-11-11 10:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("automation", "0047_auto_20191107_1025")]

    operations = [
        migrations.CreateModel(
            name="RulesDailyJobLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_dt",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name="Created at"),
                ),
            ],
        )
    ]
