# Generated by Django 2.1.11 on 2019-11-13 17:57

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0436_directdeal_name_required"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("automation", "0048_rulesdailyjoblog"),
    ]

    operations = [
        migrations.RemoveField(model_name="rule", name="account"),
        migrations.AddField(
            model_name="rule",
            name="agency",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="dash.Agency"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rule",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rule", name="modified_dt", field=models.DateTimeField(auto_now=True, verbose_name="Modified at")
        ),
        migrations.AlterField(
            model_name="rule",
            name="notification_recipients",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, null=True, size=None
            ),
        ),
    ]
