# Generated by Django 2.1.11 on 2019-12-09 14:13

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("automation", "0051_auto_20191204_0920")]

    operations = [
        migrations.AlterField(
            model_name="rulecondition",
            name="left_operand_window",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "N/A"),
                    (2, "Last day"),
                    (3, "Last 3 days"),
                    (4, "Last week"),
                    (5, "Last month"),
                    (6, "Lifetime"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rulecondition",
            name="right_operand_window",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "N/A"),
                    (2, "Last day"),
                    (3, "Last 3 days"),
                    (4, "Last week"),
                    (5, "Last month"),
                    (6, "Lifetime"),
                ],
                null=True,
            ),
        ),
    ]
