# Generated by Django 2.1.11 on 2019-12-19 09:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("automation", "0052_auto_20191209_1413")]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="window",
            field=models.IntegerField(
                choices=[(2, "Last day"), (3, "Last 3 days"), (4, "Last week"), (5, "Last month"), (6, "Lifetime")],
                default=6,
            ),
        ),
        migrations.AlterField(
            model_name="rulecondition",
            name="left_operand_window",
            field=models.IntegerField(
                blank=True,
                choices=[(2, "Last day"), (3, "Last 3 days"), (4, "Last week"), (5, "Last month"), (6, "Lifetime")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rulecondition",
            name="right_operand_window",
            field=models.IntegerField(
                blank=True,
                choices=[(2, "Last day"), (3, "Last 3 days"), (4, "Last week"), (5, "Last month"), (6, "Lifetime")],
                null=True,
            ),
        ),
    ]
