# Generated by Django 2.1.11 on 2020-01-14 09:07

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("automation", "0053_auto_20191219_0954")]

    operations = [
        migrations.AddField(model_name="rule", name="send_email_body", field=models.TextField(blank=True, null=True)),
        migrations.AddField(
            model_name="rule",
            name="send_email_recipients",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="rule", name="send_email_subject", field=models.TextField(blank=True, null=True)
        ),
    ]
