# Generated by Django 2.1.11 on 2020-01-22 18:22

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("automation", "0054_auto_20200114_0907")]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="target_type",
            field=models.IntegerField(
                choices=[
                    (1, "Ad group"),
                    (2, "Ad"),
                    (3, "Publisher"),
                    (4, "Device"),
                    (5, "Country"),
                    (6, "State"),
                    (7, "DMA"),
                    (8, "Operating system"),
                    (9, "Placement"),
                    (10, "Source"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="rulecondition",
            name="left_operand_type",
            field=models.IntegerField(
                choices=[
                    (1, "Daily cap"),
                    (2, "Daily cap spent percentage"),
                    (3, "Bid"),
                    (4, "Bid modifier"),
                    (5, "Total spend"),
                    (6, "Primary goal"),
                    (7, "Impressions"),
                    (8, "Clicks"),
                    (9, "CTR"),
                    (10, "Average CPC"),
                    (11, "Average CPM"),
                    (12, "Visits"),
                    (13, "New visits"),
                    (14, "Unique users"),
                    (15, "New users"),
                    (16, "Returning users"),
                    (17, "New users percentage"),
                    (18, "Click discrepancy"),
                    (19, "Pageviews"),
                    (20, "Pageviews per visit"),
                    (21, "Bounced visits"),
                    (22, "Non-bounced visits"),
                    (23, "Bounce rate"),
                    (24, "Total seconds"),
                    (25, "Average time on site"),
                    (26, "Average cost per visit"),
                    (27, "Average cost per new visitor"),
                    (28, "Average cost per pageview"),
                    (29, "Average cost per non-bounced visit"),
                    (30, "Average cost per minute"),
                    (31, "Video start"),
                    (32, "Video fist quartile"),
                    (33, "Video midpoint"),
                    (34, "Video third quartile"),
                    (35, "Video complete"),
                    (36, "Average CPV"),
                    (37, "Average CPCV"),
                ]
            ),
        ),
    ]
