# Generated by Django 2.1.11 on 2020-02-05 12:47

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0449_merge_20200203_0919"), ("automation", "0055_auto_20200122_1822")]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="publisher_group",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="dash.PublisherGroup"
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="action_type",
            field=models.IntegerField(
                choices=[
                    (1, "Increase bid"),
                    (2, "Decrease bid"),
                    (3, "Increase bid modifier"),
                    (4, "Decrease bid modifier"),
                    (5, "Increase budget"),
                    (6, "Decrease budget"),
                    (7, "Turn off"),
                    (8, "Blacklist"),
                    (9, "Send an e-mail"),
                    (10, "Add to publisher group"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="agency",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="dash.Agency"),
        ),
    ]
