# Generated by Django 2.1.11 on 2020-02-19 17:09

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("automation", "0056_auto_20200205_1247")]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="target_type",
            field=models.IntegerField(
                choices=[
                    (1, "Ad group"),
                    (2, "Ad"),
                    (3, "Publisher"),
                    (4, "Device"),
                    (5, "Country"),
                    (6, "State"),
                    (7, "DMA"),
                    (8, "Operating system"),
                    (9, "Environment"),
                    (10, "Source"),
                ]
            ),
        )
    ]
