# Generated by Django 2.1.11 on 2020-03-24 01:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("automation", "0058_auto_20200302_1023")]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="window",
            field=models.IntegerField(
                choices=[(1, "Last day"), (2, "Last 3 days"), (3, "Last week"), (4, "Last month"), (5, "Lifetime")],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="rulecondition",
            name="left_operand_type",
            field=models.IntegerField(
                choices=[
                    (1, "Total spend"),
                    (2, "Impressions"),
                    (3, "Clicks"),
                    (4, "CTR"),
                    (5, "Average CPC"),
                    (6, "Average CPM"),
                    (7, "Visits"),
                    (8, "New visits"),
                    (9, "Unique users"),
                    (10, "New users"),
                    (11, "Returning users"),
                    (12, "New users percentage"),
                    (13, "Click discrepancy"),
                    (14, "Pageviews"),
                    (15, "Pageviews per visit"),
                    (16, "Bounced visits"),
                    (17, "Non-bounced visits"),
                    (18, "Bounce rate"),
                    (19, "Total seconds"),
                    (20, "Average time on site"),
                    (21, "Average cost per visit"),
                    (22, "Average cost per new visitor"),
                    (23, "Average cost per pageview"),
                    (24, "Average cost per non-bounced visit"),
                    (25, "Average cost per minute"),
                    (26, "Average cost per conversion"),
                    (27, "Average cost per conversion (view)"),
                    (28, "Average cost per conversion (total)"),
                    (29, "Video start"),
                    (30, "Video fist quartile"),
                    (31, "Video midpoint"),
                    (32, "Video third quartile"),
                    (33, "Video complete"),
                    (34, "Average CPV"),
                    (35, "Average CPCV"),
                    (36, "Account name"),
                    (37, "Account created date"),
                    (38, "Days since account created"),
                    (39, "Campaign name"),
                    (40, "Campaign created date"),
                    (41, "Days since campaign created"),
                    (42, "Campaign type"),
                    (43, "Campaign manager"),
                    (44, "Campaign category"),
                    (45, "Campaign language"),
                    (46, "Primary campaign goal"),
                    (47, "Primary campaign goal value"),
                    (48, "Ad group name"),
                    (49, "Ad group created date"),
                    (50, "Days since ad group created"),
                    (51, "Ad group start date"),
                    (52, "Ad group end date"),
                    (53, "Ad group bidding type"),
                    (54, "Ad group bid"),
                    (55, "Ad group daily cap"),
                    (56, "Ad group delivery type"),
                    (57, "Ad title"),
                    (58, "Ad label"),
                    (59, "Ad created date"),
                    (60, "Days since ad created"),
                    (61, "Budget start date"),
                    (62, "Days since budget start"),
                    (63, "Budget end date"),
                    (64, "Days until budget end"),
                    (65, "Budget margin"),
                    (66, "Remaining budget"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="rulecondition",
            name="left_operand_window",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Last day"), (2, "Last 3 days"), (3, "Last week"), (4, "Last month"), (5, "Lifetime")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rulecondition",
            name="right_operand_type",
            field=models.IntegerField(
                choices=[
                    (1, "Absolute value"),
                    (2, "Constant"),
                    (3, "Current date"),
                    (4, "Account manager"),
                    (5, "Primary campaign goal value"),
                    (6, "Campaign budget"),
                    (7, "Remaining campaign budget"),
                    (8, "Ad group bid"),
                    (9, "Ad group click daily cap"),
                    (10, "Daily cap"),
                    (11, "Daily cap spent ratio"),
                    (12, "Total spend"),
                    (13, "Total spend (daily average)"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="rulecondition",
            name="right_operand_window",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Last day"), (2, "Last 3 days"), (3, "Last week"), (4, "Last month"), (5, "Lifetime")],
                null=True,
            ),
        ),
    ]
