# Generated by Django 2.1.11 on 2020-06-01 07:45

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("automation", "0060_auto_20200416_1612")]

    operations = [migrations.AddField(model_name="rule", name="archived", field=models.BooleanField(default=False))]
