# Generated by Django 2.1.11 on 2020-06-09 08:07

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0464_historystacktrace_created_dt"), ("automation", "0061_rule_archived")]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="account",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="dash.Account"
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="agency",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="dash.Agency"
            ),
        ),
    ]
