# Generated by Django 2.1.11 on 2020-07-13 14:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("automation", "0063_auto_20200609_0818")]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="window",
            field=models.IntegerField(
                choices=[(1, "Last day"), (2, "Last 3 days"), (3, "Last week"), (4, "Last month"), (5, "Last 60 days")],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="rulecondition",
            name="left_operand_window",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Last day"), (2, "Last 3 days"), (3, "Last week"), (4, "Last month"), (5, "Last 60 days")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rulecondition",
            name="right_operand_window",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Last day"), (2, "Last 3 days"), (3, "Last week"), (4, "Last month"), (5, "Last 60 days")],
                null=True,
            ),
        ),
    ]
