# Generated by Django 2.1.11 on 2020-08-14 08:45

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("automation", "0065_auto_20200810_0824")]

    operations = [
        migrations.RemoveField(model_name="rulehistory", name="changes_text"),
        migrations.AddField(
            model_name="rulehistory",
            name="failure_reason",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Unexpected error"), (2, "Campaign autopilot active"), (3, "Budget autopilot inactive")],
                default=None,
                null=True,
            ),
        ),
    ]
