# Generated by Django 2.1.11 on 2020-08-18 11:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("automation", "0066_auto_20200814_0845")]

    operations = [
        migrations.AlterField(
            model_name="rulecondition",
            name="operator",
            field=models.IntegerField(
                choices=[
                    (1, "Is equal to"),
                    (2, "Is not equal to"),
                    (3, "Is less than"),
                    (4, "Is greater than"),
                    (5, "Contains"),
                    (6, "Does not contain"),
                    (7, "Starts with"),
                    (8, "Ends with"),
                ]
            ),
        )
    ]
