# Generated by Django 2.1.11 on 2020-09-04 12:56

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0477_auto_20200903_1127"), ("automation", "0068_auto_20200826_0657")]

    operations = [
        migrations.AddField(
            model_name="rulecondition",
            name="conversion_pixel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coversion_pixel",
                to="dash.ConversionPixel",
            ),
        ),
        migrations.AddField(
            model_name="rulecondition",
            name="conversion_pixel_attribution",
            field=models.IntegerField(
                blank=True, choices=[(1, "Click-through conversion"), (2, "View-through conversion")], null=True
            ),
        ),
        migrations.AddField(
            model_name="rulecondition",
            name="conversion_pixel_window",
            field=models.IntegerField(
                blank=True, choices=[(24, "1 day"), (168, "7 days"), (720, "30 days")], null=True
            ),
        ),
    ]
