# Generated by Django 2.1.11 on 2020-09-07 14:23

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("automation", "0069_add_conversion_pixels")]

    operations = [
        migrations.AlterField(
            model_name="rulehistory",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Rule application successful"), (2, "Rule application failed"), (3, None)],
                db_index=True,
                default=1,
            ),
        )
    ]
