# Generated by Django 2.1.11 on 2020-09-07 14:30

from django.db import migrations

import automation.rules.constants


def migrate_no_changes(apps, schema_editor):
    RuleHistory = apps.get_model("automation", "RuleHistory")
    for rule_history in RuleHistory.objects.filter(status=automation.rules.constants.ApplyStatus.SUCCESS):
        if not rule_history.changes:
            rule_history.status = automation.rules.constants.ApplyStatus.SUCCESS_NO_CHANGES
            rule_history.save()


class Migration(migrations.Migration):

    dependencies = [("automation", "0070_auto_20200907_1423")]

    operations = [migrations.RunPython(migrate_no_changes)]
