# Generated by Django 2.1.11 on 2020-09-15 12:29

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("automation", "0071_auto_20200907_1430")]

    operations = [
        migrations.AlterField(
            model_name="rulehistory",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Rule application successful"),
                    (2, "Rule application failed"),
                    (3, "Rule application successful - no changes"),
                ],
                db_index=True,
                default=1,
            ),
        )
    ]
