# Generated by Django 2.1.11 on 2020-09-15 12:41

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations
from django.db import models

import utils.json_helper


class Migration(migrations.Migration):

    dependencies = [("automation", "0072_auto_20200915_1229")]

    operations = [
        migrations.CreateModel(
            name="RuleHistoryDetails",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("conditions", django.contrib.postgres.fields.jsonb.JSONField(encoder=utils.json_helper.JSONEncoder)),
                (
                    "target_condition_values",
                    django.contrib.postgres.fields.jsonb.JSONField(encoder=utils.json_helper.JSONEncoder),
                ),
                (
                    "rule_history",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="details", to="automation.RuleHistory"
                    ),
                ),
            ],
        )
    ]
