# Generated by Django 2.1.11 on 2020-09-18 10:19

from django.db import migrations

from automation.rules import ConversionAttributionType
from automation.rules import MetricType


def migrate_cpa_conditions(apps, schema_editor):
    RuleCondition = apps.get_model("automation", "RuleCondition")

    AVG_COST_PER_CONVERSION_VIEW = 27
    AVG_COST_PER_CONVERSION_TOTAL = 28
    CONVERSIONS_VIEW = 68
    CONVERSIONS_TOTAL = 69

    for condition in RuleCondition.objects.filter(
        left_operand_type__in=[
            MetricType.CONVERSIONS,
            CONVERSIONS_VIEW,
            CONVERSIONS_TOTAL,
            MetricType.AVG_COST_PER_CONVERSION,
            AVG_COST_PER_CONVERSION_VIEW,
            AVG_COST_PER_CONVERSION_TOTAL,
        ]
    ):
        if condition.left_operand_type == MetricType.CONVERSIONS:
            condition.conversion_pixel_attribution = ConversionAttributionType.CLICK
        elif condition.left_operand_type == CONVERSIONS_VIEW:
            condition.left_operand_type = MetricType.CONVERSIONS
            condition.conversion_pixel_attribution = ConversionAttributionType.VIEW
        elif condition.left_operand_type == CONVERSIONS_TOTAL:
            condition.left_operand_type = MetricType.CONVERSIONS
            condition.conversion_pixel_attribution = ConversionAttributionType.TOTAL
        elif condition.left_operand_type == MetricType.AVG_COST_PER_CONVERSION:
            condition.conversion_pixel_attribution = ConversionAttributionType.CLICK
        elif condition.left_operand_type == AVG_COST_PER_CONVERSION_VIEW:
            condition.left_operand_type = MetricType.AVG_COST_PER_CONVERSION
            condition.conversion_pixel_attribution = ConversionAttributionType.VIEW
        elif condition.left_operand_type == AVG_COST_PER_CONVERSION_TOTAL:
            condition.left_operand_type = MetricType.AVG_COST_PER_CONVERSION
            condition.conversion_pixel_attribution = ConversionAttributionType.TOTAL
        condition.save()


class Migration(migrations.Migration):

    dependencies = [("automation", "0073_rulehistorydetails")]

    operations = [migrations.RunPython(migrate_cpa_conditions)]
