# Generated by Django 2.1.11 on 2020-09-23 10:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations
from django.db import models

import utils.json_helper


class Migration(migrations.Migration):

    dependencies = [("automation", "0074_map_conversion_conditions")]

    operations = [
        migrations.AddField(
            model_name="rulehistorydetails", name="stack_trace", field=models.TextField(blank=True, null=True)
        ),
        migrations.AlterField(
            model_name="rulecondition",
            name="conversion_pixel_attribution",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Click-through conversion"), (2, "View-through conversion"), (3, "Total conversions")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rulecondition",
            name="left_operand_type",
            field=models.IntegerField(
                choices=[
                    (1, "Total spend"),
                    (2, "Impressions"),
                    (3, "Clicks"),
                    (4, "CTR"),
                    (5, "Average CPC"),
                    (6, "Average CPM"),
                    (7, "Visits"),
                    (8, "New visits"),
                    (9, "Unique users"),
                    (10, "New users"),
                    (11, "Returning users"),
                    (12, "New users percentage"),
                    (13, "Click discrepancy"),
                    (14, "Pageviews"),
                    (15, "Pageviews per visit"),
                    (16, "Bounced visits"),
                    (17, "Non-bounced visits"),
                    (18, "Bounce rate"),
                    (19, "Total seconds"),
                    (20, "Average time on site"),
                    (21, "Average cost per visit"),
                    (22, "Average cost per new visitor"),
                    (23, "Average cost per pageview"),
                    (24, "Average cost per non-bounced visit"),
                    (25, "Average cost per minute"),
                    (26, "Average cost per conversion"),
                    (29, "Video start"),
                    (30, "Video fist quartile"),
                    (31, "Video midpoint"),
                    (32, "Video third quartile"),
                    (33, "Video complete"),
                    (34, "Average CPV"),
                    (35, "Average CPCV"),
                    (36, "Account name"),
                    (37, "Account created date"),
                    (38, "Days since account created"),
                    (39, "Campaign name"),
                    (40, "Campaign created date"),
                    (41, "Days since campaign created"),
                    (42, "Campaign type"),
                    (43, "Campaign manager"),
                    (44, "Campaign category"),
                    (45, "Campaign language"),
                    (46, "Primary campaign goal"),
                    (47, "Primary campaign goal value"),
                    (48, "Ad group name"),
                    (49, "Ad group created date"),
                    (50, "Days since ad group created"),
                    (51, "Ad group start date"),
                    (52, "Ad group end date"),
                    (53, "Ad group bidding type"),
                    (54, "Ad group bid"),
                    (55, "Ad group daily cap"),
                    (56, "Ad group delivery type"),
                    (57, "Ad title"),
                    (58, "Ad label"),
                    (59, "Ad created date"),
                    (60, "Days since ad created"),
                    (61, "Budget start date"),
                    (62, "Days since budget start"),
                    (63, "Budget end date"),
                    (64, "Days until budget end"),
                    (65, "Budget margin"),
                    (66, "Remaining budget"),
                    (67, "Conversions (click)"),
                    (70, "Average cost per unique user"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="rulehistorydetails",
            name="conditions",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, encoder=utils.json_helper.JSONEncoder, null=True
            ),
        ),
        migrations.AlterField(
            model_name="rulehistorydetails",
            name="target_condition_values",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, encoder=utils.json_helper.JSONEncoder, null=True
            ),
        ),
    ]
