# Generated by Django 2.1.11 on 2020-10-06 08:24

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("automation", "0075_auto_20200923_1048")]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="target_type",
            field=models.IntegerField(
                choices=[
                    (1, "Ad group"),
                    (2, "Ad"),
                    (3, "Publisher"),
                    (4, "Device"),
                    (5, "Country"),
                    (6, "State"),
                    (7, "DMA"),
                    (8, "Operating system"),
                    (9, "Environment"),
                    (10, "Source"),
                    (11, "Placement"),
                    (12, "Browser"),
                    (13, "Connection type"),
                ]
            ),
        )
    ]
