# Generated by Django 2.1.11 on 2020-10-13 14:53

import django.db.models.deletion
import jsonfield.fields
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("automation", "0076_auto_20201006_0824"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuleChangeHistory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("snapshot", jsonfield.fields.JSONField()),
                ("created_dt", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="change_history", to="automation.Rule"
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AlterField(
            model_name="rulehistory",
            name="failure_reason",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Unexpected error"),
                    (2, "Campaign autopilot active"),
                    (3, "Budget autopilot inactive"),
                    (4, "No CPA goal"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
