# Generated by Django 2.1.11 on 2020-11-03 10:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("automation", "0077_auto_20201013_1453")]

    operations = [
        migrations.AlterField(
            model_name="autopilotlog",
            name="autopilot_type",
            field=models.IntegerField(
                choices=[
                    (1, "Optimize Bids and Daily Spend Caps"),
                    (2, "Disabled"),
                    (3, "Optimize Bids"),
                    (4, "Optimal Bid Bidding Strategy"),
                ],
                default=2,
            ),
        )
    ]
