# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0111_auto_20160817_0904'),
        ('actionlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='conversion_pixel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dash.ConversionPixel'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(choices=[(b'create_custom_audience', b'Create custom audience'), (b'create_pixel', b'Create pixel'), (b'set_publisher_blacklist', b'Set publisher blacklist'), (b'get_content_ad_status', b'Get content ad status'), (b'get_reports', b'Get reports'), (b'set_campaign_state', b'Set campaign state'), (b'set_property', b'Set property'), (b'create_campaign', b'Create campaign'), (b'get_reports_by_publisher', b'Get reports by publisher'), (b'insert_content_ad', b'Insert content ad'), (b'insert_content_ad_batch', b'Insert content ad batch'), (b'update_content_ad', b'Update content ad'), (b'submit_ad_group', b'Submit ad group to approval'), (b'get_campaign_status', b'Get campaign status')], db_index=True, max_length=100),
        ),
    ]
