AGENCY_RCS_ID = 220
AGENCY_NEWSCORP_ID = 86
CPC_GOAL_TO_BID_AGENCIES = (AGENCY_RCS_ID, AGENCY_NEWSCORP_ID)
# Non NAS AGENCY
AGENCY_MEDIAMOND_ID = 196
AGENCY_AMMET_ID = 289
AGENCY_ROI_MARKETPLACE_ID = 208
