# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 15:13


from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dash', '0144_change_demo_running_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdGroupTargeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_targeting', jsonfield.fields.JSONField(default=[])),
                ('start_date', models.DateField()),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.AdGroup')),
            ],
        ),
    ]
