# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 16:56


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizwire', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adgrouptargeting',
            unique_together=set([('start_date', 'interest_targeting')]),
        ),
    ]
