# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-28 17:06


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizwire', '0002_auto_20161122_1656'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdGroupTargeting',
            new_name='AdGroupRotation',
        ),
    ]
