# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-28 17:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizwire', '0003_auto_20161228_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgrouprotation',
            name='start_date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='adgrouprotation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='adgrouprotation',
            name='interest_targeting',
        ),
    ]
