# Generated by Django 2.1.2 on 2018-10-15 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("bizwire", "0004_auto_20161228_1707")]

    operations = [
        migrations.AlterField(
            model_name="adgrouprotation",
            name="ad_group",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="dash.AdGroup"),
        )
    ]
