# Generated by Django 2.1.2 on 2018-10-17 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("bizwire", "0005_foreignkey_add_on_delete")]

    operations = [
        migrations.AlterField(
            model_name="adgrouprotation",
            name="ad_group",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="dash.AdGroup"),
        )
    ]
