export enum RuleTargetType {
    Ad = 'AD',
    AdGroup = 'AD_GROUP',
    AdGroupPublisher = 'PUBLISHER',
    AdGroupCountry = 'COUNTRY',
    AdGroupRegion = 'REGION',
    AdGroupDma = 'DMA',
    AdGroupDevice = 'DEVICE',
    AdGroupOs = 'OS',
    AdGroupPlacement = 'PLACEMENT',
    AdGroupSource = 'SOURCE',
}

export enum RuleActionType {
    IncreaseBid = 'INCREASE_BID',
    DecreaseBid = 'DECREASE_BID',
    IncreaseBidModifier = 'INCREASE_BID_MODIFIER',
    DecreaseBidModifier = 'DECREASE_BID_MODIFIER',
    IncreaseDailyBudget = 'INCREASE_BUDGET',
    DecreaseDailyBudget = 'DECREASE_BUDGET',
    TurnOff = 'TURN_OFF',
    Blacklist = 'BLACKLIST',
    SendEmail = 'SEND_EMAIL',
}

export enum RuleActionFrequency {
    Day1 = '1_DAY',
    Days3 = '3_DAYS',
    Days7 = '7_DAYS',
}

export enum Macro {
    AgencyId = 'AGENCY_ID',
    AgencyName = 'AGENCY_NAME',
    AccountId = 'ACCOUNT_ID',
    AccountName = 'ACCOUNT_NAME',
    CampaignId = 'CAMPAIGN_ID',
    CampaignName = 'CAMPAIGN_NAME',
    AdGroupId = 'AD_GROUP_ID',
    AdGroupName = 'AD_GROUP_NAME',
    AdGroupDailyCap = 'AD_GROUP_DAILY_CAP',
    CampaignBudget = 'CAMPAIGN_BUDGET',
    TotalSpendLastDay = 'TOTAL_SPEND_LAST_DAY',
    TotalSpendLastThreeDays = 'TOTAL_SPEND_LAST_3_DAYS',
    TotalSpendLastSevenDays = 'TOTAL_SPEND_LAST_7_DAYS',
    TotalSpendThirtyDays = 'TOTAL_SPEND_LAST_30_DAYS',
    ClicksLastDay = 'CLICKS_LAST_DAY',
    ClicksLastThreeDays = 'CLICKS_LAST_3_DAYS',
    ClicksLastSevenDays = 'CLICKS_LAST_7_DAYS',
    ClicksThirtyDays = 'CLICKS_LAST_30_DAYS',
    ImpressionsLastDay = 'IMPRESSIONS_LAST_DAY',
    ImpressionsLastThreeDays = 'IMPRESSIONS_LAST_3_DAYS',
    ImpressionsLastSevenDays = 'IMPRESSIONS_LAST_7_DAYS',
    ImpressionsThirtyDays = 'IMPRESSIONS_LAST_30_DAYS',
    AvgCpcLastDay = 'AVG_CPC_LAST_DAY',
    AvgCpcLastThreeDays = 'AVG_CPC_LAST_3_DAYS',
    AvgCpcLastSevenDays = 'AVG_CPC_LAST_7_DAYS',
    AvgCpcThirtyDays = 'AVG_CPC_LAST_30_DAYS',
    AvgCpmLastDay = 'AVG_CPM_LAST_DAY',
    AvgCpmLastThreeDays = 'AVG_CPM_LAST_3_DAYS',
    AvgCpmLastSevenDays = 'AVG_CPM_LAST_7_DAYS',
    AvgCpmThirtyDays = 'AVG_CPM_LAST_30_DAYS',
    VisitsLastDay = 'VISITS_LAST_DAY',
    VisitsLastThreeDays = 'VISITS_LAST_3_DAYS',
    VisitsLastSevenDays = 'VISITS_LAST_7_DAYS',
    VisitsThirtyDays = 'VISITS_LAST_30_DAYS',
    UniqueUsersLastDay = 'UNIQUE_USERS_LAST_DAY',
    UniqueUsersLastThreeDays = 'UNIQUE_USERS_LAST_3_DAYS',
    UniqueUsersLastSevenDays = 'UNIQUE_USERS_LAST_7_DAYS',
    UniqueUsersThirtyDays = 'UNIQUE_USERS_LAST_30_DAYS',
    NewUsersLastDay = 'NEW_USERS_LAST_DAY',
    NewUsersLastThreeDays = 'NEW_USERS_LAST_3_DAYS',
    NewUsersLastSevenDays = 'NEW_USERS_LAST_7_DAYS',
    NewUsersThirtyDays = 'NEW_USERS_LAST_30_DAYS',
    ReturningUsersLastDay = 'RETURNING_USERS_LAST_DAY',
    ReturningUsersLastThreeDays = 'RETURNING_USERS_LAST_3_DAYS',
    ReturningUsersLastSevenDays = 'RETURNING_USERS_LAST_7_DAYS',
    ReturningUsersThirtyDays = 'RETURNING_USERS_LAST_30_DAYS',
    PercentNewUsersLastDay = 'PERCENT_NEW_USERS_LAST_DAY',
    PercentNewUsersLastThreeDays = 'PERCENT_NEW_USERS_LAST_3_DAYS',
    PercentNewUsersLastSevenDays = 'PERCENT_NEW_USERS_LAST_7_DAYS',
    PercentNewUsersThirtyDays = 'PERCENT_NEW_USERS_LAST_30_DAYS',
    ClickDiscrepancyLastDay = 'CLICK_DISCREPANCY_LAST_DAY',
    ClickDiscrepancyLastThreeDays = 'CLICK_DISCREPANCY_LAST_3_DAYS',
    ClickDiscrepancyLastSevenDays = 'CLICK_DISCREPANCY_LAST_7_DAYS',
    ClickDiscrepancyThirtyDays = 'CLICK_DISCREPANCY_LAST_30_DAYS',
    PageviewsLastDay = 'PAGEVIEWS_LAST_DAY',
    PageviewsLastThreeDays = 'PAGEVIEWS_LAST_3_DAYS',
    PageviewsLastSevenDays = 'PAGEVIEWS_LAST_7_DAYS',
    PageviewsThirtyDays = 'PAGEVIEWS_LAST_30_DAYS',
    PageviewsPerVisitLastDay = 'PAGEVIEWS_PER_VISIT_LAST_DAY',
    PageviewsPerVisitLastThreeDays = 'PAGEVIEWS_PER_VISIT_LAST_3_DAYS',
    PageviewsPerVisitLastSevenDays = 'PAGEVIEWS_PER_VISIT_LAST_7_DAYS',
    PageviewsPerVisitThirtyDays = 'PAGEVIEWS_PER_VISIT_LAST_30_DAYS',
    BouncedVisitsLastDay = 'BOUNCED_VISITS_LAST_DAY',
    BouncedVisitsLastThreeDays = 'BOUNCED_VISITS_LAST_3_DAYS',
    BouncedVisitsLastSevenDays = 'BOUNCED_VISITS_LAST_7_DAYS',
    BouncedVisitsThirtyDays = 'BOUNCED_VISITS_LAST_30_DAYS',
    NonBouncedVisitsLastDay = 'NON_BOUNCED_VISITS_LAST_DAY',
    NonBouncedVisitsLastThreeDays = 'NON_BOUNCED_VISITS_LAST_3_DAYS',
    NonBouncedVisitsLastSevenDays = 'NON_BOUNCED_VISITS_LAST_7_DAYS',
    NonBouncedVisitsThirtyDays = 'NON_BOUNCED_VISITS_LAST_30_DAYS',
    BounceRateLastDay = 'BOUNCE_RATE_LAST_DAY',
    BounceRateLastThreeDays = 'BOUNCE_RATE_LAST_3_DAYS',
    BounceRateLastSevenDays = 'BOUNCE_RATE_LAST_7_DAYS',
    BounceRateThirtyDays = 'BOUNCE_RATE_LAST_30_DAYS',
    TotalSecondsLastDay = 'TOTAL_SECONDS_LAST_DAY',
    TotalSecondsLastThreeDays = 'TOTAL_SECONDS_LAST_3_DAYS',
    TotalSecondsLastSevenDays = 'TOTAL_SECONDS_LAST_7_DAYS',
    TotalSecondsThirtyDays = 'TOTAL_SECONDS_LAST_30_DAYS',
    AvgTimeOnSiteLastDay = 'AVG_TIME_ON_SITE_LAST_DAY',
    AvgTimeOnSiteLastThreeDays = 'AVG_TIME_ON_SITE_LAST_3_DAYS',
    AvgTimeOnSiteLastSevenDays = 'AVG_TIME_ON_SITE_LAST_7_DAYS',
    AvgTimeOnSiteThirtyDays = 'AVG_TIME_ON_SITE_LAST_30_DAYS',
    AvgCostPerVisitLastDay = 'AVG_COST_PER_VISIT_LAST_DAY',
    AvgCostPerVisitLastThreeDays = 'AVG_COST_PER_VISIT_LAST_3_DAYS',
    AvgCostPerVisitLastSevenDays = 'AVG_COST_PER_VISIT_LAST_7_DAYS',
    AvgCostPerVisitThirtyDays = 'AVG_COST_PER_VISIT_LAST_30_DAYS',
    AvgCostPerNewVisitorLastDay = 'AVG_COST_PER_NEW_VISITOR_LAST_DAY',
    AvgCostPerNewVisitorLastThreeDays = 'AVG_COST_PER_NEW_VISITOR_LAST_3_DAYS',
    AvgCostPerNewVisitorLastSevenDays = 'AVG_COST_PER_NEW_VISITOR_LAST_7_DAYS',
    AvgCostPerNewVisitorThirtyDays = 'AVG_COST_PER_NEW_VISITOR_LAST_30_DAYS',
    AvgCostPerPageviewLastDay = 'AVG_COST_PER_PAGEVIEW_LAST_DAY',
    AvgCostPerPageviewLastThreeDays = 'AVG_COST_PER_PAGEVIEW_LAST_3_DAYS',
    AvgCostPerPageviewLastSevenDays = 'AVG_COST_PER_PAGEVIEW_LAST_7_DAYS',
    AvgCostPerPageviewThirtyDays = 'AVG_COST_PER_PAGEVIEW_LAST_30_DAYS',
    AvgCostPerNonBouncedVisitLastDay = 'AVG_COST_PER_NON_BOUNCED_VISIT_LAST_DAY',
    AvgCostPerNonBouncedVisitLastThreeDays = 'AVG_COST_PER_NON_BOUNCED_VISIT_LAST_3_DAYS',
    AvgCostPerNonBouncedVisitLastSevenDays = 'AVG_COST_PER_NON_BOUNCED_VISIT_LAST_7_DAYS',
    AvgCostPerNonBouncedVisitThirtyDays = 'AVG_COST_PER_NON_BOUNCED_VISIT_LAST_30_DAYS',
    AvgCostPerMinuteLastDay = 'AVG_COST_PER_MINUTE_LAST_DAY',
    AvgCostPerMinuteLastThreeDays = 'AVG_COST_PER_MINUTE_LAST_3_DAYS',
    AvgCostPerMinuteLastSevenDays = 'AVG_COST_PER_MINUTE_LAST_7_DAYS',
    AvgCostPerMinuteThirtyDays = 'AVG_COST_PER_MINUTE_LAST_30_DAYS',
}

export enum RuleConditionOperandType {
    AbsoluteValue = 'ABSOLUTE',
    CurrentDate = 'CURRENT_DATE',
    TotalSpend = 'TOTAL_SPEND',
    AverageDailyTotalSpend = 'AVERAGE_DAILY_TOTAL_SPEND',
    Impressions = 'IMPRESSIONS',
    Clicks = 'CLICKS',
    Ctr = 'CTR',
    Cpc = 'AVG_CPC',
    Cpm = 'AVG_CPM',
    Visits = 'VISITS',
    UniqueUsers = 'UNIQUE_USERS',
    NewUsers = 'NEW_USERS',
    ReturningUsers = 'RETURNING_USERS',
    PercentNewUsers = 'NEW_USERS_RATIO',
    ClickDiscrepancy = 'CLICK_DISCREPANCY',
    Pageviews = 'PAGEVIEWS',
    PageviewsPerVisit = 'PAGEVIEWS_PER_VISIT',
    BouncedVisits = 'BOUNCED_VISITS',
    NonBouncedVisits = 'NON_BOUNCED_VISITS',
    BounceRate = 'BOUNCE_RATE',
    TotalSeconds = 'TOTAL_SECONDS',
    TimeOnSite = 'AVG_TIME_ON_SITE',
    CampaignBudget = 'CAMPAIGN_BUDGET',
    RemainingCampaignBudget = 'REMAINING_CAMPAIGN_BUDGET',
    CampaignBudgetMargin = 'CAMPAIGN_BUDGET_MARGIN',
    CampaignBudgetStartDate = 'CAMPAIGN_BUDGET_START_DATE',
    CampaignBudgetEndDate = 'CAMPAIGN_BUDGET_END_DATE',
    DaysSinceCampaignBudgetStart = 'DAYS_SINCE_CAMPAIGN_BUDGET_START',
    DaysUntilCampaignBudgetEnd = 'DAYS_UNTIL_CAMPAIGN_BUDGET_END',
    CtrCampaignGoal = 'CTR_CAMPAIGN_GOAL',
    CpcCampaignGoal = 'CPC_CAMPAIGN_GOAL',
    CpmCampaignGoal = 'CPM_CAMPAIGN_GOAL',
    PercentNewUsersCampaignGoal = 'PERCENT_NEW_USERS_CAMPAIGN_GOAL',
    PageviewsPerVisitCampaignGoal = 'PAGEVIEWS_PER_VISIT_CAMPAIGN_GOAL',
    BounceRateCampaignGoal = 'BOUNCE_RATE_CAMPAIGN_GOAL',
    TimeOnSiteCampaignGoal = 'TIME_ON_SITE_CAMPAIGN_GOAL',
    AccountName = 'ACCOUNT_NAME',
    AccountManager = 'ACCOUNT_MANAGER',
    AccountCreationDate = 'ACCOUNT_CREATION_DATE',
    DaysSinceAccountCreation = 'DAYS_SINCE_ACCOUNT_CREATION',
    CampaignName = 'CAMPAIGN_NAME',
    CampaignCreationDate = 'CAMPAIGN_CREATION_DATE',
    DaysSinceCampaignCreation = 'DAYS_SINCE_CAMPAIGN_CREATION',
    CampaignManager = 'CAMPAIGN_MANAGER',
    AdGroupName = 'AD_GROUP_NAME',
    AdGroupCreationDate = 'AD_GROUP_CREATION_DATE',
    DaysSinceAdGroupCreation = 'DAYS_SINCE_AD_GROUP_CREATION',
    AdGroupStartDate = 'AD_GROUP_START_DATE',
    AdGroupEndDate = 'AD_GROUP_END_DATE',
    AdGroupDailyBudget = 'AD_GROUP_DAILY_BUDGET',
    AdGroupDailyClickCap = 'AD_GROUP_DAILY_CLICK_CAP',
    CreativeName = 'CREATIVE_NAME',
    CreativeLabel = 'CREATIVE_LABEL',
    CreativeCreationDate = 'CREATIVE_CREATION_DATE',
    DaysSinceCreativeCreation = 'DAYS_SINCE_CREATIVE_CREATION',
}

export enum RuleConditionOperandGroup {
    TrafficAcquisition = 'Traffic acquisition',
    AudienceMetrics = 'Audience metrics',
    Budget = 'Budget',
    Goals = 'Goals',
    Settings = 'Settings',
}

export enum RuleNotificationType {
    None = 'NONE',
    OnRuleRun = 'ON_RULE_RUN',
    OnRuleActionTriggered = 'ON_RULE_ACTION_TRIGGERED',
}

export enum RuleConditionOperator {
    LessThan = 'LESS_THAN',
    GreaterThan = 'GREATER_THAN',
    Contains = 'CONTAINS',
    NotContains = 'NOT_CONTAINS',
    Equals = 'EQUALS',
    NotEquals = 'NOT_EQUALS',
}

export enum TimeRange {
    LastDay = 'LAST_DAY',
    LastThreeDays = 'LAST_3_DAYS',
    LastSevenDays = 'LAST_7_DAYS',
    LastThirtyDays = 'LAST_30_DAYS',
    Lifetime = 'LIFETIME',
    NotApplicable = 'NOT_APPLICABLE',
}
