# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0024_auto_20160413_1436'),
        ('zemauth', '0025_auto_20160415_1412'),
    ]

    operations = [
    ]
