# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0027_auto_20160418_1410'),
        ('zemauth', '0025_auto_20160418_1453'),
    ]

    operations = [
    ]
