# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0028_remove_user_show_onboarding_guidance'),
        ('zemauth', '0028_auto_20160421_1523'),
    ]

    operations = [
    ]
