# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0029_merge'),
        ('zemauth', '0029_auto_20160422_0805'),
    ]

    operations = [
    ]
