# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0031_auto_20160425_1152'),
        ('zemauth', '0033_auto_20160425_1500'),
    ]

    operations = [
    ]
