# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0032_auto_20160425_1443'),
        ('zemauth', '0034_merge'),
    ]

    operations = [
    ]
