# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0035_merge'),
        ('zemauth', '0033_auto_20160428_1218'),
    ]

    operations = [
    ]
