# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 18:50


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0056_auto_20160607_0751'),
        ('zemauth', '0056_auto_20160608_1549'),
    ]

    operations = [
    ]
