# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0057_auto_20160610_1141'),
        ('zemauth', '0058_auto_20160610_1255'),
    ]

    operations = [
    ]
