# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 13:53


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0072_auto_20160803_1254'),
        ('zemauth', '0071_auto_20160802_1532'),
    ]

    operations = [
    ]
