# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 14:20


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0073_auto_20160804_1353'),
        ('zemauth', '0073_merge'),
    ]

    operations = [
    ]
