# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-12 12:49


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0078_auto_20160811_1524'),
        ('zemauth', '0077_auto_20160812_1152'),
    ]

    operations = [
    ]
