# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-22 12:48


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0081_auto_20160819_1325'),
        ('zemauth', '0077_auto_20160810_1438'),
    ]

    operations = [
    ]
