# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-26 11:42


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0082_auto_20160825_1257'),
        ('zemauth', '0083_auto_20160822_1248'),
    ]

    operations = [
    ]
