# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 08:42


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0085_auto_20160826_1239'),
        ('zemauth', '0085_auto_20160829_1449'),
    ]

    operations = [
    ]
