# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-02 10:39


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0099_auto_20161024_1401'),
        ('zemauth', '0100_auto_20161028_1432'),
    ]

    operations = [
    ]
