# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-12 08:38


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0108_auto_20170111_0808'),
        ('zemauth', '0108_auto_20170111_0923'),
        ('zemauth', '0108_auto_20170111_1018'),
    ]

    operations = [
    ]
