# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-02 12:57


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0113_auto_20170201_1307'),
        ('zemauth', '0114_auto_20170202_1138'),
    ]

    operations = [
    ]
