# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-06 12:22


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0116_auto_20170206_1049'),
        ('zemauth', '0115_merge'),
    ]

    operations = [
    ]
