# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-09 12:39


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0119_auto_20170209_1121'),
        ('zemauth', '0119_auto_20170209_1024'),
    ]

    operations = [
    ]
