# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-13 11:13


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0120_auto_20170213_0839'),
        ('zemauth', '0120_merge'),
    ]

    operations = [
    ]
