# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-13 13:27


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0121_merge'),
        ('zemauth', '0118_auto_20170207_0745'),
    ]

    operations = [
    ]
