# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-20 13:09


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0122_merge'),
        ('zemauth', '0123_auto_20170217_0824'),
    ]

    operations = [
    ]
