# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 15:28


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0126_auto_20170227_1207'),
        ('zemauth', '0126_auto_20170227_1018'),
    ]

    operations = [
    ]
