# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 14:10


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0131_auto_20170324_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('expire_date', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zemauth.Device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='users',
            field=models.ManyToManyField(through='zemauth.UserDevice', to=settings.AUTH_USER_MODEL),
        ),
    ]
