# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 15:35


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0133_auto_20170404_1139'),
        ('zemauth', '0133_auto_20170404_0757'),
    ]

    operations = [
    ]
