# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 07:34


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0134_merge_20170407_1535'),
        ('zemauth', '0134_auto_20170405_1534'),
    ]

    operations = [
    ]
