# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 09:33


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0136_auto_20170421_1031'),
        ('zemauth', '0136_auto_20170420_1253'),
    ]

    operations = [
    ]
