# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 10:14


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0138_auto_20170505_1202'),
        ('zemauth', '0137_merge_20170425_0933'),
    ]

    operations = [
    ]
