# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 12:06


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0143_auto_20170529_0859'),
        ('zemauth', '0143_auto_20170526_1151'),
    ]

    operations = [
    ]
