# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 10:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0145_auto_20170530_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_service',
            field=models.BooleanField(default=False, help_text='Designates whether a user represents an internal service.'),
        ),
    ]
