# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0155_auto_20171026_1309'),
        ('zemauth', '0156_auto_20171027_1257'),
    ]

    operations = [
    ]
