# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 10:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0161_auto_20180124_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_test_user',
            field=models.BooleanField(default=False, help_text='Designates whether user is an internal testing user and will not contribute towards certain statistics.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, null=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username.', 'invalid')], verbose_name='username'),
        ),
    ]
