# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0164_auto_20180321_1012'),
        ('zemauth', '0164_auto_20180321_1300'),
    ]

    operations = [
    ]
