# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0174_auto_20180608_1123'),
        ('zemauth', '0174_auto_20180607_1139'),
    ]

    operations = [
    ]
