# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zemauth', '0177_auto_20180629_1446'),
        ('zemauth', '0177_auto_20180626_0923'),
    ]

    operations = [
    ]
