# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("zemauth", "0187_auto_20180903_1203"), ("zemauth", "0187_auto_20180906_1306")]

    operations = []
