# Generated by Django 2.1.2 on 2018-10-16 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("zemauth", "0195_auto_20181015_0527")]

    operations = [
        migrations.AlterField(
            model_name="userdevice",
            name="device",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="zemauth.Device"),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
