# Generated by Django 2.1.2 on 2018-10-17 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("zemauth", "0196_foreignkey_add_on_delete")]

    operations = [
        migrations.AlterField(
            model_name="userdevice",
            name="device",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="zemauth.Device"),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
