# Generated by Django 2.1.2 on 2018-11-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("zemauth", "0197_auto_20181109_1240"), ("zemauth", "0197_auto_20181109_1123")]

    operations = []
