# Generated by Django 2.1.2 on 2018-11-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("zemauth", "0197_auto_20181107_1311"), ("zemauth", "0198_merge_20181112_0853")]

    operations = []
