# Generated by Django 2.2.4 on 2019-08-26 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("zemauth", "0223_auto_20190820_1249"), ("zemauth", "0223_auto_20190823_0929")]

    operations = []
