# Generated by Django 2.1.11 on 2020-01-24 13:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations

import zemauth.models


class Migration(migrations.Migration):

    dependencies = [("zemauth", "0231_add_sspd_sources_markets")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sspd_sources_markets",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, null=True, validators=[zemauth.models.validate_sspd_sources_markets]
            ),
        )
    ]
