# Generated by Django 2.1.11 on 2020-02-03 11:58

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("zemauth", "0232_sspd_sources_markets_validation")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="outbrain_user_id",
            field=models.CharField(blank=True, help_text="Outbrain ID", max_length=30, null=True),
        )
    ]
