# Generated by Django 2.1.11 on 2020-04-10 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models

import zemauth.features.entity_permission.instance
import zemauth.features.entity_permission.validation


class Migration(migrations.Migration):

    dependencies = [("dash", "0459_auto_20200407_1232"), ("zemauth", "0236_auto_20200327_0843")]

    operations = [
        migrations.CreateModel(
            name="EntityPermission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("can_see_entity", "View accounts, campaigns, ad groups and ads."),
                            ("can_edit_entity", "Edit accounts, campaigns, ad groups and ads."),
                            ("can_edit_user", "Manage other users."),
                            ("can_edit_budget", "Allocate budgets to campaigns."),
                            ("can_edit_budget_margin", "Configure campaign budget margin."),
                            ("can_see_margin", "View margin."),
                            ("can_see_agency_spend", "View agency spend."),
                            ("can_see_licence_fee", "View licence fee."),
                            ("can_see_media_cost", "View media cost."),
                            ("can_see_data_cost", "View data cost."),
                            ("can_use_restapi", "RESTAPI access"),
                        ],
                        max_length=128,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="dash.Account"
                    ),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="dash.Agency"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(
                zemauth.features.entity_permission.instance.EntityPermissionMixin,
                zemauth.features.entity_permission.validation.EntityPermissionValidatorMixin,
                models.Model,
            ),
        )
    ]
