# Generated by Django 2.1.11 on 2020-04-21 08:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("zemauth", "0237_entitypermission")]

    operations = [
        migrations.AlterField(
            model_name="entitypermission",
            name="permission",
            field=models.CharField(
                choices=[
                    ("can_see_entity", "View accounts, campaigns, ad groups and ads."),
                    ("can_edit_entity", "Edit accounts, campaigns, ad groups and ads."),
                    ("can_edit_user", "Manage other users."),
                    ("can_edit_budget", "Allocate budgets to campaigns."),
                    ("can_edit_budget_margin", "Configure campaign budget margin."),
                    ("can_see_agency_spend_margin", "View agency spend and margin."),
                    ("can_see_data_cost_media_cost_licence_fee", "View media cost, data cost and licence fee."),
                    ("can_use_restapi", "RESTAPI access"),
                ],
                max_length=128,
            ),
        )
    ]
