# Generated by Django 2.1.11 on 2020-05-28 06:37

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("dash", "0464_historystacktrace_created_dt"), ("zemauth", "0243_auto_20200520_1733")]

    operations = [
        migrations.AlterField(
            model_name="entitypermission",
            name="permission",
            field=models.CharField(
                choices=[
                    ("read", "View accounts, campaigns, ad groups and ads."),
                    ("write", "Edit accounts, campaigns, ad groups and ads."),
                    ("user", "Manage other users."),
                    ("budget", "Allocate budgets to campaigns."),
                    ("budget_margin", "Configure campaign budget margin."),
                    ("agency_spend_margin", "View agency spend and margin."),
                    ("media_cost_data_cost_licence_fee", "View media cost, data cost and licence fee."),
                    ("restapi", "RESTAPI access"),
                ],
                db_index=True,
                max_length=128,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="entitypermission",
            unique_together={("user", "agency", "permission"), ("user", "account", "permission")},
        ),
    ]
