# Generated by Django 2.1.11 on 2020-06-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("zemauth", "0244_auto_20200528_0637"), ("zemauth", "0244_auto_20200601_0747")]

    operations = []
