# Generated by Django 2.1.11 on 2020-06-18 17:34

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("zemauth", "0246_auto_20200608_1239")]

    operations = [
        migrations.AlterField(
            model_name="entitypermission",
            name="permission",
            field=models.CharField(
                choices=[
                    ("read", "View accounts, campaigns, ad groups and ads."),
                    ("write", "Edit accounts, campaigns, ad groups and ads."),
                    ("user", "Manage other users."),
                    ("budget", "Allocate budgets to campaigns."),
                    ("budget_margin", "Configure campaign budget margin."),
                    ("agency_spend_margin", "View agency spend and margin."),
                    ("media_cost_data_cost_licence_fee", "View media cost, data cost and licence fee."),
                    ("base_costs_service_fee", "View base media cost, base data cost and service fee."),
                    ("restapi", "RESTAPI access"),
                ],
                db_index=True,
                max_length=128,
            ),
        )
    ]
