# Generated by Django 2.1.11 on 2020-07-10 07:30

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("zemauth", "0247_auto_20200618_1734")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company_type",
            field=models.IntegerField(blank=True, null=True, verbose_name="company type"),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name="country"),
        ),
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name="job title"),
        ),
        migrations.AddField(
            model_name="user",
            name="programmatic_platforms",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(), blank=True, default=list, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="start_year_of_experience",
            field=models.IntegerField(blank=True, null=True, verbose_name="start year of experience"),
        ),
    ]
