# Generated by Django 2.1.11 on 2020-09-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("zemauth", "0258_auto_20200914_0853"), ("zemauth", "0258_auto_20200911_0851")]

    operations = []
