# Generated by Django 2.1.11 on 2020-09-22 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("zemauth", "0260_auto_20200918_0610"), ("zemauth", "0260_auto_20200922_0509")]

    operations = []
