# Generated by Django 2.1.11 on 2020-11-17 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("zemauth", "0271_auto_20201116_1252"), ("zemauth", "0271_auto_20201117_0610")]

    operations = []
