# Generated by Django 2.1.11 on 2020-11-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("zemauth", "0272_auto_20201117_1554"), ("zemauth", "0272_merge_20201117_0956")]

    operations = []
