# Generated by Django 2.1.11 on 2021-01-14 12:27

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("zemauth", "0277_auto_20210105_1938")]

    operations = [
        migrations.AlterField(
            model_name="user", name="sales_office", field=models.CharField(blank=True, max_length=255, null=True)
        )
    ]
