# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterializationRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('finished_dt', models.DateTimeField(auto_now_add=True, verbose_name=b'Finished at')),
            ],
        ),
    ]
