# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materializationrun',
            name='finished_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Finished at'),
        ),
    ]
