# Generated by Django 2.1.11 on 2020-05-11 14:38

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("etl", "0002_auto_20180212_1000")]

    operations = [
        migrations.CreateModel(
            name="EtlBooksClosed",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField()),
                ("finished_time", models.DateTimeField(auto_now_add=True)),
                ("etl_books_closed", models.BooleanField(default=False)),
            ],
        )
    ]
