export const callToAction = [
    {id: 'Read More', text: 'Read More'},
    {id: 'Book Now', text: 'Book Now'},
    {id: 'Contact Us', text: 'Contact Us'},
    {id: 'Learn More', text: 'Learn More'},
    {id: 'Shop Now', text: 'Shop Now'},
    {id: 'Sign Up', text: 'Sign Up'},
    {id: 'Watch More', text: 'Watch More'},
    {id: 'Download', text: 'Download'},
    {id: 'Apply Now', text: 'Apply Now'},
    {id: 'Bet Now', text: 'Bet Now'},
    {id: 'Buy Now', text: 'Buy Now'},
    {id: 'Compare', text: 'Compare'},
    {id: 'Directions', text: 'Directions'},
    {id: 'Donate Now', text: 'Donate Now'},
    {id: 'Enroll Now', text: 'Enroll Now'},
    {id: 'Follow Now', text: 'Follow Now'},
    {id: 'Get App', text: 'Get App'},
    {id: 'Get Coupon', text: 'Get Coupon'},
    {id: 'Get Now', text: 'Get Now'},
    {id: 'Get Offer', text: 'Get Offer'},
    {id: 'Get Quote', text: 'Get Quote'},
    {id: 'Get Rates', text: 'Get Rates'},
    {id: 'Get Sample', text: 'Get Sample'},
    {id: 'Install', text: 'Install'},
    {id: 'Join Now', text: 'Join Now'},
    {id: 'Launch', text: 'Launch'},
    {id: 'Listen Now', text: 'Listen Now'},
    {id: 'Play Now', text: 'Play Now'},
    {id: 'Play Game', text: 'Play Game'},
    {id: 'Record Now', text: 'Record Now'},
    {id: 'Register', text: 'Register'},
    {id: 'Remind Me', text: 'Remind Me'},
    {id: 'Save Now', text: 'Save Now'},
    {id: 'Sell Now', text: 'Sell Now'},
    {id: 'Subscribe', text: 'Subscribe'},
    {id: 'Try Now', text: 'Try Now'},
    {id: 'Use App', text: 'Use App'},
    {id: 'Vote Now', text: 'Vote Now'},
    {id: 'Watch Now', text: 'Watch Now'},
];
