# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 14:39


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    state_operations = [
        migrations.DeleteModel(
            name='ReportJob',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
        ),
    ]
